### ISSUE TITLE
apply stylesheet, clear cookies, bind "j" "k" for scrolling

### ISSUE THREAD

**Issue by boutsko** [atlas-engineer/next#102]
Conkeror was my best friend for many years, now when it stopped working with firefox57 I'm looking for a browser where I could use emacs style keybinding and nEXT looks extremely pomissing. I'm just wondering if you could help me with the following questions :

1. I would like to be able to apply eye friendly stylesheet to web pages. In conkeror I used the following snippet :
```
dark_css_uri =
    make_css_data_uri(['* { background: #333333! important; color: #bbbbbb !important }',
                       ':link, :link * { color: #dddddd !important }',
                       ':visited, :visited * { color: #95e454 !important }',
					   ' input,  select,  textarea * { background-color:black !important; border:1px solid red !important; color:#111111 !important; font-size:12px !important; }'],
                      $url_prefixes = ["view-source:http", "http", "about", "file"]);

dark_mode = false;

interactive("toggle-dark-mode", "Switch between normal and dark mode.",
            function (I) {
                if (dark_mode) {
                    unregister_user_stylesheet(dark_css_uri);
                    dark_mode = false;                    
                } else {
                    register_user_stylesheet(dark_css_uri);
                    dark_mode = true;
                }
            });

define_key(default_global_keymap, "D", "toggle-dark-mode");
```

Is it possible to achieve similar in nEXT ?

2. Could you please share how it is possible to clear cookies in nEXT.

3. When I try to bind "j" and "k" to scroll page up and down :

```
(define-key *document-mode-map* (kbd "k") 'scroll-up)
(define-key *document-mode-map* (kbd "j") 'scroll-down)
```

"j" and "k" letters later can't be used in entering address of a
website. Is there a fix for this.

**Comment by jmercouris** [comment]
I am deeply sorry for the long delay in response, these past few months I've been quite busy, and am only now getting active again in the project!

1. Yes, you would have to write some parenscript and hook into after the page load, I have not done this yet, nor provided an example of how to do this.

2. This is dependent upon whether you are on OSX or GTK/ your OS. The Webkit ports store things in different locations, so I am afraid I can't give a good answer :\

3. There is a fix for this, you can define a sort of "evil" mode. If you look in the issues/EXTENSIONS.org gallery, I believe you'll find some info for how to achieve this

**Comment by Ambrevar** [comment]
For point 2., you can delete the file stored in `XDG_DATA_HOME/share/next/cookies.txt` if you are on GNU/Linux.

For point 3., I hope to implement proper VI-style bindings soon.  See issue #28.

**Comment by Ambrevar** [comment]
Closing in favour of #362 and maybe #213.
