### ISSUE TITLE
Deprecated feature in gtk

### ISSUE THREAD

**Issue by equwal** [atlas-engineer/next#108]
This code came up in my `*inferior-lisp*`:
`(sbcl:20139): Gtk-WARNING **: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version`.

**Comment by Ambrevar** [comment]
I haven't looked closely but at first glance this looks more like a deprecated feature in GTK, not SBCL.

**Comment by equwal** [comment]
Yes that is correct, it is this one:
https://developer.gnome.org/gtk3/stable/GtkComboBox.html#GtkComboBox--s-shadow-type

**Comment by Ambrevar** [comment]
Feel free to re-open if there is something wrong with Next.
