### ISSUE TITLE
HTTPS doesn't always work

### ISSUE THREAD

**Issue by Chaformbintrano** [atlas-engineer/next#110]
I get «Unacceptable TLS certificate» when i try connecting to some websites (they work just fine on Firefox).

**Comment by Ambrevar** [comment]
Example?

**Comment by Chaformbintrano** [comment]
dom1n.com

**Comment by Ambrevar** [comment]
dom1n.com certificate seems to be invalid.  If you try http://dom1n.com it works just fine.
Same with Firefox.  I'll work on the Lisp interface with invalid certificates so that the use can decide what to do in case the certificate is invalid.

**Comment by Ambrevar** [comment]
Now that we have full network interception, maybe we should add some helper functions / modes to help defining the behaviour of Next when hitting a bad certificate.

**Comment by Ambrevar** [comment]
certificate-whitelist-mode is in 1.5 and on master.
Make sure it's enabled then call add-domain-to-certificate-whitelist to add a certificate exception for the current domain.
To make it permanent, add it to *default-certificate-whitelist* in your ~/.config/next/init.lisp.
