### ISSUE TITLE
C-x b doesn't work

### ISSUE THREAD

**Issue by Chaformbintrano** [atlas-engineer/next#111]
Nothing happens when i click completions with mouse, navigate with arrows and press RET or even enter the full name of a buffer.

**Comment by Ambrevar** [comment]
What's your OS?

@jmercouris: I think we should add a CONTRIBUTING.org asking issue reporters to mention the OS / webkit version, etc.

**Comment by Chaformbintrano** [comment]
@Ambrevar 
GNU/Linux (Ubuntu)

**Comment by Ambrevar** [comment]
And which desktop environment / window manager?

**Comment by Chaformbintrano** [comment]
MATE on Ubuntu and StumpWM on Arch

**Comment by Jebes** [comment]
I would like to drop in to say i'm experiencing the same issue. Afaik (inserting breaks, recompiling, restarting, etc.) It does not seem to be calling the switch-buffer command. I'm doing more investigation so take that with a grain of salt. If i happen to figure it out i'll put in a pull request.

**Comment by Jebes** [comment]
in `gtk.lisp` the function `minibuffer-get-input-complete` will always have a cursor of nil for at least kill buffer and switch buffer. By the look of the code it should be a numeric string. 

You can manually switch buffer by ctrl+return but this brings another bug about `switch-active-visible-buffer` being a string. That's about as far as I've gotten

**Comment by Ambrevar** [comment]
This is now fixed with the new API on master.
