### ISSUE TITLE
linux installation doesn't work (ubuntu 18.04)

### ISSUE THREAD

**Issue by intuser** [atlas-engineer/next#113]
I followed your instructions for a linux setup. All steps from "Run from source" seem to work but the last one, (next:start). Here my sbcl session:

* (require :asdf)

NIL
* (asdf:load-asd "/my/pass/to/next.asd")

#<ASDF/FIND-SYSTEM:DEFINE-OP >
#<ASDF/PLAN:SEQUENTIAL-PLAN {100385C353}>
0] (ql:quickload :next)
To load "next":
  Load 1 ASDF system:
    next
; Loading "next"
...........

(:NEXT)
0] (next:start)

debugger invoked on a UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {10005E85B3}>:
  The function INTERFACE:INITIALIZE is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE      ] Retry calling INTERFACE:INITIALIZE.
  1: [USE-VALUE     ] Call specified function.
  2: [RETURN-VALUE  ] Return specified values.
  3: [RETURN-NOTHING] Return zero values.
  4: [ABORT         ] Reduce debugger level (to debug level 1).
  5:                  Give up on "next"
  6:                  Exit debugger, returning to top level.

("undefined function")
0[2]  

First time I tried it there were of course many more steps between (ql:quickload :next) and (:NEXT). (No error messages.) When I followed your instruction I was wandering about the installation of cl-webkit. I put it into the directory but was wandering, how it would be detected. (I also tried ~/quicklisp/local-projects/cl-webkit, but this didn't help.)

Any suggestions?

**Comment by intuser** [comment]
I also tried to compile a binary. No errors or warnings during the process. If I run next-gtk from the terminal I just get five times S-W-M, nothing more.

**Comment by Ambrevar** [comment]
Did you follow the GNU/Linux instructions?  You must use next/gtk.

About cl-webkit: quicklisp uses `~/quicklisp/local-projects/` by default, so `cl-webkit` will be automatically loaded when stored there.

Make sure quicklisp is loaded from your `~/.sbclrc`:

```

;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

**Comment by intuser** [comment]
It doesn't seem to be crashing, it doesn't start. I just get the five "S-W-M" and nothing else: Nothing starts, no error message like in issue #97. I also tried to recompile with your workarround, but I don't see any change. (I'm not sure, what I have to delete to really recompile, I just deleted the binary and the directories common-lisp and next in the common-lisp/sbcl... cache.)

**Comment by Ambrevar** [comment]
You should not have to delete anything.  The error message indicates that you
did not compile in the interface.  Can you post the complete recipe of the
installation process you've used?

**Comment by intuser** [comment]
I followed your instructions (under ubuntu 18.04):

1. > sudo apt-get install sbcl
2. Download https://beta.quicklisp.org/quicklisp.lisp
3. > sbcl  --load quicklisp.lisp to load quicklisp
4. (quicklisp-quickstart:install)
5. (ql:add-to-init-file)
    (.sbclrc looks as you indicated above)
6. (quit)
7. > sudo apt-get install libwebkit2gtk-4.0-dev
8. <git clone --recursive https://github.com/next-browser/cl-webkit.git ~/common-lisp/quicklisp/local-projects/cl-webkit>
9. after the first unsuccessful try:
    <git clone --recursive https://github.com/next-browser/cl-webkit.git ~/quicklisp/local-projects/cl-webkit>
10. > sbcl
11. Then see session above.
12. (quit)
13. Then in ~/next/next:
> make build-gtk

**Comment by intuser** [comment]
About deleting something: If I don't delete next-gtk it doesn't get rebuild but just loaded. If I delete this file and the indicated directories I get the following:

sbcl --load next.asd \
	--eval '(ql:quickload :next/gtk)' \
	--eval '(setq *exit-timeout* nil)' \
	--eval '(asdf:make :next/gtk)' \
	--eval '(quit)'
This is SBCL 1.4.5.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.
SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

To load "next/gtk":
  Load 1 ASDF system:
    next/gtk
; Loading "next/gtk"
..................................................
[package next]....................................
[package interface]...............................
[package cl-webkit2]..............................
[package jscore].........................
[undoing binding stack and other enclosing state... done]
[defragmenting immobile space... 1893+35011+2495+4234+28823+33239 objects... done]
[saving current Lisp image into /home/x/next/next/source/next-gtk:
writing 0 bytes from the read-only space at 0x20000000
writing 6560 bytes from the static space at 0x20100000
writing 72941568 bytes from the dynamic space at 0x1000000000
writing 3104768 bytes from the immobile space at 0x20300000
writing 22823856 bytes from the immobile space at 0x21b00000
done]

**Comment by intuser** [comment]
I tried your first command. This results in:

```
T
NIL
#P"/home/xxx/common-lisp/quicklisp/local-projects/cl-webkit/webkit2/cl-webkit2.asd"
NIL
NIL 
```
This looks correct, doesn't it? There is BTW another cl-webkit under /home/xxx/quicklisp/local-projects, but that's exactly the same and your command shows, that it isn't used.

**Comment by Ambrevar** [comment]
The installation process has been completely revamped.  Now a simple `make all` should do!

Run `make` to display some more options.
