### ISSUE TITLE
Browser crashes

### ISSUE THREAD

**Issue by Compro-Prasad** [atlas-engineer/next#114]
I just installed this browser for the first time and it doesn't seem to open. I did a `make build-gtk` and the executable fails to open. It gives the following output:
```
Arguments parsed: (VERBOSE T) and NIL
S-W-M
S-W-M
S-W-M
S-W-M
S-W-M
```

**Comment by j3kyl** [comment]
Aint this one related to
https://github.com/next-browser/next/issues/109

**Comment by Compro-Prasad** [comment]
For me it wont even open. I am running the latest master.

**Comment by intuser** [comment]
To me it looks more like #113 . What system are you working on?

**Comment by Compro-Prasad** [comment]
@intuser Yes. #113 is the one. I am using Arch Linux with the latest packages.

**Comment by Ambrevar** [comment]
This should now be fixed on master!
