### ISSUE TITLE
Browser buffers by current url?

### ISSUE THREAD

**Issue by watkinsr** [atlas-engineer/next#115]
Is there a way to enable this / can I ask this as a feature request? It becomes very hard to grep between buffers without knowing which buffer is what.

**Comment by jmercouris** [comment]
Hi, this sounds like a very cool idea, let me see what I can do :)

**Comment by watkinsr** [comment]
@jmercouris Thanks! If I knew common-lisp a bit better myself, I'd take a crack at it. I want to switch from Chrome/firefox -> Next browser fully but in order to do so I need "vimium"-like features. And this happens to be a pretty big one when you have a lot of browser tabs open during development like documentation, github issues, stackoverflow etc.

**Comment by j3kyl** [comment]
Next Browser is based on Emacs bindings. 

It has most features of Vimium as C-n, C-p, C-b,C-f to move around pages and C-g to display link hints.

More on Next Manual: https://github.com/nEXT-Browser/nEXT/blob/master/documents/MANUAL.org

**There is a browser with vim bindings: https://github.com/qutebrowser/qutebrowser**

**Comment by watkinsr** [comment]
@j3kyl I am aware. It's just that if you happen to have multiple tabs open and you navigated from a given URL to a different one, the buffer name remains the foremost URL which isn't pragmatic.

**Comment by vindarel** [comment]
I didn't understand the request, but chances are this is fixed. Buffer browsing is pretty good now!

**Comment by alexanderbarbosa** [comment]
@vindarel  he means link hints

**Comment by Ambrevar** [comment]
I think this is OK now on master.  Feel free to reopen if there is anything you'd like to add.

**Comment by jmercouris** [comment]
I’m pretty sure it is not yet working, the idea would be like projectile, switch buffer, but only look at buffers with the same base URL as the one you are looking at. Let’s say I have 30 tabs open, 10 of them are on Wikipedia, I’m looking at Wikipedia and I type switch-buffer-url, it should only show me Wikipedia completions because they have the same base URL.

**Comment by Ambrevar** [comment]
OK, thanks for the explanation.  This is easy to fix, we just need an extra filter on the completion function.

**Comment by jmercouris** [comment]
Done!

cd81662e

please let me know how it works for you! :-)
