### ISSUE TITLE
init.lisp custom function not working

### ISSUE THREAD

**Issue by watkinsr** [atlas-engineer/next#116]
(in-package :next)

(define-comand mpv-current-page ()
"Download a youtube video in the currently open buffer"
  (let ((url (interface:web-view-get-url (view *active-buffer*))))
    (uiop:run-program
     (list "mpv" url))))

(define-key *global-map* (kbd "C-c d")
  'mpv-current-page)

With this in my ~/.config/next/init.lisp the browser will not start.

**Comment by watkinsr** [comment]
@vindarel I didn't get a stacktrace as I was just attempting to start the app from dmenu. I assume if I had managed to use slime / sly and loaded it as you said, it would have been fine but I just attempted to do this and I was getting:

Unbound variable: CCL::COMMAND-LINE-ARGUMENTS
   [Condition of type UNBOUND-VARIABLE]

**Comment by Ambrevar** [comment]
Are you on GNU/Linux?  If so, SBCL is known to work.  Don't know that status of CCL.
CCL is known to work on macOS.

**Comment by watkinsr** [comment]
@Ambrevar I am on MacOS. I basically did all the usual Jazz from the docs..
In a new Terminal execute the following:

lisp to create a new Lisp Repl (replace lisp with sbcl or ccl)
Execute (require :asdf) if asdf is not already loaded
Execute (asdf:load-asd "/full/path/to/next.asd") to load the Next system definition (you can not use relative pathnames).
Execute (ql:quickload :next) to load the Next system into your Lisp image. To load the MacOS version quickload :next/cocoa. To load the GTK version quickload :next/gtk.
Execute (next:start) to open your first Next window.

And on that last step I get:
Unbound variable: CCL::COMMAND-LINE-ARGUMENTS
[Condition of type UNBOUND-VARIABLE]

**Comment by Ambrevar** [comment]
I think this is your issue:
https://github.com/next-browser/next/pull/101.

**Comment by watkinsr** [comment]
@Ambrevar so I should try SBCL right?

**Comment by Ambrevar** [comment]
I'm told that SBCL does not have bordeaux threads on macOS (please confirm).  If true, then it won't work I think.

@jmercouris: how is commandline args situation with you?

**Comment by jmercouris** [comment]
just download the pre-built binary for OS x in the meantime, the command line args also cause a problem for me, I’m actually working on a new version on a different branch

**Comment by watkinsr** [comment]
@jmercouris The issue with the pre-built binary is that you can't redefine functions right? Like, I can't use swank/sly to hook into the browser's live lisp instance?

**Comment by vindarel** [comment]
@Ambrevar @watkinsr I think your new issue is https://github.com/next-browser/next/issues/106 which is resolved.

Try to update your Quicklisp dist: `(ql:update-dist "quicklisp")`.

**Comment by watkinsr** [comment]
@vindarel Neat. I'll give that a shot.

**Comment by watkinsr** [comment]
Weirdly enough after the quicklisp update I am now getting:

Permission denied : "/Users/ryanwatkins/.cache/common-lisp/ccl-1.11-f96-macosx-x64/Users/ryanwatkins/projects/dev/lisp/next/next/source/cocoa/repl-TMP.dx64fsl"
   [Condition of type CCL::SIMPLE-FILE-ERROR]

**Comment by watkinsr** [comment]
@vindarel @Ambrevar @jmercouris Managed to get this working by updating quicklisp and running CCL in sudo in MacOS High Sierra.

I only have one remaining question and that is, how do I manage to run a lisp process with root privileges in Emacs in Slime / Sly?

**Comment by jmercouris** [comment]
@watkinsr

I'm sorry, I didn't catch it in your previous comment, but yes you can use swank/sly to hook into the browser's live lisp instance, see here:

https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#slime-with-a-compiled-version-of-next
