### ISSUE TITLE
Randomly closes after a while with Gtk CRITICAL error

### ISSUE THREAD

**Issue by yur3i** [atlas-engineer/next#119]
The browser performs normally until this point then it breaks, here is the terminal output

``
(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:186:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:186:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2749:24: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2749:24: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2940:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2940:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2946:17: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4083:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4083:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4088:17: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4729:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4729:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: xfce.css:47:16: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: xfce.css:47:16: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:16:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:16:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:26:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:26:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:40:16: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:40:16: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:96:14: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:100:16: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:100:16: Expected a string.

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:279:14: not a number

(next:10577): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:279:14: Expected a string.
S-W-M
S-W-M
S-W-M
S-W-M

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:186:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:186:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2749:24: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2749:24: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2940:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2940:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2946:17: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4083:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4083:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4088:17: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4729:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4729:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: xfce.css:47:16: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: xfce.css:47:16: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:16:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:16:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:26:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:26:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:40:16: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:40:16: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:96:14: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:100:16: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:100:16: Expected a string.

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:279:14: not a number

(WebKitWebProcess:10591): Gtk-WARNING **: Theme parsing error: lightdm-gtk-greeter.css:279:14: Expected a string.

(next:10577): Gtk-CRITICAL **: gtk_tree_path_to_string: assertion 'path != NULL' failed

**Comment by jmercouris** [comment]
Thank you for your report, I have literally no idea where to begin debugging this :D

**Comment by Ambrevar** [comment]
This is now fixed on master since the GTK rewrite! :)

**Comment by yur3i** [comment]
@Ambrevar Thanks man, can't wait to try it later
