### ISSUE TITLE
Linux Crowdfunding Campaign

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/next#120]
Hi everyone, I've been listening to the issues that you all have raised. I care about making Next a really high quality, and accessible product for everyone. That is why I'm l launching a campaign that'll enable me to create a stable, quality, Linux release. If you could please spread the word, or support the project, I would be forever in your debt, thank you,

https://www.indiegogo.com/projects/next-browser-nix-support#/

-John

**Comment by azzamsa** [comment]
@jmercouris I *think* we should put it in readme, maybe ?

**Comment by jmercouris** [comment]
@azzamsa sorry for not replying to this earlier. I saw it in my email, was about to do it and then got distracted. I am very sorry! You are right, that would have been a good idea. It is too late now, but luckily we still got enough funding to proceed (with me keeping up with the additional costs as necessary)!

Since fundraising is now over, I will close this issue. Thank you to anyone that donated, starred, the project, contributed, or participated in any way!
