### ISSUE TITLE
0.08 Release build opens to 404

### ISSUE THREAD

**Issue by neauoire** [atlas-engineer/next#123]
Running [0.08](
https://github.com/atlas-engineer/next/releases/tag/0.08)

```
https://next-browser.github.io/start
```

<img width="1035" alt="screen shot 2018-10-06 at 8 19 44 am" src="https://user-images.githubusercontent.com/1455726/46558285-b49bcf00-c940-11e8-9152-db2b96cef986.png">

Latest release build from Github

**Comment by jmercouris** [comment]
Hi, you're correct, I've changed the URL, but did not update the release! Thank you for pointing this out to me! I will get to it ASAP!

**Comment by Ambrevar** [comment]
Now fixed on master.
