### ISSUE TITLE
Move 'next' one level up

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#132]
I'm wondering if we should not move the next folder one level up.  I find having "next/next"  confusing.  In my opinion, flat hierarchies are simpler to grasp than deep ones.

Finally, it would make it "more" trivial for Lisp build system to compile if the .asd file were in the root directory.

**Comment by jmercouris** [comment]
I have thought about this myself as well for quite a while.

I wanted to create two READMEs, one for prospective users, and one for developers. This was the most logical way I could think about doing this.

Having said this, if the GitHub page is no longer the de-facto way that people will interact with and discover Next, then I am open to making things more flat.

**Comment by Ambrevar** [comment]
> This was the most logical way I could think about doing this.

You mean because you want the file to be named `README.org` so that it displays on GitHub?
What about moving the dev README to the `documents` folder then?

**Comment by jmercouris** [comment]
That is a good solution, let's do it!

**Comment by jmercouris** [comment]
Test comment
