### ISSUE TITLE
Title and executable name

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#133]
The readme's first section is "Next Web Browser".  It's the only part where "web" is used.

Should we use "Next", "Next Browser" or "Next Web Browser"?
Should it be capital "B" in "Browser?

What about the executable name?  I think `next-browser` would be less ambiguous and reduce the change of running into a name conflict in the PATH.

**Comment by jmercouris** [comment]
I think "Next Browser", and I agree that the executable should be `next-browser`

-John

**Comment by Ambrevar** [comment]
Makes sense, thanks for clarifying!
