### ISSUE TITLE
Can't start Swank in compiled version of Next.

### ISSUE THREAD

**Issue by j3pic** [atlas-engineer/next#135]
I tried `S-h s` as described in the README.org, but nothing at all happened. No error message, no status message indicating that Swank had started, and no ability to connect SLIME to port 4006. I interpreted `S` as meaining `shift`, but I also tried interpreting it as meaning "Super" (which I in turn interpreted as being the Command key (⌘) because I have an installation of Emacs that binds "Super" to that key). 

I quickly discovered a hack that I hoped would serve as a workaround, but all it did was give me a little bit of debugging info: You can run /Applications/Next.app/Contents/MacOS/next directly from a Terminal, and then use `C-c` to send SIGINT and break into the debugger, from which I tried this:

    (swank::create-server :port 4006 :style :spawn :dont-close t)

This seems to work, until I connect to it. Then Emacs gives me this:

```
Can't locate module: SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [*ABORT] Return to SLIME's top level.
 1: [ABORT-BREAK] Reset this thread
 2: [ABORT] Kill this thread

Backtrace:
  0: (SWANK::MODULE-FILENAME SWANK-IO-PACKAGE::SWANK-PACKAGE-FU)
  1: (SWANK:SWANK-REQUIRE (SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTATIONS SWANK-IO-PACKAGE::SWANK-MACROSTEP SWANK-IO-PACKAGE::SWANK-FUZZY ..))..
  2: (CCL::CALL-CHECK-REGS SWANK:SWANK-REQUIRE (SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTATIONS SWANK-IO-PACKAGE::SWANK-MACROSTEP ..)))
  3: (CCL::CHEAP-EVAL (SWANK:SWANK-REQUIRE ..)))
  4: (SWANK:EVAL-FOR-EMACS (SWANK:SWANK-REQUIRE ..)) "COMMON-LISP-USER" 2)
  5: ((:INTERNAL SWANK::SPAWN-WORKER-THREAD))
  6: (SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK #<Compiled-function SWANK:SWANK-DEBUGGER-HOOK #x300001C45FFF> #<Compiled-function (:INTERNAL SWANK::SPAWN-WORKER-THREAD) (Non-Global)  #x300001D38F2F>)
  7: ((:INTERNAL SWANK::SPAWN-WORKER-THREAD))
  8: (CCL::RUN-PROCESS-INITIAL-FORM #<PROCESS worker(25) [Active] #x30200178B4FD> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x30200178B26F>))
  9: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) #<PROCESS worker(25) [Active] #x30200178B4FD> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x30200178B26F>))
 10: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))
 --more--
```

When called from a working copy of CCL, `SWANK::MODULE-FILENAME` returns a pathname to a FASL somewhere on the filesystem.

**Comment by jmercouris** [comment]
Hi, thank you for your very detailed report!!!

Firstly, I assume you mean the manual section here: https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#slime-with-a-compiled-version-of-next

You are also correct to assume that "S" in Next terminology means "Super" rather than "Shift" as it does in Emacs, it always bothered me that "C", "M", were uppercase, but "Super" was not, and it seemed more logical that shift, should be lowercase as it is not a Bucky key, but rather a modifier key.

I'm not sure what could be causing this, could you please clarify what version of MacOS you are on? Thank you!

**Comment by j3pic** [comment]
I'm using High Sierra (but it concerns me that CCL doesn't even run on Mojave, because my employer will eventually force an upgrade).

Could you confirm that "Super" maps to the ⌘ key on MacOS? Also, the documentation should explain which key is Super on each OS that Next runs on (should be the Windows key on any OS using PC hardware). 

You might want to consider mapping "Super" to something else on Linux and Windows. I believe Windows and most Linux window managers intercept it for their own purposes instead of passing it through to apps.

**Comment by jmercouris** [comment]
@j3pic 

I understand your concern. Hopefully by that time you must upgrade, the SBCL/Cross-platform upgrade will be complete (as stated above, we're working hard on it).

I will also confirm that "Super" is indeed ⌘ on MacOS. With regards to "what is super on Linux"? That is a difficult question, users on Linux may use xmodmap (and other software) to map just about any key that they like to "Super", so one cannot say "On Linux, "Super" is always the "Windows Key"", hence its absence from the documentation,

-John

**Comment by Ambrevar** [comment]
This is now fixed on master.
