### ISSUE TITLE
Very low number of implemented key bindings

### ISSUE THREAD

**Issue by intuser** [atlas-engineer/next#139]
After quite some time a finally could run next browser from a sbcl session.

But it was a huge disappointment: Essential key bindings are missing. Please compare the number of key bindings conkeror provides out of the box! (Please, please, do!)

There are three types of key bindings which should be implemented:

1. Coming from emacs (and conkeror) I would expect that not only C-n but also C-v, M-v and many others would work.
2. Coming from emacs (and conkeror) I would expect that keys which don't conflict with emacs and are generally implemented in browsers (space and page down for page down, page up for page up ...) would work.
3. I don't see **any** reason why next browser should use key bindings different from the established ones for things like "increase size" (C-x C-= in next browser, C-x + or C-x C-+ in the rest of the world).

If you don't want to implement those keybindings out of the box, you at least should provide ample examples of configuration files which provide those bindings. I don't find any.

Sorry for the not too happy tone ...

**Comment by jmercouris** [comment]
Hi Intuser,

I’m sorry for your disappointment, the project is still in very early stage. We’re working hard to improve cross platform compatibility and add more functionality.

If you look at the extensions guide you can see functions for M-v, C-v to move the page up and down by a screen,

-John

**Comment by alexanderbarbosa** [comment]
that should be, more than, fixed, by now! :D

**Comment by vindarel** [comment]
- `C-n but also C-v, M-v`: ✓
- `space and page down for page down, page up for page up`: ✓
- ` C-x + or C-x C-+`: agreed, in PR.

> C-x C-= in next browser`

that one is Emacs' default, so Emacs users would feel right at home. I suggest common ones in the PR.

**Comment by Ambrevar** [comment]
The main bindings that are missing are for the minibuffer:

- Page up / down are not implemented.

- VI bindings are missing.  The main thing that block it is that we need
  a way to signal the switch between insert mode and normal mode.  I can
  think of 2 options:

  - Change the cursor shape (easy).

  - After we add a mode line, we would simply display the list of modes
    there.  Still, wouldn't we always display the list of modes of the
    current buffer, and not of the minibuffer?
