### ISSUE TITLE
Cannot build interface system: Symbol "WITHIN-GTK-THREAD" not found in the GTK package.

### ISSUE THREAD

**Issue by wvxvw** [atlas-engineer/next#140]
Brief examination of `cl-cffi-gtk` (which I think is aliased to `gtk`) doesn't find this macro. Is this a missing dependency? A typo?

(This happens on Arch Linux, SBCL 1.4.11, source checkout from master)

**Comment by jmercouris** [comment]
I can't help much more  than that :\ the only thing I can imagine is different versions of cl-cffi-gtk and different versions of the GTK shared library. Linux compatibility is a nightmare, and we'll get it sorted with the new version through our architecture simplification. In the meantime, I'm sorry for the trouble, and hopefully a Linux user can chime in with some troubleshooting help!

**Comment by wvxvw** [comment]
Well, if you can tell me where `within-gtk-thread` is from (i.e. the package name and version), I will be able to get that package and version.

**Comment by jmercouris** [comment]
I would if I could, I'm not a Linux user. @Ferada  should know which versions he has installed, since he submitted the patch. Thoughts?

**Comment by vindarel** [comment]
This macro is an addition from Ferada's cl-ffi-gtk which wasn't in Quicklisp until the latest release.

So you'd clone https://github.com/Ferada/cl-cffi-gtk/ into `~/quicklisp/local-projects` and Quicklisp will load it from here.

You could also update Quicklisp: `(ql:update-dist :quicklisp)`.

**Comment by jmercouris** [comment]
Ah, very cool, good to know! @Ferada  thanks for continuing the work on CL-CFFI-GTK!

**Comment by Ferada** [comment]
Welcome, keep the bug reports coming if you see anything.

@wvxvw did what vindarel wrote work for you?

**Comment by Ambrevar** [comment]
This issue is gone since the GTK rewrite.
