### ISSUE TITLE
History navigation sometimes ignores pages on the same domain

### ISSUE THREAD

**Issue by akkartik** [atlas-engineer/next#143]
I'm on Mac OS and running from a `.dmg` I downloaded today. From the quickstart, it like `C-b` should go back one page on the current tab's history? But it always goes back to the first page I opened on the current tab. Then `C-f` seems to browse forward one page, and later pages in history are lost.

**Comment by akkartik** [comment]
Hmm, it's working fine after a restart.

**Comment by akkartik** [comment]
It looks like `C-b` sometimes skips past history on the same domain (B) and goes to the previous page on a different domain (A). Pressing `C-f` then skips to the first page visited in domain B. Later pages in domain B are lost from history.

**Comment by jmercouris** [comment]
hi @akkartik thank you for your report! :) This happens for web pages that manipulate the URL from javascript and just use Ajax to load content. You aren't actually navigating on these pages. What is actually happening is these "web apps" are pretending to load pages and change the URL. Youtube is a great example of this. We'll have to figure out a way to fix this!

**Comment by akkartik** [comment]
Is https://next.atlas.engineer using Javascript?! That's where I first spotted the issue :)

**Comment by akkartik** [comment]
Ohh, I see, the history isn't updated on the click on github's issue tab. Ok, I see what you mean :)

**Comment by Ambrevar** [comment]
Oh, this actually has been fixed for a little while: 915cc42646dc537845c162deea987a6f8924f91f :)
