### ISSUE TITLE
Find in page

### ISSUE THREAD

**Issue by akkartik** [atlas-engineer/next#144]
Is there a way to search for text on the current page? I tried the Emacs analogue `C-s`. I'm happy to try to create an extension if necessary. Is there an existing function I can bind a key to? Thank you.

**Comment by jmercouris** [comment]
Hi!
=S-s s= will let you search the current page. You can look for the default bindings in base.lisp, though they area about to change momentarily with a new release!

**Comment by jmercouris** [comment]
The new binding is `C-s s`, you can look through `search-buffer.lisp` to see how it works. It needs a lot of work, all PRs are appreciated :D
