### ISSUE TITLE
Getting next to run under NixOS

### ISSUE THREAD

**Issue by GrafBlutwurst** [atlas-engineer/next#146]
So I tinkered around with next for an evening and to get it to compile with `make next-gtk` you have to manually add the path for CFFI 

```
(ql:quickload :cffi)
(pushnew #P"/home/grafblutwurst/.local/lib/"
         cffi:*foreign-library-directories*)
```

and add all sorts of paths for pkg-config in PKG_CONFIG_PATH for it to finally compile.

However when I then start next-gtk-webkit and connect from sbcl I get an error saying: "TLS/SSL support not available; install glib-networking" 

trying to navigate to an URL does nothing except provoke javascript errors. As shown bellow.

Is there a runtime linked library missing? if so which one? 

![image](https://user-images.githubusercontent.com/2368458/49250130-5e1daf00-f41e-11e8-886b-33c09328500a.png)

**Comment by Ambrevar** [comment]
I've been working on a Guix package too.  I'll release is very soon.
See #92.

glib-networking is a dependency for webkit, you'll need to install it into your user profile if you don't have a Nix package.
See the README.org for the full list of dependencies.

**Comment by GrafBlutwurst** [comment]
I do have it installed. But I was wondering where is next looking for glib? I'll probably have to link it from there to `/nix/store...` where my glib actually is.

**Comment by Ambrevar** [comment]
Next is not looking for glib-networking, WebKit does.  It works automatically on Guix, so in your case it might be a Nix issue with the WebKit package.

**Comment by GrafBlutwurst** [comment]
Quite possible. Thanks for the pointers I'll dig into it.

**Comment by GrafBlutwurst** [comment]
alright I got next to boot properly by setting both env variables `GIO_EXTRA_MODULES` and `GSETTINGS_SCHEMA_DIR` to point to glib-networking and gsettings-desktop-schemas respectively. I'll see if anything else breaks and then get started at rolling it all up into a nix package.

**Comment by Ambrevar** [comment]
Fantastic!

**Comment by azazel75** [comment]
@GrafBlutwurst do you have anything to share, even just half baked?

**Comment by GrafBlutwurst** [comment]
@azazel75 I'm very sorry for the late response. I tinkered around with it for a couple days but ultimately capitulated because I couldn't get sbcl with the dependencies correctly set up as part of a nix build. So I really don't have anything actionable but would be very happy to help as I at least found out how to get next to run on nixOS.

However you can find what meager stuff I tried on my fork of nixpkgs: https://github.com/GrafBlutwurst/nixpkgs/tree/next-browser

**Comment by GrafBlutwurst** [comment]
but now with the released guix package I might give this another crack and just depend on it. that should be far easier

**Comment by Ambrevar** [comment]
Next 1.2.1 is out!  @GrafBlutwurst: Interested in giving this another spin? :p

**Comment by Ambrevar** [comment]
Next is coming to Nix! https://github.com/NixOS/nixpkgs/pull/68453
@GrafBlutwurst @vindarel @jmercouris

**Comment by GrafBlutwurst** [comment]
Cool to hear! Because I gave up on getting this to run. but it'll be a great learning experience actually looking at the working package definition :D

**Comment by GrafBlutwurst** [comment]
Package is available now and I started to play around with it. Sadly it seems there's some issues:

`
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: Could not prepare an sqlite statement.
Code ERROR: no such column: visits.
Database: /home/grafblutwurst/.local/share/next/history.db
SQL: select url from typed where url like ? order by visits desc.
`

Also the entire windows is white, help is blank as well:

![image](https://user-images.githubusercontent.com/2368458/65752252-b12ec400-e10c-11e9-9909-1bf10cbe688c.png)

There doesn't seem to be any errors logged on startup though

**Comment by Ambrevar** [comment]
For the SQLite issue, delete .local/share/next/history.db, that should
do it.

For the empty web window:

- Can you report your video card and your driver?

- Post the content of .local/share/next/next-gtk-webkit.log.

- Try running Next by exporting WEBKIT_FORCE_COMPOSITING_MODE=1 and the
	WEBKIT_DISABLE_COMPOSITING_MODE=1 environment variables (separately).

**Comment by GrafBlutwurst** [comment]
GPU: `01:00.0 VGA compatible controller: NVIDIA Corporation GP104BM [GeForce GTX 1070 Mobile] (rev a1)`

Disabling compositing mode fixes the problems. forcing it doesn't. Thanks for the hint with the history.db I guess I had an old one from when I was trying to get it to build from source. 

I'll start to use next, I was waiting a while to get to play around with it. Thanks! From my side this issue can be closed.

**Comment by Ambrevar** [comment]
Can you confirm that Epiphany works for you without the compositing mode workaround?
Also are you using Nouveau or the propriotery Nvidia drivers?

I believe the same issue has been reported before, we need to do
something about it.

**Comment by GrafBlutwurst** [comment]
Epiphany works fine (at least a quick navigation to google.com in a `nix-shell -p epiphany`) 
I am currently using the proprietary nvidia-drivers but am considering switching to bumblebee if I can get it to work. Once I got that I will retry with all 3 possible configs.

**Comment by Ambrevar** [comment]
Closing in favour of #422.
