### ISSUE TITLE
Higher zoom levels lead to overlapping lines

### ISSUE THREAD

**Issue by intuser** [atlas-engineer/next#152]
Given my eyesight the default zoom level is much too low for me. But increasing the zoom level for many (most) pages lead to overlapping lines.

Example: https://www.theguardian.com/politics/2018/dec/03/cabinet-minister-suspension-brexit-legal-advice-deal (Try to look at it with a zoom factor 1.6)

**Comment by jmercouris** [comment]
hi @intuser thank you for the report, that is indeed a problem. I wonder why that is. Probably it is best to also be able to set a default font size as well (in addition to the zoom size as we had discussed), also sorry about the delay in producing a code snippet, I have been quite busy today! I will try to get to it as soon as I can!

**Comment by intuser** [comment]
Hi! Yes, I agree that to be able to set a defautl font size as well would be helpfull!

**Comment by Kunderscore** [comment]
same here, would appreciate if a bigger font size can be set

**Comment by Ambrevar** [comment]
Does the example outlined in https://github.com/atlas-engineer/next/issues/293 help you?

**Comment by Ambrevar** [comment]
I cannot reproduce on master anymore.
This is probably due to a fix in WebKitGTK.  I'm using version 2.28.

Looks like we are good with zooming now! :)
