### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#153]
It would help all platforms to provide a Docker image on the Docker Hub.

Here's a WIP: https://github.com/vindarel/next/blob/master/Dockerfile it builds, I don't know how to run the two binaries yet. (edit: https://github.com/vindarel/next/blob/dockerfile/Dockerfile)

To try:
- docker build . -t next-on-debian
- docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix --net host -e DISPLAY=unix$DISPLAY --device /dev/snd next-on-debian (see comments)

**Comment by jmercouris** [comment]
Hi Vindarel, we will not officially support Docker, and have opted for Guix instead. 

Personally I am biased against tools like Docker, but a community support is of course possible, it is all open source after all!

**Comment by vindarel** [comment]
Does that look like a correct way to run Next ?

>  cp ports/gtk-webkit/next-gtk-webkit /usr/local/bin/ && ./next

it shows a blank window (sometimes) and loops on "Polling platform port..."

(yeah excellent choice of Guix)

**Comment by Ambrevar** [comment]
Yes, you can install it this way.  You can also extend your PATH environment
variable, or set `*gtk-webkit-command*` from your ~/.config/next/init.lisp.

It should only show "Polling platform port..." a couple of times.  Does it loop
indefinitely?

Have a look at /tmp/next-webkit-gtk.log for more details.

But did you manage to build next-gtk-webkit properly in the end?  If libsoup is
missing, it's not going to work :(

**Comment by vindarel** [comment]
ok thanks.

I'm surprised libsoup is an old version in this docker image (Debian testing) but thanks for the remainder. Have to (re(re))check.

yes it loops indefinitely.

**Comment by vindarel** [comment]
allright one more step, I made it work from within Docker.

**Comment by Ambrevar** [comment]
Great!

**Comment by jmercouris** [comment]
@vindarel any updates on this?

**Comment by vindarel** [comment]
I upgraded my Debian system and the installation worked smoothly, so I am not working on this Docker image anymore. Closing.
