### ISSUE TITLE
Error on AUR install - needs dependency `sbcl`

### ISSUE THREAD

**Issue by chris-aeviator** [atlas-engineer/next#156]
When installing next via AUR, I can only succeed when installing the dependency `extra/sbcl`. The PKGBUILD  should therefore include the package as an dependency to install.

**Comment by jmercouris** [comment]
@chris-aeviator thank you for bringing this to our attention!

**Comment by Ambrevar** [comment]
You are right.  I had initially written the PKGBUILD to support any Lisp
compiler (I assume you have some other lisp compiler installed?) but since now
it explicitly depends on sbcl.

I'll update the PKGBUILD, thanks for letting me know!

**Comment by Ambrevar** [comment]
Updated, thanks for reporting!
