### ISSUE TITLE
C-g hides some links if is too large

### ISSUE THREAD

**Issue by bbuccianti** [atlas-engineer/next#159]
Would be nice to minimize the amount of the "minibuffer" that prompts for the two letters of the link. When I try to open a link that is low in the page I can't see his letters.

**Comment by jmercouris** [comment]
I see, that makes a lot of sense! Thanks for the suggestion!

**Comment by eubarbosa** [comment]
Exactly!

**Comment by Ambrevar** [comment]
Fixed in 3d435b58a7869de5c720e726511f8075d68b008d.  Feel free to re-open if the issue persists.

**Comment by bbuccianti** [comment]
I have the same problem!

I haven't tried next in some time because I was using alpine, but now that we have next on alpine (not yet in aports) still the problem persists.

For example in help. When I'm in the bottom of the page and try to open a link to the manual with C-g, the minibuffer hide the link and I can't see the letters in order to go there.

Thanks!

**Comment by Ambrevar** [comment]
@bbuccianti : To clarify, when you press `C-g`, does the minibuffer expand or not?

**Comment by bbuccianti** [comment]
Yes!

It expands and it hides the bottom links!

**Comment by Ambrevar** [comment]
You must be using an old version.  C-g does not expand anymore since the
aforementioned commit.

**Comment by lxbarbosa** [comment]
@bbuccianti 
Latest version of Next have it fixed.

**Comment by bbuccianti** [comment]
Yeah! I don't see the new version. 

Sorry, C-g does no expand like you said.

Thanks!!
