### ISSUE TITLE
Prevent unnatural scroll behaviour when selecting candidates in completion menu

### ISSUE THREAD

**Issue by Compro-Prasad** [atlas-engineer/next#162]
Reproduction steps:
1. `C-h v`
2. `C-n` `C-n`
3. `C-p`
4. `C-n`

When pressing `C-p` the selection moves to the top. Pressing `C-n`(4) brings back the selection to where it was before pressing `C-p`. This is confusing to use.

**Comment by Ambrevar** [comment]
I can reproduce.

@jmercouris: Can you?

**Comment by jmercouris** [comment]
Yes this is in fact confusing/frustrating behavior and I can reproduce. Unfortunately it is the way webkit implements the query to show the visible element. There's nothing we can do about this short of writing a mini library of our own to show the position of an element on screen.

**Comment by Ambrevar** [comment]
I haven't studied the code much yet.  Can you explain the issue a little more?

I'm confused: if the cursor position is right when pressing "C-n C-n", why can't
we have the same display when pressing "C-p" afterwards?

**Comment by Ambrevar** [comment]
I understand there is an issue with the current code, but I'm quite convinced
that this problem has a solution.  Consider the following:

- M-x
- C-n C-n ... (enough until we reach the line before the last one).

Now we are in state A.  Then:

- C-n
- C-p

At this point, we would like to be in state A again.  But unfortunately, we are
in a state where the selected line is at the top.

If the desired state can be reached at some point, then there must be a way to
go back to that state.

**Comment by jmercouris** [comment]
Using the current implementation of Webkit which puts the current element in view, it is impossible to go back to state A, we would have to implement a browser native function ourselves, which will be very expensive time/computationally speaking

**Comment by Ambrevar** [comment]
This is fixed in pull request #356 !
