### ISSUE TITLE
[macOS] [10.14.2] [cocoa-webkit] Build fails - Error 65

### ISSUE THREAD

**Issue by rprimus** [atlas-engineer/next#163]
Thu Dec  6 09:11:57 GMT 2018

<details>
<summary>System Info:</summary>

#### OS:

 - ProductName:	Mac OS X
 - ProductVersion:	10.14.2
 - BuildVersion:	18C54

#### SBCL:
 - SBCL 1.4.13

#### XCode:
 - Version 10.1 (10B61)

<hr>
</details>

`make cocoa-webkit` [logfile](https://gist.github.com/526f9fd1379032711b83159cef87cee5)

This is my first time running `xcodebuild`.

`ports/cocoa-webkit/cocoa-webkit.xcodeproj/project.xcworkspace/contents.xcworkspacedata` contains:
```
location = "self:/Users/jmercouris/Work/Atlas/Next/next-core/ports/cocoa-webkit/cocoa-webkit.xcodeproj">
```

Would the above cause any problems?

**Comment by jmercouris** [comment]
hmm yes, indeed that would cause problems, I wonder why it hard-coded a directory on my machine, I will look into that thank you for the report!

**Comment by rprimus** [comment]
Thu Dec  6 10:04:10 GMT 2018

@jmercouris 

From the (linked) logfile above: any ideas about all the other errors?   Seems lots of header files from `/usr/local/include` are being referenced and generating errors.

**Comment by rprimus** [comment]
Thu Dec  6 11:38:20 GMT 2018

Yup - that matches with my setup:

<img width="1679" alt="xcode-next-cocoa-webkit_2018-12-06_11 39 26" src="https://user-images.githubusercontent.com/278414/49582111-e1259480-f94b-11e8-83f1-91f9277c3033.png">

Currently failing with 69 issues.  _Challenge_ accepted. :-)

**Comment by jmercouris** [comment]
Well, if you can figure it out, I would be very glad to accept a PR! It's strange because the frameworks library is right there, and all of libxmlrpc is in there, I wonder why it is complaining :\

-John

**Comment by rprimus** [comment]
Thu Dec  6 13:27:35 GMT 2018

```
169:    HEADER_SEARCH_PATHS = /usr/local/include/**
```

This accounted for the 68 build errors - all the errors seen in the logfile.
After un-setting this value, only 1 error remained:

```
/usr/local/src/next/ports/cocoa-webkit/cocoa-webkit/Buffer.m:8:10: fatal error: 'xmlrpc-c/base.h' file not found
#include <xmlrpc-c/base.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /usr/local/src/next/ports/cocoa-webkit/build/cocoa-webkit.build/Release/cocoa-webkit.build/Objects-normal/x86_64/Buffer.o /usr/local/src/next/ports/cocoa-webkit/cocoa-webkit/Buffer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by rprimus** [comment]
Thu Dec  6 13:35:45 GMT 2018

Looks like the header files for `xmlrpc` are missing:
```
: ; ag -ail 'xmlrpc-c'
libxmlrpc_util.3.39.dylib
libxmlrpc_client.3.39.dylib
libxmlrpc_abyss.3.39.dylib
libxmlrpc_xmltok.3.39.dylib
libxmlrpc_server_cgi.3.39.dylib
libxmlrpc_xmlparse.3.39.dylib
libxmlrpc_packetsocket.8.39.dylib
libxmlrpc_server_abyss.3.39.dylib
build/cocoa-webkit.build/Release/cocoa-webkit.build/Objects-normal/x86_64/Buffer.dia
libxmlrpc.3.39.dylib
cocoa-webkit/Buffer.m
cocoa-webkit.xcodeproj/project.xcworkspace/xcuserdata/rprimus.xcuserdatad/UserInterfaceState.xcuserstate
libxmlrpc_server.3.39.dylib
cocoa-webkit/NextApplication.m
cocoa-webkit/Global.h
cocoa-webkit/Server.m
cocoa-webkit/Window.m
cocoa-webkit/Global.m
cocoa-webkit/Minibuffer.m
```

**Comment by rprimus** [comment]
Thu Dec  6 13:40:24 GMT 2018

Have installe `xmlrpc-c`.  Testing ...

**Comment by rprimus** [comment]
Thu Dec  6 13:45:00 GMT 2018

Build succeeded with:
```
HEADER_SEARCH_PATHS = /usr/local/Cellar/xmlrpc-c/1.39.12/include/**
```

**Comment by jmercouris** [comment]
how do you propose we fix this problem?

**Comment by rprimus** [comment]
Thu Dec  6 13:58:55 GMT 2018

Attempting: `open build/Next.app` produces:
```
LSOpenURLsWithRole() failed with error -10810 for the file /usr/local/src/next/build/Next.app.
```

Running the binary:  `./build/Next.app/Contents/MacOS/next` *or* (next:start) from REPL produces
a continuous stream of:
```
Polling platform port...
```

**Comment by jmercouris** [comment]
ok, so the first thing that you have to do is run the Xcode application, since it seems that it is now working for you, and then after cocoa-webkit has started, in the repl type in (next:start). Also, completely restart the repl so that you can rebind s-xml-rpc.

Please let me know how that goes!

**Comment by rprimus** [comment]
Thu Dec  6 14:02:48 GMT 2018

> how do you propose we fix this problem?

Easiest would be to:
1. bundle xmlrpc-c with `next` source
2. adjust  `HEADER_SEARCH_PATHS` to point to where the header files are installed.

**Comment by jmercouris** [comment]
@rprimus would you be willing to make this fix? I'm not very familiar with Xcode nor how to do this, so I would be very grateful!

**Comment by jmercouris** [comment]
ah well, xcodebuild is the command line interface, not Xcode :P

I have the dylibs loaded just fine, and I use install name tool to set them up to point to those in the app bundle. If you take a look at the Next.app and run `otool -L cocoa-webkit` in the binary within the app bundle, you'll see what I mean. Of course you could also look at the Makefile :D

I understand if you don't have the time, I was just hoping you had the time/expertise, oh well, thank you for documenting the issue!

**Comment by rprimus** [comment]
Thu Dec  6 14:45:04 GMT 2018

PR done.

There's something different with my environment - hence the 68 errors when using the default
`HEADER_SEARCH_PATHS`.

May also explain the `dyld` problems - not using the libs under `cocoa-webkit`.

Would be good to have a macOS user test the PR - someone without `xmlrpc-c` installed.

**Comment by rprimus** [comment]
Thu Dec  6 14:50:54 GMT 2018

> Of course you could also look at the Makefile

WRT the Makefile,  would be good to:
1.  Replace target `all` with `linux`
2.  Add a `macos` target with deps: next cocoa-webkit
```
macos: next cocoa-webkit
```

**Comment by Ambrevar** [comment]
Sounds reasonable.  @jmercouris?

**Comment by jmercouris** [comment]
It does sound reasonable enough, so I would type "make macos"? how about "make darwin" instead, just because that sounds cooler? I'm of course ok with either but yeah :D

**Comment by rprimus** [comment]
Fri Dec 14 04:33:16 GMT 2018

After a `git pull`, `make cocoa-webkit` is still failing (with the same error):
https://gist.github.com/05ce874538434ac5f28a194805d0fba2

Removing `/usr/local/include/**` from `Header Search Paths` allows for a successful build:
https://gist.github.com/39614025c7a8c9ef9c83ae1cfd5db5c3

`open build/Next.app` now works properly.   Whoop, Whoop! 🥇 

(Will close this at noon EST.)

**Comment by jmercouris** [comment]
@rprimus thank you for verifying that it builds successfully! I wonder why removing `/usr/local/include/**` from the Header Search Paths was necessary though :\
