### ISSUE TITLE
Paste from clipboard

### ISSUE THREAD

**Issue by swedebugia** [atlas-engineer/next#166]
When I try S-INS (shift-insert) it does not paste.
Equally C-v does not paste.
Equally C-y does not paste.
Equally (mouse-middleclick) does not paste.

How do I paste?

**Comment by jmercouris** [comment]
As of today, without system clipboard integration, the only way to paste
is via right click "paste".

-John

**Comment by Ambrevar** [comment]
On GNU/Linux with GTK, "C-v" works.

**Comment by jmercouris** [comment]
unless of course you are trying to paste into the mini buffer, which does not work :D

**Comment by jmercouris** [comment]
however, it should be easy enough to use the minibuffer's self-insert and bind C-v in the minibuffer to paste the clipboard contents

**Comment by Ambrevar** [comment]
Wouldn't that insert "C-v"?

**Comment by jmercouris** [comment]
I was saying something like:

`(define-key *minibuffer-mode-map* (key "C-v") #'(lambda () (self-insert *minibuffer* (get-clipboard-contents))))`

if that makes sense

**Comment by Ambrevar** [comment]
Oh, absolutely.  What about using http://quickdocs.org/trivial-clipboard/ then?

**Comment by jmercouris** [comment]
that sounds like a good cross-platform solution!

**Comment by Ambrevar** [comment]
Implemented in be23c2e3ff0c31d3164e0202223d6e19ec78fc92.
Feel free to re-open if there is something else.
