### ISSUE TITLE
[GUIX] Unable to create server

### ISSUE THREAD

**Issue by eubarbosa** [atlas-engineer/next#169]
Hey, as I run  next on terminal I receive this error and it wont open

`Unable to create server: Could not listen on address 0.0.0.0, port 8082: Error binding to address: Address already in use`

Thanks

Debian SID
Guix 0.16 (guix-install.sh)
T430

**Comment by Ambrevar** [comment]
Check your running processes and kill all "next" / "next-gtk-webkit" that are running, then try again :)

For now we have limited subprocess management, we are working on it.

Also note that you can configure both ports from Lisp, e.g.
```lisp
(setf *core-port* 8888
  (getf *platform-port-socket* :port) 8889) 
```

**Comment by eubarbosa** [comment]
oh great!

**Comment by eubarbosa** [comment]
Next won't open.

Might be a something only on Guix package as Next works correctly by locally compiling it!

**Comment by Ambrevar** [comment]
It works here on GuixSD.  Please post the commandline plus backtrace when you start it, and post the content of /tmp/next-gtk-webkit.

**Comment by Ambrevar** [comment]
@eubarbosa : Could you fix the issue?  What was the problem?
