### ISSUE TITLE
Document Guix install steps

### ISSUE THREAD

**Issue by dangirsh** [atlas-engineer/next#170]
I was unable to find instructions for installing next with Guix. 

Eventually, I found [this issue](https://github.com/atlas-engineer/next/issues/92), which led me to believe the magic command was `guix package -i sbcl-guix`.

Originally, I tried unpacking the linkned `.tar.lz`. Some searching around led me to use `lzip -d`, then `tar -xf` to extract it. I ran `bin/next` from the extracted archive, but got

```
dan@dan-dell:~/Downloads/bin$ ./next
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_US.UTF-8
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10005885B3}>:
  Couldn't execute "/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit": No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005885B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1003792243}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1003792243}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1003792243}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1003792243}>)
4: (SB-KERNEL::%SIGNAL #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {1003792243}>)
5: (ERROR "Couldn't execute ~S: ~A" "/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit" "No such file or directory")
6: (RUN-PROGRAM "/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit" ("--port" "8082" "--core-socket" "http://localhost:8081/RPC2") :ENV NIL :ENVIRONMENT NIL :WAIT NIL :SEARCH T :PTY NIL :INPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :OUTPUT #P"/tmp/next-gtk-webkit.log" :IF-OUTPUT-EXISTS :APPEND :ERROR :OUTPUT :IF-ERROR-EXISTS :APPEND :STATUS-HOOK NIL :EXTERNAL-FORMAT :UTF-8 :DIRECTORY NIL)
7: (UIOP/LAUNCH-PROGRAM:LAUNCH-PROGRAM ("/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit" "--port" "8082" "--core-socket" "http://localhost:8081/RPC2") :OUTPUT #P"/tmp/next-gtk-webkit.log" :ERROR-OUTPUT :OUTPUT)
8: ((:METHOD NEXT::RUN-PROGRAM (NEXT::PORT)) #<NEXT::PORT {1001CB0BF3}>) [fast-method]
9: (NEXT:START :WITH-PLATFORM-PORT-P T)
10: (NEXT-EXEC:MAIN)
11: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
12: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10035CE84B}>)
13: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-27" :IN SAVE-LISP-AND-DIE))
15: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

`uname -a`: Linux ... 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Hopefully someone with a better understanding of next + Guix can piece this into a coherent install guide!

**Comment by Ambrevar** [comment]
Are you familiar with Guix or did you  just install it because of Next?

When I wrote this part of the README, I imagined that Guix users would know how
to install the package (indeed with `guix package -i sbcl-next`).

I guess adding the command to the README would not hurt ;)

Regarding the Guix pack: it's currently broken, I'm working on it.  Sorry for
the mess!

**Comment by dangirsh** [comment]
This line in the README made me believe installing Guix was the best path to getting Next running on Linux:

"Guix is a package manager that can be installed on any GNU/Linux distribution; should Next be missing from your distribution, there is always the possibility to install Guix on your system and use it to install Next."

It seems like the best current approach for most (non-Arch / non-GuixSD) GNU/Linux users would actually be to build from source. If so, maybe a simple re-wording of the README would be the best action.

**Comment by Ambrevar** [comment]
I'll reword it then.

Both approaches are fine:

- If Guix is easily available for your distribution (e.g. as a package), then
  this is definitely the simplest route.
- If not, or if you want to help developing Next, then building from source is
  the commended route.

Hopes that makes sense!

Does it work well with the Guix package by the way?

**Comment by dangirsh** [comment]
Great, thanks.  Might be helpful to also give the Guix package name and full install command. My guess is that many people trying the Guix option will be using Guix for the first time. 

I ended up running `guix package -i sbcl-next`. It took a few hours on my laptop to build the deps. When it finished I had to run `export PATH="/home/dan/.guix-profile/bin${PATH:+:}$PATH"` (helpfully recommended by Guix. Finally I had `next` in my path. Simple navigation tests make me think it's working OK.

Both the source build and Guix require fairly advanced GNU/Linux skill + patience. Can Guix be used to produce a standalone binary for Linux users just looking to quickly try Next?

**Comment by Ambrevar** [comment]
> Might be helpful to also give the Guix package name and full install command.

What do you mean?  Isn't  `guix package -i sbcl-next` enough?

> It took a few hours on my laptop to build the deps.

You can use a substitute server (which might not be enabled by default on your
system) to get the pre-built binary.  In which case it will install in seconds.
See https://www.gnu.org/software/guix/manual/en/html_node/Substitutes.html.

> Can Guix be used to produce a standalone binary for Linux users just looking
> to quickly try Next?

That's what I'm working on.  Sadly I'm facing a blocking issue: the result
cannot use XML-RPC properly, not sure why.  See issue #160.

**Comment by dangirsh** [comment]
> What do you mean?  Isn't  `guix package -i sbcl-next` enough?

Yes, just didn't see you recently updated the README with that.

Thanks for the info on the substitute server. Ubuntu 16.04 users won't have this as a default.

Glad to hear you're working on a standalone binary.
