### ISSUE TITLE
Debian stable users shouldn't use testing packages

### ISSUE THREAD

**Issue by equwal** [atlas-engineer/next#171]
Using the wrong fork packages in debian is [not recommended as it has a tendency to blow up the operating system](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) through dependency issues. The right recommendation is to upgrade the whole system to the testing fork.

**Comment by jmercouris** [comment]
I'm not sure what exactly you're trying to say here. You'll have to be more specific with regards to what exactly you wish for us to change.

**Comment by equwal** [comment]
Don't recommend using the testing repository from stable, instead recommend reinstalling the operating system as testing.

**Comment by Ambrevar** [comment]
Agreed, I'll merge this recommendation.
