### ISSUE TITLE
Something like Noscript & vertical tabs

### ISSUE THREAD

**Issue by Atreus-Tantalus** [atlas-engineer/next#174]
Any plans for implementing noscript like ability to block individual scripts on websites and/or vertical tabs?

**Comment by Ambrevar** [comment]
I think Atreus-Tentalus meant "tabs laid down vertically".  You can do that with
Firefox.

That said, I think Next takes the right approach with the concept of "buffers".
Conversely, a vertical, side-by-side display of the minibuffer would fit the
"vertical tabs" role.

**Comment by Ambrevar** [comment]
Also see #55.

**Comment by Ambrevar** [comment]
There is now a Noscript mode, but we still miss a good way to hook it per-domain.  Also see #237 for hooks.

Vertical tabs are still to be implemented.

**Comment by Ambrevar** [comment]
We can now toggle modes per-domain with the `request-resource-hook`.

Closing this, refer to #55 for the vertical minibuffer.
