### ISSUE TITLE
Feature request: Send keystroke directly to renderer

### ISSUE THREAD

**Issue by swedebugia** [atlas-engineer/next#177]
vimb has this. c-v they choose for this.
It is real nice e.g. when using web-applications like roundcube.

**Comment by jmercouris** [comment]
see application-mode.lisp, if you also did a setf on the global bindings and saved them in a slot while you were in that mode, you would effectively unbind everything,

-John

**Comment by Ambrevar** [comment]
I'm a bit confused here:

- What setf?
- Which slot?
- How do we switch to application mode?

**Comment by jmercouris** [comment]
I'm saying you'd switch the mode to application-mode.lisp (which is designed with this intent), and then you would do something like `(setf *global-map* (make-hash-table))` and store the existing =*global-map*= in a slot of application-mode.

Then you'd have to bind at least one key within application-mode called something like "q" for "quit" and it would reassign =*global-map*= to the original =*global-map*= hash table, and switch to the the previous mode, or another mode in that buffer. Does that make sense?

**Comment by Ambrevar** [comment]
Yes it does, thanks for clarifying.

Now we need to need to think about modes: Can we activate several modes at once?
If so, then we would need to nullify all active mode maps, right?

**Comment by jmercouris** [comment]
Only one mode may be active at once (per buffer). However, though not yet designed, one should probably be able to have multiple minor modes, much like Emacs.  I've been thinking about this idea for a long time. What are minor modes in the context of Next? I don't know, something we'll have to think about, however that does not pertain to this particular problem and is a bit off tangent :D.

**Comment by noctuid** [comment]
On a related note, it would be nice to be able to bind keys to passthrough other keys (e.g. see qutebrowser's [fake-key](https://qutebrowser.org/doc/help/commands.html#fake-key)). An example use case is changing the keybindings for some sites that support keyboard shortcuts (e.g. gmail).

**Comment by Ambrevar** [comment]
You can already to it with the `rpc-generate-input-event' function.
There is no high-level approach for this.
Note that we have a dummy "application-mode" that is supposed to
implement it.
It's not too hard to finish, just got to find the time to sit down... :)
