### ISSUE TITLE
[C-x b] Switch to next buffer if there only two buffers open

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#179]
Hey, I dont think that even Emacs has it:

If there are only two buffers open, C-x b would just switch to  the next buffer imeddiately...

That is it! :D

**Comment by Ambrevar** [comment]
Inded, that's a cool idea, thanks for the suggestion!

Would you like to work on this?  It would be an easy first contribution ;)

**Comment by jmercouris** [comment]
I disagree that this is a good idea, I think inconsistent UI is bad practice. C-x b should always show you the buffer list so you can be aware there is only one other buffer

**Comment by Ambrevar** [comment]
I misunderstood the initial request: I thought that @eubarbosa meant that the defalut selected buffer should be the "other one".

At the moment, with two buffer, `C-x b` will always default-select the same buffer.  It would be convenient if we could just press `C-x b RET` to always switch back to the other buffer.

**Comment by eubarbosa** [comment]
> I misunderstood the initial request: I thought that @eubarbosa meant that the defalut selected buffer should be the "other one".
> 
> At the moment, with two buffer, `C-x b` will always default-select the same buffer. It would be convenient if we could just press `C-x b RET` to always switch back to the other buffer.

Or, C-x b SPACE?

**Comment by jmercouris** [comment]
The thing with the buffer order is that it is based on the buffer creation order and not on last access. We aren't using a stack or anything like that (which would recreate Emacs default behavior), since it is basically just the hash-table values dumped by Alexandria. We could compose a data structure that combines the two to reproduce this kind of behavior (the re-ordering of the buffers).

**Comment by vindarel** [comment]
I think something should be done about this, I find it annoying too. We could simply ensure that the first choice isn't the current url.

**Comment by Ambrevar** [comment]
I suggest the following: add an "access-time" slot to buffers and add a
fuzzy-match sorting function to sort by access-time for buffers.

Makes sense?

**Comment by jmercouris** [comment]
I suggest just using a stack, I don't think it is necessary to perform a sort based on access-time.

**Comment by jmercouris** [comment]
That is, making the data structure I was talking about, we could it a `hash stack` :D

**Comment by Ambrevar** [comment]
Why `hash stack`?

The thing with access-time is that it's more universal, because then we could use the same functions for bookmarks, history entries, commands, etc.

**Comment by jmercouris** [comment]
Couldn't you also use a `hash stack` for all of those other use cases :D?

Anyways, we could have a more generic sort: how about we just have a value as we had talked about called "weight", for some candidates it will be the time. Then we just sort by weight. A small difference for sure, but a more generalized concept than having access-time specifically.

**Comment by vindarel** [comment]
related: #290

**Comment by Ambrevar** [comment]
I think we are talking about the same thing :p

Note that you want to compute the weight (a.k.a. score) at run time,
orthogonal to the data structure, because the user might want to
customize it.

**Comment by jmercouris** [comment]
Ah, indeed!
