### ISSUE TITLE
[GUIX] Next do not remember passwords 

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#181]
Hi, As I close Next and run it again it is not saving password even if "remember me" is selected.

It do remembers all my bookmarks, though! 

Related to: https://github.com/atlas-engineer/next/issues/180

Thanks !

**Spec:**
sbcl-next
Guix 0.16 (user install)
Debian SID
Awesome 4.3
Kernel 4.19
Lenovo T430

**Comment by Ambrevar** [comment]
Are you running Next 1.2+?

Which website?

Can you check if the cookies are save in ~/.local/share/next?

**Comment by eubarbosa** [comment]
the latest next from Guix 
reddit, github, gitlab ...

No cookies... at all, just bookmark.db and history.db

https://i.ibb.co/3ND52RZ/shot-2018-12-25-T12-16-35-02-00.png

**Comment by Ambrevar** [comment]
Oops!  Looks like this slipped under my radar...  Sorry about that.
Cookies should be stored properly with Next 1.2.0 onwards.
Make sure that no Next process is already running, i.e. kill everything then restart it.

Regarding your last issue, this will be fixed in the upcoming release.

**Comment by Ambrevar** [comment]
(Closed accidentally.)

**Comment by Ambrevar** [comment]
This should be fixed in Next 1.2.1. Feel free to re-open if you still experience the issue.
