### ISSUE TITLE
Use the webview library instead of writing platform ports

### ISSUE THREAD

**Issue by mardukbp** [atlas-engineer/next#189]
The [webview](https://github.com/zserge/webview) library is cross-platform and uses the native web renderer in macOS, Windows and Linux.

Thank you so much for this project! I have been dreaming of a browser like this for a long time.

**Comment by jgkamat** [comment]
On February 15, 2019 7:26:42 AM PST, "Marduk Bolaños" <notifications@github.com> wrote:
>The [webview](https://github.com/zserge/webview) library is
>cross-platform and uses the native web renderer in macOS, Windows and
>Linux.


I don't see the advantage of this library over using webkitgtk directly, it seems to use webkitgtk itself.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mardukbp** [comment]
It uses webkitgtk only on Linux. In my view, it frees the Next devs from maintaining the bindings to the rendering engines of each platform, which gives them time to write more Lisp :)

**Comment by jmercouris** [comment]
an interesting idea to look into, however we were also planning on a pyqt platform, what are some reason we might choose this over pyqt?

**Comment by mardukbp** [comment]
IMHO, using PyQt amounts to adding a lot of complexity on top of Chromium, which sits at the core of the QtWebEngine module. I would say that the platforms should be the web engines themselves: WebKit, Blink (through the Chromium Embedded Framework), MSHTML/Trident, Gecko-Quantum.

webview uses native windows and provides bindings to Cocoa WebKit, GtkWebKit and MSHTML. The minibuffer can be implemented with JavaScript inside of the window. This is very similar to how Emacs works. In addition, minimal dependencies simplify development a lot.

**Comment by jmercouris** [comment]
The mini buffer is already implemented with JavaScript inside the window. However, for reasons of sandboxing, it is a completely separate web view. Why? Because we wish to be able to invoke Lisp code directly when the user clicks on something within the minibuffer. Could we get this same level of security if we were using an embedded JavaScript minibuffer within the main window? I don't believe so, but correct me if I am wrong.

**Comment by mardukbp** [comment]
You are right. What I really meant is that the minibuffer does not need List widgets from Qt or Gtk. That kind of UI can be implemented with JS. The windows can be provided by the cross-platform [UI library](https://github.com/andlabs/ui) for Go, which uses native widgets.

**Comment by jmercouris** [comment]
I'm not sure I understand what you are saying, can you please clarify? We would or would we not use a separate webview?

**Comment by mardukbp** [comment]
Yes. I agree with you that they are necessary for security. I am just saying that one could avoid using big GUI toolkits just to get a window with two panels.

**Comment by mardukbp** [comment]
After doing some research and thinking about it, I concluded that it is better to stick to what you have now, which coincides with my idea above: the platforms should be the web engines themselves. Wrappers reduce flexibility. And webview is meant for developing SPA in JS.

I leave it up to you to close this issue or leave it open just to remember that webview exists. It should provide some hints to implement the Windows port of Next ;)

**Comment by Ambrevar** [comment]
I find it interesting, actually.  It might be better than the python/qtwebengine approach, but I'd need to have a closer look at `webview` to make sure.

**Comment by mardukbp** [comment]
Well, I wouldn't discard a Chromium port. That is actually a cross-platform web renderer. And, [apparently](https://github.com/cztomczak/cefpython), PyQt could provide an easy route to implementing it.

**Comment by vindarel** [comment]
That was a constructive suggestion. We went with PyQt, which isn't offered by Webview.
