### ISSUE TITLE
Use Go instead of C

### ISSUE THREAD

**Issue by mardukbp** [atlas-engineer/next#190]
Go has built-in XML and RPC libraries, there is a [UI library](https://github.com/andlabs/ui/) with native bindings for macOS, Windows and Linux, there is a [JavaScript compiler](https://github.com/gopherjs/gopherjs), it has bindings to the [webiew](https://github.com/zserge/webview) library, and it makes it really easy to [deploy](https://goreleaser.com) cross-platform applications.

**Comment by jgkamat** [comment]
On February 15, 2019 7:44:45 AM PST, "Marduk Bolaños" <notifications@github.com> wrote:
>Go has built-in XML and RPC libraries, there is a [UI
>library](https://github.com/andlabs/ui/) with native bindings for
>macOS, Windows and Linux, it has bindings to the webiew library, and it
>makes it really easy to deploy cross-platform applications.

Where is the C code that will be replaced? 

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mardukbp** [comment]
In the ports directory there are C headers interacting with C libraries.

Don't get me wrong. I just think that Go has got everything that Next needs and it could simplify the development.

**Comment by Ambrevar** [comment]
I guess this could work.  I'm still not completely sure we would really benefit from it, as "Go-over-webview-over-[webkitgtk|whatever]" would add a significant layer of complexity.

Anyways, it would not cost much to write a "Go platform port" as it would work side by side with the current ports.  @mardukbp: Would you like to propose a patch?

**Comment by mardukbp** [comment]
On the bright side, webview is a single-header library that provides an interface to the native rendering engine of the three major operating systems. Plus, the Go bindings are officially supported. I really think it would be a good match for Next. I will work on it in my free time and let you know.

**Comment by mardukbp** [comment]
I have been thinking that the XML-RPC client-server infrastructure should be independent from the rendering engines. As stated in the README of the `ports` directory, it is the bridge between Lisp and the ports. Therefore, it should be a common component living in a separate directory. And I think that go is the right tool for the job.

What do you think?

**Comment by jmercouris** [comment]
If I am understanding correctly, the XML-RPC should have a middleware between the Lisp Core and a Platform Port? Why? Could you please clarify the logic behind adding another layer to the stack?

**Comment by mardukbp** [comment]
No, I am not suggesting to add a new layer. What I am saying is that the XML-RPC client-server coupled to the ports could be factored out. As I see it, this component is platform-independent, but it interacts with platform-specific GUI and web renderers. 

What I have in mind is a modular design in which each port consists of a GUI, a web view, and an implementation of the `port` interface. The XML-RPC client-server interacts with a `port`, but it does not need to know how each port implements the interface (I hope the difference between `port` and port is clear).

**Comment by Ambrevar** [comment]
The XML-RPC component in the platform port is tightly coupled with the underlying web renderer.  There is almost no platform independent code at all.  Or did I misunderstand what you meant?  Maybe you can provide a concrete code example?

**Comment by mardukbp** [comment]
I know that. The question is whether that is really necessary or a good idea. The goal of Next is to provide a web engine-agnostic emacsy web browser. Therefore, it is important to distinguish which parts are platform-agnostic and which are platform-specific.

For example, the list of buffers and the minibuffer as data structures are common to all platforms. However, their visual representation with the native GUI toolkit is platform-specific. The signals zoom in/out, scroll, hide/show minibuffer, etc. are also common to all platforms, but they have a platform-specific implementation. In my view, the XML-RPC client-servers should provide the interface between the platform-agnostic parts of Next.

Once again, I just want to help Next fulfill its purpose of being a high-quality browser for power users. That entails using a modular design and providing abstract interfaces between its components in order to keep the code as small and simple as possible.

**Comment by timmyjose** [comment]
@mardukbp I still don't get what would be the actual benefits of using Go specifically in lieu of the existing C, even given the architecture you have in mind.  Could you elaborate?
