### ISSUE TITLE
'make all' on Debian 9 fails

### ISSUE THREAD

**Issue by drysdam** [atlas-engineer/next#192]
[output.txt](https://github.com/atlas-engineer/next/files/2877193/output.txt)

**Comment by Ambrevar** [comment]
Hi @drysdam, this is an issue with SBCL (and many other libraries) being heavily outdated on Debian 9.  In particular, WebKitGTK is quite old on Debian which can is most critical, considering the speed at which web renderers evolve.
You need at least Debian Testing (or Unstable?) to compile Next.

**Comment by Ambrevar** [comment]
Alternative, if updating/re-installing your system is not an option, you can consider installing [Guix](https://guix.info): it works side to side with your current system and allows you to install a whole bunch of (mostly up-to-date) packages, including Next.

**Comment by Ambrevar** [comment]
Closing.  Feel free to re-open if there is anything else.
