### ISSUE TITLE
How to fix this giant status bar to be more-like a mini-buffer?

### ISSUE THREAD

**Issue by ryukinix** [atlas-engineer/next#194]
![](https://imgur.com/E0NUhuQ.png)

**Comment by bradjcheme** [comment]
For what it's worth if you hit `C-f' it will go away.

**Comment by ryukinix** [comment]
Thanks @bradjcheme! That's a nice workaround, i'll use. However, do you know how to limit the height of this pane for the moment that is recreated?

**Comment by jmercouris** [comment]
This is an implementation problem with the webkit-gtk port and I do not know if it can be fixed without updating the webkit-gtk port. It is on our radar though! You can also type in `C-x q` to dismiss the echo area.

**Comment by ryukinix** [comment]
Good news! o/ at leasting is not only in my machine. Thanks for the nice reception and info.

This project it's incredible. I really afford it. I hope I can contribute with something oneday, I have some Common Lisp experience but not that much.

**Comment by Ambrevar** [comment]
Lo and behold!  One of Next's most tenacious bug has just been fixed with e23232844f4425ae7ceada0d955da2f76cd80507!

**Comment by ryukinix** [comment]
Great news!
