### ISSUE TITLE
Add a document to interact with JavaScript

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/next#204]

**Comment by jmercouris** [comment]
I would be willing to extend the documentation, but not add a document specifically about dealing with JavaScript interaction. I am however willing to listen to any rationale for why adding a document specifically about JS only would be advantageous.

**Comment by alexherbo2** [comment]
Can we talk on [IRC]?

[IRC]: https://webchat.freenode.net?channels=nEXT-Browser

**Comment by togakangaroo** [comment]
I'll note that I'm specifically clicking around because I'm interested in this project but trying to figure out if yall run javascript without having to install the darn thing

**Comment by jmercouris** [comment]
We don’t run javascript, no. We use parenscript which compiles to Javascript, but that is mostly a technical detail.

**Comment by togakangaroo** [comment]
Yeah, I guess maybe I misunderstood this issue too. 

My point was to say that I came to this project because I - like everyone - want to not leave emacs to browse websites. The first question that I had upon browsing was "will this work with websites that require javascript to run?". After 10 or so minutes I couldn't figure that out easily.

It would be a good idea to have this clearly spelled out up front in the docs, I'm sure I'm not the only one with that question.

**Comment by Ambrevar** [comment]
This is a full blown browser: it uses WebKitGTK or QtWebengine as a
backend to render the websites and execute Javascript.

I guess for most users, this would be the expected behaviour from a web
browser.  So I believe that mentioning that Next can execute Javascript
is only stating the obvious ;)

**Comment by togakangaroo** [comment]
Maybe. It's just that all the screenshots are of Wikipedia that is like the
one page remaining on the web that doesn't require J's (and good for them).
How about just adding a screenshot of Facebook running or something?

**Comment by vindarel** [comment]
oh we can do that fore sure :)

**Comment by Ambrevar** [comment]
I'd rather not display Facebook though :p

Let's focus on free software.
Mastodon could be a nice option.

Jitsi would be even better, when we support WebRTC that is to say ;)

**Comment by jmercouris** [comment]
I think this is a non-issue. The exception does not make the rule!

**Comment by vindarel** [comment]
> Mastodon could be a nice option.

sure, don't you worry, moreover it's impossible for me to see fb since I added this satisfactory hook:

```
;; For *you* who shouldn't use Facebook ;)
(defun no-facebook-hook (url)
  "Always redirect to Diaspora."
  (let ((uri (quri:uri url)))
    (if (search "facebook.com" (quri:uri-host uri))
        (progn
          (setf (quri:uri-host uri) "pod.geraspora.de")
          (let ((new-url (quri:render-uri uri)))
            (log:info "You shall not go to Facebook!" new-url)
            new-url))
        url)))
(add-to-default-list #'no-facebook-hook 'buffer 'load-hook)
```
