### ISSUE TITLE
No column "visits" in typed table

### ISSUE THREAD

**Issue by latiagertrutis** [atlas-engineer/next#205]
I was getting this error when running next (compiled from source in Manjaro 18.0.4):
```
debugger invoked on a SQLITE:SQLITE-ERROR in thread
#<THREAD "main thread" RUNNING {10005D05B3}>:
  Could not prepare an sqlite statement.
Code ERROR: table typed has no column named visits.
Database: /home/unchartech2/.local/share/next/history.db
SQL: insert into typed (url, visits) values (?, 1) on confisits = typed.visits + 1

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from

restarts (invokable by number or by possibly-abbreviated n
  0: [ABORT] Exit from the current thread.

(SQLITE:SQLITE-ERROR :ERROR "Could not prepare an sqlite s:DB-HANDLE #<SQLITE:SQLITE-HANDLE {100555C9F3}> :SQL-TEXT isits) values (?, 1) on conflict (url) do update set visit
   source: (ERROR
            (IF (EQ ERROR-CODE :CONSTRAINT)
                'SQLITE-CONSTRAINT-ERROR
                'SQLITE-ERROR)
            :FORMAT-CONTROL
            (IF (LISTP MESSAGE)
                (FIRST MESSAGE)
                MESSAGE)
            :FORMAT-ARGUMENTS
            (IF (LISTP MESSAGE)
                (REST MESSAGE))
            :DB-HANDLE DB-HANDLE :ERROR-CODE ERROR-CODE :E
            (IF (AND DB-HANDLE ERROR-CODE)
                (SQLITE-FFI:SQLITE3-ERRMSG (HANDLE DB-HAND
            ...)
```

I added the column manually and it works fine:
```SQL
ALTER TABLE typed ADD COLUMN visits int;
```

Just a little report, keep it up and kind regards.

**Comment by latiagertrutis** [comment]
Hmmm, probably this was caused because was previously installed from Arch AUR repository, and the table created with this AUR version was not updated and did not contain visits.

**Comment by Ambrevar** [comment]
Thanks for reporting.

I had taken provisions for updating the history database to include the
new "visits" field, but it seems that in your case it didn't work.

Did you solve the issue?  How?

**Comment by latiagertrutis** [comment]
The point is that before compile it from source I installed it from the [AUR](https://aur.archlinux.org/packages/next-browser-git/) repository (not updated since 2018-12-20) so when executed this binary it generated a table that I assume that has a different format from the new version of your git repository, so when launched the binary compiled from the git, it detected that the DB was already created. Then just removing the "cache" in `~/.local/share/next` solved it, or adding the column manually from sqlite also works.

**Comment by Ambrevar** [comment]
I understand.  But the latest versions should add the "visits" column
automatically to an existing history database.  We must obviously be
doing this wrong :p

Do you know a bit of Common Lisp?
If so, you can have a look at `%initialize-history-db` in `history.lisp`
if you can spot the problem.

**Comment by latiagertrutis** [comment]
I started learning Common Lisp a few days ago, but I'll be glad to help if you are not in hurry for this point.

**Comment by easye** [comment]
@Ambrevar I ran into the same problem this morning trying to run `master`.  I saved a copy of the database that refused to update if you would like to diagnose it.

**Comment by Ambrevar** [comment]
Sure, feel free to send it to me, I'll have a look.
Do you have any idea what could cause the issue?  (It could be my
misunderstanding of SQL, I'm not very good at it.)

**Comment by easye** [comment]
Sent via email.

**Comment by Ambrevar** [comment]
Fixed on master!
Thank you @latiagertrutis and @easye!
