### ISSUE TITLE
On Mac OS, can't type space or return

### ISSUE THREAD

**Issue by stevenbagley** [atlas-engineer/next#208]
Next version 1.2.1, Mac OS 10.14.4

Navigate to www.google.com. Type "this is a test". The spaces don't echo, and I can't enter using the RETURN key.

**Comment by pbgc** [comment]
1.2.1 and MacOX 10.14.4 here.

I cannot use ESC 

If I press ESC ... NExt crashes. Running it from the command line I get:

`debugger invoked on a SB-INT:SIMPLE-STREAM-ERROR in thread
#<THREAD "main thread" RUNNING {10006605B3}>:
  Couldn't write to #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8081, peer: 127.0.0.1:57494" {1004B8D7A3}>:
    Broken pipe

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 4: #<CLOSURE (LAMBDA
(
                                                                                         S-XML-RPC::FD)
                                                                                      :IN
                                                                                      S-XML-RPC::START-STANDARD-SERVER) {1007B12B2B}>>
1: [ABORT            ] Exit from the current thread.

((FLET "H0" :IN S-XML-RPC::XML-RPC-SERVER-CONNECTION-HANDLER) #<SB-INT:SIMPLE-STREAM-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {1004B96743}>)
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0]`

**Comment by jmercouris** [comment]
Interesting. I'm not sure if we are capturing or handling space anywhere in the codebase, but it seems they are not being properly created by the endpoint that is supposed to generate events

**Comment by kreisys** [comment]
Does `M-l` work for you on macOS?

**Comment by jmercouris** [comment]
It seems not at the moment, latest release broke some things. The new PyQt port should address all of these issues though. Sorry for the problems!

**Comment by NuclearKev** [comment]
Mine crashes when I hit the `esc` key as well. It also seems like meta doesn't work because I can't run any meta commands.

**Comment by jmercouris** [comment]
Hi Kevin,

this is correct, working on a new macOS release, thanks for your patience!

**Comment by jmercouris** [comment]
Fixed on master :-)
