### ISSUE TITLE
Google as default search engine

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#214]
I prefer using FLOSS everywhere, and DDG partly covers me well on that topic, but a general browser should not be that optionated unless is there any other issue I am unaware about.

I reckon that most users init files will just overide ddg with google, so why not just make it easier! 

What you all think about this?

Thanks!

**Comment by Ambrevar** [comment]
Hi!

Opinionated about the default browser?  You can change it in your
init.lisp if that's what you are asking.

Or are you suggesting we put Google as a default search engine?

**Comment by alexanderbarbosa** [comment]
@Ambrevar 

yes, indeed, that what I do, as most probably do/will too. 

Google as default search engine, but on that point, I argue that its kinda too pushy choosing some cool services instead of "famous" ones.

IMHO!

**Comment by jmercouris** [comment]
To be absolutely clear, we will not set Google as the default search engine as it is completely against the ethos of Next

**Comment by alexanderbarbosa** [comment]
@jmercouris 
Oh! I understand now. fair enough!

**Comment by Ambrevar** [comment]
While DuckDuckGo stands for privacy, it does not give many guarantees
either.  In particular, it's not free software.

The only free software option that I know of is
https://asciimoo.github.io/searx/.  Unfortunately, I find the result
rather poor in practice.  We could still make it the default and make it
more obvious in the documentation on how to change it.

Thoughts?

**Comment by Ambrevar** [comment]
To clarify: Searx is a meta engine, so its results depends on other search engines.  Searx can be configured to retrieve Google, DuckDuckGo and many other sources results.

The nice thing with Searx is that it's rather easy to use a local instance.  With Guix, it would be easy to have Next rely on it.

About using public instance, from Searx' doc:
```
If someone uses a public instance, he/she has to trust the administrator of that instance. This means that the user of the public instance does not know whether his/her requests are logged, aggregated and sent or sold to a third party.
```

**Comment by alexanderbarbosa** [comment]
@Ambrevar 
Cool, using searx now! ...

**Comment by vindarel** [comment]
> The only free software option that I know of

Yacy ! http://search.yacy.net/ Works on distributed, peer-to-peer instances. Results are… different, too few people run instances. And the search doesn't work right now.

**Comment by Ambrevar** [comment]
Interesting!  Never heard about it, and yet it seems to be... 14 years
old :p
