### ISSUE TITLE
Support for key code mappings

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/next#215]
It could be nice to be able to map physical keys on the keyboard (as opposed to the characters generated by pressing keys).

**Comment by Ambrevar** [comment]
There is provision for hardware keycode support, although `define-key`
does not expose it.
If you look at the `key-chord` structure, you'll see it has a `key-code` slot.

Patches are welcome!  Otherwise, I'll work on it when I start working on
the VI bindings.

**Comment by Ambrevar** [comment]
Fixed in 3feb084adf6e2f6af0db6bf75e6aad619cc77655.
To bind a command to a key code, use the `#N` syntax, where N is the hardware keycode.
For instance "C-#38" is equivalent to "C-a" on my keyboard with a qwerty keymap.
