### ISSUE TITLE
Next ignores history if using mice to acess links

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#219]
Hi, 

Using mice to surf through pages links and going backward on history (c-b), Next jumps to the earliest page that user use links-hint (c-g) or start page.

**Reproduce:**
- open github.com page
- click on pull EXPLORE link (navbar)
- click on any repository
- hit c-b (back on history)
- jump to github.com page, instead of EXPLORE page.

------
OS: Debian
Next (cfe5ae5) (1.2.2)

**Comment by jmercouris** [comment]
Hi, can you please try on a site that doesn't use jquery to load things?

**Comment by alexanderbarbosa** [comment]
@jmercouris 
You spot in on. 
Cnn, reddit and twitter work as it is supposed.
