### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by seanfarley** [atlas-engineer/next#225]
Unfortunately, it seems I cannot run this due to an assumption that the filesystem is case-insensitive. I had a pull request a while ago to fix the `next` -> `nEXT` but it seems other dependencies are also missing (perhaps dynamic loading?). I didn't have time to figure out which ones but at the very least not a single keybinding is working.

Just making this issue in case someone has time to investigate more.

**Comment by Ambrevar** [comment]
Thanks for the report, but you might be looking in the wrong direction, we make no assumption on case sensitivity.
We spell it "Next" in writing and `next` in the code.

**Comment by seanfarley** [comment]
Oops, sorry I (out of habit) typed `nEXT`. I meant that I couldn't compile the cocoa port due to typos in capitalization:

```diff
diff --git a/ports/cocoa-webkit/CocoaWebkit/NextApplicationDelegate.m b/ports/cocoa-webkit/CocoaWebkit/NextApplicationDelegate.m
index e618c4f..09c89f0 100644
--- a/ports/cocoa-webkit/CocoaWebkit/NextApplicationDelegate.m
+++ b/ports/cocoa-webkit/CocoaWebkit/NextApplicationDelegate.m
@@ -6,7 +6,7 @@
 #import "NextApplicationDelegate.h"
 #import <AppKit/AppKit.h>
 #import <Foundation/Foundation.h>
-#import <Webkit/Webkit.h>
+#import <WebKit/WebKit.h>
```

But even after compiling this is the error:

```sh
$ open build/Next.app
The application cannot be opened because its executable is missing.
```

And to fix that required:

```diff
diff --git a/assets/Info.plist b/assets/Info.plist
index 4e655ed..47368a0 100644
--- a/assets/Info.plist
+++ b/assets/Info.plist
@@ -13,7 +13,7 @@
     <key>CFBundleSignature</key>
     <string>????</string>
     <key>CFBundleExecutable</key>
-    <string>Next</string>
+    <string>next</string>
     <key>CFBundleIdentifier</key>
     <string>engineer.Atlas.Next</string>
     <key>NSAppTransportSecurity</key>
```

Even after all that is done, keybindings still don't work. Which I'm guessing is because something is trying to load a file but is specifying the wrong case.

... but now that I pull I see that the cocoa code is completely removed ... haha; well, I guess that's one way to fix it! I'll close this and reopen if there is case-sensitive errors in the future :-)
