### ISSUE TITLE
Blocking extension support, or blocking mechanism support

### ISSUE THREAD

**Issue by IvanDelsinne** [atlas-engineer/next#227]
The well-known ublock origin extension is really something that cannot be ignored nowadays.

Having a browser without it is really a shame, so if integrating an extension mechanism is not something to be expected, why not implement a blocking mechanism based on lists *right in the browser*?

**Comment by alexherbo2** [comment]
[Megumin][Megumin pouting]!

[Megumin pouting]: https://vignette.wikia.nocookie.net/konosuba/images/d/d3/Megumin_pouting.jpg

**Comment by Ambrevar** [comment]
@IvanDelsinne This is one of the 3-4 top-priority items on our TODO-list :)
In fact, it's already possible to block domains from your user config.  See the `request-resource` end point in `remote.lisp`.

Next step is to make a high-level mode and implement some database synchronization system.  Patches are welcome ;)

**Comment by vindarel** [comment]
closing in favor of https://github.com/atlas-engineer/next/issues/32
