### ISSUE TITLE
Problem building Next on ubuntu with file ffi-types-unix.c

### ISSUE THREAD

**Issue by Eskatrem** [atlas-engineer/next#230]
When running `make all`on Ubuntu, I get:

`; g++ -m64 -Wno-write-strings -I/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/grovel/ -o /home/samuel/.cache/common-lisp/sbcl-1.4.5.debian-linux-x64/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix /home/samuel/.cache/common-lisp/sbcl-1.4.5.debian-linux-x64/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix.c

debugger invoked on a IOLIB/GROVEL::GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {10005E85B3}>: External process exited with code 1.
Command was: "g++" "-m64" "-Wno-write-strings" "-I/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/grovel/" "-o" "/home/samuel/.cache/common-lisp/sbcl-1.4.5.debian-linux-x64/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix" "/home/samuel/.cache/common-lisp/sbcl-1.4.5.debian-linux-x64/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix.c"
Output was:

Error output was:
/home/samuel/.cache/common-lisp/sbcl-1.4.5.debian-linux-x64/home/samuel/code/next/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix.c:14:10: fatal error: lfp.h: No such file or directory
 #include <lfp.h>
          ^~~~~~~
compilation terminated.
`

I installed the dependencies listed in the README(webkit2gtk, SQLite, glib-networking, gsettings-desktop-schemas, gstreamer, gst-plugins).

Could someone help me to fix it?

**Comment by Ambrevar** [comment]
Yes, you need to install `libfixposix`.

I had forgotten to add it to the list of dependencies in the README.
Fixed now, thanks!

**Comment by Eskatrem** [comment]
Indeed, it works now, thanks!
