### ISSUE TITLE
Is Next adapted for non-Lisp users?

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/next#232]

**Comment by jmercouris** [comment]
Not sure what this question is asking.

**Comment by Ambrevar** [comment]
For now Next mostly targets power users, but in the future we might even make it more attractive to a broader audience.  Time will tell!

**Comment by alexanderbarbosa** [comment]
Nope.

**Comment by alexherbo2** [comment]
Do you mind adding a wiki to the project?

The wiki could have a page dedicated to the configuration.  Having a link to known Next user configs could be helpful to learn by example.

**Comment by alexanderbarbosa** [comment]
@alexherbo2 
https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#customization

**Comment by Ambrevar** [comment]
I'd rather stay away from a wiki for now: it's an extra maintenance
burden and it's certainly going to get out of sync as we release new
versions.

Instead, I'd like to focus on embedded, explorable documentation.  We
can also embed a manual and tutorials à-la Emacs.

**Comment by azzamsa** [comment]
@Ambrevar I think this issue is solved. We shouldclose this and other solved issues.

**Comment by jmercouris** [comment]
Agreed
