### ISSUE TITLE
latest macOS version: hitting the escape key crashes app

### ISSUE THREAD

**Issue by mark-watson** [atlas-engineer/next#233]
I can add the 'report to Apple' stack trace if you need it.

**Comment by jmercouris** [comment]
Hi Mark,

Thank you for the offer, but that will not be necessary, the port for macOS is getting a rewrite.

thanks,

John

**Comment by Ambrevar** [comment]
@jmercouris I guess this is fixed now, right?

**Comment by jmercouris** [comment]
Correct, this is fixed!
