### ISSUE TITLE
Next not starting: SQLite Error

### ISSUE THREAD

**Issue by Aphsai** [atlas-engineer/next#234]
Hi, I'm getting an error that's preventing Next from starting

```(SQLITE:SQLITE-ERROR :ERROR "Could not prepare an sqlite statement." :STATEMENT NIL
:DB-HANDLE #<SQLITE:SQLITE-HANDLE {1004DF4D53}> :SQL-TEXT "select visits from typed
where url like ? limit 1;")
   source: (ERROR
            (IF (EQ ERROR-CODE :CONSTRAINT)
                'SQLITE-CONSTRAINT-ERROR
                'SQLITE-ERROR)
            :FORMAT-CONTROL
            (IF (LISTP MESSAGE)
                (FIRST MESSAGE)
                MESSAGE)
            :FORMAT-ARGUMENTS
            (IF (LISTP MESSAGE)
                (REST MESSAGE))
            :DB-HANDLE DB-HANDLE :ERROR-CODE ERROR-CODE :ERROR-MSG
            (IF (AND DB-HANDLE ERROR-CODE)
                (SQLITE-FFI:SQLITE3-ERRMSG (HANDLE DB-HANDLE)))
            ...)
```

I'm not sure it'll help but this came up as I was building:
```WARNING:
   bare references to struct types are deprecated. Please use (:POINTER
                                                               (:STRUCT
                                                                SQLITE3)) or (:STRUCT
                                                                              SQLITE3) instead.
WARNING:
   bare references to struct types are deprecated. Please use (:POINTER
                                                               (:STRUCT
                                                                SQLITE3-STMT)) or (:STRUCT
                                                                                   SQLITE3-STMT) instead.
``` 
Though I imagine warnings shouldn't pose too much of a problem.

My SQLite version is : 
`3.28.0 2019-04-16 19:49:53 884b4b7e502b4e991677b53971277adfaf0a04a284f8e483e2553d0f83156b50
`

Edit: Another piece of important debugging information I forgot to add:
```
#<THREAD "main thread" RUNNING {10006105B3}>:
  Could not prepare an sqlite statement.
Code ERROR: no such column: visits.
Database: /home/aphsai/.local/share/next/history.db
SQL: select visits from typed where url like ? limit 1;

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.
```

**Comment by vindarel** [comment]
ok, the important bit here is `Code ERROR: no such column: visits.`. Thanks for the report.

Can you try deleting the db and re-running Next ?

**Comment by Aphsai** [comment]
Oh, it worked but after rerunning:

```
#<THREAD "main thread" RUNNING {10006105B3}>:
  The value
    "https://next.atlas.engineer/start"
  is not of type
    NUMBER
  when binding SB-KERNEL::X

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

(SB-KERNEL:TWO-ARG-+ "https://next.atlas.engineer/start" 1) [external]
0]
```

So after deleting the database, the browser runs successfully the first time, and any successive attempts cause that.

**Comment by jmercouris** [comment]
I assume that reading the number from the database does not properly get a NUMBER value, but rather a string of some sort. Perhaps PARSE-INTEGER needs to be invoked on the value before INCF'ing?

**Comment by vindarel** [comment]
btw, this first error probably happens because you tried Next some time ago and you tried again recently, after we made (deliberately) a breaking change in the DB structure, but after we removed the migration code (which also brought problems of its own with oldish sqlite versions).

**Comment by Aphsai** [comment]
Ah, makes sense. I did try Next a month or two ago before coming back to it.

Also in reply to the parse-integer attempt:

I tried adding it over the retrieval from the database and it gave:
```
#<THREAD "main thread" RUNNING {10006105B3}>:
  The value
    1
  is not of type
    STRING
  when binding STRING

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

(PARSE-INTEGER 1) [more]
```

This was the code I added:
```
(visits (or (parse-integer (sqlite:execute-single db "select visits from typed where url like ? limit 1;" url))
                     0))
(visits (incf visits)))
```

**Comment by jmercouris** [comment]
So if you remove the history code, Next starts properly? If you manually increment the value as you've done in your example, and then update the database, does that work?

**Comment by Aphsai** [comment]
If I delete the SQLite database, next starts properly, but if I visit the same page twice, which is when the visit counter increments I imagine, it fails.

**Comment by jmercouris** [comment]
Ok, so you executed the code in the REPL rather than modifying the sources?

**Comment by Aphsai** [comment]
Uh no I modified the source, I'm not very familiar with lisp so I'm not sure how to work with the REPL.

I modified the source and rebuilt.

**Comment by jmercouris** [comment]
Ok no worries, thank you for the information, one of us will take a closer look later! That was very helpful!

**Comment by vindarel** [comment]
Hello, what if you tried with a fresh install ?

Also, I'm sorry, I was unable to use Next accordingly to test this for a few weeks (!).

**Comment by OrdoFlammae** [comment]
I got this error, and it appears to be fixed if you build using the latest version (v.s. the version tagged `1.2.2`).

**Comment by Aphsai** [comment]
Fresh install does seem to be working!
