### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#237]
We need hooks to let the user customize any event.

Emacs has hooks but there are limited.

Some questions need to be answered:

- What can be hooked?  Modes, commands, what else?  Buffers?
It's quite clear that we need a hook for network events.  So should we add this hook manually or should we add a hook to all RPC endpoints?

- What should the hook be allowed to do?  I'd say it should be allowed to run `:before`, `:after` and `:around` like auxiliary methods.  Should it be allowed to override the command or mode constructor/destructor?  (Like Emacs' `:override` advice.)

- Implementation: There is this library: https://gitlab.com/Gnuxie/method-hooks.
Can we use it?  Can we leverage CLOS somehow?

**Comment by noctuid** [comment]
[Pentadactyl's autocommand documentation](http://bug.5digits.org/help/pentadactyl/autocommands.xhtml) is probably worth looking at. I didn't have a ton of autocommands. Besides page loading, the main one I used was `DownloadPost` to open dired or ranger with the downloaded file cut.

I remember there being a reasonably portable advice library but can't remember its name right now.

**Comment by noctuid** [comment]
I think [cl-advice](https://bitbucket.org/budden/budden-tools/src/default/cl-advice/?at=default) is the library I was thinking of.

**Comment by Ambrevar** [comment]
Thanks for the links, @noctuid!  I'll look into it.
Another project worth looking into is https://github.com/cxxxr/lem I believe.

**Comment by Ambrevar** [comment]
StumpWM also has hooks, but I believe they are quite limited.

**Comment by Ambrevar** [comment]
Hooks could also effectively supersede the setf-ability of `get-default`.
The latter has multiple issues:
- Changes are irreversible.  If A sets a default and B too, we lose information.
- It's not compatible with all compilers, e.g. CCL.  Ultimately it would be nice to have CCL/ECL support.

**Comment by Ambrevar** [comment]
See #346.

About cl-advice: Yes we can use it, but I think for a slightly different purpose: advising existing functions.
So with cl-advice it's impossible to call an advice in other places than `:around` (before and after).  With hooks we can insert handlers anywhere.

That said, we can't use hooks on functions that don't have `run-hook...` in them, so for those cl-advice could be useful.

**Comment by Ambrevar** [comment]
Hooks have just been merged: 052a5189655da6f70c08704670a88b66792ffd27!

**Comment by vindarel** [comment]
Exciting change!

**Comment by Ambrevar** [comment]
Indeed!  Feel free to play with it and share your cool configuration snippets!

**Comment by jmercouris** [comment]
Nice, looks suspiciously like the old implementation ;)

**Comment by Ambrevar** [comment]
The old implementation was not re-used because I thought we could use a
third-party library instead, cl-hooks.

The implementation of cl-hooks is a bit different.
On the Next side, to be precise, there are some differences as well,
mostly because the `command' API has changed significantly.

There are two command hooks instead of just one, which are regular
variables, not keywords.

There are also mode hooks and other specific hooks, like download hooks :)

**Comment by jmercouris** [comment]
I see the differences, I'm just saying, it looks a little bit like the old implementation :D

any rate, top notch and better!
