### ISSUE TITLE
Next opens a blank page with `target="_blank"` links

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#240]
Hi,

Some pages force browsers to open clicked links in a new window or tab.

On next it it opens a new instance but a blank page is provided.
 
Reddit is known for always open links as a new window/tab: https://www.reddit.com/r/javascript/comments/bzq1j9/functional_javascript_traversing_trees_with_a/

**Comment by Ambrevar** [comment]
This should now be fixed in 53d37cfdc238370cb3d3909044d9fb5967e3de8a.
Feel free to reopen if there is another issue.
