### ISSUE TITLE
history: soft and hard navigation history clearing

### ISSUE THREAD

**Issue by lxbarbosa** [atlas-engineer/next#246]
Hi,

One neat feature Next is lacking is clearing browser history. 

It should clear all visited pages history but keep pages cookies and bookmarks.

And a buffer listing user browsing history.

Of course it would be great to have an option to clear everything, too.

Thanks!

**Comment by Ambrevar** [comment]
At the moment, the history can be fully cleared by removing
`~/.local/share/next/history.db'.  Same with cookies, bookmarks, etc.

It would be nice to be able to select-delete entries from the
browser.

**Comment by Ambrevar** [comment]
I've added delete-history-entry in 9f2695b65e43e0aa8afbaa441a4e85e464de70b7.
Now if you invoke it, press `M-a` to select everything and confirm, it will effectively empty your history.

Feel free to re-open if that's not enough ;)
