### ISSUE TITLE
NOSCRIPT: Is it enabled by default?

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#248]
Hi,

Since noscript has been added to Next, most heavy-on JS pages are issuing: "Enable Javascript..."

To get JS back working I need to "enable noscript" then "disable noscript" and reload page again.

Thanks!

**Comment by Ambrevar** [comment]
Yup, I've noticed the bug and I've fixed it this morning.
Pushing soon, stay tuned!

(And thanks again for the continuous feedback!)

**Comment by alexanderbarbosa** [comment]
Ya guys, rocks! 

o/

**Comment by Ambrevar** [comment]
Should be fixed in 0b598f16d9610edb9c5a517bf50e3aa2a31bad06.
Let me know if it works for you.
