### ISSUE TITLE
link hints: single letters at viewport

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#249]
hi,

Vimium has a neat feature that most link hints at viewport are single letters

That helps a loooot! 

![vimium screenshot](https://krzysztofmorcinek.files.wordpress.com/2013/08/vimium-links-chrome.png)

And, as we are at it, maybe, what would help even more is colorfoul hint links, so to differ from page's background, usually white/black. (color blind people would thank you, for one).

Thanks!

**Comment by Ambrevar** [comment]
The screenshot you linked shows hints with 2 letters as well.  What's
the difference with Next?

Regarding the colors, it's an easy tweak.

But most of the current link hinting implementation will be replaced
after 1.3 by a much more powerful system that will perform completion
based on the link URL and title.

In the meantime, pull requests are welcome of course :)

**Comment by jmercouris** [comment]
I would like to point out that not all links contain text as the body, so the existing link hint system will still have to exist for image based links.

Additionally a salient point, you can edit the colors of the link hints if you want, please see link-hint.lisp line number 42:

`(setf (ps:@ el style background) "rgba(255, 255, 255, 0.75)")`

You can copy this whole function to your init file and modify it to change the colors of link hints. Here is the complete function for reference:

```
  (defun hint-create-element (link hint)
    "Creates a DOM element to be used as a hint"
    (ps:let* ((rect (ps:chain link (get-bounding-client-rect)))
              (position (hint-determine-position rect))
              (el (ps:chain document (create-element "span"))))
      (when (< (ps:@ position left) 0)
        (setf (ps:@ position left) (+ (ps:@ position left) 20)))
      (when (< (ps:@ position top) 0)
        (setf (ps:@ position top) (+ (ps:@ position top) 20)))
      (setf (ps:@ el class-name) "next-link-hint")
      (setf (ps:@ el style background) "rgba(255, 255, 255, 0.75)")
      (setf (ps:@ el style border) "1px solid red")
      (setf (ps:@ el style font-weight) "bold")
      (setf (ps:@ el style position) "absolute")
      (setf (ps:@ el style text-align) "center")
      (setf (ps:@ el style left) (+ (ps:@ position left) "px"))
      (setf (ps:@ el style top) (+ (ps:@ position top) "px"))
      (setf (ps:@ el text-content) hint)
      el))
```

**Comment by alexanderbarbosa** [comment]
@Ambrevar 

bad example.

Still, would be easier as single letter at viewport. Vimium aint perfect.

@jmercouris 

I get that Next is fully customizable but I was point out those as Next default, following Vimium, Vimfx...

Thanks, anyway!

**Comment by Ambrevar** [comment]
Good point with the picture, also true for input fields, etc.
We could still complete over the picture URL or the input field ID, etc.

And mix-match both approaches.

**Comment by Ambrevar** [comment]
I agree that the defaults are not so good.
Anyone willing to change them?

Also the color customization should be made easier.  I'll work on it.

**Comment by noctuid** [comment]
FWIW, here is some css similar to vimium that looks nice:
```css
.next-link-hint {
  font-weight: bold;
  text-transform: lowercase;
  padding: 1px 3px 0px 3px;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.6);
  background: linear-gradient(to bottom, #FFF785, #C38A22);
  box-shadow: 0 3px 7px 0px rgba(0,0,0,0.3);
  /* if you want border changes too */
  border: 1px #C38A22 solid;
  border-radius: 3px;
}

**Comment by Ambrevar** [comment]
Thanks for sharing, I tried it and I like it a lot.

That said, we need a more convenient way to compose parenscript elements
together.

For instance, we would probably like to extract the function that sets
the style of the hint.
But how do we do that?  We could concatenate the PS results, e.g.

```lisp
(str:concat (ps:ps (defun add1 (a) (1+ a)))
            (ps:ps (add1 17)))
```

But that is not ideal.

@jmercouris @vindarel ?

**Comment by jmercouris** [comment]
you could inject a style using `cl-css` instead of setting the properties of each element dynamically, 

https://github.com/Inaimathi/cl-css

you can already see this approach being used in `minibuffer.lisp`

**Comment by Ambrevar** [comment]
There is `PS:DEFPSMACRO` which works quite well, for instance

--8<---------------cut here---------------start------------->8---
(ps:defpsmacro make-hint (text)
  `(ps:let* ((el (ps:chain document (create-element "span"))))
     (setf (ps:@ el class-name) "next-link-hint")
     (setf (ps:@ el style background) "linear-gradient(to bottom, #FFF785, #C38A22)")
     (setf (ps:@ el style foreground) "black")
     (setf (ps:@ el style border) "1px #C38A22 solid")
     (setf (ps:@ el style font-weight) "bold")
     (setf (ps:@ el style text-transform) "lowercase")
     (setf (ps:@ el style padding) "1px 3px 0px 3px")
     (setf (ps:@ el style position) "absolute")
     (setf (ps:@ el style text-align) "center")
     (setf (ps:@ el style text-shadow) "0 3px 7px 0px rgba(0,0,0,0.3)")
     (setf (ps:@ el style border-radius) "3px")
     (setf (ps:@ el text-content) ,text)
     el))
--8<---------------cut here---------------end--------------->8---

But the problem remains: how de we let the user customize the hint
style?
Defining a new MAKE-HINT macro in init.lisp won't work without
re-evaluating all functions that depend on it.

Instead, we could call MAKE-HINT from a `ps:ps*` macro instead of a
`ps:ps` macro, the former evaluating its arguments at run time.

THoughts?

**Comment by jmercouris** [comment]
You can invoke two separate functions. One of them using compiled Parenscript, and one evaluating at run time. The one evaluating at run-time simply injects the CSS which is defined as part of a function like `(link-hint-style () ...)`

**Comment by Ambrevar** [comment]
@jmercouris: Good call with cl-css.

**Comment by Ambrevar** [comment]
Not sure what you mean with "two separate functions".

Something that would work is to make ADD-LINK-HINTS dynamic, e.g. with

--8<---------------cut here---------------start------------->8---
(define-parenscript add-link-hints (_)
--8<---------------cut here---------------end--------------->8---

(Notice the `_` dummy argument.)

But at this point I'm wondering if using static parenscript is a good
idea:

- It prevents the user from customizing it.

- It saves some compilation time, but even big functions like
ADD-LINK-HINTS take 0.000 seconds of real time according to TIME on my machine (!!!)
so aren't we doing premature optimization here?  Or is there a real
benefit for having static parenscript?

**Comment by jmercouris** [comment]
I would tend to agree based on the above information, seems to be premature optimization! I had assumed the penalty was greater!

**Comment by Ambrevar** [comment]
I've fixed this:
- Now the `define-parenscript` macros only generates dynamic parenscript, which makes everything so much simpler.  Should we ever need static parenscripts, we can always extend it differently later.
- The link hints _and_ search boxes are now customizable from the `box-style` slot of the `buffer` class.  See the documentation update and commit 644a341a1ea7914049cd6627d6c0cdf2f0491883.  I've re-used the style suggested by @noctuid, thanks!

**Comment by alexanderbarbosa** [comment]
@jmercouris @Ambrevar 

Sorry to yet again annoy you all:

Upcase words would make it easier for users to notice which letters should be typed...

:D

**Comment by Ambrevar** [comment]
I guess it's a matter of taste, I wrote an example in the manual on how
to configure it and make it uppercase.  Would that be enough for you?
Would you argue that the defaults are better in uppercase?

**Comment by alexanderbarbosa** [comment]
@Ambrevar 

Its a matter of taste. :D 

Thanks!
