### ISSUE TITLE
Search engine: unable to search for results

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#250]
Hi,

In "Open URL in buffer", should user type a search engine term as **Algol** and hit return, Next use term as last part of a url: **https://algo/** and issue:

`Error resolving “algol”: Name or service not known`

Thanks!

**Comment by jmercouris** [comment]
Hi, thank you for your report! Just to clarify, does it create a url: `https://algo/` or was that a typo and it is supposed to be `https://algol/`?

**Comment by alexanderbarbosa** [comment]
@jmercouris 

![2019-06-25-103351_1366x768_scrot](https://user-images.githubusercontent.com/40282381/60102787-c292b980-9734-11e9-8c12-6fba17768490.png)


Reproducing:

c-l

type algol

hit return

https://algol/

**Comment by Ambrevar** [comment]
Indeed, this is because "algo" is a valid domain...  But fair enough,
it's probably not what the user expects.

I've fixed this in commit 79bad9ad7372bf86c241ea342faa940a827f29a6 which
handles 2 extra edge cases, hopefully it will cover all user
expectations now.
