### ISSUE TITLE
Opening page with Next through terminal

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#254]
Hi,

Next still need some cool terminal interface features, one of those is opening pages:

`$ next duckduckgo.com`

So we can open pages with Next from anywhere.. eg: Emacs' `browse-url-at-point`.

Or:

`$ next fortran syntax`

And it opens a page searching 'fortran syntax' in duckdckgo.com! 

o/

**Comment by Ambrevar** [comment]
This should work already.  What's the output?

**Comment by alexanderbarbosa** [comment]
Its working correctly.

Thanks!
