### ISSUE TITLE
Bookmarks: Import, Export and Manage

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#255]
Hi,

Ive been wondering if there is a way to export so I can version control bookmarks.

either way, those features are basic in most browser.

Though I would like some way to sync with version control bookmarks.

**Comment by jmercouris** [comment]
You might try synchronizing your sqlite database of bookmarks, we don't currently persist/export in a S-EXP format or anything like that. Though we would really like to! Thank you for starting the conversation!

**Comment by Ambrevar** [comment]
Hi,

bookmarks are almost at the top of my priorities for post 1.3.
I had opened an issue a long time ago with a rough roadmap: #79.

Feel free to close this issue and continue the discussion in #79.
