### ISSUE TITLE
Socket error in "socket"

### ISSUE THREAD

**Issue by dj67** [atlas-engineer/next#257]
Hi, 
I try to install next browser with the AUR package, no problem but Next can't run, could you help me? 

Here find the message after typing next on a terminal

Thank you and excuse my english
DJ

Polling platform port...
Polling platform port...
Polling platform port...
Polling platform port...
Unhandled SB-BSD-SOCKETS:SOCKET-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10005B85B3}>:
  Socket error in "socket": 24 (Too many open files)

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005B85B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-BSD-SOCKETS:SOCKET-ERROR {10042F6E23}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-BSD-SOCKETS:SOCKET-ERROR {10042F6E23}>)
2: (INVOKE-DEBUGGER #<SB-BSD-SOCKETS:SOCKET-ERROR {10042F6E23}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-BSD-SOCKETS:SOCKET-ERROR {10042F6E23}>)
4: (SB-KERNEL::%SIGNAL #<SB-BSD-SOCKETS:SOCKET-ERROR {10042F6E23}>)
5: (ERROR SB-BSD-SOCKETS:SOCKET-ERROR :ERRNO 24 :SYSCALL "socket")
6: (SB-BSD-SOCKETS:SOCKET-ERROR "socket" 24)
7: ((LAMBDA ()))
8: (S-XML-RPC:XML-RPC-CALL "<methodCall><methodName>window.make</methodName></methodCall>" :URL "/RPC2" :AGENT NIL :HOST "localhost" :PORT 8082 :AUTHORIZATION NIL :PROXY-HOST NIL :PROXY-PORT NIL)
9: ((:METHOD NEXT::WINDOW-MAKE (NEXT::REMOTE-INTERFACE)) #<NEXT::REMOTE-INTERFACE {1003C65F33}>) [fast-method]
10: (NEXT::MAKE-WINDOW)
11: (NEXT::INITIALIZE-PORT)
12: (NEXT:START :WITH-PLATFORM-PORT-P T)
13: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
14: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10038359DB}>)
15: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
16: ((FLET "WITHOUT-INTERRUPTS-BODY-34" :IN SAVE-LISP-AND-DIE))
17: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting

**Comment by Ambrevar** [comment]
The backtrace you shared is from a very old version of Next.
Did you install it from the AUR recently?  Please retry, the error
should go away if you build against the latest Git version.

**Comment by dj67** [comment]
Thank you for your reply;

yes I used the latest version on the AUR repositories, downloaded yesterday

I will try with the Git version

**Comment by dj67** [comment]
I try with the GIT version, same problem ....il you execute /usr/local/bin/next to get started, as you whrite in the documentation
but il you use /bin/next al works fine.

Thank you. DJ

**Comment by jmercouris** [comment]
It is not possible that you have the same problem, we are not using BSD sockets anymore, only Unix domain sockets. The binary in /usr/local/bin/next must be old.

**Comment by Ambrevar** [comment]
The AUR package does not install to /usr/local/bin/next.

However, the Guix pack does.  So I think you've extracted the Guix pack
to your root some time ago.

I hope this fixes it.  If so, feel free to close the issue.

**Comment by dj67** [comment]
It's right the binary was old, Now, everything works fine, thank you.

some remarks for your documentation "extract the archive (you need lzip)" and then extract the file.tar you have obtained after extrating the file.tar.lz and then "execute ./usr/local/bin/next to get started!"

**Comment by Ambrevar** [comment]
In practice you don't extract with lzip, you just extract everything in
one go with tar (or your favourite archiver, like `aunpack from atools).
I guess we could specify this in the docs.
