### ISSUE TITLE
Link hints: Not working anymore

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#258]
Hi,

I noticed that Next is not anymore following links, it does generate links but once we  ask to follow it does nothing.

Thanks! 

Next: Upstream
OS: Debian SID

**Comment by jmercouris** [comment]
Hello, indeed, we happened to accidentally break it while trying to add support for input boxes! We will get this fixed!

**Comment by Ambrevar** [comment]
I've reverted the offending commit, it wasn't working anyways.
We will fix it properly later.

Thanks for reporting!
