### ISSUE TITLE
Cannot build, OPERATION-FORCED is undefined

### ISSUE THREAD

**Issue by noctuid** [atlas-engineer/next#259]
I'm having a similar issue to #138. I've tried running `(ql:quickload :next)` with sbcl 1.5.4, and I get the error `The function ASDF/INTERFACE::OPERATION-FORCED is undefined.`. My asdf version is 3.3.1. I've tried installing next from the aur (sbcl 1.5.2) and get the same error. Any ideas?

I will probably trying installing from guix in order to try it out, but I'd prefer to run next from the source and interact with it from Emacs (what is the way to do that? running `(start)`?).

As a side note, whenever I try a new browser or plugin, I usually make a list of missing functionality that pentadactyl or other browsers have and then open issues. Usually the list is quite long; do you mind if I open a bunch of new issues all at once?

**Comment by Ambrevar** [comment]
Hmm, off the top of my head, this could be because some
defsystem-depends are missing.

Using Quicklisp, make sure that `trivial-features` and `prove-asdf` are
installed.

> I will probably trying installing from guix in order to try it out,
> but I'd prefer to run next from the source and interact with it from
> Emacs (what is the way to do that? running `(start)`?).

Yes, you can run Next by simply calling `(next:start)` from a REPL.

Note that current Guix version (1.2.2) is now quite outdated, 1.3 is
coming out soon and will improve Next tremendously.

> As a side note, whenever I try a new browser or plugin, I usually make
> a list of missing functionality that pentadactyl or other browsers
> have and then open issues. Usually the list is quite long; do you mind
> if I open a bunch of new issues all at once?

Please do, that would be fantastic!
The more feedback the better, especially with your knowledge of VI /
Evil / Pentadactyl!  Current VI implement is really basic, but that's a
start :)

**Comment by Ambrevar** [comment]
I could find this similar error for Lem:

https://github.com/cxxxr/lem/issues/84

Rings a bell, @vindarel?

**Comment by vindarel** [comment]
No, I didn't fix it, it just disappeared.

You can still try to delete the cached fasl files, moreover if you tried Nex with another config before. They are located at ~/.cache/common-lisp/.

**Comment by noctuid** [comment]
Both are installed, and I didn't have any luck with deleting the cached files.

**Comment by jmercouris** [comment]
What happens when you update ASDF?

**Comment by Ambrevar** [comment]
@noctuid I know at least one Arch user who can build it properly, so there is something specific with your system.
Do you have a ~/common-lisp folder or similar (registry folders) with local checkouts of common lisp libraries?  Try to clean them up.

Finally you could try building in a chroot, see if that helps.

**Comment by noctuid** [comment]
It looks like `operation-forced` was removed from asdf in 3.2.0, but the version of swank I have is outdated and still relies on it. Is there some way to see where quicklisp is trying to load something from? I don't have anything in `~/common-lisp` or my quicklisp local projects folder, and I don't use slime. Did you install swank/slime in some other way?

**Comment by Ambrevar** [comment]
Ha!  Looks like we are getting closer, thanks for investigating.

What's your version of Swank?  I have tested with 2.22 and 2.23 here.

Swank is usually installed with SLIME, so make sure you use an
up-to-date SLIME version and you should be alright.

But Swank is also a dependency of Next, and it's pulled by Quicklisp.
If you look in your quicklisp/dists/quicklisp/software/, you should see
a "slime-..." folder.  Make sure it's recent enough.

You can update your Quicklisp packages with

```
(ql:update-client)
(ql:update-dist)
```

I think.

**Comment by noctuid** [comment]
`(asdf:locate-library :swank)` told me that it was trying to load swank from a `.cask` folder (for lispy). Oops :man_facepalming: looks like I had this in my asdf search path. Got rid of emacs stuff from the search path, and everything works fine. My bad!

**Comment by Ambrevar** [comment]
Thanks for reporting this.  Any idea why Lispy would require an old
swank?
Was it a (very) old install?
Do you know which version of swank it was?

**Comment by noctuid** [comment]
I don't think this would affect a normal lispy user. Cask is used for development/testing, and I had a version of slime from 2017 left lying around from testing on an older version of Emacs.

**Comment by Ambrevar** [comment]
Understood.  It's probably not worth mentioning in the readme then, but
I'll try to remember if some other unlucky dev hits the same issue :)
