### ISSUE TITLE
Editing: SPACE, not working anymore!

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#260]
Hi, 

Latest commit added the canonical scroll up/down with SPACE/s-SPACE, but somewhat it works in vi-mode but not in Emacs-mode.

Next scroll down page instead of add a space between words in "writing mode".

------------------------------------
Next: Upstream
Debian SID
SBCL: 1.4.16

**Comment by Ambrevar** [comment]
Oops!  My bad, fixed in
bb6b04ea95f6f7085f71c47baed600db14d52775.
Thanks for the thorough testing as usual! :)
