### ISSUE TITLE
Installation hangs on fetching dependencies

### ISSUE THREAD

**Issue by azer** [atlas-engineer/next#268]
Hi! 

I wanted to install Next in my new computer (Arch Linux), and this time it was not able to download the dependencies unfortunately. It's probably an availability error irrelevant to the project itself, but just wanted to mention here, hoping to find out a workaround. 

Here is the last output;

```
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-jpl-util/2015-10-31/cl-jpl-util-20151031-git.tgz">
; 35.18KB
==================================================
36,026 bytes in 0.01 seconds (2706.28KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/bordeaux-threads/2018-07-11/bordeaux-threads-v0.8.6.tgz">
; 21.43KB
==================================================
21,941 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/jpl-queues/2010-10-06/jpl-queues-0.1.tgz">
; 14.76KB
==================================================
15,113 bytes in 0.09 seconds (160.42KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/iterate/2018-02-28/iterate-20180228-git.tgz">
```

I tried re-downloading it all day, at home and at work, unfortunately failed. 

Any ideas? 

Cheers
Azer

**Comment by Ambrevar** [comment]
This is most probably an issue with the Quicklisp server (independent of Next).
Can you try again?

**Comment by azer** [comment]
I know! Is there a better place to report this issue ? I still can't install Next. I wonder if it works for other people living in different regions.

**Comment by jmercouris** [comment]
Well, time to make our own Quicklisp dist/server :D

**Comment by azer** [comment]
Problem seems to be solved!

**Comment by jmercouris** [comment]
Yay! Nice!
