### ISSUE TITLE
Qt Webengine pyinstaller executable - tests required  (Linux, Mac, Windows)

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#275]
Hi everyone,

We are studying [pyinstaller](https://www.pyinstaller.org/) to ship self-contained executables of the PyQt port, based on the Webengine browser engine (aka Blink of Google Chrome). It *seems* to work, however we need more tests ! 

I put a little shell script here: https://github.com/atlas-engineer/next/blob/vindarel%2Fdownload-webengine-script/ports/pyqt-webengine/next-install-webengine.sh We download the pyinstaller archive, rename it, and we download the lisp core. Then we run `./next` and it should work©. The pyinstaller binary is supposed to be trully cross-platform: GNU/Linux, Mac and Windows. The lisp core downloaded here is for Linux systems though.

The question is, does that really work if you don't have all the required Python and system dependencies on your system ? 
Don't hesitate to paste huge shell output.

When it works and when it doesn't, please give the version of your OS, of Python, check if you have a version of `pyqt5`, `PyQtWebEngine` and/or `dbus-python` installed globally with pip, and if you have dbus started on your system.

You can also simply test the PyQt port by installing it locally (see `ports/pyqt-webengine/`).

Many thanks

**Comment by jmercouris** [comment]
Firstly, yay!!!

Secondly, I am not sure the the PyInstaller binary will be cross-platform because it uses a shared library for PyQtWebEngine

**Comment by Mestelan** [comment]
Seems the link for the script is dead?

**Comment by jmercouris** [comment]
Yes, if you are on Linux, for now just use WebKitGTK+, you'll have a much better experience.

**Comment by vindarel** [comment]
Very sorry. It's back. This version is very outdated (will update as soon as I can), but a feedback on how this installs would still be very valuable.

**Comment by Ambrevar** [comment]
I guess we can close this issue since we've dropped the D-Bus architecture and the PyQt platform port.
Master uses FFI against WebKitGTK and soon QtWebEngine :)
