### ISSUE TITLE
download-open-file: let user enter which program to open file

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#281]
Hi,
 
xdg-open, sometime, defaults to some weird programsm, as Calibre for `pdf`, if user has not set it own mimeapps list, which is a pain...

Letting users choosing what program  which they prefer to use, would help even more in certain cases

Thanks!

PS:Loved that function!

:D

**Comment by vindarel** [comment]
Hello, 

We discussed on comments after the PR, and we agreed on (for a start) giving the user the possibility to override the `open-file` function, like this: https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#decide-how-to-open-files We can think of evolutions for the future.

Should be ok ? 

thanks

**Comment by alexanderbarbosa** [comment]
@vindarel 

I agree with you all. 

GuixSD user :D
