### ISSUE TITLE
Killing last page open shows a blank screen

### ISSUE THREAD

**Issue by lxbarbosa** [atlas-engineer/next#282]
Hi,

As we kill last page Next presents a plain and blank page.

Chrome/Firefox take us back to their dashboard. What I mostly disabled all that shiniest feature but it has some utility.

Thanks!

**Comment by vindarel** [comment]
mmh I'm not shocked. We can think of displaying a future dashboard page, and of course to give options (dashboard, quickhelp, nothing,…).

As a reminder, keybindings are a `M-x help` away (added not long ago).

**Comment by alexanderbarbosa** [comment]
@vindarel 

That would be awesome.
