### ISSUE TITLE
Page's title instead of current URL on statusbar

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#283]
Hi,

As statusbar is, now, fixed it keep displaying a rather not useful link of currents page.

Maybe, current pages title would be more helpful?

Thanks!

**Comment by Ambrevar** [comment]
We can display both! :)

**Comment by Ambrevar** [comment]
Fixed in 663a8be9941d48ce3f287854654cd8e15f891715, thanks for reporting!

**Comment by alexanderbarbosa** [comment]
@Ambrevar 

I beg to differ. 

https://edition.cnn.com/business/live-news/tariffs-on-china-reaction/index.html

:D

**Comment by Ambrevar** [comment]
Can't have it all! :(
URL first is more important in my opinion, it identifies the page uniquely.
If the user wants the title, they can copy it to the clipboard.
Later we can add a "inspect-buffer" function that displays all its properties.
