### ISSUE TITLE
switch buffer: sort buffers with an access time parameter ?

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#290]
Currently, switch-buffer presents an ordered list of buffer. Since https://github.com/atlas-engineer/next/pull/285, the current buffer is not presented the first of the list, for commodity.

Shall we fuzzy match the list with an access time parameter ?

>  Another possibly more general way to do this would be to add an access-time slot and to sort by it in fuzzy-match.

A concern of mine is that I like to see a linear list of my buffers, as it is my mental model.
If we do this, it should be easily configurable.

**Comment by Ambrevar** [comment]
Sorting by access-time would not make this non-linear, I don't
understand your concern.

Another benefit of using access-time over a stack is that the
access-time can be used to weight in when fuzzy-matching, while the
stack cannot (well, it's harder).

To clarify:
- The initial candidates are '(stacked-1 stacked-2foo stacked-2bar).

- After typing "2", the candidate list may be narrowed to '(stacked-2bar
stacked-2foo): the stack order is not preserved.

This would not be a problem with access-time.

**Comment by Ambrevar** [comment]
Last but not least, "stack order" does not work for bookmarks or history, since those entries are persisted to disk, and those no "stack order" is known on startup.

**Comment by Ambrevar** [comment]
Fixed here: b390b576479de3838a31c3753d68b7d21e1bfb4a
