### ISSUE TITLE
Failure on startup (Ubuntu 18.04.2 LTS)

### ISSUE THREAD

**Issue by marcoheisig** [atlas-engineer/next#292]
I'm using the pre-packaged archive from the Next homepage. This is the stacktrace I get:
```
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_US.utf8
 <INFO> [15:36:37] next base.lisp (start) - NEXT::+VERSION+: "1.3.0" 
 <INFO> [15:36:37] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/rzlin/hu62bodi/.config/next/init.lisp...
 <WARN> [15:36:37] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
Unhandled SB-KERNEL:CASE-FAILURE in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                              {100560A843}>:
  NIL fell through ETYPECASE expression. Wanted one of (STRING VECTOR).

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100560A843}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-KERNEL:CASE-FAILURE expected-type: (OR STRING VECTOR) datum: NIL> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-KERNEL:CASE-FAILURE expected-type: (OR STRING VECTOR) datum: NIL>)
2: (INVOKE-DEBUGGER #<SB-KERNEL:CASE-FAILURE expected-type: (OR STRING VECTOR) datum: NIL>)
3: (ERROR SB-KERNEL:CASE-FAILURE :NAME ETYPECASE :DATUM NIL :EXPECTED-TYPE (OR STRING VECTOR) :POSSIBILITIES (STRING VECTOR))
4: (DBUS/UTILS:ENCODE-HEX-STRING NIL :START 0 :END NIL)
5: ((:METHOD DBUS/PROTOCOLS:FEED-AUTHENTICATION-MECHANISM (DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM T)) #<unused argument> :INITIAL-RESPONSE) [fast-method]
6: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {1006397BB3}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {10062DA203}> :IF-FAILED #<unused argument>) [fast-method]
7: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
8: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005C7519B}> #<event base, 0 FDs monitored, using: #<epoll(4) multiplexer> {1005708C73}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005871863}>))
9: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
13: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
15: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F6B2DC3ED8B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100560A843}>> NIL T NIL)
16: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100560A843}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100560A7EB}> NIL)
17: ("foreign function: call_into_lisp")
18: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
```

**Comment by jmercouris** [comment]
It seems that the GTK platform port is not able to communicate, is D-Bus running on your machine?

**Comment by Ambrevar** [comment]
Which window manager are you running?  Which login manager?

**Comment by marcoheisig** [comment]
Dbus is running.
```
$ pgrep -lf dbus
861 dbus-daemon
7245 dbus-daemon
7519 dbus-daemon
8222 update-apt-xapi
9239 dbus
```
My desktop environment is KDE Plasma.
My login manager is lightdm.

**Comment by marcoheisig** [comment]
Here is a deal: If you add a `--swank` flag to next, I will track down that bug myself :)

**Comment by jmercouris** [comment]
We're working on it right now :D but we can add a swank flag to the start-up options, that would make a lot of sense!

**Comment by jmercouris** [comment]
did you do the following `sysctl -w kernel.unprivileged_userns_clone=1` per the instructions here? https://next.atlas.engineer/download

**Comment by marcoheisig** [comment]
Yes, I did that, too.

**Comment by jmercouris** [comment]
Did you perhaps have to do the other set of instructions? We did get it to work on a Linux Mint machine, which should be fairly similar :\, perhaps we'll add a swank flag sooner than we think :D

**Comment by marcoheisig** [comment]
You mean the `echo 0 > /proc/sys/kernel/userns_restrict`?
When I try that, I get `bash: /proc/sys/kernel/userns_restrict: No such file or directory`

**Comment by jmercouris** [comment]
Hm, I wish I knew more about Linux to help :( , unfortunately for this case, I am a BSD user, perhaps someone else may chime in..

**Comment by vindarel** [comment]
So, the Guix package is working for me© on Mint 19, based on Ubuntu 18.04, with the Mate desktop. I had to do the `systctl` command.

> If you add a --swank flag to next, I will track down that bug myself :)

You could install Next locally and see if there's the same bug ? In which case you'll have the full CL at your disposal. We made it easy to install (`make`), and it doesn't disturb your local quicklisp dist.

**Comment by triclops200** [comment]
Would like to report that I'm getting the same bug on Ubuntu 19.04 and I have run the sysctl command and dbus is running.

**Comment by triclops200** [comment]
Also, side note, the alternative kernel path for the unpriveleged usernamespace clone is `/proc/sys/kernel/unprivileged_userns_clone`

**Comment by Ambrevar** [comment]
Can you try installing libfixposix?

**Comment by triclops200** [comment]
Already have it installed as well as the -dev package

**Comment by Ambrevar** [comment]
Didn't know, thanks for this!

**Comment by triclops200** [comment]
Another note, I compiled from source and the webkit version, at least, runs fine with that build.

**Comment by e-user** [comment]
Same bug here on Fedora 30 Workstation. Fedora has user namespaces fully integrated, so no `kernel.unprivileged_userns_clone` option present. I will try compiling from source as well.

**Comment by Ubroi** [comment]
Same bug on Debian Stretch with i3wm.
dbus running, and i have run sysctl command.

**Comment by whirm** [comment]
Same on Debian SID running on Awesome with 
```log 
# sudo sysctl -w kernel.unprivileged_userns_clone=1
kernel.unprivileged_userns_clone = 1
```

**Comment by alexanderbarbosa** [comment]
Debian 10 SID working fine.!

**Comment by whirm** [comment]
> Debian 10 SID working fine.!

Which kernel are you running?

**Comment by alexanderbarbosa** [comment]
@whirm 
`$ uname -r
4.19.0-5-amd64
`

**Comment by whirm** [comment]
@alexanderbarbosa I'm running 5.0.0. I'll give a try to 4.19 just to be sure. Thanks!

**Comment by alexanderbarbosa** [comment]
@whirm  
Too late, its now 5.2 
:D

**Comment by whirm** [comment]
> @whirm
> Too late, its now using `5.2.0-2-amd64` and working correctly

I tried 4.19, 5.0 and 5.2 so it's not the kernel
 
> Are you compiling your kernel?

Nope, Debian upstream's

@alexanderbarbosa would you mind posting the output of `sudo sysctl -a` and ` dpkg -l "*dbus*"` so I can see what's different between our setups?

**Comment by alexanderbarbosa** [comment]
@whirm 

Here it goes: 
sysctl -a:  https://paste.debian.net/1095641/
dpkg -l "*dbus*": https://pastebin.com/pgh6pMT9

**Comment by Ambrevar** [comment]
Thanks for investigating this.

To all of you who are having issues with the Guix pack at the moment: a
good alternative is to install [guix](https://guix.gnu.org) then

- add the Next Guix channel as per the readme;
- `guix pull` as usual;
- run `guix install next`.

**Comment by whirm** [comment]
@alexanderbarbosa 
> sysctl -a: https://paste.debian.net/1095641/
This one seems to have expired. Do you mind reposting it?

Thanks!

**Comment by inigoserna** [comment]
Same here with Fedora 30, swaywm & gdm.

dbus is running but kernel.unprivileged_userns_clone does not exist:
`/opt/next # sysctl -w kernel.unprivileged_userns_clone=1
sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory`

Backtrace:

/opt/next $ ./usr/local/bin/next 
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_GB.utf8
 <INFO> [20:45:30] next base.lisp (start) - NEXT::+VERSION+: "1.3.1" 
 <INFO> [20:45:30] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/inigo/.config/next/init.lisp...
 <WARN> [20:45:30] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1005FCDD13}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005FCDD13}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {1005FD8A73}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {1005FD8A73}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {1005FD8A73}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {1005FD7463}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {1005FD5D63}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005FBE7BB}> #<event base, 0 FDs monitored, using: #<epoll(4) multiplexer> {1005FBC6F3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005FBE673}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F380631ED8B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005FCDD13}>> NIL T NIL)
14: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005FCDD13}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1005FCDCBB}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting

**Comment by Ambrevar** [comment]
My hunch is that the Guix pack's dbus does not work properly for some reason (and makes PRoot fail).

Try with

```
$ export $(dbus-launch) && next
```

Another more reliable option is to install [Guix](https://guix.gnu.org).
Until Next is packaged for Ubuntu and Fedora, that is to say! :)

**Comment by inigoserna** [comment]
> My hunch is that the Guix pack's dbus does not work properly for some reason (and makes PRoot fail).
> 
> Try with
> 
> ```
> $ export $(dbus-launch) && next
> ```

Hey! This works!
Thanks for the tip.

**Comment by Ambrevar** [comment]
>> $ export $(dbus-launch) && next
>> ```
>
> Hey! This works!

Ha!  So we are making progress!

In commit 8236e5ebd174e0f995c13a82ca6ab4629b3be0a6 I added a fallback
that was supposed to do exactly that.  Apparently it didn't work, but
I'm not sure why.

@vindarel: Can you try exporting a fake DBUS_SESSION_BUS_ADDRESS (look
at its current value and just set it to a wrong path), then run next and
see if the fallback works?

**Comment by Ambrevar** [comment]
I've just pushed some extra log details which should help here.  @inigoserna: Would you mind trying against master and report the error output?  Thanks!

**Comment by inigoserna** [comment]
> I've just pushed some extra log details which should help here. @inigoserna: Would you mind trying against master and report the error output? Thanks!

I've compiled current master using the sbcl package Fedora 30 provides:
    sbcl - 1.4.14-2.fc30
    cl-asdf - 20101028-15.fc30
    common-lisp-controller - 7.4-16.fc30
    libfixposix - 0.4.3-1.fc30

This is the messages in the console when I execute the program:

```
$ ./next 
 <INFO> [21:24:20] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-4f8a98d" 
 <INFO> [21:24:20] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/inigo/.config/next/init.lisp...
 <WARN> [21:24:20] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
 <INFO> [21:24:20] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1006AAB393}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006AAB393}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {1006ABE2F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {1006ABE2F3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {1006ABE2F3}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {1006ABCD13}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {1006ABB613}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1006AB375B}> #<event base, 0 FDs monitored, using: #<epoll(4) multiplexer> {1006AB1CE3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1006AB3613}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FDFED1AED6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006AAB393}>> NIL T NIL)
14: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006AAB393}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1006AAB33B}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
```

and with your trick, it works:

```
$ export $(dbus-launch) && ./next
 <INFO> [21:24:43] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-4f8a98d" 
 <INFO> [21:24:43] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/inigo/.config/next/init.lisp...
 <WARN> [21:24:43] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
 <INFO> [21:24:44] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-IGmRNqVi4Z">)
 <INFO> [21:24:44] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.1
 <INFO> [21:24:44] next port.lisp (run-program port) -
  Current directory: /home/_compiling/linux/network/next/
 <INFO> [21:24:44] next port.lisp (run-program port) -
  Platform port path: /home/_compiling/linux/network/next/ports/gtk-webkit/next-gtk-webkit
 <INFO> [21:24:44] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [21:24:44] next port.lisp (run-program port) -
  Platform port log file: /home/inigo/.local/share/next/next-gtk-webkit.log

```

**Comment by Ambrevar** [comment]
Thanks a lot for trying this is out, we are making progress!

First of all, you don't need to install cl-asdf or common-lisp-controller
(which are severely out of date by the way).
But I don't think that's related to this issue.

Now let's look at the log.

- `D-Bus session inaccessible...` was not printed, which means that the
  following works:

```
  (dbus:with-open-bus (bus (session-server-addresses))
        ;; Dummy call to make sure dbus session is accessible.
        (declare (ignore bus))
        t)
```

- But see the different in the socket address between the 2 outputs:

>   D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)

fails, while

>   D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-IGmRNqVi4Z">)

works.

So it seems that the default session bus, which might be started by
systemd, exports the DBUS_SESSION_BUS_ADDRESS environment variable, but
it's not possible to perform "more advanced d-bus duties" on it.

What we've got to do:

- Investigate what's so special about this (possibly systemd) D-Bus
  session running at /run/user/$UID/bus.

- Extend `ensure-dbus-session' in `remote.lisp` to request a name on the
  bus (with `(dbus:request-name bus +core-name+ :do-not-queue)`) and see
  if that fails.  I presume that this is the part that's not authorized
  by D-Bus.

I believe just the latter point is enough to work around the issue, but
I'd rather fully understand what's going on before proceeding.

**Comment by Ambrevar** [comment]
@inigoserna: Can you try two things:

- Make sure `/run/user/1000/` is readable and writable.
```
ls -l /run/user/1000/
```

- Since you run Fedora, you might be using dbus-broker by default.  This could be the issue.
Can you confirm this?  Try the following

```
sudo lsof | grep /run/user/1000/bus
## The above should give you a process name and PID
readlink -f $(which <process-name>)
## The above should give you the full path to the dbus daemon you are running.
rpm -qf <the-above-path>
## The above should tell you which package the daemon executable belongs to.
```
Thanks!

**Comment by inigoserna** [comment]
> Thanks a lot for trying this is out, we are making progress! 

Thanks to you for your help!

> First of all, you don't need to install cl-asdf or common-lisp-controller (which are severely out of date by the way)

I can't do anything, they are hard dependencies for Fedora 30 SBCL package that are installed automatically.

**Comment by inigoserna** [comment]
>     * Make sure `/run/user/1000/` is readable and writable.

It is for my user (userid 1000).
Have not found a problem for any other program that use /run/user/_userid_

>     * Since you run Fedora, you might be using dbus-broker by default.  This could be the issue.
>       Can you confirm this?  Try the following

Yes, I confirm it. 
At session start, `systemd --user` is executed, which runs `dbus-broker-lauch`, which runs `dbus-broker`.

I've also tried running `next` with a fresh new user in a GNOME session. It crashes with the same error.

Thanks again!

**Comment by Ambrevar** [comment]
OK, I'll push the workaround I mentioned then.

A proper fix would be
- either add support for dbus-broker to cl-dbus.
- or (better) fix dbus-broker to be more backward compatible.

**Comment by Ambrevar** [comment]
@inigoserna: OK, I've pushed the workaround.  Can you try again see if
it works this time (without `export $(dbus-launch)`)?

**Comment by inigoserna** [comment]
> @inigoserna: OK, I've pushed the workaround. Can you try again see if it works this time (without `export $(dbus-launch)`)?

Same error:

```$ ./next 
 <INFO> [17:35:44] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-7d652e5" 
 <INFO> [17:35:44] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/inigo/.config/next/init.lisp...
 <WARN> [17:35:44] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
 <INFO> [17:35:44] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1006ABAE53}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006ABAE53}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {1006AC9AA3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {1006AC9AA3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {1006AC9AA3}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {1006AC84C3}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {1006AC6EA3}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1006AAF7CB}> #<event base, 0 FDs monitored, using: #<epoll(4) multiplexer> {1006AADD53}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1006AAF683}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F31B4B56D6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006ABAE53}>> NIL T NIL)
14: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006ABAE53}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1006ABADFB}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting```

**Comment by Ambrevar** [comment]
This means that the following works

``` lisp
(dbus:with-open-bus (bus (session-server-addresses))
        (dbus:request-name bus +core-name+ :do-not-queue)
        t)
```

bus somehow `bus/protocols:authenticate` fails with dbus-broker.
@death: Any clue what's going on?

**Comment by death** [comment]
After opening a connection, `dbus:with-open-bus` attempts to authenticate with the DBUS server using the authentication mechanisms requested by it, one by one until it succeeds or there are no more mechanisms left.  Once none are left, the error that you're seeing is signaled.

CL DBUS currently supports two mechanisms: `DBUS_COOKIE_SHA1` and `EXTERNAL`, so either the server requested unsupported mechanisms, or authentication failed for another reason.

To see which authentication mechanism is requested by the server, you can `(trace dbus::receive-authentication-response)`: the first call should return a list of authentication mechanism names. (It may be a good idea to add a `print-object` method to `dbus:generic-authentication-mechanism` so you could trace `dbus:supported-authentication-mechanisms` instead.)

If a mechanism is not supported, you can extend CL DBUS to support it. If authentication using a supported mechanism fails, this requires further debugging.  You can play with this in the REPL:

```lisp
CL-USER> (iolib:with-event-base (evb)
           (dbus:with-open-connection (conn evb (dbus:session-server-addresses))
             (dbus:supported-authentication-mechanisms conn)))
(#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {100FD506E3}>)
CL-USER> (iolib:with-event-base (evb)
           (dbus:with-open-connection (conn evb (dbus:session-server-addresses))
             (dbus:authenticate (dbus:supported-authentication-mechanisms conn)
                                conn)))
T
```

**Comment by death** [comment]
Looking at the backtrace given by @marcoheisig I see that the `EXTERNAL` authentication mechanism is used. The code passes the value of `(dbus::current-username)` to `dbus::encode-hex-string`, but it fails because this value is NIL.  CL DBUS uses POSIX `getpwuid` and `getuid` to get the current user's name, but for some reason the information is not provided.

**Comment by Ambrevar** [comment]
Thanks @death for this thorough explaination!  (And sorry for coming
back so late on this.)

Over the last couple of weeks we've studied the problem of RPC /
webkit-webengine bindings and we are thinking of engaging into a
different approach, so we might not have to use D-Bus in the future.

More on this soon, stay tuned!

**Comment by lxbarbosa** [comment]
yep, running in the same issue with `dbus-broken`

is there any drawback by running next with: `export $(dbus-launch) && next` ?

I will keeping calling it that way till a better solution arrives as advised.

Fedora 31 Mate (fresh install)

Thanks, anyway! :D

**Comment by Ambrevar** [comment]
No, there is no drawback!

We might roll out a permanent solution to the d-bus problem soon, stay tuned!

**Comment by Ambrevar** [comment]
Master does not use D-Bus anymore, so there should be no more startup problems.
Feel free to re-open if you are still experiencing issues on master.
