### ISSUE TITLE
Introspection capabilities like Emacs

### ISSUE THREAD

**Issue by Compro-Prasad** [atlas-engineer/next#295]
Is there something similar to `C-h k`, `C-h f` and `C-h v` like in Emacs? Will be great to introspect currently running `next` instance.

**Comment by Ambrevar** [comment]
Indeed!

For now there is `M-x inspect-variable` and `M-x inspect-function`, but
those are very limited and don't display much at the moment.

Enhanced internal and explorable documentation in one of the highest
priority goal for the next version.

**Comment by Ambrevar** [comment]
Master has improved introspection.
`C-h k`, `C-h f` and `C-h v` work.
The commands have been rename `describe-variable`, `describe-command`, `describe-key`.
There is also `describe-bindings` (C-h b).

**Comment by Compro-Prasad** [comment]
I did a serious try someday and I really got hooked into it but then forgot about it. I have now replaced Firefox with Next in application favourites. Will try to make it my daily workflow. Another thing from a Firefox user is that I am using containers to separate logins and cookies. Is that there in Next?

**Comment by Ambrevar** [comment]
Containers are not a first class feature yet, but they can already be
implement straight from the user's "init.lisp" file.

A poor man's option is to set XDG_DATA_HOME to a different value when
starting Next.

**Comment by Compro-Prasad** [comment]
Great to hear that. Is there an existing way to include a package? Is it the common lisp way or there will be a different package manager for next?

**Comment by Ambrevar** [comment]
For now you can use the Common Lisp way, e.g. drop the library you want
in `~/common-lisp`, then load the system from your init.lisp, e.g.

```
(asdf:load-system :my-lib)
```

Then you'll be able to access the library with

```
my-lib:foo-symbol
```

Way down the road Next might include a package manager.
