### ISSUE TITLE
Error building from source: next-pyqt-webengine.py missing [macOs]

### ISSUE THREAD

**Issue by rpgoldman** [atlas-engineer/next#298]
When running `make all` I get the following error:

```
mkdir -p ./Next.app/Contents/MacOS
mkdir -p ./Next.app/Resources
mv ./next ./Next.app/Contents/MacOS
cp -r ./ports/pyqt-webengine/ ./Next.app/Contents/MacOS
mv ./Next.app/Contents/MacOS/next-pyqt-webengine.py ./Next.app/Contents/MacOS/next-pyqt-webengine
mv: cannot stat './Next.app/Contents/MacOS/next-pyqt-webengine.py': No such file or directory
make: *** [app-bundle] Error 1
```

Looking at `./ports/pyqt-webengine/ ` I see that `next-pyqt-webengine.py` is there, but for some reason the `mv` command expects it to be one directory up instead.

I *think*  removing that `mv` line from the Makefile, and then copying `next-pyqt-webengine.py` from `./ports/pyqt-webengine/`  might fix this problem; at least that gets me through the build process.

**Comment by Ambrevar** [comment]
This is no longer relevant on master and in the 2.0 release (coming soon) since we don't use platform ports / dbus anymore.
