### ISSUE TITLE
Links in chat box are not highlighted

### ISSUE THREAD

**Issue by Manoj321** [atlas-engineer/next#30]
nEXT version: 0.05, 
OS: MacOS sierra 10.12.6

In hangout chat windows links are not highlighted with M-g/C-g hence there is no way to open them.

**Comment by jmercouris** [comment]
Hi, thank you for your report! this is because M-g/C-g are only used for link navigation at the current time, the system has to be expanded to handle things like buttons and input boxes. I'm working on designing a good way of doing this. I'll keep you updated!

**Comment by Ambrevar** [comment]
This is the same as #218.

**Comment by jmercouris** [comment]
Buttons are now handled! Please let me know if you would like to reopen this issue (problem unsolved, more suggestions etc), thank you!
