### ISSUE TITLE
libGL error on Gentoo with NVidia drivers

### ISSUE THREAD

**Issue by zovt** [atlas-engineer/next#303]
Hello, running the prebuilt binary on Gentoo with NVidia drivers gives the following error:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:17469): Gdk-ERROR **: 23:45:59.352: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 196 error_code 2 request_code 150 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I've attached the full log.

This results in nothing being displayed in the Next browser window, aside from being able to open
the URL bar.

Lutris seems to have a similar issue: https://github.com/lutris/lutris/issues/1926

Not sure if they are related, though. Let me know if you need any more information on my end, happy to help debug.
[next-gtk-webkit.log](https://github.com/atlas-engineer/next/files/3488483/next-gtk-webkit.log)

**Comment by Ambrevar** [comment]
Does it work if you export the environment variable

`WEBKIT_DISABLE_COMPOSITING_MODE=1`

?

For instance, if you run Next like this:

    env WEBKIT_DISABLE_COMPOSITING_MODE=1 next

I'm not sure Next can do anything about this, this is most probably an
OS configuration issue.

**Comment by zovt** [comment]
That does appear to fix the issue. Interesting, I'll mess around with it on my end and see if I can come up with a hack to fix it.

Thanks for the help

**Comment by Ambrevar** [comment]
I've also seen similar issues with Qutebrowser and Nvidia.
Have a look there:

https://github.com/qutebrowser/qutebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue+nvidia
