### ISSUE TITLE
M-backspace has some uncommon behaviour

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#306]
In the minibuffer, M-backspace has not the most effective behaviour, it is a bit too different from say Firefox:

- when the input ends with many slashes, it deletes only one, like a simple backspace. I'd like to remove all trailing slashes AND one word.
- it deletes one word AND the trailing slash (or space, point or any word delimiter). I'd like it to leave the slash. (`foo/bar/` M-backspace => `foo`, I want `foo/`)

**Comment by Ambrevar** [comment]
Ideally, we can write a customizable function.  Or maybe several
functions which the user would be free to choose from (or write their
own).

- Choice A: Delete 1 word if any then all punctuation.
  Examples:  `foo_-bar` => `foo`
  `foo_-` => `foo`

- Choice B: Delete 1 word _or_ all punctuation
  Examples: `foo_-bar` => `foo_-`
  `foo_-` => `foo`

**Comment by vindarel** [comment]
That's right. Tha's now easier to do with my little refactoring.
