### ISSUE TITLE
macos, iterm2, dbus errors

### ISSUE THREAD

**Issue by seanfarley** [atlas-engineer/next#308]
This is more of a The More You Know™ issue: `launchctl getenv DBUS_LAUNCHD_SESSION_BUS_SOCKET` returns nothing in iTerm2 due to its integration with tmux. I randomly found the info here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/73

For me, switching to another terminal fixed the issue (e.g. Alacritty, Terminal.app, etc). Just making this issue here incase anyone else runs into it.

**Comment by seanfarley** [comment]
Forgot to log the output:

```
./Next.app/Contents/MacOS/next
 <INFO> [16:00:55] next base.lisp (start) - NEXT::+VERSION+: "1.3.0-6d439d6"
 <INFO> [16:00:55] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /Users/sean/.config/next/init.lisp...
 <WARN> [16:00:55] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
 <INFO> [16:00:56] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.161
 <INFO> [16:00:56] next port.lisp (run-program port) -
  Current directory: /Volumes/Untitled/next/
 <INFO> [16:00:56] next port.lisp (run-program port) -
  Platform port path: ./Next.app/Contents/MacOS/next-pyqt-webengine
 <INFO> [16:00:56] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [16:00:56] next port.lisp (run-program port) -
  Platform port log file: /Users/sean/.local/share/next/next-pyqt-webengine.log
<ERROR> [16:00:57] next base.lisp (initialize-port remote-interface) -
  Could not connect to platform port: ./Next.app/Contents/MacOS/next-pyqt-webengine
<ERROR> [16:00:57] next port.lisp (kill-program port) -
  process #<PROCESS-INFO {100761BAB3}> is not running.
```

**Comment by Ambrevar** [comment]
Thanks for sharing, very useful indeed!
@jmercouris: We should probably mention this in the README.  Thoughts?

**Comment by jmercouris** [comment]
You know, I'm not sure, I've been thinking about this, and I'm wondering what a terminal would have to do with the dbus environment. I am not entirely sure about the context of which an application bundle is launched, perhaps it inherits from the default shell or something, I will have to do some searching before saying anything definitive.

**Comment by jmercouris** [comment]
this is fixed on master :-)
