### ISSUE TITLE
Failed start-up with newly built next app on Mac

### ISSUE THREAD

**Issue by rpgoldman** [atlas-engineer/next#312]
Built next from source last night.  When I try to start it from the shell I get this error message:

```
$ open ./Next.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/rpg/lisp/next/Next.app.
```

This may be some sandboxing thing.

The version from homebrew starts successfully.

MacOS 10.14.6

I don't know if this message during compilation is related:
```
   Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:PREPARE-OP
                                                     "next"), but dependency (ASDF/FIND-SYSTEM:DEFINE-OP
                                                                              "next") wasn't done yet!
WARNING: redefining PATH (#<STANDARD-CLASS NEXT::PORT>) in DEFMETHOD
WARNING:
   Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:COMPILE-OP
                                                     "next"), but dependency (ASDF/FIND-SYSTEM:DEFINE-OP
                                                                              "next") wasn't done yet!
WARNING:
   Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:LOAD-OP
                                                     "next"), but dependency (ASDF/FIND-SYSTEM:DEFINE-OP
                                                                              "next") wasn't done yet!
```
The `plan NIL` in the above is somewhat worrisome, and may indicate issues in the ASDF system definition.  Haven't had time to look.

**Comment by rpgoldman** [comment]
I should have mentioned -- I tried to run this from the source directory, instead of installing it in `/Applications` first.

**Comment by rpgoldman** [comment]
When I open as per @seanfarley example in another issue posting I see this:
```
rpg@RPG-MacBook-Pro: ~/lisp/next $ ./Next.app/Contents/MacOS/next
 <INFO> [09:49:03] next base.lisp (start) - NEXT::+VERSION+: "1.3.0-bdeb634" 
 <INFO> [09:49:03] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /Users/rpg/.config/next/init.lisp...
 <WARN> [09:49:03] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1006026373}>:
  No server addresses left to try to open.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006026373}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No server addresses left to try to open." {1006E60743}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No server addresses left to try to open." {1006E60743}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No server addresses left to try to open." {1006E60743}>)
3: (ERROR "No server addresses left to try to open.")
4: ((LAMBDA NIL :IN DBUS/PROTOCOLS:OPEN-CONNECTION))
5: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1006620F5B}> #<event base, 0 FDs monitored, using: #<kqueue(2) multiplexer> {100611E0F3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1006274163}>))
6: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
7: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
12: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {29FFD8B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006026373}>> NIL T NIL)
13: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006026373}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100602631B}> NIL)
14: ("foreign function: call_into_lisp")
15: ("foreign function: new_thread_trampoline")
16: ("foreign function: _pthread_body")
17: ("foreign function: _pthread_start")
18: ("foreign function: thread_start")
```
Not sure if this is the same bug or if I am hitting a different bug from starting the application differently.

**Comment by Ambrevar** [comment]
The ASDF warning can safely be ignored (for now, but we need to fix it
later).

The error "No server addresses left to try to open" is related to D-Bus.

@jmercouris ?

**Comment by glacambre** [comment]
I've had the same `No server addresses left to try to open.` issue on linux (debian testing/unstable). The problem indeed was with dbus ; although I did have a dbus process running for my session (other software such as notify-send were able to connect to it), next somehow wasn't able to find its address.

This might be related to the way dbus is configured on my machine (systemd starts it with `--address=systemd:` and I don't have any of the DBUS_SESSION_BUS_ADDRESS, DBUS_SESSION_BUS_PID or DBUS_SESSION_BUS_WINDOWID environment variables).

I'm working around this by starting a new dbus process in my shell and exporting its environment variables before running next, e.g. `export $(dbus-launch); ./next`.

Not sure if this helps. I hope it does :)

**Comment by Ambrevar** [comment]
Traditionally two dbus sessions can be run: the system session and the
user session.

It may be that systemd only starts the system bus, on which user
applications cannot register if I'm not mistaken.

Ghjuvan, which login manager and window manager are you using?  If you
run a low-level window manager, it's often required to start dbus
manually the way you did.

**Comment by glacambre** [comment]
I do have a system dbus and a user dbus runnnig. The user dbus is started by systemd. It has a weird address though (`"--address=systemd:"`), maybe that's why next couldn't find it.
In any case, don't waste time on my issue, I just mentionned my problem and the way I fixed it in the hope that it would help @rpgoldman fix his problem.

**Comment by rpgoldman** [comment]
I got dbus installed and running from brew, and once I got the dbus infrastructure set up and the requirements installed, now I get this error:
```
$ cat /Users/rpg/.local/share/next/next-pyqt-webengine.log
Traceback (most recent call last):
  File "./Next.app/Contents/MacOS/next-pyqt-webengine", line 9, in <module>
    from PyQt5.QtNetwork import QNetworkProxy
ModuleNotFoundError: No module named 'PyQt5.sip'
```
There's a bunch of discussion about the problem about `PyQt5.sip`, most of it confusing and none of it satisfactory.
I tried installing `pyqt5-sip` and then reinstalling `PyQt5`.  That fixed the above error but... now I get this:
```
$ cat /Users/rpg/.local/share/next/next-pyqt-webengine.log
Traceback (most recent call last):
  File "./Next.app/Contents/MacOS/next-pyqt-webengine", line 13, in <module>
    import buffers
ModuleNotFoundError: No module named 'buffers'
```
Looking at the file, it seems that this is a failure loading the `buffers.py` in `next-pyqt-webengine`.  Is there any chance that `next-pyqt-webengine.py` is making an assumption about `PYTHONPATH` that is not justified? Would this be fixed by changing it to `import .buffers` or adding an `__init__.py` there and doing `import next-pyqt-webengine.buffers` instead?

Possibly relevant to `PYTHONPATH` issue -- here is how I tried to run `next`:

    ./Next.app/Contents/MacOS/next

Also, I note that here is the webengine:
```
$ ls Next.app/Contents/MacOS/next-pyqt-webengine 
Next.app/Contents/MacOS/next-pyqt-webengine*
```
and that the buffers file it is looking for is not there (possibly related to the earlier `Makefile` issue):
```
$ ls Next.app/Contents/MacOS/
next*  next-pyqt-webengine*  pyqt-webengine/
rpg@RPG-MacBook-Pro: ~/lisp/next $ ls Next.app/Contents/MacOS/pyqt-webengine/
Makefile    core_interface.py     requirements.txt     testclient.py
README.org  dev-requirements.txt  test-dbus-client.py  utility.py
buffers.py  minibuffer.py         test-dbus-server.py  window.py
```

The following pretty disgusting kludge gets the webengine to start:
```
$ cat /tmp/next-pyqt-webengine.patch 
diff --git a/ports/pyqt-webengine/next-pyqt-webengine.py b/ports/pyqt-webengine/next-pyqt-webengine.py
index 0e41328..70d03b3 100755
--- a/ports/pyqt-webengine/next-pyqt-webengine.py
+++ b/ports/pyqt-webengine/next-pyqt-webengine.py
@@ -3,6 +3,7 @@
 import logging
 import sys
 from urllib.parse import urlparse
+import os
 
 import dbus
 import dbus.service
@@ -10,6 +11,10 @@ from PyQt5.QtNetwork import QNetworkProxy
 # from PyQt5.QtNetwork import QNetworkProxyFactory
 from PyQt5.QtWidgets import QApplication
 
+logging.basicConfig(level=logging.INFO)
+
+sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/pyqt-webengine")
+logging.info('After update, sys.path is {path}'.format(path=sys.path))
 import buffers
 import utility
 import window
@@ -18,9 +23,6 @@ try:
     from dbus.mainloop.pyqt5 import DBusQtMainLoop as MainLoop
 except ImportError:
     from dbus.mainloop.glib import DBusGMainLoop as MainLoop
-
-logging.basicConfig(level=logging.INFO)
-
 """
 This is a Next port with Qt's Web Engine, through PyQt.
 
```
... but then the lisp program seems to fail to connect and just hangs without popping up a Next browser window or putting the app icon in the Mac's dock.

**Comment by jmercouris** [comment]
fixed on master :-)
