### ISSUE TITLE
NEXT_RPC_AUTH_TOKEN error

### ISSUE THREAD

**Issue by inglada** [atlas-engineer/next#314]
When using the guix package I get this error when I start the browser:

```
** (next-gtk-webkit:16451): ERROR **: 20:05:59.598: An auth token must be provided over the NEXT_RPC_AUTH_TOKEN env var.
Trace/breakpoint trap
```
I am using the guix package manager, not the Guix OS.

Thanks

**Comment by inglada** [comment]
Sorry, I had not installed next-sbcl. However, I thought that if there was a dependency, it would be automatically installed.

**Comment by Ambrevar** [comment]
Note that upstream Guix does not have the latest version of Next (it
only has 1.2.2 for now).

If you want the latest version of Next, you must add the Next Guix
channel: https://gitlab.com/atlas-engineer/next-guix-channel
