### ISSUE TITLE
Hint delay on large pages

### ISSUE THREAD

**Issue by glacambre** [atlas-engineer/next#316]
On large pages such as https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html or https://en.wikipedia.org/wiki/Battle_of_Mosul_(2016%E2%80%932017), there is a noticeable delay before hints are displayed. Tridactyl and Qutebrowser's hints appear immediately, so I think there's probably a way to improve next's performance in this area.

**Comment by Ambrevar** [comment]
Indeed, the hinting code was mostly imported from the old LispKit
project, and it's far from ideal (slow and unflexible).  Besides, it
does not support buttons or input fields.

We need to rewrite it completely.  Patches welcome :)

**Comment by glacambre** [comment]
>We need to rewrite it completely.  Patches welcome :)

Don't worry, I do plan on contributing more and complaining less, but I still have to figure out how to setup my environment, it seems tools are mostly made to work with emacs, which I don't use, so I'm having a hard time navigating the project/debugging things :).

**Comment by Ambrevar** [comment]
You might find those pages useful then:

https://lispcookbook.github.io/cl-cookbook/getting-started.html
https://lispcookbook.github.io/cl-cookbook/editor-support.html

**Comment by Ambrevar** [comment]
Update: This is still a problem on master.

**Comment by jmercouris** [comment]
I had traced it to a problem with document query selector in Javascript. I looked at other link hinting utilities to see what they use to gather the link hints, and it is the same function. I can't understand why the performance suffers so much. It should be instantaneous like the buffer searching. I will look into this again in the future and do some more profiling.

**Comment by Ambrevar** [comment]
My guess is that other browsers do this withing the visible part of the
document, while we do it for the entire document.

If this is true, the fix would need to fill the hint list asynchronously.

**Comment by jmercouris** [comment]
That is not the problem, they do it for the whole document AND THEN filter only the visible ones (I looked at the source of two). If we remove the drawing part of the equation, and only consider capturing the link tags, it is still unbearably slow. That is the bottleneck, I was thinking we might be able to run the parenscript through some performance profiler or something, or try in a different way to capture the links. Maybe we can do it together one day and figure it out during a meeting or something, as it is a big pain point for me when using Next, waiting for the link hints to populate :-D

**Comment by Ambrevar** [comment]
Fixed in 
5c99c46d7b4358f25e7326b846f77e165cbecc7c.
