### ISSUE TITLE
There is no applicable method for the generic function NEXT::HISTORY-BACKWARDS

### ISSUE THREAD

**Issue by glacambre** [atlas-engineer/next#317]
Sorry if PEBKAC, but with the following configuration:
```lisp
(add-to-default-list 'vi-normal-mode 'buffer 'default-modes)
(define-key :scheme :vi-normal "J" 'history-backwards)
```
Pressing `J` after having browsed a few websites results in the following warning:
```
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: There is no applicable method for the generic function
                                                                #<STANDARD-GENERIC-FUNCTION NEXT::HISTORY-BACKWARDS (1)
                                                              when called with arguments
                                                                (#<NEXT::ROOT-MODE {100896F773}>).
See also:
  The ANSI Standard, Section 7.6.6.
```

I'm not sure what I'm doing wrong since other bindings (e.g. `(define-key :scheme :vi-normal "j" 'scroll-down)`)) seem to work correctly and [history-backwards](https://github.com/atlas-engineer/next/blob/41b6960004d7c9af08806064d7d86ba8f9c5568a/source/document-mode.lisp#L22) and [scroll-down](https://github.com/atlas-engineer/next/blob/41b6960004d7c9af08806064d7d86ba8f9c5568a/source/document-mode.lisp#L26) don't seem to require different binding methods.

**Comment by Ambrevar** [comment]
In Next, commands are bound to modes.
Commands that don't specify a mode are bound to the `root-mode` by
default.

This allows us to have commands of the same name for different modes.

Since `history-backwards` is bound to document-mode, you need to specify
it in `define-key`:

```
(define-key :scheme :vi-normal :mode 'document-mode
  "J" 'history-backwards)
```

Hope that helps!

**Comment by glacambre** [comment]
Ah, yes, now I'm not getting a warning anymore, however binding `J` to `'history-backwards` still does not work. I think this might be the same problem as https://github.com/atlas-engineer/next/issues/318, so I'll close this issue. Thanks for your help :)
