### ISSUE TITLE
Audio does not stop when buffer is killed

### ISSUE THREAD

**Issue by goose121** [atlas-engineer/next#322]
As in the title; it keeps going and there is no way to stop it afaict besides exiting. I ran into the issue on YouTube and strangely, autoplay seemed to work as well somehow, as the next video's audio began to play despite the buffer not seeming to exist any more.

Platform: Linux
Running commit: 962df03

**Comment by Ambrevar** [comment]
Are you sure you killed  the buffer (with M-x delete-buffer) and not the window?

**Comment by jmercouris** [comment]
If you are using the Qt port, I know why the audio keeps playing, I've experienced many of the same problems. The issue is incorrectly releasing the WebView, which we plan on fixing :)

**Comment by goose121** [comment]
> If you are using the Qt port, I know why the audio keeps playing, I've experienced many of the same problems. The issue is incorrectly releasing the WebView, which we plan on fixing :)

Ah, that would be it; thanks!

**Comment by Ambrevar** [comment]
@jmercouris Does this issue persist on master?

**Comment by jmercouris** [comment]
No, it does not persist on master. We can handle the destruction of webviews now that we can use del in C++ rather than python bindings deciding to implicity release objects when no references are left

**Comment by Ambrevar** [comment]
C++?
WebKitGTK is in C ;)

**Comment by jmercouris** [comment]
This issue was about a problem specifically with the Qt port

**Comment by Ambrevar** [comment]
OK! :)
