### ISSUE TITLE
youtube videos not playing with 1.3 (guix)

### ISSUE THREAD

**Issue by inglada** [atlas-engineer/next#327]
Hi,
Next works very well for me except for youtube, which does not play videos saying that my browser does not recognize any of the formats supported.
Is this a next bug or a missing dependency of the guix package?
Thanks.

**Comment by jmercouris** [comment]
I believe there is something optional with regards to gstreamer to enable video, however, I also believe this should have been in the latest Guix pack. Did you download the Guix pack or add the channel?

**Comment by inglada** [comment]
I added the channel

**Comment by inglada** [comment]
Looking at how the guix pack is built, I found that I was missing gst-libav and gst-plugins-bad (I had the good and the ugly ...). So I guess these are missing dependencies on the guix channel package.

**Comment by Ambrevar** [comment]
Both gst-libav and gst-plugins-bad are part of the Guix pack.  Did you
use the right pack?
(sha256sum is
8addfeebf1d0855307a2f38210ab33825fc8e30e9802652b977d9d5f7c64a485.)

It's possible nonetheless that the plugins to fail to load within the
pack, but then you can use your local package manager to install them
and it should work.

**Comment by inglada** [comment]
I think that I did not explain well enough the problem. I use the next guix channel to install next. It seems to me that the package description on the channel may be missing these dependencies, because I had to install them myself with guix.

**Comment by Ambrevar** [comment]
That's correct, it's because those dependencies are optional, as for all
other webkit-based browser in Guix.

**Comment by inglada** [comment]
OK. Thanks.
