### ISSUE TITLE
Minibuffer freezes after using C-s s

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#328]
When I use C-s s to search for something, the search succeeds but after that the minibuffer is frozen and no further commands work.  So far I haven't found other commands that cause the same problem.

I think it may be similar to what's happening in #182?

I'm using ubuntu and i3, and I have Chrome and qutebrowser open (not sure if that's relevant).  I installed using the tar file linked on https://next.atlas.engineer/download.

Let me know if there is any useful information I can provide.

**Comment by Ambrevar** [comment]
Why did you close the issue?  Did you solve it?
I cannot reproduce on my end.

**Comment by 4t0m** [comment]
Yeah, I think I was just confused about the different modes, and trying to use vi commands when that mode wasn't activated.  Feel free to delete this issue if you can.

**Comment by Ambrevar** [comment]
OK, no problem!
