### ISSUE TITLE
Reopening closed tabs

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#331]
Correct me if I'm wrong, but I don't think there's currently a way to do this.

My first thought would just be to have a text file such that:
1. When a tab is closed, the url is added to the top.
2. When "reopen-tab" is called, a new buffer is created with the top url of the file, and that url is removed.
3. The file is wiped each session.
(4. Maybe limit the total number of urls to ~50?)

**Comment by alexanderbarbosa** [comment]
https://github.com/atlas-engineer/next/issues/253#issuecomment-505616191

**Comment by 4t0m** [comment]
Shoot.  I thought I had searched for an issue but clearly not.  Should this be merged into that one.

Regarding the other discussion, are you thinking it's better to wait until the general problem can be solved, rather than doing something simpler like described above (or similar but without writing to a file).

**Comment by jmercouris** [comment]
No need to use a file, could just write to a queue for killed buffers or something. The general solution needs more thought yet, until then we can implement it as a queue. Thoughts?

**Comment by 4t0m** [comment]
Sounds good. I'm not totally sure what I'm getting into but it doesn't seem like this should be too hard.  I'll get to work on it as soon as I can get the development installation set up.  Unfortunately I'm having quite a bit of difficulty.

**Comment by jmercouris** [comment]
Feel free to ask here, on IRC or via email! We’ll be glad to help!

**Comment by 4t0m** [comment]
Thanks :)  At the moment I'm dealing with the same problem as #333.

**Comment by jmercouris** [comment]
Don't worry, this isn't StackOverflow :)
