### ISSUE TITLE
Expanding the minibuffer during link hinting

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#332]
I prefer the vimium or qutebrowser implementations of link hinting, where the no minibuffer is expanded and links are followed immediately on the "hint" keypress (i.e. without the need to press enter).  

Are there advantages to having it work as it currently does?

**Comment by alexanderbarbosa** [comment]
That is a long term discussion...

**Comment by Ambrevar** [comment]
Yes, link-hinting is currently a quick-n-dirty implementation.
We will improve it in the near future, there are plans about making
something real nice, like fuzzy-searching link URLs and titles, fuzzy
search the hints themselves, adding hints to buttons, fields and
pictures, etc.

If someone feels like giving it a shot, PRs are welcome! :)

**Comment by Ambrevar** [comment]
Closing in favour of #354.
