### ISSUE TITLE
Error when running `guix package -f build-scripts/guix.scm`

### ISSUE THREAD

**Issue by daviwil** [atlas-engineer/next#333]
Hi all!

I'm trying to build next from source using Guix and I've encountered the following error:

```
$ guix package -f build-scripts/guix.scm
guix package: error: failed to load 'build-scripts/guix.scm':
ice-9/boot-9.scm:2803:6: In procedure resolve-interface:
no code for module (next packages lisp)
```

I haven't been using Guix for very long so I'm not sure how to diagnose this issue.  Any pointers?

Just in case it matters, the only thing I've got installed in my current profile is `glibc-locales`:

```
$ cat /var/guix/profiles/per-user/daviwil/guix-profile/manifest
(manifest
  (version 3)
  (packages
    (("glibc-locales"
      "2.28"
      "out"
      "/gnu/store/acl2wxzzkkcjv74rlqswdf9p8pwddlmk-glibc-locales-2.28"
      (propagated-inputs
        (("linux-libre-headers"
          "4.14.67"
          "out"
          "/gnu/store/3c9a43ifhbjm8lsc1s183y8a8874fz01-linux-libre-headers-4.14.67"
          (propagated-inputs ())
          (search-paths ())
          (properties))))
      (search-paths ())
      (properties)))))
```

Thanks!

**Comment by 4t0m** [comment]
What happens when you try to run "guix pull".  I get an error there and I'm wondering if we're having the same problem.

**Comment by MasterCsquare** [comment]
You also need to add guix channel, some non-free dependencies are required. That's why it say that "no code for module".

**Comment by daviwil** [comment]
@4t0m `guix pull` works fine for me on two different machines today, both with the standard channel(s) and the `next` channel that @MasterCsquare mentioned above.

@MasterCsquare Thank you, that worked!  It seems obvious now but it definitely wasn't clear from the error.

**Comment by daviwil** [comment]
Created PR #334 to improve the doc header in `guix.scm` so that others don't run into this issue.

**Comment by Ambrevar** [comment]
@4t0m : The channel seems to work for @daviwil and @MasterCsquare and others.  Are you still having issues with it?

**Comment by 4t0m** [comment]
@Ambrevar: I'm still having trouble, but it seems like an unrelated problem with installing GUIX.  I'll comment here if I sort that part out and still have trouble with this step.

**Comment by 4t0m** [comment]
@Ambrevar I've got it working now.

**Comment by Ambrevar** [comment]
What was the issue?
