### ISSUE TITLE
Streamline test suite

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#335]
In PR #315 we mentioned the lack of user interface for the test suite.
We need to streamline the way the test suite is loaded though.

- make test only tests if Next starts, it does not run the test suite which is confusing.
- The .asd does not have a test-op. How did you run the test files? With C-c C-k?
    By the way we need to add prove as a dependency.

So I suggest we add a simple test-op to the .asd and we update the test rule in the Makefile to run it.

Do you know how to run all test files found in the tests folder (without listing them one by one)?

@vindarel ?

**Comment by jmercouris** [comment]
I don't know of a way to run all test files in the folder other than iterating through the files and loading them one by one. In any case, I prefer explicit over implicit, and the test op should, in my opinion explicitly mention the files.

**Comment by Ambrevar** [comment]
Don't we want to test all test files?  I see explicit listing as an extra maintenance burden, which is error prone.

**Comment by jmercouris** [comment]
There are very few scenarios in which we don't want to test all files, you are correct. However, I don't like the magic of things just being loaded when dropped into the test folder. Seems dangerous.

**Comment by vindarel** [comment]
Yes, I ran the test with C-c C-k. It was already a help for development. I'll assign this to me.

btw, I don't want to stick with Prove, but consider Rove.

**Comment by Ambrevar** [comment]
Rove looks nice, and it has coverage support, yaik!

**Comment by Ambrevar** [comment]
@jmercouris: I would not call it "magic", but rather "automation".
After all, this is what computing is all about.

Saying "test all files in a folder" does not mean we lose control or
hide information: the test report remains explicit (e.g. what was
tested, what failed, etc.).

**Comment by jmercouris** [comment]
I like Rove, looks nice! I would not call it automation, it is most definitely a magical folder :D

However, my feelings are not so strong, either way is OK!

**Comment by Ambrevar** [comment]
Fixed in 17d07abba75567f86a9859c4f7020836ab037bf7.
We now test every subsystem.
The Guix build scripts also calls all test suites.
The Makefile tests the "next" system + that `next -h` returns exit code 0.

**Comment by jmercouris** [comment]
Great! thank you!
