### ISSUE TITLE
Enable dead-key support

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#339]
from #324

**Comment by Ambrevar** [comment]
Fixed in  aebc9110723dddeb3f83f167b92e964e0a60d310.
Note that I don't know how PyQt handles this.  @vindarel @jmercouris ?

**Comment by jmercouris** [comment]
The answer, currently, not well :)

Basically we have trouble distinguishing modifier keys from non modifier keys in Qt... I could go into it, but it would be a very very lengthy explanation. I spent an easy two weeks on this problem alone if you combine EQL + the PyQt port.

**Comment by Ambrevar** [comment]
This fix does not need to know about modifiers.

What I did in the aforementioned commit it to force the forwarding of every keypress to a dummy "text widget".  Whenever the widget has 1 character in it, I pop it and store it in to the key string.

I don't know how that would map to Qt, but actually it's even possible that it works out of the box in Qt.  It really depends how Qt deals with input methods (a.k.a. IM).

**Comment by Ambrevar** [comment]
This issue should no longer exist on master.

**Comment by Ambrevar** [comment]
Actually dead keys work in the web view but not in the minibuffer.

**Comment by Ambrevar** [comment]
They now work in the minibuffer with 28405ebc2298cad69c75a4221d45dd342b9051b8.
