### ISSUE TITLE
Support keypad keys

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#340]
Keypad scrolling keys (page down/next/end…) have no effect in either the Gtk or PyQt port.

**Comment by Ambrevar** [comment]
I propose to use a translation table (we already have one, but it is not
general enough) the following way:

"When a key is unbound, check all translations successively from a table.
And maybe: after the table has been checked, try again without modifiers."

For instance, the translation (hash) table could have the values:

"KP_Left" -> ("Left")

Then "C-KP_Left", if unbound, would fallback on "C-Left", which would
fallback on "KP_Left", which would fallback on "Left".
