### ISSUE TITLE
search for :  remember recent searches  in current page

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#341]
Hi,

Searching for a term in current page, if user need to search that term again, user will need to rewrite it yet again as it searches terms are not stored as browsing history.

Such a feature is available is in Chrome and Firefox.

Thanks!

**Comment by Ambrevar** [comment]
Indeed.

Once we've overhauled the minibuffer to be stateless (and use a new
minibuffer instance every time), we can implement Emacs / Helm's `M-p`
to bring up a minibuffer of input history.

By the way, input history should work per-command, and only fall back
to the generic history if no specialized history is specified.

**Comment by Ambrevar** [comment]
Fixed in f56bf3019aa1d67198203bb782910c3faf448b5d.  Feel free to re-open if you have any issue!
