### ISSUE TITLE
ensure-dbus-session fails on macOS w/ Homebrew dbus

### ISSUE THREAD

**Issue by tviti** [atlas-engineer/next#350]
I compiled `next` from source, and although the compilation seems to have gone swimmingly, I can't seem to get it to actually run (at face value, I would guess there's some problem with my dbus installation?).

OS is macOS v 10.14.6 

Per the dev. install instructions in `next/ports/pyqt-webengine/README.org`,
I setup the python requirements in a new `conda`  env as:
```
$ conda create -n next_browser python=3
$ conda activate next_browser
$ cd ./ports/pyqt-webengine/
$ pip install -r ./requirements.txt
```

`dbus` was installed and started with
```
$ brew install dbus
$ brew services start dbus
```

Without really knowing how dbus works (and thus what I'm really looking at here), the following seemed to confirm to me that `dbus` was working:

In a new terminal window, I did a `$ dbus-monitor`, then in a new tab
```
$ ./ports/pyqt-webengine/next-pyqt-webengine.py 
INFO:root:Listening...
``` 

With the first terminal tab then showing:
```
signal time=1567650310.491081 sender=org.freedesktop.DBus -> destination=:1.3 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.3"
signal time=1567650310.491152 sender=org.freedesktop.DBus -> destination=:1.3 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.3"
method call time=1567650314.946903 sender=:1.4 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1567650314.946922 sender=org.freedesktop.DBus -> destination=:1.4 serial=1 reply_serial=1
   string ":1.4"
signal time=1567650314.946937 sender=org.freedesktop.DBus -> destination=(null destination) serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.4"
   string ""
   string ":1.4"
signal time=1567650314.946949 sender=org.freedesktop.DBus -> destination=:1.4 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.4"
method call time=1567650314.947626 sender=:1.4 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "engineer.atlas.next.platform"
   uint32 0
signal time=1567650314.947648 sender=org.freedesktop.DBus -> destination=(null destination) serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "engineer.atlas.next.platform"
   string ""
   string ":1.4"
signal time=1567650314.947661 sender=org.freedesktop.DBus -> destination=:1.4 serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "engineer.atlas.next.platform"
method return time=1567650314.947668 sender=org.freedesktop.DBus -> destination=:1.4 serial=4 reply_serial=2
   uint32 1
```

However, actually trying to run `next` suggested to me that `next` was not "seeing" `dbus`:
```
$ ./Next.app/Contents/MacOS/next
 <INFO> [16:29:07] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-4f8a98d" 
 <INFO> [16:29:07] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /Users/taylor/.config/next/init.lisp...
 <WARN> [16:29:07] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
<ERROR> [16:29:07] next remote.lisp (ensure-dbus-session fun1 fun18) -
  D-Bus launcher "dbus-launch" not found.  Please install D-Bus.
```

Again, without really knowing what I am doing here, I thought I'd try hard coding in the abs-path to dbus-launch, by encapsulating the body of `ensure-dbus-session` within a `let` block:
```
(defun ensure-dbus-session (interface)
  (let ((+dbus-launch-command+ "/usr/local/bin/dbus-launch"))

...

```

which upon recompiling and re-trying to run yields
```
$ ./Next.app/Contents/MacOS/next
 <INFO> [16:33:44] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-4f8a98d" 
 <INFO> [16:33:44] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /Users/taylor/.config/next/init.lisp...
 <WARN> [16:33:44] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
<ERROR> [16:33:44] next remote.lisp (ensure-dbus-session fun1 fun18) -
  D-Bus launcher "/usr/local/bin/dbus-launch" not found.  Please install D-Bus.
```

Again, without knowing the expected behaviour, trying `dbus-launch` from a terminal yields an error:
```
$ dbus-launch
dbus-daemon[4268]: Failed to start message bus: Check-in failed: No such process

EOF in dbus-launch reading address from bus daemon
```

If that is indeed the problem (i.e. that `dbus-launch` on its own shouldn't just throw an error) then the error message from `next` feels misleading.

**Comment by tviti** [comment]
Ok, so noticing that the error I am getting from `dbus-launch` is mentioned here https://github.com/zbentley/dbus-osx-examples/tree/master/installation#manually-launching-the-session-bus, I figured I'd try setting up `dbus` per those instructions, instead of just the default whatever-it-is that Homebrew does.

```
$ brew services stop dbus
$ mkdir /tmp/dbus
```

and then modified `/usr/local/opt/dbus/share/dbus-1` as follows:
``` 
<!-- <listen>launchd:env=DBUS_LAUNCHD_SESSION_BUS_SOCKET</listen> -->
<listen>unix:path=/tmp/dbus/taylor.session.usock</listen>
```

Now, trying to start `next` yields the following error:
```
$ ./Next.app/Contents/MacOS/next
 <INFO> [17:42:06] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-4f8a98d" 
 <INFO> [17:42:06] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /Users/taylor/.config/next/init.lisp...
 <WARN> [17:42:06] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
 <INFO> [17:42:06] next remote.lisp (ensure-dbus-session fun1 form-fun-21) -
  D-Bus session inaccessible, starting our own one.
  Old D-Bus addresses: (NIL
                        /private/tmp/com.apple.launchd.BVdwHHiCac/unix_domain_listener)
  New D-Bus address: unix:path=/tmp/dbus/taylor.session.usock,guid=4e1674a5cd81c16f74d09cb75d70840e
 <INFO> [17:42:06] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/tmp/dbus/taylor.session.usock">)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1005F547D3}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005F547D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {100612EF63}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {100612EF63}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {100612EF63}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {10061279E3}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {10060598B3}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005F5B54B}> #<event base, 0 FDs monitored, using: #<kqueue(2) multiplexer> {1005F59B33}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005F5B403}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {29FFD9B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005F547D3}>> NIL T NIL)
14: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005F547D3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1005F5477B}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")
17: ("foreign function: _pthread_body")
18: ("foreign function: _pthread_start")
19: ("foreign function: thread_start")

unhandled condition in --disable-debugger mode, quitting
```

or

```
$ open ./Next.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/taylor/next/Next.app.
```

**Comment by Ambrevar** [comment]
Thanks @tviti for this very thorough investigation, this is very helpful!

1. you are right about the error message saying that D-Bus should be installed.  I've just fixed it, so now it should complain with the right error.

2. It's weird that it doesn't work with Homebrew.  I would really like to know what's going on.

3. Your last attempt at setting D-Bus manually seems like it's almost working.  Can you confirm that your user has full read/write access on the socket?

```
ls -l /tmp/dbus
ls -l /tmp/dbus/taylor.session.usock
```

**Comment by tviti** [comment]
Yup, I did a `chmod u+rwx` after making the folder. Here's what I get (this is starting from no running `dbus-daemon` instances, and then using `next` to launch one, i.e. allowing `next` to create `taylor.session.usock` using `dbus-launch`):

```
(next_browser) R-Daneel:next taylor$ ./Next.app/Contents/MacOS/next
 <INFO> [11:24:35] next base.lisp (start) - NEXT::+VERSION+: "1.3.1-4f8a98d" 
 <INFO> [11:24:35] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /Users/taylor/.config/next/init.lisp...
 <WARN> [11:24:35] next minibuffer.lisp (echo) -
  Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface
 <INFO> [11:24:35] next remote.lisp (ensure-dbus-session fun1 form-fun-21) -
  D-Bus session inaccessible, starting our own one.
  Old D-Bus addresses: (NIL
                        /private/tmp/com.apple.launchd.BVdwHHiCac/unix_domain_listener)
  New D-Bus address: unix:path=/tmp/dbus/taylor.session.usock,guid=1beba825767201f5a07e686d5d717d13
 <INFO> [11:24:35] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/tmp/dbus/taylor.session.usock">)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1005F5C5E3}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005F5C5E3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {1006136F63}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {1006136F63}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {1006136F63}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {100612F9E3}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {1006060CB3}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005F648FB}> #<event base, 0 FDs monitored, using: #<kqueue(2) multiplexer> {1005F62EE3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005F647B3}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {31FFD9B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005F5C5E3}>> NIL T NIL)
14: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005F5C5E3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1005F5C58B}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")
17: ("foreign function: _pthread_body")
18: ("foreign function: _pthread_start")
19: ("foreign function: thread_start")

unhandled condition in --disable-debugger mode, quitting
(next_browser) R-Daneel:next taylor$ ls -l /tmp/dbus
total 0
srwxrwxrwx  1 taylor  wheel  0 Sep  5 11:24 taylor.session.usock
(next_browser) R-Daneel:next taylor$ ls -l /tmp/dbus/taylor.session.usock 
srwxrwxrwx  1 taylor  wheel  0 Sep  5 11:24 /tmp/dbus/taylor.session.usock
(next_browser) R-Daneel:next taylor$ 
````

Possibly worth mentioning: This is all done without having a background `dbus` process started by `launchd` (i.e. this is after having doing a `brew services stop dbus`).

Also: I'd have to spend some time fiddling with it later on to trace my steps exactly, but a better option for macOS (if this is indeed stepping in the right direction) may be to setup `+dbus-launch-command+` to explicitly point to a particular socket. That way, a user doesn't have to go messing around in config files during the install process. Last night I tried something along these lines (with the default `session.conf`), and managed to get to the same error message. IIRC, I did something along the lines of:

global.lisp:
```
(defparameter +dbus-launch-command+ '("dbus-daemon" "--session" "--fork" "--address=unix:path=/Users/taylor/next/dbus/usock"))
```

With `ensure-dbus-session` in remote.lisp set to accept `+dbus-launch-command+` as a list instead of a string (I basically just removed the `(list ...)` statement that encloses the reference).

**Comment by Ambrevar** [comment]
I like your last suggestion, I'll implement this.

So regardless of the way you start dbus, Next always fails with the same error?

Does `dbus-launch` work when run from a shell?

**Comment by tviti** [comment]
> I like your last suggestion, I'll implement this.

Cool!


> So regardless of the way you start dbus, Next always fails with the same error?
> 
> Does `dbus-launch` work when run from a shell?

I'm not sure what did it, but having to manually specify the bus address seems to no longer be an issue (using the default `session.conf`, next and other dbus fanfare can now connect to the session bus). I'm not 100% on what did it, (since I'm not even positive when the change happened; previously I was automatically setting it up as `DBUS_SESSION_BUS_ADDRESS=unix:path=$DBUS_LAUNCHD_BUS_ADDRESS`, then randomly disabled it and noticed I could still connect), but one thing I did do at one point was reinstall dbus and dbus-glib from source (again using brew).

I tried the two `test-dbus...` scripts in `ports/pyqt-webengine`, and from what I can tell (from evesdropping using `dbus-monitor`), the both client and server connect to the bus OK, and can communicate with `org.freedesktop.DBus` OK. The client is also well aware of the API the server provides (it will even complain if you try to call a method that doesn't exist), but the server never seems to actually get the messages.

The first sign of failure is that the server never responds to the client's `Introspection` request, and if you bypass introspection (by setting `introspect=false` in method call), and modify `test-dbus-server.py` to contain:

```
    def ping(self):
        print("Somebody called ping()!")
        return 'pong'
```

Nothing is ever printed by the server.

**Comment by tviti** [comment]
Ok, so I REALLY wanted to see this browser working, but also get fedup with trying to debug `dbus-python`, so I wound up just forking `next` and changing the PyQtWebengine port to use `QDBus` for RPC.

And it works! Kind of... I can get a browser window now, and at first glance things seem to be functional, but for some reason the core will frequently get stuck in some kind of a situation where it fills the `key-chord-stack` with `key-chords` as it receives them, ad infinitum, and nothing will work. If I manually wipe the `key-chord-stack` from the LISP repl with `(setf (key-chord-stack *interface*) nil)`, then it drops me back into the normal "mode" where I can pop up the minibuffer and do things. I haven't figured out the exact chain of events that triggers this bug, but one way I can reliably create it is by going to some page with an input form (e.g. google.com), and then clicking inside of the form. 

From what I can tell, the `EventFilter` never hits a logic branch in which it DOESN'T set `x` and `y` to the magic `-1` vals, so in the `push-input-event` callback, `pointer-event-p` always evals to `nil`, and so the callback never enters the branch with `rpc-generate-input-event` (which I'm guessing is supposed to kick the `key-chord`s back to the port).

I'm aware that at this point, I'm probably on my own as far as support goes since I've forked, but I did want to ask: is this a known bug with the QT port? Or should I still be suspicious that this is to do with the switch to `QDBus`?

**Comment by Ambrevar** [comment]
Thanks a lot for this extremely thorough effort! :)  You are helping a
lot!

You are not on your own, we really want to fix the PyQt port which is
much more experimental than the WebKit port.
The question of which D-Bus library to use has been a struggle before,
and it seems that it still is!

Question: if you don't click on any input field, can you use the
minibuffer (e.g. "C-l foo RET") and click on links?

As for the logic issue, this probably means that the PyQt platform port
is not setting the "don't forward key back" boolean, so the keys keep
looping around between the platform port and the Lisp core.

@vindarel?

@tviti: Since you seem so passionate about Next (I really appreciate
it!), I can give you some guidance on how to investigate the issue
deeper.
First, have a look at
https://github.com/atlas-engineer/next/blob/master/ports/README.org, it
explains how the key business is handled.



Note that if you just want to see Next working, you can also install the
X11 layer for macOS (forgot the name), and run the WebKit port instead!
Feedback welcome in that area too ;)

**Comment by tviti** [comment]
Well, I seem to have sorted out the logic issue. Per my previous post (sorry, in retrospect putting the edit at the top probably made things unclear), that was my fault, and turned out to be a problem with the way I setup the dbus service. I don't fully understand the sequence of events, but I do know that I had the wrong argument types declared on the service (in particular, string arrays were showing up as variant arrays during introspection). So, I think what was happening, is that `push-input-event` actually WAS hitting the right logic branch to forward the `key-chord` back to the port using `rpc-generate-input-event`, but the call to `rpc-generate-input-event` would fail because the sent argument types didn't match the argument type declarations on the service, and hence the line that wipes the `key-chord-stack` clean never got hit. I'm surprised that the failure wouldn't just crash the lisp interpreter, but admittedly I don't know much about lisp (part of the reason I got stoked about this browser was it seemed like a cool excuse to learn some more lisp).

Took a little more hacking to get upper case and spacebar working (I'm pretty sure the way I did that is a fudge too; I am just waiting for the moment I do a key combo that crashes everything), but I am thankfully writing this message to you from within next browser!

**Comment by Ambrevar** [comment]
I replied by email, so I didn't see your edit.  Because GitHub does not notify for edits, I think it's good practice to never edit the content of a message beside fixing typos.

**Comment by Ambrevar** [comment]
Congrats on getting Next to work!  Would you mind sharing your work, e.g. a link to your fork with your latest changes?  We could learn a lot from there.

Regarding the space bar: the character is send as "SPACE" via D-Bus.  Like BACKSPACE, DELETE, HYPHEN, RETURN, ESCAPE, TAB and a couple more.  Are any of those keys working?

**Comment by tviti** [comment]
Sure! Fork can be found at https://github.com/tviti/next

> Regarding the space bar: the character is send as "SPACE" via D-Bus. Like BACKSPACE, DELETE, HYPHEN, RETURN, ESCAPE, TAB and a couple more. Are any of those keys working?

Yep! Backspace wipes one char previous, delete wipes the next char, return works for newline or entry on an input field, escape I haven't tested much but it works for getting out of `VI-insert-mode`, and tab toggles to the next "object" in the browser window.

The only weirdness I notice so far (based on the looking through the log): It looks like when I am typing quickly, and I accidentally overlap a space with a shift, it gets interpreted as a page up, but this is probably because of how I am naively ignoring `generate_input_event`.

**Comment by Ambrevar** [comment]
Strange indeed.  Maybe a macOS thing?  It's common that some combition of key and modifiers generate other keys at the kernel level.

**Comment by Ambrevar** [comment]
Back to the original D-Bus issue: see the end of the discussion at #292 and in particular @death comments.
I'm also working on it.

**Comment by Ambrevar** [comment]
This issue should be no longer relevant with master.
We can close this once 2.0 is released.
