### ISSUE TITLE
Could not connect to platform port error on Ubuntu.

### ISSUE THREAD

**Issue by BenKey** [atlas-engineer/next#351]
Your installation documentation leaves something to be desired.

I ran the following command as instructed.

> sudo sysctl -w kernel.unprivileged_userns_clone=1

The result was as follows.

> sysctl -w kernel.unprivileged_userns_clone=1

The instructions then say to modify either /proc/sys/kernel/userns_restrict or /proc/sys/kernel/unprivileged_userns_clone depending on which file exists. In my case, the file /proc/sys/kernel/unprivileged_userns_clone exists. Therfore I attempted the following command.

> sudo echo 0 > /proc/sys/kernel/unprivileged_userns_clone

The result is as follows.

> bash: /proc/sys/kernel/unprivileged_userns_clone: Permission denied

Running ./usr/local/bin/next results in the following error.

> <ERROR> [02:58:19] next base.lisp (initialize-port remote-interface) -
>  Could not connect to platform port:
> /gnu/store/5hh6qpp4lqa6gy1ghdb4ppvjamgb3mbc-next-gtk-webkit-1.3.1/bin/next-gtk-webkit

Note. I think both are attempting to modify the same value. In one command, if I am reading it correctly, you set the value to 1. In the other, you set the value to 0. Which is it, 0 or 1?

Since I was able to get the sysctl command to work, I tried both values and they both result in the same error.

Please help.

The following is the result of running uname -a.

> Linux bk-linux 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Ambrevar** [comment]
Thanks for reporting.  I can see how some parts of the instructions can be confusing.  I'll update them.

So you are supposed to enable user namespaces using _either_ the `sysctl` comand, or the `/proc` command.
Note that when the command starts with a `#` it's meant  to be run as root.
`sudo echo 0 > ...` won't work because only "echo 0" is executed with higher privileges, not the redirection to a file.  So either you run `sudo su` to switch to root and run the command, or you can run `sudo sh -c "echo 0 > /proc/...`

Does that make more sense?  Let me know if you need more help.

**Comment by Ambrevar** [comment]
It might not fix your issue though.  Can you please post the complete output?

**Comment by Ambrevar** [comment]
@BenKey: I've updated the instructions at https://next.atlas.engineer/download, hopefully it will now be clearer!  Thanks for pointing that out!

**Comment by BenKey** [comment]
Thanks. The updated instructions are far more clear now. I think I will
need to  install Guix <https://guix.gnu.org/> and run 'guix install next.'
I will try it this evening.
*-- *

*Ciao,*
*Ben Key*
*Email: bkey76@gmail.com <bkey76@gmail.com>*
*Website: https://sullivanandkey.com/ <https://sullivanandkey.com/>*
*-- *

**Comment by Ambrevar** [comment]
This issue should be gone on master.
We can this with the release of 2.0.

**Comment by Ambrevar** [comment]
2.0 release inbound. Closing.
