### ISSUE TITLE
Is there smooth scrolling support?

### ISSUE THREAD

**Issue by jasonsun0310** [atlas-engineer/next#357]

**Comment by jmercouris** [comment]
Hi Jason, unfortunately not at the moment, but if you can do it in parenscript, you can do it in Next! Thank you for the suggestion!

**Comment by Ambrevar** [comment]
The lack of smooth scrolling is a bit annoying on laptops indeed.
We can add support in full Lisp, shouldn't be too hard:

- Store the time/speed of the last scroll call, e.g. in a mode or in the
`window' class.

- Change the scroll functions to take the previous values into account
to compute the current scroll "speed".

Jason, would you be interested in contributing a patch?

**Comment by jasonsun0310** [comment]
Sure. I will contribute to this one.

**Comment by Ambrevar** [comment]
Hooray! :)

**Comment by ajgrf** [comment]
Once WebKit implements [#188043](https://bugs.webkit.org/show_bug.cgi?id=188043), smooth scrolling will be very easy:

    (define-parenscript %scroll-half-page-down ()
      (ps:chain window (scroll-by (ps:create top (/ (ps:@ window inner-height) 2)
                                             left 0
                                             behavior "smooth"))))

Of course there's no need to wait if you want to implement it now, though.

**Comment by Ambrevar** [comment]
Good to know, thanks for the link!

**Comment by Ambrevar** [comment]
Master has smooth scrolling support.

**Comment by Shamaoke** [comment]
> Master has smooth scrolling support.

How it can be enabled?

**Comment by jmercouris** [comment]
it should already be enabled on master, is it not working for you? What is your system information?

**Comment by Shamaoke** [comment]
What is meant by “smooth scrolling”? Is that mouse wheel scrolling or keyboard scrolling (^n, ^p)? For me, keyboard scrolling isn't smooth. When I press ^n, ^p the page is scrolled line by line, so scrolling is discrete. Mouse wheel scrolling is not so discrete as keyboard scrolling, but I wouldn't call it “smooth”.

I'm on Arch (Linux). I built Next today from master.

**Comment by jmercouris** [comment]
C-n and C-p are not intended to be smooth, the arrow keys should be smooth though, the mouse/trackpad should also be relatively smooth... I guess smooth is a relative term :-D

**Comment by Ambrevar** [comment]
We have two scrollings, which I think can be considered a feature.  The
benefit of non-smoot scrolling is that it's faster, especially on
websites where the smooth-scroll speed is very slow.

**Comment by Shamaoke** [comment]
> especially on websites where the smooth-scroll speed is very slow

What does that mean? Scroll speed should be constant on all websites.

**Comment by jmercouris** [comment]
It is not, for example, websites can take over the in browser scroll and do other things (try it on the apple website for some products)
