### ISSUE TITLE
no minibuffer for changing/setting url

### ISSUE THREAD

**Issue by spiderbit** [atlas-engineer/next#358]
In nixos with exwm I don't see a minibuffer for entering url. There is a minibuffer for execute-command but even if I try to open the set url command in there doesn't give me a input buffer.

When I start next I get following message:

> <WARN> [18:13:49] next minibuffer.lisp (echo) -
>   Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface

I use the next 1.3.1 guix package.

**Comment by Ambrevar** [comment]
Hmm, curious issue.

Can you share the full shell output?

Did you install the Guix pack or the Guix package using =guix install next=?

My hunch is that since it works for execute-command, the issue might be
that set-url depends on SQLite and the history.db file.  What are the
files in ~/.local/share/next?

>> <WARN> [18:13:49] next minibuffer.lisp (echo) -
>>   Can't echo 'MINIBUFFER-MODE enabled.' without minibuffer or interface

This message is harmless, no need to worry about it.  (It will disappear
very soon by the way.)

**Comment by spiderbit** [comment]
Yes I just set the window to floating and when I pressed C-l it outputs that:

> WARNING:
>    Method handler (NEXT::CORE-OBJECT
>                    NEXT::PUSH-INPUT-EVENT) signaled an error: Could not prepare an sqlite statement.
> Code ERROR: no such column: visits.
> Database: /home/black/.local/share/next/history.db
> SQL: select url from typed where url like ? order by visits desc.

so your assumptions are right.

**Comment by Ambrevar** [comment]
It's a migration issue.  We will get rid of SQLite soon, so for now that
easiest way to go is simply to remove
/home/black/.local/share/next/history.db and restart Next.

**Comment by spiderbit** [comment]
ok that worked now I have problems because of high-dpi so I have to wait till the highdpi bugs are solved :D but maybe it's a alternative for my old netbook instead of vimb.

There was no working solution for default zoom for the content yet right?

**Comment by Ambrevar** [comment]
Now that we have hooks, you can set the default zoom for content (at
last!).

I'll expand on this soon when I start working on the font size in the
minibuffer, which should solve the HiDPI issue.

Coming Soon©, stay tuned!

**Comment by Ambrevar** [comment]
You can now set the default zoom for content and for the minibuffer.
See https://github.com/atlas-engineer/next/issues/293 for an example.

Hope this helps!  Feel free to re-open if there is anything else.
