### ISSUE TITLE
Display commands in lowercase

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#364]
`M-x` displays commands in all caps.  What about switching to lower case?  It would be typographically less "aggressive".
It's a trivial change.

**Comment by vindarel** [comment]
\+ 1

**Comment by jmercouris** [comment]
I like the all caps, no room for ambiguity in the letters, gives weight to what you are doing

**Comment by Ambrevar** [comment]
Why would there be ambiguity in lowercase?
Are you talking about the font style?

**Comment by alexanderbarbosa** [comment]
I see no way how would that improve anything. Most FLOSS use capital modifiers.

**Comment by jmercouris** [comment]
Yes I’m simply referring to the font style, for example “l” vs “i”, it can be made lowercase if a mono space font is specified, I think that would be a good compromise

**Comment by Ambrevar** [comment]
> Yes I’m simply referring to the font style, for example “l” vs “i”, it can be made lowercase if a mono space font is specified, I think that would be a good compromise 

Yes, we can totally customize the font!

**Comment by alexanderbarbosa** [comment]
@Ambrevar 
I mean, that most users of Windows managers, editors and video players expect C-nnn as modifier

**Comment by Ambrevar** [comment]
@alexanderbarbosa: We are not talking about key bindings here, but the name of Next "commands", i.e. the items displayed in the list of =M-x=.
A command is for instance `set-url-current-buffer`.

**Comment by Ambrevar** [comment]
Fixed in 476195a05e29216c07ba615a5b08c0b20eeb64d3.
We can still customize the font.
