### ISSUE TITLE
32 bit build

### ISSUE THREAD

**Issue by spiderbit** [atlas-engineer/next#368]
Could somebody make a guix lzip file for 32bit?

I assume that is the issue because I got "Exec format error" from the "linux" version.

Also maybe you could make a notice on the webpage that it's a 64bit binary.

**Comment by Ambrevar** [comment]
Good point.
Technically I should be able to cross-compile to 32-bit, I'll see what I
can do.
In the mean time, you could install Guix and run =guix install next=,
that will work.

**Comment by Ambrevar** [comment]
I've successfully built a 32-bit Guix pack, but I don't have a 32-bit to test.
I actually wonder how many people need this.  It adds a little bit of maintenance cost, so I'm trying to measure what's more reasonable to do here.

**Comment by spiderbit** [comment]
@Ambrevar that's difficult in nixos I think nixos and guixsd don't like each other I think I tried it once but it expects some stuff normal distros have but this 2 distros don't have.

**Comment by Ambrevar** [comment]
If you use Nix, then no worries, a Nix package is in the work!  
 https://github.com/NixOS/nixpkgs/pull/68453

I can run Nix on Guix without problem and as far as I know the other way around works too.

**Comment by Ambrevar** [comment]
Guix and Nix don't conflict.  Maybe a proper "Guix" package is missing
from Nix.

Guix provides a Nix package + a Nix service, so all this is taken care of.

**Comment by spiderbit** [comment]
So yes it's then easier the other way. Probably because Nixos is more popular yet and has probably more packages and if you will so guix is more or less a fork of nix.

I gave up yesterday because the stuff on that website did not work 1:1 here. You are right that there is nothing that makes it impossible to run the one at the other, but you need a special way to install it.

When a nix package is on the way I probably be patient and wait for that now... the one thing that holds me in nixos instead of guixsd is that it has no lvm support I am a lisp guy, but interesting to know that it's easy to access nixos packages so easy that would make a transition in 5 years when they finaly get lvm support even smother :D

**Comment by Ambrevar** [comment]
The Nix package is here!
I'm closing this since I don't think we are going to upload a 32-bit Guix pack.  Feel free to reopen if you feel that we should nonetheless.

**Comment by spiderbit** [comment]
Well the problem is that this package is not "browsers/next/default.nix:74 is not supported on ‘i686-linux’, refusing to evaluate:
NixOS/nixpkgs#70360

Therefor there is no real nixos support for i686 in nixos therefor a 32-bit Guix pack would be great, and it's not only that, I even use here in my modern 64bit pc the guixpack because the nixos package is not well maintained (old). Currently it's version 1.3.1 in nixos when the guix package is 1.3.3.

**Comment by Ambrevar** [comment]
I believe this issue should be reported upstream.

- A version bump from 1.3.1 to 1.3.3 is trivial.
- 32-bit support should not be too hard if Guix can do it.

**Comment by spiderbit** [comment]
But you could then not offer the 64bit version for the same reason, it's easy outside of nixos to install guix package manager and therefor you don't need to have the 64bit guix package in your download section right?

**Comment by jmercouris** [comment]
I think most people are running 64 bit machines and software and would prefer 64 bit. Very few users are still using 32 bit, for example, macOS is deprecating it in Catalina. We can  definitely offer both, but I don't think it would be wise to remove 64 bit and only offer 32 bit.

**Comment by Ambrevar** [comment]
By the way current version is 1.3.4, not 1.3.3 ;)

**Comment by spiderbit** [comment]
Well removing 64 bit and adding 32 bit was not my suggestion, the point I tried to make is that it sounded that you are considering adding 32bit guix lz file if there is a good reason, I think I demonstrated a good one.

Then the only reasons for not adding it were reasons you could also make for the 32bit package. there is a nix package (that actually works for 64 bit right now) and for everybody else they can install guix in their distros and install it that way.

Of course you car argue that 32bit is partially deprecated and not that much users are out there, but then all the other arguments would not have mattered in the first place and a clear "we don't want to do the work to create a guix pack file for 32bit because we don't want to waste time supporting 32bit" would been enough.

The point was:
"Feel free to reopen if you feel that we should nonetheless."

And I do feel that now. I was ok without because I thought there is nixos support, but that was before I know how:
1. out of date that package is
2. that 32bit is not supported yet (and they are not the fastest to react to questions/bugs, it sometimes takes them literally months)

I don't know how much the effort is to create such 7z file, do you need a 32bit installation to create such 32bit pack-file? If not it should not take that long right?

I also think that you should not compare to apple. This tool is a geek Tool they often have multiple devices and some strange ones.

Again I can live with no 32bit support, even on that machine next would be most important, because on more modern machine I can use firefox with a few extensions and as example watch youtube directly, while this old machines are to slow / ram restricted anyway so youtube would never run well on that machine anyway, but with the external youtube-dl support or maybe some scripting to open stuff up in mplayer it would be possible to watch it outside of the browser.

So your browser is interesting for low end machines, not exclusively but I would guess that is a huge enough percentage to care about.

**Comment by Ambrevar** [comment]
The most constructive approach here, I believe, is to
open an issue on the Nix issue tracker.  Would you like to do that?

The thing with 32-bit is that it's not the only less-used architecture
out there: what about AArch64, ARMv7, etc.?  We could provide Guix
packs for all those, but in the end the Guix pack is supposed to be a
ready-to-use demonstration package, not the proper way to install Next.

Another better way to install Next is to compile it from source (which
is as simple as a `make next`).

**Comment by spiderbit** [comment]
I did open a bugreport on nix (maybe the wrong subproject but it's there) and linked it in this thread.

I can live with that now, I happen to have a guix installation (even that notebook has therefor no wlan support and other issues) but I might try to pack it myself or wait a few months till the nix(os) guys react to my bugreport.

Without darkmode the browser is not usable at the moment anyway, so it's not urgent. It sounded to me like the reason you would not want to upload a guix 32bit package is because there is now a nix package, but if you don't want to support x86 in that way generally it's ok for me.

Maybe docker support get's better till all the distros eventually get the packaging done right.

**Comment by Ambrevar** [comment]
It will work on Nix.

Did you report the out-of-date version to Nixpkgs? If not, I can do it.

**Comment by spiderbit** [comment]
No didn't do that, thanks.
