### ISSUE TITLE
Using URL www.emacs.org gives error "Unacceptable TLS certificate"

### ISSUE THREAD

**Issue by azynheira** [atlas-engineer/next#372]
**Describe the bug**
Using URL www.emacs.org gives error "Unacceptable TLS certificate"

**Precise recipe to reproduce the issue**
Open a new window and use "www.emacs.org" as a new URL.
"Unacceptable TLS certificate" is shown and no page is loaded.

**Information**
- Ubuntu : 19.04
- Linux dpHP 5.0.0-27-generice
- GNOME 3.12
- Next 1.3.1
- Compiled from source
- SBCL 1.5.6
- ???

**Comment by damien-biasotto** [comment]
Yep that's the only thing that prevents me to use Next at work :( 
As far as I've read it's a webkit issue. Midori, epiphany have the same issue.

Is there a workaround? I'm okay with whitelisitng websites for now

**Comment by Ambrevar** [comment]
Whitelisting still needs a bit of work to be implemented.
I'll try to give it a shot this week.

**Comment by lxbarbosa** [comment]
Yep, I've seen that more than once, but never thought it might be a Next issue... lol

But I never browsed emacs site, so it happens with another domains too!

**Comment by Ambrevar** [comment]
certificate-whitelist-mode is in 1.5 and on master.
Make sure it's enabled then call `add-domain-to-certificate-whitelist` to add a certificate exception for the current domain.
To make it permanent, add it to `*default-certificate-whitelist*` in your ~/.config/next/init.lisp.

**Comment by fictitiousexistence** [comment]
Is there documentation somewhere on how to add and use "default-certificate-whitelist" in nyxt? Thanks!

**Comment by Ambrevar** [comment]
This thread is a bit dated, the variable in recent versions of Nyxt is now `NYXT/CERTIFICATE-EXCEPTION-MODE:*DEFAULT-CERTIFICATE-EXCEPTIONS*`.

You can consult the documentation with `f1 v`.

Example:

```lisp
(setf nyxt/certificate-exception-mode:*default-certificate-exceptions* '("www.emacs.org" "example.org"))
```

**Comment by fictitiousexistence** [comment]
Looks like we now use:

(setf nyxt/mode/certificate-exception:*default-certificate-exceptions*
        '("test.example.com" "test.example2.com"))

**Comment by aartaka** [comment]
Yes, that's the one. Package prefixes 😍
