### ISSUE TITLE
Use library for rings?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#373]
Does anyone know of a library that could replace our home-grown implementation of the ring data structure?

I've found out that cl-containers has a ring-buffer data structure that's almost what we want.  See
https://old.reddit.com/r/Common_Lisp/comments/d3pc4e/a_library_for_emacs_ring_structure/?.

@jmercouris @vindarel @noogie13 ?

**Comment by noogie13** [comment]
I don’t know of any replacement. What are you looking for in a library?

Could we add features to make up for it? Or shall we try to find one and switch even if the features are the same?

**Comment by Ambrevar** [comment]
I jsut raised the question to see if we should continue to develop this
library or switch to one.
It seems that nothing fits our exact needs here.

From there, I can think of two ways to go forward:

- Keep developing this library (add a ring:delete function for
  instance).
- Rewrite it on top of cl-containers' ring-buffer.  We should open an
  issue upstream and ask if we can add two tweaks to the existing
  ring-buffer:

  - Option "first-in-first-out" or "first-in-last-out" (we want the
  latter, on the former is supported).

  - A "delete" method to remove an element.

  - Optional: a "pop-to-front" method which is just a combination of
    "delete" and "enqueue".

Thoughts?

**Comment by Ambrevar** [comment]
Closing in favor of #560 .
