### ISSUE TITLE
Remove all `interface` arguments

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#374]
We have a lot of functions taking an `interface` argument (which is always the `*interface*` global) but we are not very consistent about it, since many other just use `*interface*` right away.

I find that this argument is rather noisy and not so useful.  We don't use it now, and should we want to use it in the future, we could very well rebind it dynamically with a macro

```
(with-interface my-interface
  (make-buffer ...))
```
which would `unwind-protect` the setting of `*interface*` so that we ensure that the global is restored on exit, even on error.

This approach is quite idiomatic in Lisp.

Thoughts?

**Comment by jmercouris** [comment]
A very welcome change, I like the with-interface macro!

**Comment by vindarel** [comment]
yes! +1

**Comment by Ambrevar** [comment]
OK, will do after merging #371.

**Comment by Ambrevar** [comment]
Done in 7be977db9a27933c4ece44b38d1d124bb34c2176.
