### ISSUE TITLE
CUA bindings

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#375]
We have some inconsitencies in bindings, e.g. C-v can be "paste" or "page down".
This is because we are trying to do 2 things at once with the Emacs bindings: please Emacs users _and_ CUA users (default Firefox / Chrome bindings).

I suggest we add a CUA binding scheme and default to it.
Since CUA lacks many bindings that we need here (but that Emacs has), I suggest we completment the missing bindings with those of Emacs.

Thoughts?

**Comment by inglada** [comment]
Just my opinion, but what brought me to Next was the emacs-like behaviour. So I would default to emacs bindings.

**Comment by Ambrevar** [comment]
Hmmm...
Emacs users are probably techies, so they are probably capable of setting the keymap scheme they want in the init.lisp.
Less tech-oriented users might not be so inclined, and those might expect CUA bindings.

Anyways, this can probably wait after we provide CUA bindings.

Another inconsistency that has been reported by a number of users: the `C-g` behaviour.
Coming from Emacs, it can be disconcerting that C-g "follows hints".

I suggest we remap it as follows:

- C-g / M-g for CUA bindings.
- M-g for Emacs bindings.

Thoughts?

**Comment by jmercouris** [comment]
I'm not sure about M-g for following hints. There is no equivalent in Emacs. The closest thing that comes to mind would be something like `M-.` which is used to jump to definition and opens up another file. The same idea could be applied to URLS where `M-.` allows you to jump to a new link...Not sure. We could also use `C-o` or something for "Open"?

**Comment by Ambrevar** [comment]
Well, `M-g M-g` is `goto-line`, so it's not that far! :)
`C-o` could work too.

**Comment by inglada** [comment]
I have been using Conkeror for a while and then Webmacs. They have key bindings which seem to me very suited to Emacs users:
- f to follow hints
- C-u f to follow hint in a new buffer
- C-x C-f to open a url
- C-u C-x C-f to open a url in a new buffer

Have a look at this:
http://conkeror.org/QuickStart

**Comment by jmercouris** [comment]
I'm a former Conkeror user myself, I'm not sure I found them that intuitive

**Comment by Ambrevar** [comment]
I've added a CUA scheme in dc705bdf38b31941fe676205139c9de4df9b46f7.
It's mostly a copy-pasted version of Emacs bindings, so we need to start tweaking it now.

**Comment by jmercouris** [comment]
I've added some CUA bindings myself, I'll be referring to the Firefox bindings for inspiration

**Comment by jmercouris** [comment]
You can see the Firefox bindings here: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by jmercouris** [comment]
I’ve gone through the list and implemented more or less all that are possible, will push soon

**Comment by jmercouris** [comment]
s/possible/possible and applicable

**Comment by jmercouris** [comment]
I think this is sufficient for a 2.0 release. Most of our users will want Emacs and/or VI bindings anyways :-)

**Comment by Ambrevar** [comment]
Fantastic, thanks!
