### ISSUE TITLE
History-tree structure (or how to fix buffer histories)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#378]
Something is wrong with buffer histories when going back and forth.
I suspect the issue to be in the `add-or-traverse-history`.

Anyways, I propose the following:
- Replace all the tree-related functions  with a `libraries/history-tree` library.
- The above library would essentially be the same class: a general tree that, when the user goes back to the parent,  reorders the children so that the last visited child URL comes first.  This way we can "remember" all the way forward.

With the above library, the document-mode history implementation becomes trivial.

Side question:  We actually have 2 histories: the buffer histories and the global history.  Note that they are significantly different.  Should we find a better name for one of them to avoid confusion?

**Comment by jmercouris** [comment]
The name is OK, it is a library for tree history and orthogonal to what we may call the “global history” or something like that to differentiate.

Thoughts?

**Comment by Ambrevar** [comment]
I didn't mean the library, I meant within Next, the distinction between the
"buffer history" and the global "history".

**Comment by jmercouris** [comment]
I think the name global history or even just *history* captures the difference, the star version may be too subtle though and people may not get it

**Comment by Ambrevar** [comment]
Yup, besides the stars often disappear when you say it out loud.

**Comment by jmercouris** [comment]
I feel like that could have been a deep prophetic thing that you just said: “the stars disappear when you say it out loud. everything is lost, like tears in rain”

**Comment by Ambrevar** [comment]
Hahaha :D

**Comment by Ambrevar** [comment]
Merged in
d55413c6c482629e352067422dc9c2cf0f3f088c.
