### ISSUE TITLE
Rename `document-mode` to `web-mode`?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#379]
Thoughts?

**Comment by jmercouris** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thoughts?

It is for documents on the web. The idea is to also have a media mode,
picture mode, etc. Otherwise there would just be a master mode that
handles all things. Document mode is currently this way, but it will not
always be so.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>


-- 
-John

**Comment by Ambrevar** [comment]
Then what about a web-mode which handles the buffer histories (among
others), and the media-mode / document-mode /etc. which inherit from
web-mode.

**Comment by jmercouris** [comment]
That was the idea behind root mode, all things inherit from it. Perhaps the hierarchy could be root -> web -> document

Why root *and* web? Because root would also be inherited by special buffers like help mode etc, whereas web would only be for web buffers.

thoughts?

**Comment by Ambrevar** [comment]
Absolutely.

**Comment by Ambrevar** [comment]
Done in 3bfc471d71bfcd95de69f71ce84bb65329796c4e.
