### ISSUE TITLE
Unwanted behavior in VI-INSERT-MODE -> VI-NORMAL-MODE on click

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#384]
Clicking on the currently-active input box while in VI-INSERT-MODE causes a switch to VI-NORMAL-MODE, which is annoying when using the mouse to move the cursor.  

I would personally want to maintain VI-INSERT-MODE when selecting other input elements as well.

**Comment by Ambrevar** [comment]
I've noticed this, but it only happens on specific input fields it
seems.  I can reproduce consistently on GitHub comments.

I've been annoyed by this for too long, this is high on my priority list
(but not before a week at least).

Patches welcome!  :)
The function to look at is `vi-button1` in vi-mode.lisp.

**Comment by Ambrevar** [comment]
This should be fixed now, feel free to re-open if the issue persists.
