### ISSUE TITLE
switch to last open buffer

### ISSUE THREAD

**Issue by lxbarbosa** [atlas-engineer/next#385]
Hi,

With more than a few open buffers, c-x b will choose any, maybe the first open buffer, as the one to switch on.

What would be neater is: user switch from cnn to github buffer, then cnn being the first one on buffer entries list to switch on.

Kinda of like: Open last closed tab from famous browsers.

PS: Someone at reddit described Next as the Fish Shell of Browsers. :D

**Comment by Ambrevar** [comment]
Now I wonder if it's a complement ;)

The behaviour you are describing should already be the default: the last
active buffer is the first candidates.

Can you provide a precise recipe?
