### ISSUE TITLE
next points to wrong next-gtk-webkit directory in guix store on install

### ISSUE THREAD

**Issue by rople380** [atlas-engineer/next#388]
**next points to wrong next-gtk-webkit directory in guix store on install**

    guix install next

or:

    guix package --manifest=$HOME/.package-lists/guix-manifest.scm --keep-failed && . ~/.guix-profile/etc/profile

where guix-manifest.scm:

    (specifications->manifest
      '(
        "next"
        ))

Installed next points to:

    /gnu/store/lybgcz5bknzc75bnfhvyyy6g9lksn6vr-next-gtk-webkit-1.3.1/bin/next-gtk-webkit

Going to store, found it is actually: 

    /gnu/store/qzfaj4nhsqsnss878c2nq89wqz8w2v25-next-gtk-webkit-1.3.1/bin/next-gtk-webkit

Set in init.lisp as an override, but believe this should be automatically set correctly?

**Information**
- OS name+version: Ubuntu 19.04 x86_64
- Kernel name+version: 5.0.0-27-generic 
- Desktop environment / Window manager name+version: i3 version 4.16.1
- Next version (from =M-x next-version= or =next --version=): 1.3.1
- How you installed Next (Guix pack, package manager, build from source): guix
- SBCL version (if built from source): N/A
- WebKitGTK+ / PyQt-Webengine version: next-gtk-webkit-1.3.1s

**Comment by Ambrevar** [comment]
Are you saying that right after a `guix package ...`
the path
`/gnu/store/lybgcz5bknzc75bnfhvyyy6g9lksn6vr-next-gtk-webkit-1.3.1` does
not exist?  Are you sure you didn't run `guix gc` or the like in the
meantime?

There is indeed an issue in Guix which prevents it from seeing
next-gtk-webkit as a dependency.
You can mitigate the issue by re-installing Next after a `guix gc` or by
using the `--no-grafts` argument to `guix package...` or `guix build...`.

See https://issues.guix.gnu.org/issue/33848 for more details.

**Comment by rople380** [comment]
Looks like that was it, I was running a guix gc after installing the profile. Fixed my guix upgrade script to have profile installation as last.
