### ISSUE TITLE
Repeated Minibuffer Selections

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#395]
I think it would be nice to have the option to keep the minibuffer open after making a selection, so that another option can be selected.  

For example, one might want to delete or reopen several buffers at a time or follow multiple hints in new (unfocused) buffers, without having to reopen the minibuffer between selections.

I'm imagining a keybinding that calls the following command repeatedly until the user manually quits the minibuffer.   So, is there a way to add a (synchronous) callback to the `with-result' calls?  The below never waits for user input.

    (define-command open-multiple ()

      (reopen-buffer)

      (open-multiple))

Or maybe there's a simpler way to do this where the minibuffer isn't closed after it returns its input?

**Comment by Ambrevar** [comment]
Don't worry, this has been on my todo-list for more than a year, and
since the recent minibuffer refactoring last week, it will finally be
doable very soon (like the coming week -- no promise).

I suggest something maybe better than keeping the minibuffer open:
multiple selection (à-la Emacs Helm).  Press C-SPACE to selection an
entry, M-a to select all currently narrowed down elements, M-u to
unselect, etc.

This way, deleting all wikipedia buffers amounts to

C-x C-k wiki M-a RET

Thoughts?

**Comment by 4t0m** [comment]
Yeah that sounds to me.  If you C-SPACE on a selection, and then type something into the minibuffer that narrows away from that selection, you're thinking that the selection is preserved, right (still acted on at the end)?

The only thing about this is that it seems to require more adaption for other functions.  They'd all have to be changed to accept a list from the minibuffer, no?

In terms of implementation, an active minibuffer (maybe not the right term?) would have a list of items to return, and then 
- C-SPACE and M-a would add selections to the list without returning,
- M-u would remove a matching selection from the list, and
- ENTER would add the current selection to the list & return.

This doesn't seem too hard, but so far I've been pretty confused by the minibuffer.  Are you imagining something different?

**Comment by Ambrevar** [comment]
You are mostly correct on all fronts!

- When narrowing, the previous selection is preserved indeed.
- M-u would unselect all.
- C-SPACE toggles a selection.
- Most functions have to be rewritten to accept a list of candidates
  indeed.  For some functions it does not make sense (like M-x) so those 
  should not allow multiple selections.

To ease this implementation, I'm thinking that read-minibuffer should
returns (values first-candidate all-candidates) on multi-selection.
This way we remain compatible with the previous functions that accept
only 1 argument.

**Comment by 4t0m** [comment]
I'm confused regarding how "values" works.  It looks like if we return (values first-c all-c) then that's the same as just returning first-c?  How does one access the later values?

Also, does toggle-selection require that we define a match-predicate for anything we select in the minibuffer?

**Comment by 4t0m** [comment]
Okay, so we would:
- return (values first-c all-c) from the minibuffer
- leave unchanged functions that only accept one selection
- in functions that sometimes accept multiple selections, we use 
     `  (multiple-value-bind (first-c all-c) minibuffer-result (do-something)) `    ?

I'm noticing that I'll still want something a bit different for opening a bunch of links in the background, since it would be a bit tedious to delete the minibuffer text between hint selections.  

A variable option to reset the minibuffer on toggle-selection would work, but I'm worried about the proliferation of this sort of configuration variable.

**Comment by Ambrevar** [comment]
> - return (values first-c all-c) from the minibuffer
> - leave unchanged functions that only accept one selection
> - in functions that sometimes accept multiple selections, we use 
>      `  (multiple-value-bind (first-c all-c) minibuffer-result (do-something)) `    ?

Correct.  We can also use `(nth-value ...)`.

> I'm noticing that I'll still want something a bit different for
> opening a bunch of links in the background, since it would be a bit
> tedious to delete the minibuffer text between hint selections.
>
> A variable option to reset the minibuffer on toggle-selection would
> work, but I'm worried about the proliferation of this sort of
> configuration variable.

Sorry I don't understand what you mean.

By the way, since you are asking about the implementation details, are
you planning to work on this?  Let me know, otherwise I was thinking of
implementing it today.

**Comment by Ambrevar** [comment]
I've started working on it and I got a pretty neat result, stay tuned!

I've dropped the idea of using `(values ...)` since it does not work with `with-result` and it would require too much refactoring.

**Comment by 4t0m** [comment]
Sorry yeah I was thinking of working on this.  Glad to see you're handling it though.

**Comment by Ambrevar** [comment]
Sorry for overtaking your enthusiasm :(

Pull request coming soon.

**Comment by Ambrevar** [comment]
See #415.  It's awesome! :D

**Comment by Ambrevar** [comment]
Merged.
