### ISSUE TITLE
Pop ups

### ISSUE THREAD

**Issue by anhluong156** [atlas-engineer/next#40]
Hi John,

I was wondering if there's any way I can see the pop-up windows when using nEXT. Sometimes I need to view the pop-up windows and click on them in order to continue what I'm doing on certain sites.  If this is not possible right now, will it available anytime soon?

Thanks,

Anh

**Comment by jmercouris** [comment]
Hi Anh,

thank you for your report! I've not had to use a site with pop-ups in a while :)

I think I have to implement some sort of delegate for the web-view, I'm not sure, I will look into it though! Currently I am overhauling many parts of the GUI / Working on the Linux port, so this will probably be something I touch upon soon (support for multiple windows is also coming soon), I will keep you updated!

thanks,

-John

**Comment by jmercouris** [comment]
hi @anhluong156 I'm sorry for the huge delay, but this finally works :)

thank you for your patience!

**Comment by jmercouris** [comment]
if you encounter any issues, please do not hesitate to re-open this issue! thanks!

-John
