### ISSUE TITLE
Rename `-completion-fn` to `-completer`?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#403]
I don't like the "fn" abbreviation, plus `-completer` is shorter ;p

**Comment by jmercouris** [comment]
completion function is however far clearer than “completer”, there’s a lot of things I don’t like, but I think this is both a regression and a nit :D

**Comment by vindarel** [comment]
`-completion-function`, or actually just `-completion`. "function" should be there for variables (`*foo-function*`) because they convey the type, but no need otherwise.

**Comment by Ambrevar** [comment]
Agreed that "function" should be there for variables.

`-completion` alone is ambiguous: some could understand it as the candidate, or the return value.

**Comment by jmercouris** [comment]
So you agree with leaving things as `completion-fn`? or are you talking about individual instances where something will be `(defun completion-fn-x ....`

**Comment by alexherbo2** [comment]
I agree to `-completion-function`.

**Comment by Ambrevar** [comment]
No, I agreed with Vincent that a function should not have "-function"
(or "-fn") in their name.
And I find the "-completion" suffix too ambiguous.

**Comment by alexherbo2** [comment]
@Ambrevar I agree to not use an abbreviation so. xD

**Comment by jmercouris** [comment]
Oh, so a defun that is just called x-completer, how about x-filter?

**Comment by Ambrevar** [comment]
x-filter is fine with me! :)

**Comment by jmercouris** [comment]
Ok! It is now decided :-)

**Comment by Ambrevar** [comment]
Wait, @vindarel any opinion on this?
Not that I want to push the bikeshed any further... xD

**Comment by jmercouris** [comment]
We don't need full consensus on everything! Otherwise, we wouldn't have gitlab ci still in the root of the repository :-)

Let's go with 2/3 rule, or the good enough rule, thoughts?

**Comment by vindarel** [comment]
no opposition on this, you can decide!

When we talk about fuzzy completion it may be nice to find the "completion" word in the code though.

**Comment by Ambrevar** [comment]
Cool, I'll just leave it open until I actually do the rename, otherwise
I might forget!

**Comment by Ambrevar** [comment]
@vindarel: We actually use the term "completion" for the minibuffer candidates.  I'm personally in favor of renaming those to `candidates`.

**Comment by Ambrevar** [comment]
Fixed in 13b5247ab9dfdf253bc569c0c6bb28eee163cc2c.
