### ISSUE TITLE
Add a context system

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/next#408]
Add a context system to allow keys to act differently depending on the context.  An example is to have a page context with an <kbd>y</kbd> mapping to yank the page URL and a link context with an <kbd>y</kbd> mapping to yank the link address.

**Comment by Ambrevar** [comment]
How do you define "context"?

Maybe we already have what you want: modes.  Bindings are stored in modes, and the first mode has highest priority.
So if mode A and B bind `y`, the behaviour of `y` depends on which mode is loaded and in which order.

**Comment by alexherbo2** [comment]
Oh that’s it.  I think it is because I did not see Next leverage that particularity.

**Comment by Ambrevar** [comment]
Also https://github.com/atlas-engineer/next/pull/404 should make this all much more convenient once it's merged!
