### ISSUE TITLE
Weird gray-blue polygons on textarea

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#412]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1027022/65760315-15598400-e11d-11e9-91d5-1d1e324cb72b.png)

This is blue on mouseover sometimes (same as if text was being selected).

**Precise recipe to reproduce the issue**

1- Open existing issue in Github
2- Mouse over the textarea at the bottom

**Information**
- OS name+version: OpenSUSE 15.1
- Kernel name+version: 4.12.14-lp151.28.13-default
- Desktop environment / Window manager name+version: i3 4.15
- Next version (from =M-x next-version= or =next --version=): Next 1.3.2-aebc911 (yesterday)
- How you installed Next (Guix pack, package manager, build from source): built from source
- SBCL version (if built from source): 1.5.4-lp151.100.1-suse
- WebKitGTK+ / PyQt-Webengine version: webkit2gtk: 2.24.2-lp151.2.3.1

**Comment by Ambrevar** [comment]
I can reproduce.  I wonder if it's a WebKitGTK bug though.
Can you reproduce with Epiphany?

**Comment by hsanjuan** [comment]
No, I don't see it with Epiphany...

**Comment by Ambrevar** [comment]
Do you have a precise recipe to reproduce this reliably?

**Comment by hsanjuan** [comment]
It happens with github textareas very consistently

**Comment by Ambrevar** [comment]
I recall it happened to me a lot a couple of weeks (months?) ago, but I haven't seen it in a while and I'm not able to reproduce now.
I'm running WebKitGTK 2.24.4, maybe that's what fixed it.

**Comment by terlar** [comment]
I don't see this in the latest version, however I do remember seeing it in the browser luakit before, so it was probably a WebKitGTK bug.

**Comment by hsanjuan** [comment]
ok, let's move this out of the way and I'll re-open if it keeps happening with newer webkitgtk. Thanks everyone!
