### ISSUE TITLE
ANN: We now have a subreddit and a Wiki

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#414]
As an announce to our watchers:

- https://www.reddit.com/r/next_browser/ 
- https://github.com/atlas-engineer/next/wiki

Feel free to chime in!

**Comment by Ambrevar** [comment]
Hooray!

**Comment by Ambrevar** [comment]
Shall we add Next to http://old.reddit.com/r/lisp+common_lisp+scheme+racket+clojure+lisp_ja+emacs+learnlisp+dylanlang+shenlanguage+lispmachine+stumpwm+sbcl+lispmemes ?

**Comment by Ambrevar** [comment]
(StumpWM is in there after all.)

**Comment by jmercouris** [comment]
Not sure what that link is? Is that a known thing?

**Comment by Ambrevar** [comment]
If you go to /r/lisp, in the right bar you'll see


    (r (apply #'+ subreddits))

**Comment by jmercouris** [comment]
I see, I guess it can't hurt to be in that list
