### ISSUE TITLE
Edit current url

### ISSUE THREAD

**Issue by noctuid** [atlas-engineer/next#416]
When I did get next working, I tried it out and came up with a few dozen suggestions I didn't see existing issues for but didn't have time to write up detailed issues. I'll probably try to pop into irc at some point(s) in the next few weeks to ask about a bunch of them before creating issues. Still, I apologize in advance if I end up creating any duplicate tickets or miss an existing feature.

I was surprised at how barebones it was but also at how easy it looked to extend (which is very appealing, wish I had the time to contribute a lot). Best of luck to the project; I'll donate some to the campaign before it ends.

Anyway, a nice functionality of other browsers/plugins is to be able to edit the current url. For example with `c` and `C` (or `O` and `T` in pentadactyl; I don't remember whether there is a default binding for this in qutebrowser), you'd get the current url on the commandline for editing and then enter would open it in the current tab or a new tab.

In both pentadactyl and qutebrowser, you could do this without a separate command by binding a key to input an incomplete command (e.g. `set-cmd-text :open --related {url:pretty}` in qutebrowser) though this doesn't seem to fit well with next using the minibuffer for just the url. Might be nice to have a simple way to set the default `input-buffer` to allow something similar for next (e.g. just a `let` around whatever existing command that uses the minibuffer, though that might not be the best way to do this).

**Comment by Ambrevar** [comment]
Thanks for your feedback, and thanks a lot in advance for your contribution! :)

Don't hesitate to open new issues, we feed on new ideas :p  

Regarding "presetting the minibuffer input": this is a feature that has been asked before and I understand it's quite popular!  Would you be interested in working on it?
It's quite simple: make sure the minibuffer accepts an `input-text` (or `input-buffer`) initarg.
Then make a command that works like `set-url-current-buffer`:

```lisp
...
(with-result (url (read-from-minibuffer
                       (make-instance 'minibuffer
                                      :input-prompt "Open URL in buffer:"
                                      :input-text (url (current-buffer))  ; <= CHANGE HERE
                                      :completion-function 'history-typed-complete
                                      :history history
                                      :empty-complete-immediate t)))
      ...
```

Makes sense?

**Comment by vindarel** [comment]
\+1, I miss this key badly but I have always important things to finish…

**Comment by noctuid** [comment]
> Would you be interested in working on it?

I definitely would but probably won't be able to anytime soon. I'll comment here if I do get some time though.

**Comment by impaktor** [comment]
Ah, yes, in Conkeror there's `find-alternate-url`, bound to C-x C-v that lets you edit current url in minibuffer.

**Comment by Ambrevar** [comment]
Current we can do this in next by pressing `M-h` (minibuffer-history).
I understand some users would like to see the current URL directly in the prompt.  We'd need a specialized command for this.

**Comment by jmercouris** [comment]
Et Voilà!

71fb093

**Comment by hsanjuan** [comment]
I wonder if you can make the cursor appear already at the end of the url for this new command?

**Comment by jmercouris** [comment]
It is possible, but I believe it is better at the beginning because you can C-k (which is probably being done more often). If you want the cursor to appear at the end of this command, you could wrap the command and then add the minibuffer command to go to the end of the buffer, bound to C-e

**Comment by impaktor** [comment]
I take it this new function is not bound to any key by default?

**Comment by jmercouris** [comment]
Correct, it is currently unbound

**Comment by noctuid** [comment]
The behavior for every browser or browser plugin I've tried is to put the cursor at the end of the url (because normally if you're changing a url, you're changing its end e.g. with backspace or `C-w`), but since it's possible to do, the default doesn't matter that much. Thanks for adding this.

**Comment by Ambrevar** [comment]
I've added a change on master: now in any of the set-url*
command the first candidate is the current URL, so you only have to
press TAB and it inserts the URL in the input, with the point at the end.
