### ISSUE TITLE
vi mode doesn't work: `undefined function: COMMON-LISP-USER::ADD-TO-DEFAULT-LIST`

### ISSUE THREAD

**Issue by petRUShka** [atlas-engineer/next#418]
**Describe the bug**
Next doesn't start with following line in config:

```
cat /home/user/.config/next/init.lisp                                                                                                                                                                  
(add-to-default-list 'vi-normal-mode 'buffer 'default-modes)
```

Traceback:

```
 <INFO> [15:54:03] next base.lisp (start) - NEXT:+VERSION+: "1.3.2" 
 <INFO> [15:54:03] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/user/.config/next/init.lisp...

; file: /home/user/.config/next/init.lisp
; in: ADD-TO-DEFAULT-LIST 'VI-NORMAL-MODE
;     (ADD-TO-DEFAULT-LIST 'VI-NORMAL-MODE 'BUFFER 'DEFAULT-MODES)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::ADD-TO-DEFAULT-LIST
; 
; compilation unit finished
;   Undefined function:
;     ADD-TO-DEFAULT-LIST
;   caught 1 STYLE-WARNING condition
While evaluating the form starting at line 1, column 0
  of  <WARN> [15:54:03] next base.lisp (load-lisp-file fun1) -
  Error: we could not load the Lisp file /home/user/.config/next/init.lisp: The
                                                                                function
                                                                                COMMON-LISP-USER::ADD-TO-DEFAULT-LIST
                                                                                is
                                                                                undefined.
#P"/home/user/.config/next/init.lisp":
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10005E04C3}>:
  Could not load the lisp init file /home/user/.config/next/init.lisp: 
The function COMMON-LISP-USER::ADD-TO-DEFAULT-LIST is undefined.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005E04C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Could not load the lisp init file ~a: ~&~a" {1004863F03}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Could not load the lisp init file ~a: ~&~a" {1004863F03}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Could not load the lisp init file ~a: ~&~a" {1004863F03}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SIMPLE-ERROR "Could not load the lisp init file ~a: ~&~a" {1004863F03}>)
4: (SB-KERNEL::%SIGNAL #<SIMPLE-ERROR "Could not load the lisp init file ~a: ~&~a" {1004863F03}>)
5: (ERROR "Could not load the lisp init file ~a: ~&~a" #P"/home/user/.config/next/init.lisp" #<UNDEFINED-FUNCTION ADD-TO-DEFAULT-LIST {1004862093}>)
6: (NEXT::LOAD-LISP-FILE #P"/home/user/.config/next/init.lisp" :INTERACTIVE T)
7: (NEXT:START)
8: (NEXT:ENTRY-POINT)
9: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
10: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10045846DB}>)
11: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
13: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

**Precise recipe to reproduce the issue**

Add above-mention line and start `next`/

**Information**
- OS name+version: Arch linux
- Kernel name+version: 4.19
- Desktop environment / Window manager name+version: dwm
- Next version (from =M-x next-version= or =next --version=): 1.3.2
- How you installed Next (Guix pack, package manager, build from source): AUR

**Comment by Ambrevar** [comment]
If you want to manipulate the functions / variables from the Next
package, you need to either prefix them with `next:` or place the file
under the Next package (recommended) like so:

```
(in-package :next)

(add-to-default-list 'vi-normal-mode 'buffer 'default-modes)
```

It would be nice if we programmatically analyze the error and report
suggestions to the user.
Any idea @jmercouris @vindarel?

**Comment by jmercouris** [comment]
It would be like reinventing a debugger if we do that, that's what the conditions and signals are for. If we go that far we might as well add an interactive debugger on start-up for faulty inits (with the appropriate restarts selectable)

Thoughts?

**Comment by Ambrevar** [comment]
That'd be fantastic!  We need to re-invent SLIME for Next though :p

**Comment by petRUShka** [comment]
@Ambrevar, adding `(in-package :next)` make it work! Thanks.

Possibly that line should be mentioned in manual. Because `init.lisp` file is absence. And following [the manual](https://next.atlas.engineer/documentation#keybinding) take you to the error.

So new step of reproducing:

1) Be non familiar with lisp
2) Be a new user of Next Browser
3) Be a vimer
4) Follow [keybinding manual](https://next.atlas.engineer/documentation#keybinding) section to configure Next for vim-like
5) Face the above-mentioned error. 

So possible solutions:
1) Add `(in-package :next)` to the manual
2) Generate `init.lisp` with `(in-package :next)` on first start
3) Check `init.lisp` if it has `(in-package :next)` on any start before loading the file

**Comment by Ambrevar** [comment]
The `(in-package )` line is mentioned in the manual, but not at the
right spot.  Will fix that just now.

The structure of the manual could be largely improved in general.
This will come when
- #419 is sorted.
- We implement support for embedded documentation.

**Comment by just1602** [comment]
The line in the documentation about setting vi keybind by default does not render correctly, it'd be nice to fix it. :)
![image](https://user-images.githubusercontent.com/427123/70481964-3261ea00-1ab2-11ea-9585-b0dc4dd4194f.png)

**Comment by Ambrevar** [comment]
Good catch!
Fixed, thanks!

**Comment by Ambrevar** [comment]
Closing this, feel free to reopen if there is anything else.
