### ISSUE TITLE
echo fails on some input (paths with a tilde)

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#423]
**Describe the bug**

`echo` is fragile.

    (next:echo "video dled to ~/Downloads/")

```
error in FORMAT: No more arguments
  video dled to ~/Downloads/
```

Doubling the tilde seems alright:

    (next:echo "video dled to ~a" (str:replace-all "~" "~~" "~/Downloads/"))

      NEXT::TEXT: "video dled to ~/Downloads/" 

log4cl code might be a good resource.

**Information**
- OS name+version:
- Kernel name+version:
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- Next version (from =M-x next-version= or =next --version=):
- How you installed Next (Guix pack, package manager, build from source): master
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version:

**Comment by Ambrevar** [comment]
This is expected from the definition of echo:

```lisp
(defun echo (&rest args)
  "Echo ARGS in the status buffer.
The first argument can be a format string and the following arguments will be
interpreted by `format'."
  (%echo-status (apply #'format nil args)))
```

I'm not sure if it's a bug or a feature: if `echo` is documented to behave like `format`, then the behaviour should not trip the users.  Thoughts?

**Comment by jmercouris** [comment]
I believe that `echo` should behave exactly like format, given all the same expressive power, otherwise we'll find ourselves frequently writing `(echo (format nil ...))`.

**Comment by vindarel** [comment]
I agree for the usage. At least we should not fail. I suggest we model echo to log4cl, which fails to log here too.

```
(log:info "video downloaded to ~/Downloads/")
; in: LOG:INFO "video downloaded to ~/Downloads/"
;     (FORMAT #:|stream1261| "video downloaded to ~/Downloads/")
; 
; caught WARNING:
;   Too few arguments (0) to FORMAT "video downloaded to ~/Downloads/": requires at least 1.
;   See also:
;     The ANSI Standard, Section 22.3.10.2
; in: LOG:INFO "video downloaded to ~/Downloads/"
;     (FORMAT #:|stream1261| "video downloaded to ~/Downloads/")
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::DOWNLOADS
; 
```

But echo fails, so it's a bug.

We could also have a `:safe` argument or something, that would do proper escaping. Thus, no headache for the developer when he wants to.

**Comment by Ambrevar** [comment]
The proper way to deal with raw strings with format & co. is to use the
~s format string.  For instance:

```
(defun raw-string (whatever)
 (format nil "~s" whatever))
```

Here `raw-string` will accept anything, "~" included.

Echo works the same way:

```
(echo "~a" "Whatver ~special chars~")
```

I believe this is quite idiomatic (in most languages, including C with printf).

**Comment by jmercouris** [comment]
+1 on using the correct directive for format when trying to escape things.
