### ISSUE TITLE
Request: a delete-all-buffers command

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#424]
That's a good first issue: write a command to delete all buffers, except the current one probably.

See buffers.lisp.

**Comment by jmercouris** [comment]
It already exists in Taylor Viti's config: https://github.com/tviti/next-cfg/blob/master/init.lisp#L64

**Comment by Ambrevar** [comment]
Note that master has "multiple selection" support, so you can delete all
buffers with

`C-x k M-a RET`.

**Comment by vindarel** [comment]
Is it documented?

**Comment by Ambrevar** [comment]
Now there is a `(s)` added to the input of all commands that support
multiple selections.

I'll update the manual just now.

**Comment by vindarel** [comment]
done in https://github.com/atlas-engineer/next/commit/489bdabd0c49eca90ada6c6d3407335dbf6fdd8c

https://github.com/atlas-engineer/next/issues/490
