### ISSUE TITLE
Swank crashes

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/next#428]
**Describe the bug**
When I connect to a swank server running in next from Emacs, the swank server crashes

**Precise recipe to reproduce the issue**

In next: M-x start-swank
```
 Can't echo 'MINIBUFFER-MODE enabled.' without status buffer or interface
;; Swank started at port: 4006.
```

In Emacs: M-x slime-connect  - localhost - 4006
```
Versions differ: 2.24 (slime) vs. nil (swank). Continue? (y or n)
```
Reply `y`.
```
Lisp connection closed unexpectedly: connection broken by remote peer
```

Back in the terminal from which I started next:
```
CL-USER> WARNING:
   DEPRECATED-FUNCTION-STYLE-WARNING: Using deprecated function ASDF/BACKWARD-INTERFACE:SYSTEM-DEFINITION-PATHNAME -- please update your code to use a newer API.
The docstring for this function says:
DEPRECATED. This function used to expose ASDF internals with subtle
differences with respect to user expectations, that have been refactored
away since. We recommend you use ASDF:SYSTEM-SOURCE-FILE instead for a
mostly compatible replacement that we're supporting, or even
ASDF:SYSTEM-SOURCE-DIRECTORY or ASDF:SYSTEM-RELATIVE-PATHNAME
if that's whay you mean.

;; swank:close-connection: NIL
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: Can't locate module: SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG.
```

Note: I can run a Slime session for SBCL just fine, so my configuration can't be too wrong.

**Information**
- OS name+version:
Guix 717b6ba

- Desktop environment / Window manager name+version:
None (ssh connection from macOS)

- Next version (from =M-x next-version= or =next --version=):
1.3.2

- How you installed Next (Guix pack, package manager, build from source):
Guix

- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version:
WebKitGTK+ 2.20.5

**Comment by Ambrevar** [comment]
This is a known issue with distributed Common Lisp binaries (e.g. the Guix package):

- The Next binary embeds a version of Swank which is `nil`.

- Your local installation of SLIME embeds another Swank which is 2.24.
  For some reason (Swank bug?), continuing by pressing "y" always fails.

We should ask upstream.

**Comment by Ambrevar** [comment]
Done: https://github.com/slime/slime/issues/533.

**Comment by khinsen** [comment]
@Ambrevar There is indeed a version mismatch in Guix at my current commit: emacs-slime is at 2.24, whereas sbcl-slime-swank is at 2.22. I can probably fix that myself. But why does Next report `nil` as its swank version?

**Comment by Ambrevar** [comment]
OK, I think I've figure: sbcl-swank is not compiled properly on Guix.
Will try to fix it.

**Comment by Ambrevar** [comment]
I think I got it.  I've fixed the Guix swank package.

Try `guix pull` and `guix install next`, it should work now.

**Comment by khinsen** [comment]
Unfortunately, nothing works anymore:
```
$ dbus-launch next
Next version 1.3.3
 <INFO> [20:55:14] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-VeSXGef6w1">)
 <INFO> [20:55:14] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.1
<ERROR> [20:55:14] next base.lisp (start fun2) -
  Failed to find the TRUENAME of /home/hinsen/next: No such file or directory
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
```
And that's a freshly installed Next, so should not be the gc-or-graft-or-whatever problem with compiled SBCL code under Guix. I even tried putting the platform port executable on $PATH:

```
$ export PATH=$PATH:/gnu/store/dlh0wrnfkmdps5hpmzal69xd74a1ysiv-next-gtk-webkit-1.3.3/bin
$ dbus-launch next
Next version 1.3.3
 <INFO> [21:00:02] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-Gaz8jrxynA">)
 <INFO> [21:00:02] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.1
<ERROR> [21:00:02] next base.lisp (start fun2) -
  Failed to find the TRUENAME of /home/hinsen/next: No such file or directory
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
```

**Comment by Ambrevar** [comment]
Just tested it on a fresh guix pull, works for me.

>   Failed to find the TRUENAME of /home/hinsen/next: No such file or directory

This is weird, do you have something in your ~/.config/next/init.lisp?

Else try doing as suggested

      (setf +platform-port-command+
          "path/to/next-gtk-webkit")

**Comment by khinsen** [comment]
I didn't have an `init.lisp` so far, but I added one that sets the path and also does some diagnostics:
```
(in-package :next)

(setf +platform-port-command+
      "/gnu/store/dlh0wrnfkmdps5hpmzal69xd74a1ysiv-next-gtk-webkit-1.3.3/bin/next-gtk-webkit")

(format t "Set +platform-port-command+ to ~S~%probe-file returns: ~S~%"
        +platform-port-command+
        (probe-file +platform-port-command+))
```

Time to run Next again:
```
Next version 1.3.3
Loading configuration from #P"/home/hinsen/.config/next/init.lisp"...
Set +platform-port-command+ to "/gnu/store/dlh0wrnfkmdps5hpmzal69xd74a1ysiv-next-gtk-webkit-1.3.3/bin/next-gtk-webkit"
probe-file returns: #P"/gnu/store/dlh0wrnfkmdps5hpmzal69xd74a1ysiv-next-gtk-webkit-1.3.3/bin/next-gtk-webkit"
 <INFO> [11:19:51] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-NkHLlBljY5">)
 <INFO> [11:19:51] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.1
<ERROR> [11:19:51] next base.lisp (start fun2) -
  Failed to find the TRUENAME of /home/hinsen/next: No such file or directory
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
```
So my init.lisp is run, does what it's supposed to do, but Next nevertheless wants to run `/home/hinsen/next`.

**Comment by Ambrevar** [comment]
This is the same issue as #435.
There is something wrong with the paths we derive somewhere.
I've pushed a possible fix on master.

**Comment by Ambrevar** [comment]
Fixed in fc2275ef30ab6c6a62384d8567d10e5348430d9c.

Let me know if Swank works for you now.

**Comment by Ambrevar** [comment]
Oops, accidentally hit "close" :p

**Comment by khinsen** [comment]
And with the path problem out of the way, swank now works fine as well. I can finally start playing with Next at the configuration level - thanks!

**Comment by jmercouris** [comment]
Yay! Eager to see how you like it!
