### ISSUE TITLE
Can't input text to minibuffer

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#429]
Commit 533e0b5be0da53d85ef997f0b7834810889b07de breaks minibuffer input for me.  I'm looking into why.

Ubuntu 19.04, gtk-webkit port.

EDIT:

```
 <INFO> [17:46:53] next port.lisp (run-program port) -
  Platform port path: /home/adom/Coding/next/ports/gtk-webkit/next-gtk-webkit
 <INFO> [17:46:53] next port.lisp (run-program port) -
  Platform port arguments: NIL
```

That's the correct path as far as I can tell.

INPUT_IS_PRINTABLE looks a bit beyond me at the moment.

**Comment by tviti** [comment]
I had what sounds like a similar issue with a custom QtWebEngine port, perhaps https://github.com/tviti/next/issues/1 will be helpful? Wondering if rebuilding gtk-webkit would sort this for you (since the issue on my end was basically the port not implementing `INPUT_IS_PRINTABLE`).

**Comment by vindarel** [comment]
Happened here too, did you rebuild next-gtk?

**Comment by 4t0m** [comment]
Sorry but how do I do that?  I'm running from source since I haven't been able to get make all to work.

**Comment by vindarel** [comment]
I was thinking of `make gtk-webkit`.

The full list of Debian dependencies is

    	apt install sbcl libwebkit2gtk-4.0-dev default-dbus-session-bus glib-networking sqlite gsettings-desktop-schemas libfixposix-dev libgstreamer1.0-0 gir1.2-gst-plugins-base-1.0 xclip

**Comment by 4t0m** [comment]
Thanks a bunch! I ran `make gtk-webkit` and it's working now.  Shall I close the issue?

(Still no luck with `make all`.)

**Comment by vindarel** [comment]
Ah, glad to hear. Now try the multiple selection! 

yeah we can close, there's the issues history for future reference and `make all` is another topic.
