### ISSUE TITLE
Please store logs in a more appropriate place

### ISSUE THREAD

**Issue by alphapapa** [atlas-engineer/next#431]
I noticed that the platform port log is stored in `/home/me/.local/share/next/next-gtk-webkit.log`.  I think logs should go in `/tmp` or `TMPDIR` or `~/.cache/...`, rather than in `~/.local/share/...`, because debug logs like that shouldn't be kept long-term, and shouldn't be included in backups (which may tend to include `~/.local/...`).

Thanks.

**Comment by Ambrevar** [comment]
I have no strong opinion on the location of the log, but note that (like
anything in Next :p) you can customize it's location in your init file.

Something like

  (setf (get-default 'port 'log-file) "/path/to/log")

should do (untested).

Which reminds me that we need a `*before-init-port-hook*`.

**Comment by alphapapa** [comment]
Assuming there are or may someday be other such log/debug-like files, I'd rather not have to discover them by poking around my filesystem and override the location for each one.  There should probably be a path defined that all such files go into.

**Comment by Ambrevar** [comment]
Sure, does not cost much anyways.
Poll: what are the preferred locations of our users?

- /tmp/next-$UID/
- ~/.local/share/next
- ~/.local/share/next/logs
- ~/.cache/next/
- ?

**Comment by noctuid** [comment]
I wouldn't want logs in `/tmp` by default. `/var/log` is the most common log location. I'm not sure about the most common or best location for non-root programs that don't use syslog, but rootless X, for example, also uses `~/.local/share`. I think `.cache` would be a confusing default. Probably worth looking at what other programs do.

**Comment by Ambrevar** [comment]
If we get rid of the platform port (possibly in the near future), the
problem will disappear altogether ;)

**Comment by alphapapa** [comment]
Whatever path is used should be within the user's home directory.  Web browser logs obviously may contain (intentionally or not) private data, so storing them on a path which may be on another filesystem, e.g. in `/tmp` or `/var`, may result in sensitive data being stored outside a user's encrypted home directory, violating the user's expectations and privacy.

**Comment by Ambrevar** [comment]
Good point.

**Comment by noctuid** [comment]
My vote would be to keep logs in `~/.local/share`. Looking at my own `~/.local/share`, over 15 programs keep logs there (qutebrowser included). I did find 3 log files in `~/.cache`, but it does seem like an unusual choice to me. Almost everything in my `~/.cache` is stuff I would never want to look at as a human.

As far as backups, most of the stuff in my `~/.local/share` is stuff I wouldn't want to backup already. I don't personally have a problem with backing up log files (there have been a few times where I was glad I still had old log files around). It seems like it would make more sense to just exclude `.log` files or `logs?` directories in backups if you didn't want them.

**Comment by Ambrevar** [comment]
@alphapapa: By the way, it seems your last comment contradicts the original post with regard to /tmp ;)  Did you change your mind on the matter, or is there something else?

**Comment by alphapapa** [comment]
Users may want some log files backed up.  For example, I use GnuCash, and it keeps (or used to keep) log files for modifications to the transaction registers, to perhaps avoid or catch corruption.  Backing up those logs might help prevent loss of important financial data.

A blanket exclusion of ".log" files or "logs?" directories would be a very bad idea for a default backup configuration.  What if I call my personal journals "logs" and store them in `~/Documents/personal/logs`?  I could exclude those from the exclusion (...), but what if I forget to do so when I'm redesigning my backup systems?  I have thousands of directories, and I'm not likely to think of all the things I ought to exclude from global exclusion.

So the questions for this project are:

1.  Whether these log files have any lasting value for users.  I'd be very surprised if they do.
2.  Whether these log files have any privacy risks for users.  I'd be very surprised if they don't.  And even if they aren't intended to contain any sensitive data, as we know, software is complicated.

So, since they probably don't have any lasting value, they ought to be stored in a place that's likely to be excluded from backups by default.  I know that certain widely used backup software, such as CrashPlan, excludes `~/.cache` by default.

And since they probably do have privacy risks, they ought to be stored in a place that's likely to be on the same filesystem as the user's homedir, to benefit from any homedir encryption.

That seems to leave `~/.cache` as the best place.

@Ambrevar Hey, I'm not a browser developer, just a feeble user who has to think about things twice before all the ramifications reveal themselves.  :P

**Comment by noctuid** [comment]
Well presumably you would look at your old exclude configuration when switching to or starting to use a new backup program; I've also used several in the past few years. If you're not okay with backing up all log files but want to backup some, then you're going to have to individually evaluate every program's log files anyway. If you're doing that already, you could just blacklist specifc files/dirs instead of whitelisting and potentially forgetting about something. I see your point though. If the log file is not and will never be useful for a user, `~/.cache` would be a better default and the user wouldn't have to evaluate whether or not to back it up.

> By the way, it seems your last comment contradicts the original post with regard to /tmp ;) Did you change your mind on the matter, or is there something else?

I think the idea was that the user may have an encrypted home and an unencrypted root partition (e.g. not using tmpfs for `/tmp`; unencrypted swap could also be a possibility, but that would be a lot more problematic by itself).

**Comment by Ambrevar** [comment]
Master does not use platform ports anymore, so this issue can be closed with the release of 2.0! :)

**Comment by alphapapa** [comment]
> Master does not use platform ports anymore, so this issue can be closed with the release of 2.0! :)

Is this described in any news postings anywhere?  I haven't been able to find mention of it.

**Comment by Ambrevar** [comment]
I meant "when 2.0 is released" :)
We are hard at work on master ;)

**Comment by Ambrevar** [comment]
2.0 release inbound. Closing.
