### ISSUE TITLE
Double-click not recognized

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#433]
**Describe the bug**

On a google-sheet, double-clicking the cell does not seem to have any effect (it should allow to edit it).

**Precise recipe to reproduce the issue**

When I go here https://unixpapa.com/js/testmouse.html it is much more difficult to get a `dblclick` event with Next than with Firefox.

**Information**
- OS name+version: OpenSUSE 15.1
- Kernel name+version: 4.12.14-lp151.28.13-default
- Desktop environment / Window manager name+version: i3 4.15
- Next version (from =M-x next-version= or =next --version=): Next 1.3.2-16f2381
- How you installed Next (Guix pack, package manager, build from source): built from source
- SBCL version (if built from source): 1.5.4-lp151.100.1-suse
- WebKitGTK+ / PyQt-Webengine version: webkit2gtk: 2.24.2-lp151.2.3.1

**Comment by Ambrevar** [comment]
Indeed, this is not implemented! :p

Does anyone know how to do double-clicking in Javascript?

**Comment by hsanjuan** [comment]
funny, because I do get some doubleclick events on that test page, but not in a natural way as when doing an actual double-click.

Also: https://stackoverflow.com/questions/18399215/how-to-programmatically-fire-a-dblclick-event-defined-with-addeventlistener

**Comment by Ambrevar** [comment]
Strange indeed, because we are never sending GDK_2BUTTON_PRESS to the
web view.

https://developer.gnome.org/gdk3/stable/gdk3-Event-Structures.html#GdkEventButton

I think the fix should be easy: forward GDK_2BUTTON_PRESS and
GDK_3BUTTON_PRESS as well in the platform port.  I'll see if that works.

**Comment by Ambrevar** [comment]
Should be fixed on master! :)

**Comment by hsanjuan** [comment]
Yai! thanks!
