### ISSUE TITLE
Ubuntu package does not work

### ISSUE THREAD

**Issue by Icarium** [atlas-engineer/next#435]
I just downloaded and installed the Ubuntu package and it seem to not work at all.

Trying to launch Next from the menu does nothing. From the command line I can launch next-gtk-port and then next but then it doesn't accept any input.

**Comment by vindarel** [comment]
Can you copy-paste all the output you get on the command line when running `next` ? (you needn't run next-gtk-webkit)

Also please precise these:

- OS name+version:
- Kernel name+version:
- Graphics card and driver:
- Desktop environment / Window manager name+version:

**Comment by Icarium** [comment]
If I don't run next-gtk-webkit I get this:

```
Next version 1.3.3
 <INFO> [23:04:14] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
 <INFO> [23:04:14] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.121
<ERROR> [23:04:14] next base.lisp (start fun2) -
  Failed to find the TRUENAME of /home/user/next: No such file or directory
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")

```

**Comment by Icarium** [comment]
This is an extremely vanilla new ubuntu installation. I made a new VM for trying Next.
```
user@user-ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by Icarium** [comment]
And the problem can be fixed by `mkdir ~/next`. Seems a bit odd, though. Even if the package did it automatically.

**Comment by jmercouris** [comment]
We don't ever use `~/next`, we use the XDG locations, but never `~/next`. The output seems to confirm what you are saying, which is very strange.  What would happen if you set the platform-port-path in the init file?

**Comment by Icarium** [comment]
I tried
```
setq platform-port-path "/home/user/other")
```
in .config/next/init.lisp
but that doesn't obviously create a problem. It's been ten years since I last lisped, though. Forgive me father. ;)

**Comment by Icarium** [comment]
I think there is something wonky with the path resolution. It doesn't even use `~/next` for anything it just wants to look at it. The actual `next-gtk-webkit` is in `/usr/local/bin/next-gtk-webkit`.

**Comment by Icarium** [comment]
Okay, so I think what is happening is that xdg-config-home or xdg-data-home returns either an empty value which is interpreted as the current directory or it just returns the current directory. Either way the error changes if I change to a different directory.

I feel like I want to debug this but I have no clue where to start with lisp these days. Any advice? :)

**Comment by Ambrevar** [comment]
Thanks for this last clue, I think I know what's going on: do you have both ~/.config and ~/.local/share ?

**Comment by Ambrevar** [comment]
Regarding your question about the command, it's:

```lisp
 (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
```

You can change the path of course, but both the `+` and the variable name are important! :)

**Comment by Icarium** [comment]
> do you have both ~/.config and ~/.local/share ?

Yes.

**Comment by Ambrevar** [comment]
Can you install SBCL and return the following command outputs (from a shell):

```
sbcl --non-interactive  --eval '(print (uiop:xdg-config-home))' --quit

sbcl --non-interactive  --eval '(print (uiop:xdg-data-home))' --quit
```

**Comment by Ambrevar** [comment]
The `derive-path-from-name` function had a couple of issues which I've fixed in  7130d7987f1e772080e994aa0443fa5c242d7227.  @jmercouris @vindarel Can you confirm it works for you?

I feel that this issue is a different problem though.

**Comment by khinsen** [comment]
Coming over here from #428 to help with debugging...

I pasted the new `derive-path-from-name` into my `init.lisp` and added some diagnostic output.

1. The argument list is `("/gnu/store/dlh0wrnfkmdps5hpmzal69xd74a1ysiv-next-gtk-webkit-1.3.3/bin/next-gtk-webkit")`, i.e. the value of `+platform-port-command+` I set in my `init.lisp`.
2. `(uiop:argv0)` is `"next"`.
3. `(truename (uiop:argv0))` fails, and that's the crash report I keep seeing when launching Next.
4. Not sure it matters, but `(nth-value 2 (asdf:locate-system :next))` yields `#P"/gnu/store/yn07bfi1h5m8plv9pck9a9cw4hig09pp-next-1.3.3-lib/lib/sbcl/next.asd"`.

**Comment by khinsen** [comment]
Two more:
- `(uiop:xdg-config-home)` is `#P"/home/hinsen/.config/"`
- `(uiop:xdg-data-home)` is `#P"/home/hinsen/.local/share/"`

**Comment by Ambrevar** [comment]
Shoud be fixed in fc2275ef30ab6c6a62384d8567d10e5348430d9c.
Thanks for reporting!

**Comment by khinsen** [comment]
Works fine, thanks for the fix! It works with or without defining `+platform-port-command+`.

A comment on the logic though: If I set `+platform-port-command+` explicitly, I expect it to be used as-is, not just as a fallback when all else fails. Not my main problem, as of course I prefer not to have to set anything at all!

**Comment by Ambrevar** [comment]
It's a fallback only if you build next from source: indeed, if you
develop next you might want it to find the platform port from the build
folder instead of +platform-port-command+.

**Comment by Icarium** [comment]
> Can you install SBCL and return the following command outputs (from a shell): ``` sbcl --non-interactive --eval '(print (uiop:xdg-config-home))' --quit sbcl --non-interactive --eval '(print (uiop:xdg-data-home))' --quit ```

Probably not necessary anymore anyway but this just complains that uiop does not exist. How would I fix that?

**Comment by Ambrevar** [comment]
Your SBCL package does not load UIOP by default (some distributions do
that, don't know why).  Here is the fix:

sbcl --non-interactive --eval '(progn (require "uiop") (print (uiop:xdg-config-home)))' --quit

If you can test against master, it should work.
Do we have debs for master, @vindarel?

**Comment by vindarel** [comment]
I updated the .deb. (one must delete the two executables at `/usr/local/bin` and re-install).

**Comment by Icarium** [comment]
@Ambrevar   Package UIOP does not exist.
;)
This is just the SBCL package from Ubuntu, I'm not sure that includes everything that one should have...

**Comment by Icarium** [comment]
The problem is fixed in the new .deb it seems. Thanks everyone!

**Comment by vindarel** [comment]
And thank you!

**Comment by Ambrevar** [comment]
Thanks @vindarel for the new .deb!
