### ISSUE TITLE
Request: add a --eval command line argument

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#437]
As a proper lisp program, Next needs an `--eval` command line option!

CLI args are defined and parsed in `start.lisp`, with the [unix-opts](https://github.com/libre-man/unix-opts/) library (https://lispcookbook.github.io/cl-cookbook/scripting.html#parsing-command-line-arguments). `load-init-file` in this file shows a usage of `eval`.

**Comment by Ambrevar** [comment]
I think there is a misunderstanding on what this was supposed to do.
From my understanding, the `--eval` option was meant to send the thunk to the running instance of Next, like `emacsclient --eval`.

But it's true that what you've pushed is also useful: it allows use to use Next as a specialized Common Lisp script interpreter.

So what about doing this instead:

- Rename this command line argument to `--script`,
- Add an `--eval` command line argument that sends the thunk to the running instance.

Thoughts?  @jmercouris @vindarel

**Comment by vindarel** [comment]
Ah, right. Thing is, it looks like there are two use cases. Maybe the headless functionality you describe should go to another `nextclient` command. If we extend the present and check if there's a running Next instance, how do we differentiate the two features?  What I did is like SBCL's --eval, it's simple but it's already useful to get stuff from the Next context, with or without the user's init file context. I defined utility functions in my init file. With this `--eval`, Next loads everything and I ask some information, which is cool. So I think there are two use cases.

`--script` would be to run a file. `--repl` ? `--headless`?

ps: a rule to not forget: never rush before a release :]

**Comment by Ambrevar** [comment]
I don't think there is a need for a separate command.

Simply two separate command line options should be good enough in my opinion.

> `--script` would be to run a file. `--repl` ? `--headless`?

I am not sure I understand what you mean here.

If you want another argument for executing files, then what about an
argument that specifies _where_ to evaluate the file/string?

So we would have:

- --file FILE
- --eval STRING
- --remote

Examples:

```
next --file FILE
```

Run FILE in a new headless instance and terminates.

```
next --eval STRING --remote
```

Run STRING in a running browser.

> ps: a rule to not forget: never rush before a release :]

Agreed! :)

**Comment by Ambrevar** [comment]
Done in a0aea9e0e1b4fbb3928cb250420c0eae58343f6a.

**Comment by Ambrevar** [comment]
I've used `--load` instead of `--file` out of consistency with Emacs.

**Comment by vindarel** [comment]
Awesome. Is it documented?

**Comment by Ambrevar** [comment]
Beside `next -h`?

**Comment by Ambrevar** [comment]
I mean, do you find it confusing?

**Comment by vindarel** [comment]
no, it's just illustrating this functionality would have its place on the manual.org.

**Comment by Ambrevar** [comment]
Yeah, it would be nice to have an example, say,

- start next.
- Run `next --remote --load my-hacks.lisp`
- Run `next --remote --eval `(function-from-my-hacks-thats-awesome)`.

We need to think of something that's particularly useful for this use case.

**Comment by Ambrevar** [comment]
I've just added a section on command line arguments in the manual.
