### ISSUE TITLE
Starting a next specific dbus session on macOS

### ISSUE THREAD

**Issue by tviti** [atlas-engineer/next#438]
So I had hoped that between my init script and modifications to the port, other macOS users would have an easier time of getting next running, but https://www.reddit.com/r/emacs/comments/dc9dio/next_browser_133_multiple_selection_%C3%A0_la_helm/ makes it seem like that is not the case. The issue still seems to be that getting dbus operational on macOS (at least when installed via `homebrew`) is a PITA.

The issue seems to be that `brew services start dbus` does not ACTUALLY start the `dbus` session bus (for whatever reason). On macOS, the `dbus` `session.conf` also sets the port from `DBUS_LAUNCHD_SESSION_BUS_SOCKET`, but the variable either may not exist, or may not be set to the correct location (iirc, I've seen a _dbus on mac_ guide that explained why, but I have to go find it). Because of this, simply calling `dbus-launch` from the command line will fail.

Possible resolutions are:
    * Manually configuring `DBUS_LAUNCHD_SESSION_BUS_SOCKET` (what my `init.lisp` does, but apparently this doesn't work for everybody)
    * Manually calling `dbus-daemon` and setting up a different socket (annoying for the user)
    * Manually configuring `session.conf` to NOT use `DBUS_LAUNCHD_SESSION_BUS_SOCKET` (annoying for the user, and is also a system-wide side-effect)

This is all sort of a moot point until upstream has a browser port that works on macOS, but I'm thinking that whenever that happens, a next `brew` could be configured to start its own session-bus for rpc. I have a branch [here](https://github.com/atlas-engineer/next/compare/master...tviti:macOS) that implements an example of this. The paths are currently hard-coded, but basically `+dbus-launch-command+` is configured to use `next/dbus/session.conf`, which is configured to start a new `dbus` instance with socket at `next/dbus/session.sock`.

**Comment by jmercouris** [comment]
Firstly, thank you for your long and thoughtful write-up!

You are correct, D-Bus on macOS is pretty non-standard in its implementation depending on how it is installed, MacPorts, Brew, Fink, etc. Currently we have a provision in place where Next *should* launch its own D-Bus session when it doesn't find one. This is however not working, and will also need to be adapted for macOS.

Considering what you've said, what I envision is something like the following:

1. Package a D-Bus daemon executable within the Next.app bundle, next will then launch D-Bus, then launch `next-qt`. Alternatively, as you have pointed out, allow a user in their `init.lisp` file to specify a path to the D-Bus daemon so that Next may start its own session at a specific socket on the system.
2. You are right, the port needs a lot of work. Too many problems with PyQt for implementation, performance, deployment, and the like, I am working on a branch titled `qt`. I have not made a lot of progress, I don't know C++, so it is a bit of a learning experience for me.

Thoughts on the above? Thanks!

**Comment by tviti** [comment]
Sorry, there was supposed to be another bullet point in there that I left out on accident!

    * Setup a next-specific `session.conf` file so that next can start its own `dbus` instance with its own settings, seperate from the default session-bus

And that the branch I linked to implements this, along with my modified qt port. With that branch, I can shutdown the session bus with `brew services stop dbus`, and then what you've described:

```
Currently we have a provision in place where Next should launch its own D-Bus session when it doesn't find one. This is however not working, and will also need to be adapted for macOS.
```

> Package a D-Bus daemon executable within the Next.app bundle, next will then launch D-Bus, then launch next-qt. Alternatively, as you have pointed out, allow a user in their init.lisp file to specify a path to the D-Bus daemon so that Next may start its own session at a specific socket on the system.

Are you actually thinking of bundling the entire dbus implementation in the app bundle? Or did you mean to just create a shell script that gets copied over to `Next.app`, and which sets up the environment variables correctly and then launches?

The former seems a little heavyweight of a solution, since from what I can tell, `homebrew` `dbus` works just fine, it's just `brew services start dbus` won't dwim :P.

The latter is how I used to start next (I have a `run_next_src.sh` that used to setup `DBUS_LAUNCHD_SESSION_BUS_SOCKET` before starting next from source, until I eventually moved all the `dbus` configuration stuff to `init.lisp`).

**Comment by tviti** [comment]
One downside that comes to mind with having next launch its OWN dbus instance, is that the next core can't use the session bus to communicate with the many other system services using dbus.

**Comment by cbbrowne** [comment]
In reading ports/README.org, it looks a whole lot like the intention of the dbus usage is to provide the communications substrate between the "platform" and the "core," and, given that, it seems reasonable to think that this justifies this D-Bus instance being private to a given Next instance.

If that's so, then it's a reasonable idea to hide a socket file in ~/.local/next or similar, and have it be very much NOT shared.

I'm imagining that one might use D-Bus to say "Here's a URL I want to have displayed in the browser."  Given that, it's also plausible to think one might want to hook in another D-Bus instance to handle outwards facing RPC.

**Comment by tviti** [comment]
>     2. You are right, the port needs a lot of work. Too many problems with PyQt for implementation, performance, deployment, and the like, I am working on a branch titled `qt`. I have not made a lot of progress, I don't know C++, so it is a bit of a learning experience for me.
> 
> 
> Thoughts on the above? Thanks!

Also,  would you be interested in a PR with my next-pyqt fixes in the meantime? Some of the code is probably pretty dirty, but at least there would be a viable port for macOS till the c++ version is up and running. From there, I would be willing to try get an application package up and running again (just need to decide on how you want to sort out starting dbus).

**Comment by jmercouris** [comment]
I would be interested in a Pull request indeed! Vincent would have to also test it on Linux to make sure it doesn't break Linux things. I remember we had for example: a conflict where some code would work for keybindings on Linux, and different code would work on macOS. In this case, I guess we can do a `if linux` and `if macOS`

**Comment by tviti** [comment]
Ok, so in my fork, I actually deleted everything except for the `port` dir a few commits back. Because of that, would it be better if I branch and merge master back in, prior to submitting the PR? Or should I just submit it as is (with the deletions)?

**Comment by jmercouris** [comment]
It would be better if you merge master back in, then we can just rebase the changes and avoid some strange history :D

**Comment by tviti** [comment]
Ok, hopefully I did this right! I'm still pretty new to `git`, so largely unaware of proper etiquette/protocols for these things.

**Comment by svetlyak40wt** [comment]
Hi guys!

@tviti where is your solution? I want to test it.

**Comment by jmercouris** [comment]
You can see Taylor's pull request here: https://github.com/atlas-engineer/next/pull/491

you can also use his fork :-)

**Comment by svetlyak40wt** [comment]
Ok, I'll switch to this branch and give it a try.

Hope this pull will be merged if it works fine.

**Comment by jmercouris** [comment]
This pull will not be merged because we no longer rely on D-Bus on master, we are now using CFFI, I am also working on Qt bindings https://github.com/atlas-engineer/cl-webengine and a branch: https://github.com/atlas-engineer/next/tree/renderer-qt.

We've made the CFFI version a lot more stable than historic Next by handling some of the bugs in cl-cffi-gtk and GTK. It is also a lot faster :-)

**Comment by svetlyak40wt** [comment]
Well, then testing @tviti's branch is not seems a right thing. It is better to switch to the new renderer-qt branch, right?

**Comment by jmercouris** [comment]
The renderer-qt branch is incomplete. I would suggest to use GTK on master, I am using it right now :-)

**Comment by svetlyak40wt** [comment]
Oh, I had pretty old code in my master branch when did experience that DBUS problem. Now switched to the latest master branch from the https://github.com/atlas-engineer/next

**Comment by jmercouris** [comment]
Please note that you will need libfixposix and WebKitGTK+

I don't know about brew, but WebKitGTK+ exists on MacPorts, so probably it should be easy to take the work the MacPorts team has done and add it to brew

**Comment by jmercouris** [comment]
After those dependencies, it is as easy as `(asdf:make :next)`

**Comment by svetlyak40wt** [comment]
Fresh master branch required me to install additional requirements on OSX:

```
brew install glib gdk-pixbuf cairo pango gtk+3 libsoup
```

But finally failed on:

```
Unable to load any of the alternatives:
   ("libsoup-2.4.so.1.7.0" "libsoup-2.4.so")
   [Condition of type LOAD-FOREIGN-LIBRARY-ERROR]

Restarts:
 0: [RETRY] Try loading the foreign library again.
 1: [USE-VALUE] Use another library instead.
 2: [TRY-RECOMPILING] Recompile init and try loading it again
 3: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "cl-soup" "init">.
 4: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "cl-soup" "init"> as having been successful.
 5: [RETRY] Retry ASDF operation.
 --more--

Backtrace:
 0: (CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" ("libsoup-2.4.so.1.7.0" "libsoup-2.4.so"))
 1: (CFFI::TRY-FOREIGN-LIBRARY-ALTERNATIVES LIBSOUP ("libsoup-2.4.so.1.7.0" "libsoup-2.4.so") NIL)
 2: ((FLET CFFI::%DO-LOAD :IN CFFI::%DO-LOAD-FOREIGN-LIBRARY) #<FOREIGN-LIBRARY LIBSOUP> LIBSOUP (:OR "libsoup-2.4.so.1.7.0" "libsoup-2.4.so"))
 3: (LOAD-FOREIGN-LIBRARY LIBSOUP :SEARCH-PATH NIL)
 4: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/art/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/art/projects/lisp/next/.qlot/dists/quicklisp/software/cl..
 5: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /Users/art/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/art/projects/lisp/next/.qlot/dists/quicklisp/software/cl-webkit-20171227-git/soup/init.fas..
 6: ((FLET SB-FASL::THUNK :IN LOAD))
 7: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {C98B65B}> #<SB-SYS:FD-STREAM for "file /Users/art/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/art/projects/lisp/next/.qlo..
 8: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /Users/art/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/art/projects/lisp/next/.qlot/dists/quicklisp/software/cl-webkit-20171227-gi..
 9: (LOAD #P"/Users/art/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/art/projects/lisp/next/.qlot/dists/quicklisp/software/cl-webkit-20171227-git/soup/init.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXI..
10: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {1006D1FD6B}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
11: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-soup" "init">)
12: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
```

**Comment by svetlyak40wt** [comment]
Solved this problem by patching cl-soup's init.lisp:

```
(define-foreign-library libsoup
  (:darwin "libsoup-2.4.dylib")
  (:unix (:or "libsoup-2.4.so.1.7.0"    ; libsoup-2.48.0
              "libsoup-2.4.so"
              )))
```

**Comment by jmercouris** [comment]
That's interesting, I did not have to do that for some reason.

**Comment by Ambrevar** [comment]
Alex, you are using an old version of cl-webkit, make sure you drop
cl-webkit's master in ~/common-lisp.

**Comment by svetlyak40wt** [comment]
Yes, I see. I already added it to my qlfile (I don't like to install libraries system-wide).

But anyway, I need to install WebKitGTK+.

Wasn't able to build it manually :(
Probably will try to port it from Macports to Homebrew someday.

**Comment by jmercouris** [comment]
Fixed on master :-)
