### ISSUE TITLE
Document the built-in Webkit directory and file view, write a utility function

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#441]
We can open files and directories in Next directly, but it is not obvious, and not made discoverable. Hey, we can open videos and treat them like any buffer!

A directory:

![Next - file:---home-vince--work-next_019](https://user-images.githubusercontent.com/3721004/66169709-9c3cbe00-e641-11e9-9aca-0d4af29d7977.png)

A video:

![Next - file:---home-vince--zique-Delgres-20--20Mr-20President-20-28Official-20Music-20Video-29-UTvw3OWvpIs- mkv_020](https://user-images.githubusercontent.com/3721004/66169802-f2116600-e641-11e9-9f5d-3af0724fc9fe.png)

- enhance the defaults of `open-file` (don't always use xdg-open)
- write a utility function, looking at `source/urls.lisp` and @tviti's `open-home-dir`: https://github.com/tviti/next-cfg/blob/master/init.lisp#L232
- properly document everything

**Comment by Ambrevar** [comment]
Nice!

**Comment by alexherbo2** [comment]
Wow, it’s nice.  How is it decided to open in Next or with `xdg-open`?

**Comment by vindarel** [comment]
Now Next opens directories, and media files having one of these extensions: `"mp3" "ogg" "mp4" "flv" "wmv" "webm" "mkv"`. (list hardcoded [here](https://github.com/vindarel/next/commit/2842a10f38715d5fa7be1bc87d579ee333b53522#diff-b6a73292c3baf2149ff71f363bc0d38bR46), there might be more extensions supported by WebKit)

**Comment by alexherbo2** [comment]
It is nice.  I have to retry Next to see how it feels.

I have a question about videos.  Do you think it could be possible to embed GUI (such [mpv]) instead of using the browser rendering?  I do not mean to pop up a video player, but really embed a GUI (or terminal) program.

Both approaches have their use, depending on the context, we may want to have it integrated or detached (see [picture-in-picture]).

[mpv]: https://mpv.io
[Picture-in-Picture]: https://chrome.google.com/webstore/detail/picture-in-picture/hkgfoiooedgoejojocmhlaklaeopbecg

**Comment by alexherbo2** [comment]
It could be good for composability to be able to connect to external programs.

**Comment by Ambrevar** [comment]
I'm not sure WebKit (or WebEngine) allow for embedding widget elements
inside the web view.  To be confirmed.

Otherwise we could display another program as part of a Next subwindow.
For inspiration, we can look at EXWM and Emacs Application Framework.

**Comment by alexherbo2** [comment]
There is a program called [tabbed] from [suckless].

[suckless]: https://suckless.org
[tabbed]: https://tools.suckless.org/tabbed/

**Comment by vindarel** [comment]
I'm closing this, but feel free to re-open a feature request with what was mentioned.
