### ISSUE TITLE
Searching doesn't seem to work.

### ISSUE THREAD

**Issue by ghost** [atlas-engineer/next#444]
I have the documentation page open and I type `C-s s` and then `VI<space>` and get no results. The same happens for `vi<space>`. However under VI-style bindings (#vi-style-keybindings) the text starts with: 
    VI is a model text editor that is famous for its modal key bindings. In normal mode, all keys are commands, they won't insert any text anywhere.

Seems like the search maybe doesn't recognize it because the `VI` is a link?

**Information**
- OS name+version: Ubuntu 19.04
- Kernel name+version: 5.0.0-29-generic #31-Ubuntu SMP
- Graphics card and driver: Virtualbox
- Desktop environment / Window manager name+version: Vanilla Ubuntu
- Next version (from =M-x next-version= or =next --version=): Next 1.3.3-ca0b9fa
NOTE: `M-x next-version` doesn't seem to work. Shows no output.
- How you installed Next (Guix pack, package manager, build from source): .deb
- WebKitGTK+ / PyQt-Webengine version: webkit

**Comment by Icarium** [comment]
Sorry guys, you were too helpful so I just had to open another issue. ;)
Btw, the documentation doesn't actually state how to use VI-mode. I can activate it with `M-x vi-normal-mode` but it seems that only applies to the current tab which feels very wrong in general. :)

**Comment by Ambrevar** [comment]
Indeed, the search is very primitive now and it does not understand
cross-HTML element searches.

**Comment by Ambrevar** [comment]
Yes, the documentation is lacking, in part because it's change so fast.
We need to improve it quite a lot...
Patches welcome :)

For you specific issue, have a look at the "Modes" section, there is an
example how to add 'vi-normal-mode to the list of default modes.

**Comment by Ambrevar** [comment]
Search is much improved with 1.5 (also on master).
Documentation will be vastly overhauled for 2.0, and very soon embedded in the browser.

I'm closing this, feel free to reopen if you have more questions.
