### ISSUE TITLE
Tabbing on the "Open URL in browser" options should only fill in the URL (w/o title)

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#445]
When `C-l` the user is presented with a list of options in the form "url - Title". Hitting the tab on one of those options will replace the input line with the option.

This is super useful since usually I see a url similar to the one I want to visit and I just want to edit part of that url. However, hitting the tab also inserts the page title which I then have to delete to be left with the URL only.

So my request is to make Tab only fill in the URL, rather than the url+title as it appears on the list of options.

**Comment by Ambrevar** [comment]
Yup, that's annoying :p

Current TAB is very dumb and inserts the content of the candidate _as
is_.

To fix this, maybe we could specialize TAB on the candidate type.

**Comment by jmercouris** [comment]
The candidate object could provide a function for when TAB is pressed much how the display is isolated from the data, is that what you are suggesting?

**Comment by Ambrevar** [comment]
If I understand you right, yes, just like we have `object-string` we could have a `real-string`  method that TAB would use to know what to insert in the input prompt.

**Comment by jmercouris** [comment]
Correct! That's exactly what I was thinking. I think that would be really nice!
