### ISSUE TITLE
Add a list of supported distributions

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/next#449]
Something similar to [i3].

https://i3wm.org/downloads/

[i3]: https://i3wm.org

**Comment by alexherbo2** [comment]
[NixOS] recently added a package for Next.

https://github.com/NixOS/nixpkgs/commit/1c7d3389e43b2836a8f5de10f648833d610e86b2

[NixOS]: https://nixos.org

**Comment by Ambrevar** [comment]
It's in the README, but not on the download page, you are right!
Will fix as soon as possible.

**Comment by Ambrevar** [comment]
Done, thanks!
