### ISSUE TITLE
Git clone asks for credentials 

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#456]
Running `M-x git-clone` displays a pop up to ask me for my [Github?] credentials.

This is weird because, while the dialog's title is `OpenSSH` the message is `Username for: https://github.com" which would seem like a regular HTTPs clone.

What magic/customization do I need to do so it actually uses git+ssh clone url (`git@github.com`) and therefore the SSH agent as configured on my machine (should not ask for passwords)?

**Comment by vindarel** [comment]
I am not aware of a Next command that asks for git credentials. The `M-x git-clone` one can ask for a location. Do you mean that *after* M-x git-clone, a subsequent git command (outside of Next) asks for creds? In that case, yes there is one config: https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#cloning-git-repositories

> You can set your username for GitHub and other forges. It helps the clone command in doing the right thing©, such as using a git remote url instead of https.

    (setf next/vcs:*vcs-username* "github-handler")

**Comment by hsanjuan** [comment]
Ok, I followed the manual and setting the username works results in no longer getting a dialog about the username, but the checked-out repository is not using the git-remote url, but the https one, unlike what the documentation says (why?). I mean, https checkout should not even require a username.

I also tried setting vcs-project-roots:

```
(setf next/vcs:*vcs-projects-roots* '(("~/git")
                                      ("~/go/src/github.com/ipfs")
                                      ("~/go/src/github.com/hsanjuan")
                                      ("~/go/src/github.com/libp2p")))
```

but this results in:

```
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: Invalid pathname
                                                              designator
                                                              ("~/git").

```

What is the right way to set several project roots?

**Comment by vindarel** [comment]
Set several vcs project roots like this:

```
(setf next/vcs:*vcs-projects-roots* '("~/projects"
                                      "~/work"
                                      "~/common-lisp"
                                      "~/quicklisp/local-projects"))
```

You added a list of 1-tuples. I updated the manual, we'll add type checks.

> but the checked-out repository is not using the git-remote url,

It will actually use `git@` when you clone a repo of yours (the cloned repository root-name/organization name equals your vcs-username). We can extend all that. I updated the manual.

See the `choose-clone-url` function. You can override it:

```
;; ~/.config/next/init.lisp
(defun next/vcs::choose-clone-url (root-name project-name clone-uri)
  "Always clone with the git url."
  (log:info "We always clone with a git remote url.~&")
  (format nil "git@~a:~a/~a.git"
          (quri:uri-domain clone-uri)
          root-name
          project-name))
```

----

TODOs

- [ ] add type checks

**Comment by hsanjuan** [comment]
Thanks, that works perfectly now.

**Comment by vindarel** [comment]
Cool. Don't hesitate to post feature requests about that.
