### ISSUE TITLE
Does not build on Arch

### ISSUE THREAD

**Issue by jtgd** [atlas-engineer/next#460]
**Describe the bug**
> Error during install

**Precise recipe to reproduce the issue**
> yay -S next-browser

> End of output looks thus:

```
34: (SB-IMPL::TOPLEVEL-INIT)
35: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
36: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
37: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
;
; compilation unit aborted
;   caught 1 fatal ERROR condition

Compilation failed.
Make sure the 'xclip' binary and the 'sqlite' and 'libfixposix' development files are available on your system.
make: *** [Makefile:36: next] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: next-browser
```
However the packages mentioned are installed:
```
1 extra/xclip 0.13-2 (14.8 KiB 59.0 KiB) (Installed)
1 core/sqlite 3.30.0-1 (1.4 MiB 8.5 MiB) (Installed)
1 aur/libfixposix 0.4.3-1 (+7 0.95%) (Installed)
```
**Information**
- OS name+version:
> Arch Linux
- Kernel name+version:
> 5.1.5
- Next version (from =M-x next-version= or =next --version=):
> 1.3.4-1
- How you installed Next (Guix pack, package manager, build from source):
> yay  (which appears to be compiling source)

**Comment by Ambrevar** [comment]
Can you post about 100 lines of the end of the output?

**Comment by jtgd** [comment]
11,405 bytes in 0.00 seconds (11137.70KB/sec)
; Loading "unix-opts"
[package unix-opts]..
; Loading "next"
...Unhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                {10005084C3}>:
  Failed to find the TRUENAME of /usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp:
    No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005084C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-FILE-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {100465E7F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-FILE-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {100465E7F3}>)
2: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-FILE-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {100465E7F3}>)
3: (ERROR SB-INT:SIMPLE-FILE-ERROR :PATHNAME #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :FORMAT-CONTROL "~@<~?~@[: ~2I~_~A~]~:>" :FORMAT-ARGUMENTS ("Failed to find the ~*~A~2:* of ~A" (#P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :TRUENAME) "No such file or directory"))
4: (SB-IMPL::SIMPLE-FILE-PERROR "Failed to find the ~*~A~2:* of ~A" #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" 2 :TRUENAME)
5: (SB-IMPL::QUERY-FILE-SYSTEM #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :TRUENAME T)
6: (TRUENAME #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp")
7: (SB-C::VERIFY-SOURCE-FILE #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp")
8: (COMPILE-FILE #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :OUTPUT-FILE #P"/home/jay/.cache/common-lisp/sbcl-1.5.5-linux-x64/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages-tmpE0PA0717.fasl" :VERBOSE NIL :PRINT NIL :EXTERNAL-FORMAT :UTF-8 :TRACE-FILE NIL :BLOCK-COMPILE NIL :EMIT-CFASL NIL)
9: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:COMPILE-FILE*) {100465D69B}> NIL)
10: (UIOP/PATHNAME:CALL-WITH-ENOUGH-PATHNAME #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" NIL #<CLOSURE (LAMBDA (UIOP/LISP-BUILD::INPUT-FILE) :IN UIOP/LISP-BUILD:COMPILE-FILE*) {100465D61B}>)
11: (UIOP/LISP-BUILD:COMPILE-FILE* #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :OUTPUT-FILE #P"/home/jay/.cache/common-lisp/sbcl-1.5.5-linux-x64/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.fasl" :EXTERNAL-FORMAT :UTF-8 :WARNINGS-FILE NIL)
12: (ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-ppcre-unicode" "cl-ppcre-unicode" "packages">)
13: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-ppcre-unicode" "cl-ppcre-unicode" "packages">)
14: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
15: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-ppcre-unicode" "cl-ppcre-unicode" "packages">) [fast-method]
16: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1004B0BB13}>) [fast-method]
17: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
18: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1004B0BB13}>) [fast-method]
19: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "next"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
20: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "next"> :VERBOSE NIL)
21: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
22: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "next"> :VERBOSE NIL) [fast-method]
23: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "next" :VERBOSE NIL)
24: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
25: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "next" :VERBOSE NIL) [fast-method]
26: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1004ABB83B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
27: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
28: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1004AB1FEB}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
29: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "next" :VERBOSE NIL) [fast-method]
30: (ASDF/OPERATE:LOAD-SYSTEM "next" :VERBOSE NIL)
31: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1004AB1F3B}>)
32: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "next" :PROMPT NIL)
33: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {10035ABEAB}>) [fast-method]
34: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {10025845C3}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {10035ABEAB}>) [fast-method]
35: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) :NEXT :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
36: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {10035A3B2B}>)
37: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :NEXT) #<NULL-LEXENV>)
38: (EVAL (QUICKLISP-CLIENT:QUICKLOAD :NEXT))
39: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:LOAD . "quicklisp/setup.lisp") (:EVAL . "(ql:quickload :trivial-features)") (:EVAL . "(ql:quickload :prove-asdf)") (:LOAD . "next.asd") (:EVAL . "(ql:quickload :next)") (:EVAL . "(uiop:quit)") (:QUIT)))
40: (SB-IMPL::TOPLEVEL-INIT)
41: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
42: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
43: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
make[1]: Leaving directory '/Home/YayCache/next-browser/src/next-1.3.4'
env NEXT_INTERNAL_QUICKLISP=true sbcl --no-userinit --non-interactive \
	--eval '(require "asdf")' \
	--eval '(when (string= (uiop:getenv "NEXT_INTERNAL_QUICKLISP") "true") (load "quicklisp/setup.lisp"))' \
	--eval '(ql:quickload :trivial-features)' \
	--eval '(ql:quickload :prove-asdf)' \
	--load next.asd \
	--eval '(asdf:make :next)' \
	--eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed." "Make sure the 'xclip' binary and the 'sqlite' and 'libfixposix' development files are available on your system." && exit 1)
This is SBCL 1.5.5, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "trivial-features":
  Load 1 ASDF system:
    trivial-features
; Loading "trivial-features"

To load "prove-asdf":
  Load 1 ASDF system:
    prove-asdf
; Loading "prove-asdf"

WARNING:
   redefining ASDF/ACTION:PERFORM (#<STANDARD-CLASS ASDF/BUNDLE:IMAGE-OP>
                                   #<STANDARD-CLASS ASDF/SYSTEM:SYSTEM>) in DEFMETHOD
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/cl-colors-20180328-git/cl-colors.asd" contains definition for system "cl-colors-tests". Please only define "cl-colors" and secondary systems with a name starting with "cl-colors/" (e.g. "cl-colors/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/cl-json-20141217-git/cl-json.asd" contains definition for system "cl-json.test". Please only define "cl-json" and secondary systems with a name starting with "cl-json/" (e.g. "cl-json/test") in that file.
WARNING: System definition file #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre.asd" contains definition for system "cl-ppcre-test". Please only define "cl-ppcre" and secondary systems with a name starting with "cl-ppcre/" (e.g. "cl-ppcre/test") in that file.
WARNING: System definition file #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode.asd" contains definition for system "cl-ppcre-unicode-test". Please only define "cl-ppcre-unicode" and secondary systems with a name starting with "cl-ppcre-unicode/" (e.g. "cl-ppcre-unicode/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/s-xml-20150608-git/s-xml.asd" contains definition for system "s-xml.test". Please only define "s-xml" and secondary systems with a name starting with "s-xml/" (e.g. "s-xml/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/s-xml-20150608-git/s-xml.asd" contains definition for system "s-xml.examples". Please only define "s-xml" and secondary systems with a name starting with "s-xml/" (e.g. "s-xml/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/ieee-floats-20170830-git/ieee-floats.asd" contains definition for system "ieee-floats-tests". Please only define "ieee-floats" and secondary systems with a name starting with "ieee-floats/" (e.g. "ieee-floats/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/flexi-streams-20190107-git/flexi-streams.asd" contains definition for system "flexi-streams-test". Please only define "flexi-streams" and secondary systems with a name starting with "flexi-streams/" (e.g. "flexi-streams/test") in that file.
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
;;; Building Closure with CHARACTER RUNES
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/puri-20180228-git/puri.asd" contains definition for system "puri-tests". Please only define "puri" and secondary systems with a name starting with "puri/" (e.g. "puri/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/cl-fad-20190813-git/cl-fad.asd" contains definition for system "cl-fad-test". Please only define "cl-fad" and secondary systems with a name starting with "cl-fad/" (e.g. "cl-fad/test") in that file.
WARNING: System definition file #P"/Home/YayCache/next-browser/src/next-1.3.4/quicklisp/dists/quicklisp/software/cl-base64-20150923-git/cl-base64.asd" contains definition for system "cl-base64-tests". Please only define "cl-base64" and secondary systems with a name starting with "cl-base64/" (e.g. "cl-base64/test") in that file.
;;; Computing Hangul syllable namesUnhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                {10005084C3}>:
  Failed to find the TRUENAME of /usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp:
    No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005084C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-FILE-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {10035010F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-FILE-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {10035010F3}>)
2: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-FILE-ERROR "~@<~?~@[: ~2I~_~A~]~:>" {10035010F3}>)
3: (ERROR SB-INT:SIMPLE-FILE-ERROR :PATHNAME #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :FORMAT-CONTROL "~@<~?~@[: ~2I~_~A~]~:>" :FORMAT-ARGUMENTS ("Failed to find the ~*~A~2:* of ~A" (#P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :TRUENAME) "No such file or directory"))
4: (SB-IMPL::SIMPLE-FILE-PERROR "Failed to find the ~*~A~2:* of ~A" #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" 2 :TRUENAME)
5: (SB-IMPL::QUERY-FILE-SYSTEM #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :TRUENAME T)
6: (TRUENAME #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp")
7: (SB-C::VERIFY-SOURCE-FILE #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp")
8: (COMPILE-FILE #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :OUTPUT-FILE #P"/home/jay/.cache/common-lisp/sbcl-1.5.5-linux-x64/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages-tmpGHU3ALSZ.fasl" :VERBOSE NIL :PRINT NIL :EXTERNAL-FORMAT :UTF-8 :TRACE-FILE NIL :BLOCK-COMPILE NIL :EMIT-CFASL NIL)
9: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:COMPILE-FILE*) {10034FFEDB}> NIL)
10: (UIOP/PATHNAME:CALL-WITH-ENOUGH-PATHNAME #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" NIL #<CLOSURE (LAMBDA (UIOP/LISP-BUILD::INPUT-FILE) :IN UIOP/LISP-BUILD:COMPILE-FILE*) {10034FFE5B}>)
11: (UIOP/LISP-BUILD:COMPILE-FILE* #P"/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.lisp" :OUTPUT-FILE #P"/home/jay/.cache/common-lisp/sbcl-1.5.5-linux-x64/usr/share/common-lisp/source/cl-ppcre/cl-ppcre-unicode/packages.fasl" :EXTERNAL-FORMAT :UTF-8 :WARNINGS-FILE NIL)
12: (ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-ppcre-unicode" "cl-ppcre-unicode" "packages">)
13: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-ppcre-unicode" "cl-ppcre-unicode" "packages">)
14: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
15: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-ppcre-unicode" "cl-ppcre-unicode" "packages">) [fast-method]
16: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100376BEB3}>) [fast-method]
17: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
18: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100376BEB3}>) [fast-method]
19: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
20: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next">)
21: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
22: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next">) [fast-method]
23: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/OPERATE:BUILD-OP :NEXT)
24: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
25: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NEXT) [fast-method]
26: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100359DD3B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
27: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
28: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100358BB3B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
29: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NEXT) [fast-method]
30: (ASDF/OPERATE:MAKE :NEXT)
31: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:MAKE :NEXT) #<NULL-LEXENV>)
32: (EVAL (ASDF/OPERATE:MAKE :NEXT))
33: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . "(when (string= (uiop:getenv \"NEXT_INTERNAL_QUICKLISP\") \"true\") (load \"quicklisp/setup.lisp\"))") (:EVAL . "(ql:quickload :trivial-features)") (:EVAL . "(ql:quickload :prove-asdf)") (:LOAD . "next.asd") (:EVAL . "(asdf:make :next)") (:EVAL . "(uiop:quit)") (:QUIT)))
34: (SB-IMPL::TOPLEVEL-INIT)
35: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
36: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
37: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

Compilation failed.
Make sure the 'xclip' binary and the 'sqlite' and 'libfixposix' development files are available on your system.
make: *** [Makefile:36: next] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: next-browser
~ $

**Comment by Ambrevar** [comment]
I suspect you have some Common Lisp libraries installed at the system
level (here cl-ppcre).

**Comment by jtgd** [comment]
Do you mean Common Lisp libraries that I should NOT have installed? If I do it must be something that Emacs installed. Is there a suggested fix for this? Is there a place I can get compiled binaries?

**Comment by jtgd** [comment]
Oh, I see it now. Yes there was a package `cl-ppcre` installed. Not sure who dragged that in, but when I uninstalled it then next was able to compile.

The problem now is that `next` conflicts with an existing program of the same name.
```
(1/1) checking for file conflicts                                                                                  [#####################################################################] 100%
error: failed to commit transaction (conflicting files)
next-browser: /usr/bin/next exists in filesystem (owned by nmh)
Errors occurred, no packages were upgraded.
```
I guess I'll manually rename that to `next-browser` for now.

**Comment by Ambrevar** [comment]
In general (for all OSes), you should build in a self-contained
environment (e.g. a container, a chroot, etc.).  Then you'd not see this issue.

The error you saw was because your local cl-ppcre package was out of date.

Regarding the binary name: yes, you can simply install to next-browser
instead.

Functional package managers like Nix and Guix help deal with file
conflicts by offering multiple profiles: this is something you might
like, give it a shot :)

**Comment by jtgd** [comment]
Now I have run time errors. I think I'll check back later when things settle down. Thanks for your help.
