### ISSUE TITLE
Question: how do I enable VI bindings?

### ISSUE THREAD

**Issue by crocodile2u** [atlas-engineer/next#469]

**Comment by alexherbo2** [comment]
https://reddit.com/r/vim/comments/bzoss8/next_browser_now_has_vi_bindings/

**Comment by crocodile2u** [comment]
@alexherbo2 I did that but at first I did not put "(in-package :next)" on top. I have a Vim background, and when I learned about Next browser, switching to vi mode was the very first thing to do, and I had a moment of frustration before I found all the information I need. I think these two lines should be in the "key bindings" section of manual.

**Comment by jmercouris** [comment]
@crocodile2u Please feel free to update the manual with what you mean and make a pull request! It would mean a lot to us!

**Comment by crocodile2u** [comment]
https://github.com/atlas-engineer/next/pull/470

**Comment by impaktor** [comment]
This could be closed, since above PR was merged.

**Comment by Ambrevar** [comment]
Thanks!
