### ISSUE TITLE
Increase minibuffer box size

### ISSUE THREAD

**Issue by matthuszagh** [atlas-engineer/next#472]
**Describe the bug**
I've set increased zooming and minibuffer font/height for an HiDPI display (as described [here](https://github.com/atlas-engineer/next/issues/293#issuecomment-536301173)). I'm experiencing an issue in which increasing the minibuffer line height doesn't increase the minibuffer box size, so the text becomes cut off, as shown in this screenshot. To clarify, the line height does have an effect but it doesn't raise the minibuffer top bar so it worsens the cutoff.

![minibuf](https://user-images.githubusercontent.com/7377393/67298774-9435a880-f4a0-11e9-866b-51759759805f.png)

I've exaggerated the settings somewhat to show the effect, but even with the settings provided in the link above, I'm getting some cutoff at the bottom.

**Precise recipe to reproduce the issue**
Next version 1.3.4 on NixOS, run with
`$ export WEBKIT_DISABLE_COMPOSITING_MODE=1 && export $(dbus-launch) && next`

(disable compositing is for compatibility with my Nvidia GPU and I can't get it to find dbus without the dbus-launch part on Nix)

Full config (since it's still small)
```
(in-package :next)

;; use vi keybindings by default
(add-to-default-list 'vi-normal-mode 'buffer 'default-modes)

;; zoom for HiDPI display
(defun my-buffer-defaults (buffer)
  (setf (zoom-ratio-default buffer) 1.5)
  (unzoom-page :buffer buffer))          ; Needed for non-web-mode buffers.

(defun my-minibuffer-defaults (minibuffer)
  (setf
   (max-lines minibuffer) 20
   (minibuffer-line-height minibuffer) "2.0em"
   (minibuffer-font-size minibuffer) "1.1em"))

(defun my-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'my-buffer-defaults)
  (hooks:add-to-hook (hooks:object-hook *interface* 'minibuffer-make-hook)
                     #'my-minibuffer-defaults))

(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults)
```

**Information**
- OS name+version: NixOS git master branch
- Kernel name+version: 5.2.14
- Graphics card and driver: Nvidia 435.21
- Desktop environment / Window manager name+version: EXWM
- Next version (from =M-x next-version= or =next --version=): 1.3.4
- How you installed Next (Guix pack, package manager, build from source): Nix recipe
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version:

**Comment by Ambrevar** [comment]
You can set the minibuffer height with

```
(setf (minibuffer-open-height window) 400) ; default is 200
```

`minibuffer-open-height` is a slot of the `window` class.

**Comment by matthuszagh** [comment]
Unfortunately, still not quite getting it.
```
(defun mh-minibuffer-window-defaults (window)
  (setf
   (minibuffer-open-height window) 400))

(defun mh-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'mh-buffer-defaults)
  (hooks:add-to-hook (hooks:object-hook *interface* 'minibuffer-make-hook)
                     #'mh-minibuffer-defaults)
  (hooks:add-to-hook (hooks:object-hook *interface* 'window-make-hook)
                     #'mh-minibuffer-window-defaults))

(hooks:add-to-hook '*after-init-hook* #'mh-interface-defaults)
```
what am I missing here?

**Comment by Ambrevar** [comment]
Weird, it works for me.

Have you restarted Next?  Does it show any error output if you start it
from a shell?

**Comment by matthuszagh** [comment]
Still somehow getting the error, not quite sure what's going on. I've done a full reboot and don't see any error messages.

**Comment by jmercouris** [comment]
Perhaps there is something with regards to GTK and pixel height on HiDPi displays. Is there another way of specifying the height of a container in GTK? Does it depend on GTK version perhaps?

**Comment by Ambrevar** [comment]
I believe this should no longer be an issue on master.  @matthuszagh Can you test?

**Comment by jmercouris** [comment]
I have fixed this bug, I had it before, and I can confirm it is no longer an issue on master
