### ISSUE TITLE
Is Windows WSL supported yet?

### ISSUE THREAD

**Issue by JianshuJie** [atlas-engineer/next#474]
I'm trying to install next in ubuntu 18.04 WSL in win10 laptop. However, when I try to launch next, the following error is raised:
`Next version 1.3.4
 <INFO> [22:11:08] next remote.lisp (ensure-dbus-session fun1) -
  D-Bus session inaccessible, starting our own one.
  Old D-Bus addresses: (NIL NIL)
  New D-Bus address: unix:abstract=/tmp/dbus-NCuanHyKEA,guid=f7e9268b08c919427c0e86b15db1b0fc
 <INFO> [22:11:08] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-NCuanHyKEA">)
 <INFO> [22:11:08] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.0
 <INFO> [22:11:08] next port.lisp (run-program port) -
  Current directory: /home/jjs/
 <INFO> [22:11:08] next port.lisp (run-program port) -
  Platform port path: next-gtk-webkit
 <INFO> [22:11:08] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [22:11:08] next port.lisp (run-program port) -
  Platform port log file: /home/jjs/.local/share/next/next-gtk-webkit.log
<ERROR> [22:11:09] next port.lisp (kill-port port) -
  Process #<PROCESS-INFO {1008173EC3}> is not running
<ERROR> [22:11:09] next base.lisp (start fun2) -
  Could not connect to platform port: next-gtk-webkit
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")`
Any suggestions? Thx in advance.

**Comment by jmercouris** [comment]
Hi Jianshu, thank you for your interest in Next!

WSL Is not officially supported, however that doesn't preclude it from working!

I suggest that you follow the prompt and set your platform-port-path :-)

Installing Next should have made a program called next-gtk-webkit, you just need to point Next to that file on your disk.

**Comment by JianshuJie** [comment]
I'm sorry, but there are still some problems.
After a check, I found next-gtk-webkit is already in my $PATH, but ~/.config does not exist.
when I run 'next-gtk-webkit', it prompts out `** Message: 19:17:51.779: Starting platform port` but then nothing happens.
I've set up my GUI environment according to this instruction https://dev.to/david_j_eddy/run-linux-gui-applications-on-windows-10-3130 , and after setting DISPLAY to localhost:0.0 instead of :0, I've managed to make gvim run.

**Comment by jmercouris** [comment]
So, the thing is that `next-gtk-webkit` is supposed to be started by Next. If you start it manually yourself, the Lisp core (`next`) will assume that some component has failed. You have to create `~/.config` if it does not exist (it is part of the XDG standard https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Then simply make your `init.lisp` file like this:

```
(in-package :next)
 (setf +platform-port-command+
     "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
```

in the above snippet you'd replace the path with the correct path to `next-gtk-webkit` on your system. Please let me know how it goes!

**Comment by Ambrevar** [comment]
> If you start it manually yourself, the Lisp core (`next`) will assume
> that some component has failed.

Actually Next should start correctly even when the platform port was started manually.

**Comment by JianshuJie** [comment]
Thanks. This time another error occurs:
```
Next version 1.3.4
 <INFO> [19:53:46] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "NIL">)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1006972E33}>:
  No server addresses left to try to open.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006972E33}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No server addresses left to try to open." {1006BE5FB3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No server addresses left to try to open." {1006BE5FB3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No server addresses left to try to open." {1006BE5FB3}>)
3: (ERROR "No server addresses left to try to open.")
4: ((LAMBDA NIL :IN DBUS/PROTOCOLS:OPEN-CONNECTION))
5: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1006BE34DB}> #<event base, 0 FDs monitored, using: #<epoll(4) multiplexer> {1006BE18B3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1006BE3393}>))
6: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
7: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
12: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFFD03ED4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006972E33}>> NIL T NIL)
13: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006972E33}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1006972DDB}> NIL)
14: ("foreign function: call_into_lisp")
15: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
```

I've tried `sudo service dbus start` and found it already started. Besides, next is installed to /usr/bin/local in my laptop, and I tried `sudo next`, but the output is the same.

**Comment by Ambrevar** [comment]
D-Bus should be started as a user.
You can have both a system D-Bus and a user D-Bus running at the same
time.

Don't run Next as root.

**Comment by JianshuJie** [comment]
Thanks, I've successfully launched it using `dbus-launch next`.

**Comment by jmercouris** [comment]
> If you start it manually yourself, the Lisp core (`next`) will assume that some component has failed.
> Actually Next should start correctly even when the platform port was started manually.

Aha, I see that you are correct. I didn't think about it pinging the platform port and choosing not to start it.

**Comment by jmercouris** [comment]
Jianshu, is your issue resolved?

**Comment by JianshuJie** [comment]
yes, it is resolved. Should I close this issue now?

**Comment by vindarel** [comment]
Great news, well done!
