### ISSUE TITLE
Can't install on Arch Linux from both package and source

### ISSUE THREAD

**Issue by christiaan-janssen** [atlas-engineer/next#476]
**Describe the bug**
I'm trying to install Next on my Arch machine, but I keep getting an error about not having xclip / sqlite / libfixposix. I have tried installing different versions of these packages, but to no avail. I was talking to jmercouris on IRC and he suggested building from source and setting `NEXT_INTERNAL_QUICKLISP = false` this gave me the error `Package QL does not exist.`

**Precise recipe to reproduce the issue**
install next from package / source 

**Information**
- OS name+version: Arch Linux
- Kernel name+version: 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux
- Graphics card and driver:
- Desktop environment / Window manager name+version: stumpwm 1.0.1
- Next version (from =M-x next-version= or =next --version=):
- How you installed Next (Guix pack, package manager, build from source):
- SBCL version (if built from source): 1.5.5-1 with quicklisp
- WebKitGTK+ / PyQt-Webengine version:

**Comment by Ambrevar** [comment]
To clarify: did you try to install both from the AUR and to build from source?

**Comment by jmercouris** [comment]
The user has tried both, I have spoken to them on IRC

**Comment by christiaan-janssen** [comment]
Yes, that solved the problem, thanks a lot!
