### ISSUE TITLE
No "C-h k" / documentation for key-press?

### ISSUE THREAD

**Issue by impaktor** [atlas-engineer/next#477]
In emacs, you can prefix a key sequence with `Ctrl-h k` to bring up which function it is bound to, and it's documentation.

**Comment by Ambrevar** [comment]
Indeed, and its high on the priority list, together with other
interactive documentation features :)

**Comment by impaktor** [comment]
Also, just the single line description in mini buffer like on conkeror is nice, if not a lot of work:

I.e.  when doing `M-x buffer-` minibuffer shows relevant matching commands and short doc string:

![2019-10-30-160719_1600x900_scrot](https://user-images.githubusercontent.com/619390/67873088-39045580-fb33-11e9-833c-d6f77850485b.png)

**Comment by impaktor** [comment]
@jmercouris off-topic: regarding yesterday's IRC conversation on *history-tree*: I think what bothered me is that it is probably more just a single 1D hierarchical list, rather than an actual "tree" with parallel branches, e.g. like emacs' undo-tree (or I just never done advanced enough back/forward navigation in Next to get more than one branch?)

**Comment by Ambrevar** [comment]
It is a full tree indeed.  See the screenshots ;)

To get branches, you need to go back, then open a new URL not already in
the children.

**Comment by jmercouris** [comment]
Indeed, you need to have a non-linear history to achieve this. The easiest way to get a bunch of branches is open up a page.

Visit a link on that page
Go Back
Visit a new link on that page

Now your tree will have two or more branches!

**Comment by impaktor** [comment]
> Also, would be nice to have something on `C-h i/t/h` for info/tutorial/help. Maybe initially just bind (one of) them to `help` function?

Sounds like the conclusion of #203 is to just link to Practical Common Lisp, and/or some other useful tutorials.

**Comment by jmercouris** [comment]
More or less, yes. We can make a simple crash course for users to get started though. It may be intimating the idea that it is necessary to learn a programming language to do some simple customizations. We hope to have a "customize" functionality similar to Emacs down the road and several GUI changes to make it more friendly for novice users (that can be turned off of course!).

**Comment by Ambrevar** [comment]
`C-h k` is implemented in 87f5ad1cf5894d75911aafa95fb7d212dd4baea7.

I've opened new issues for the rest:
- https://github.com/atlas-engineer/next/issues/624: Add one-liner documentation to M-x command list.
- https://github.com/atlas-engineer/next/issues/623: Embed documentation.
