### ISSUE TITLE
Empty page for any URL, if setting list of blocked hosts with next/blocker-mode:*default-host-list*

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/next#479]
Hello,

Accessing any URL displays an empty page, when defining a list of blocked hosts as suggested in the documentation (if I remove this code, Next loads the same URLs just fine). 

`(defvar *my-blocked-hosts*
  (next/blocker-mode:make-hostlist
   :hosts '("platform.twitter.com"
            "syndication.twitter.com"
            "m.media-amazon.com")))

(defun my-buffer-defaults (buffer)
  (next/blocker-mode:blocker-mode
   :hostlists (list *my-blocked-hosts* next/blocker-mode:*default-host-list*)
   :buffer buffer))

(defun my-interface-defaults-2 ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'my-buffer-defaults))

(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults-2)
`

Issuing "follow-hint" confirms the page has no link to go to. Next is not hung, and remains available for other commands. 
Here are the logs:
``WARNING: Setting locale failed.
  Check the following variables for correct values:
  LC_ALL=en_US.utf-8
  LANG=en_US.utf-8
Next version 1.3.4
Loading configuration from #P"~/.config/next/init.lisp"...
 <WARN> [18:05:04] next utility.lisp (setf get-default) -
  The (setf (get-default ...)) and (add-to-default-list ...) forms are deprecated.
 <INFO> [18:05:04] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
 <INFO> [18:05:04] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.11541
 <INFO> [18:05:04] next port.lisp (run-program port) -
  Current directory: /home/jb/
 <INFO> [18:05:04] next port.lisp (run-program port) -
  Platform port path: /gnu/store/nn0zlm3za919a9jdi5idfb15hn5npjsj-next-gtk-webkit-1.3.4/bin/next-gtk-webkit
 <INFO> [18:05:04] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [18:05:04] next port.lisp (run-program port) -
  Platform port log file: ~/.local/share/next/next-gtk-webkit.log
 <WARN> [18:05:05] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
 <INFO> [18:05:05] next session.lisp (restore-sexp-session form-fun-4) -
  Restoring (https://lwn.net/??default)
 <INFO> [18:05:05] next minibuffer.lisp (echo form-fun-6) -
  "Loading global history of 25 URLs."
 <INFO> [18:05:05] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://lwn.net/."
 <INFO> [18:05:05] next minibuffer.lisp (echo form-fun-6) -
  "Updating hostlist ~/.local/share/next/hostlist-stevenblack from https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::REQUEST-RESOURCE) signaled an error: The alien function "CRYPTO_num_locks" is undefined..
` `

[next-gtk-webkit.log](https://gist.github.com/Mestelan/d8099942dae17cfa24ca83f5c6eb5165)
Any clues?

**Information**
- OS name+version: 
GNU/Linux Debian 10.1

- Kernel name+version:
4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 

- Next version (from =M-x next-version= or =next --version=):
Version 1.3.4

- Desktop environment / Window manager name+version:
XMonad 0.15

- How you installed Next (Guix pack, package manager, build from source):
guix pull

- WebKitGTK+ / PyQt-Webengine version:
WebKitGTK+ 1.3.4

**Comment by Mestelan** [comment]
More precisely, the error only occurs when refering to `next/blocker-mode:*default-host-list*`.
It does not occur if using a hard-coded list of hosts, as below:

`(defun my-buffer-defaults (buffer)
  (next/blocker-mode:blocker-mode
   :hostlists (list *my-blocked-hosts*)
   :buffer buffer))
`

**Comment by Ambrevar** [comment]
Maybe not related to your issue, but the line


	 Method handler (NEXT::CORE-OBJECT
									 NEXT::REQUEST-RESOURCE) signaled an error: The alien function "CRYPTO_num_locks" is undefined..

is worrying.
Which version of openssl is on your system?

**Comment by Mestelan** [comment]
Now that is a great question.

```
aptitude show openssl  
Package: openssl                         
Version: 1.1.1d-0+deb10u2
State: installed
```

The guix package also has installed a variety of versions in /gnu/store. I can see 
```
./k2m4q2av9hw73hw2jx6qrxqdyh855398-openssl-1.1.1c
./1dvkm6b97667qd36rsnw4g6isnsmpym7-openssl-1.1.1d
./m9ngbfyi8wrwiwyr7dkfnhn5fyfalq3r-openssl-1.0.2p

```
Having yet virtually no understanding of guix, I unfortunately cannot tell you which one is being used.

**Comment by Mestelan** [comment]
For comparison, I have installed next from the [Debian package](https://next.atlas.engineer/static/release/next_1.3.4_amd64.deb). With this setup:

- the message 
>The alien function "CRYPTO_num_locks" is undefined..

does not appear
- pages are displayed all right.

I will use this installation method in the future. Also, I think we might as well close this bug; I would personally struggle  to investigate things further.

**Comment by jmercouris** [comment]
OK, thank you for the update. Please let us know if you have any idea why this might be, or should anything new come to light!

**Comment by Ambrevar** [comment]
Jean-Baptiste, did you run any `guix gc` after you installed Next?

It's possible that you suffered from a grafting issue and the wrong
openssl version was used.

**Comment by Mestelan** [comment]
Thanks Pierre.
No, I had not run `guix gc`.

Do you mean I should have, in order to remove some obsolete versions of openssl?

I have just tried done so, now:
https://gist.github.com/Mestelan/a2633b6ee37e381cf5930613105c6644
```
...
deleting `/gnu/store/zbcv5m1r93rl950f7vjgkr5j8vg7wncj-next-1.3.4'
deleting `/gnu/store/bdhzc05hspsym5isbcfrx910ymx3n0nj-next-1.3.4-lib'
deleting `/gnu/store/nn0zlm3za919a9jdi5idfb15hn5npjsj-next-gtk-webkit-1.3.4'
deleting `/gnu/store/wlllrpvidx7hhg0c0jc7swkqj4cgkr9s-webkitgtk-2.26.1'
...
deleting unused links...
note: currently hard linking saves 1751.97 MiB
guix gc: freed 952.93678 MiBs

```

After which, Next can no longer be run from guix:
`<INFO> [23:28:29] next port.lisp (run-program port) -
  Current directory: /home/jb/
 <INFO> [23:28:29] next port.lisp (run-program port) -
  Platform port path: /gnu/store/nn0zlm3za919a9jdi5idfb15hn5npjsj-next-gtk-webkit-1.3.4/bin/next-gtk-webkit
 <INFO> [23:28:29] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [23:28:29] next port.lisp (run-program port) -
  Platform port log file: /home/jb/.local/share/next/next-gtk-webkit.log
<ERROR> [23:28:29] next base.lisp (start fun2) -
  Couldn't execute "/gnu/store/nn0zlm3za919a9jdi5idfb15hn5npjsj-next-gtk-webkit-1.3.4/bin/next-gtk-webkit": No such file or directory
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
`

Again, I have not taken the necessary time to study guix, so I might have done something silly during the install, which is causing all these mishaps. I would prefer to reinstall guix from scratch at some time, although not quite so soon. I am fine with the Debian packaging for the moment, if I can make it work on my system.

**Comment by Ambrevar** [comment]
No, you shouldn't have! ;)
Now you have to re-install Next, because the next-gtk-webkit reference
is broken :(

--8<---------------cut here---------------start------------->8---
guix build --no-grafts next
--8<---------------cut here---------------end--------------->8---

This is a known issue with Guix, but probably not your issue here.
