### ISSUE TITLE
Some keys don't work on Arch Linux

### ISSUE THREAD

**Issue by NQNStudios** [atlas-engineer/next#480]
**Describe the bug**

With a fresh installation from source, I'm finding that several keys and key combinations don't work in Next. As far as I can tell, those keys are:

```
C-x HYPHEN #but C-x C-HYPEN works
M-<
M->
C-x C-+
C-x +
C-x C-=
C-c
C-v
```

However, using M-x to call any of those functions directly **does work**.

Additionally, with num lock on, the following number pad keys still do not self-insert:
```
1
2
3
4
6
7
8
9
.
``` 

All of those keys perform their secondary functions (Home, up, down, PgUp, etc.)

Note that 0 on the number pad *does* self-insert, instead of performing the `Insert` key function, when num lock is on.

With num lock off, none of them self-insert. 0 does nothing.

**Precise recipe to reproduce the issue**

Build Next from source or install from AUR on Arch Linux. Run `next` from inside either an exwm session, or i3 (I tried both).

**Information**
- OS name+version: Arch Linux, Rolling
- Kernel name+version: 5.3.6-arch1-1-ARCH
- Graphics card and driver: ATI Radeon 5670, `radeon` driver 
- Desktop environment / Window manager name+version: `exwm` or `i3`
- Next version (from =M-x next-version= or =next --version=): 
- How you installed Next (Guix pack, package manager, build from source): build from source
- SBCL version (if built from source): 1.5.5 from pacman
- WebKitGTK+ / PyQt-Webengine version: not sure. Let me check

**Comment by jmercouris** [comment]
Hi, thank you for your report! A couple of quick questions:

- are you using a US keyboard layout?
- which version of Next are you using? It is unclear if you've built from source.
- Does `C-x 0` work?

thanks in advance! I think I know what may be happening if `C-x 0` does not work. Perhaps the parsing of the keybindings for certain combinations may be wonky.

**Comment by NQNStudios** [comment]
Sadly, `C-x 0` works. To clarify, I did build Next from source. When I use `M-x` and try to call `next-version` it won't let me press enter, and the completion minibuffer stays open. Other commands work normally.

For the keyboard layout, I might have forgotten to choose one when I installed Arch. I'll get back to you on that as well as the webkitgtk and pyqt-webengine versions tomorrow

**Comment by Ambrevar** [comment]
Can you share the output of the following command?

    setxkbmap -query

**Comment by NQNStudios** [comment]
```
rules:      evdev
model:      pc105
layout:     us
```

**Comment by NQNStudios** [comment]
WebkitGTK+ is version 2.26.1-1. `PyQtWebEngine` and `libfixposix` weren't installed when I built the first time--so I installed them both and re-built Next. The problem is still there. I'm going to try Vim bindings to see if they work as a temporary workaround.

**Comment by NQNStudios** [comment]
In `vi-normal-mode`, more key bindings work than do without. Keybindings I've find that **don't** work in vi mode:

`M-:`

**Comment by jmercouris** [comment]
Very interesting, please do let us know if you find something out!

**Comment by noloop** [comment]
The keys also don't work for me (void-linux):

```
M-<
M-<
C-x C-+
C-x +
C-x C-=
C-z (here comment box)
```

**Comment by Ambrevar** [comment]
What is your window manager?  Are you sure those keys aren't intercepted
by it?

**Comment by halcyon** [comment]
```
% setxkbmap -query                                                                                                                        
rules:      evdev
model:      pc105
layout:     us
options:    ctrl:swapcaps

OS name+version: Debian 10
Kernel name+version: 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
Graphics card and driver: Quaodro P500 Mobile, nouveau driver
Desktop environment / Window manager name+version: stumpwm
Next version (from =M-x next-version= or =next --version=): 1.3.4
How you installed Next (Guix pack, package manager, build from source): package manager
SBCL version (if built from source):
WebKitGTK+ / PyQt-Webengine version: ack, package manager, build from source): libwebkit2gtk-4.0-37:amd64 2.26.1-3~deb10u1 / python-pyqt5.qtwebkit 5.11.3+dfsg-1+b3
```

I'm seeing the same behavior as @noloop. `C-g` and `M-x` work, but `C-x 0`, `M-<` and `M->` don't.

**Comment by jmercouris** [comment]
Do those bindings per chance insert special characters on your machine in other programs?

**Comment by halcyon** [comment]
No, they do not.

**Comment by JeanMax** [comment]
Hey there!

I have pretty much the same problem than NQNStudios (with a similar setting: arch/i3).
I thought at first it was linked to my azerty layout, but it does the same with a classic qwerty one.

One difference though: I don't have any problem with the numpad section! (which allows me to use the font resizing mappings hehe)


Anyway, thanks for this amazing piece of software, that's a really cool project :)

**Comment by jmercouris** [comment]
Thank you for the kind words and information :-)

**Comment by w96k** [comment]
Same problem on guix distro with stumpwm

**Comment by Ambrevar** [comment]
With StumpWM you might need this:
https://github.com/stumpwm/stumpwm/wiki/FAQ#my-mouse-wheel-doesnt-work-with-gtk3-applications-add-the-following-to

Does it help?

**Comment by jmercouris** [comment]
Just a report, I also have the same problem on GTK on MacOS. Some keys are being mistranslated. There must be an OS agnostic way of doing this, or some sort of translation layer we can build...

**Comment by w96k** [comment]
@Ambrevar Nope, it didn't helped.

**Comment by intuser** [comment]
I'm testing (again, after some time) next on Ubuntu bionic. I didn't test all the key bindings, but the following don't work:

C-x C-c
C-x -
C-x C--
C-x C-+ (C-x + and C-x 0 work)
M-<
M->
C-x C-=
C-v (M-v works)
C-.
C-x C-k (C-x k works)

(Insofar as these are costumary key bindings in Emacs they all work there and also in conkeror.)

**Comment by Ambrevar** [comment]
This should be fixed on master!
Beware, master is quite experimental at this point, so expect some rough edges.
2.0 coming soon!

**Comment by Ambrevar** [comment]
2.0 release inbound. Closing.
