### ISSUE TITLE
Request: be able to TAB-complete a search engine

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#482]
> I would expect that when openting a new buffer and starting typing "wiki" or "github" and then hitting TAB that it would auto-complete it

ping @impaktor 

https://github.com/atlas-engineer/next/pull/475

**Comment by impaktor** [comment]
Cool, I'll have to give that a spin later!

**Comment by Ambrevar** [comment]
@vindarel: I don't think that the original issue was about completing
the code (in lisp files), but about completing the search engine
keywords from the minibuffer.  The latter is not implemented in #475.

**Comment by impaktor** [comment]
I'm testing master branch right now, and it seems to auto-complete in minibuffer like I wanted. 

Possibly strange that what it auto-completes to isn't visible in the minibuffer when it is showing all possible completions. I.e. the best match for what has been written should be at the top?

Might be a feature, I don't know and doesn't matter much to me.

**Comment by Ambrevar** [comment]
Hmm, I don't really understand what you mean.
Can you describe an exact recipe of what you do to "auto-complete"?
What you expect and what you get?

**Comment by impaktor** [comment]
I have a custom search, e.g. for "rateyourmusic"
``` common-lisp
(defun my-interface-defaults ()
  (setf (search-engines *interface*)
        '(("default" . "https://duckduckgo.com/?q=~a")
          ("yt" . "https://www.youtube.com/results?search_query=~a")
          ("duck" . "https://duckduckgo.com/?q=~a")
          ("discogs" "https://www.discogs.com/search/?q=~a" "https://www.discogs.com")
          ("wiki" . "https://en.wikipedia.org/w/index.php?search=~a")
          ("imdb" . "https://www.imdb.com/find?q=~a&s=all")
          ("metalarchives" . "https://www.metal-archives.com/search?searchString=~a&type=band_name")
          ("urban" . "https://www.urbandictionary.com/define.php?term=~a"))))
(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults)
```
I.e. if I open next, input key sequence:
`<C-l> rat`
I expect whatever will be auto-completed on TAB to be the top thing in the minibuffer list, but I don't see "rateyourmusic" in the list:
![2019-11-05-104812_1600x900_scrot](https://user-images.githubusercontent.com/619390/68197416-8c0a5c80-ffba-11e9-9b45-c93d8769394f.png)

now hit `<TAB>`, and the minibuffer list flickers, is re-ordered, and it auto-completes to `rateyourmusic`, sort of out of no-where. 
![2019-11-05-105111_1600x900_scrot](https://user-images.githubusercontent.com/619390/68197540-b6f4b080-ffba-11e9-9212-e306cb710b59.png)

I really like having the auto-completion function, so I'm happy, but I'm just pointing out something that is probbably un-intuitive for new users.

**Comment by Ambrevar** [comment]
Uhuh! Looks like a pretty bug! :)

Currently we don't have completion on search engines, but it would be
nice to add it of course.

What TAB does is merely insert the currently selected candidate in the
input, available for further editing.
So if you had tried to select another candidate and pressed TAB, this
candidate would replace your current input.

**Comment by impaktor** [comment]
> Currently we don't have completion on search engines, but it would be nice to add it of course.

Now I don't get it. I've tried auto-completing my custom search engines (see code snippet in my previous post), and it seems to work with all the examples I've tried on current master. I tried the same on the October release and then it didn't work, so something new has been added in the past month.

> What TAB does is merely insert the currently selected candidate in the input, available for further editing.

But when I hit tab it does not insert `rat` or the `imdb` url with "Ratings and Reviews" seen in the screenshot, it inserts my `rateyourmusic` search engine. Same with the other search eninges I've added. And the search engine works as expected. Just not that it's shown in the list.

**Comment by vindarel** [comment]
> Currently we don't have completion on search engines, but it would be nice to add it of course.

this is what this commit does, the explanations with the screenshots are exactly that. It completes the search engine names "out of nowhere". We could add them in the minibuffer candidates, if it's better. I like it like that because I prefer to see the suggested urls than the search engines I know I have. And with many search engines, we'll only see them and not the urls.

@impaktor You have a wrong search-engines structure. It must be a list of list with 3 strings. You built an alist, which complies to the description that was there, but it's not exactly correct. (edit: I just updated the doc…)

> The elements are in the form of a 3-tuple of strings (SHORTCUT SEARCH-URL FALLBACK-URL).
> You can invoke them from the minibuffer by prefixing your query with SHORTCUT.
> If the query is empty, FALLBACK-URL is loaded instead.  If
> FALLBACK-URL is empty, SEARCH-URL is used on an empty search.


```
(defun my-interface-defaults ()
  (setf (search-engines *interface*)
        '(("default"
           "https://duckduckgo.com/?q=~a"
           "https://duckduckgo.com/")
          ("yt"
           "https://www.youtube.com/results?search_query=~a"
           "https://www.youtube.com/")
          ("duck"
           "https://duckduckgo.com/?q=~a"
           "https://duckduckgo.com/")
          ("discogs" "https://www.discogs.com/search/?q=~a" "https://www.discogs.com")
          ("rateyourmusic"
           "https://rateyourmusic.com/search?searchtype=a&searchterm=~a"
           "https://rateyourmusic.com/")
          ("wiki"
           "https://en.wikipedia.org/w/index.php?search=~a"
           "https://en.wikipedia.org/")
          ("imdb"
           "https://www.imdb.com/find?q=~a&s=all"
           "https://www.imdb.com/")
          ("metalarchives"
           "https://www.metal-archives.com/search?searchString=~a&type=band_name"
           "https://www.metal-archives.com/")
          ("urban"
           "https://www.urbandictionary.com/define.php?term=~a"
           "https://www.urbandictionary.com/"))))
(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults)
```

**Comment by impaktor** [comment]
> We could add them in the minibuffer candidates, if it's better. I like it like that because I prefer to see the suggested urls than the search engines I know I have. 

Technically, they should be no different than URLs, in my mind, for instance I have search engines that clash, for instance "scholar" (for Google scholar article search) and "scheme" for Scheme documentation. Thus, there's a case to be made to see which one a "sch" would auto-complete to.

> And with many search engines, we'll only see them and not the urls.

well, it should narrow to search, in an ideal world. "TAB" should select/complete to the top item in the list, or that's what's intuitive to me. Anyway, I'm sure effort is better spent elsewhere than nitpicking this. 

Thanks for the feature, I'm enjoying it!

**Comment by Ambrevar** [comment]
@vindarel: https://github.com/atlas-engineer/next/pull/475 only changes
the default value of search engines, I don't understand how this changes
the minibuffer completion.

**Comment by vindarel** [comment]
Don't look at 475's code, I linked it because Impaktor made his comment/feature request there. The commit is https://github.com/atlas-engineer/next/commit/b38f90cebc36074fd33dde70f9ddbbebc7494a9c
