### ISSUE TITLE
Question about placeholder replacement in search engines 

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/next#485]
Hello,

I noticed that a '+' sign gets added to the generated URL when using a search engine with the `~a` placeholder. For instance, if we declare 
`("gh" . "https://github.com/search?q=~a")`, 
then
`gh next` expands to `https://github.com/search?q=+next`.

Is this intended? Why not `https://github.com/search?q=next`?

This '+' sign causes issues in some search engines/URL patterns. For example, I have
`("jira-calcite" . "https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-~a")`;
so invoking `jira-calcite 3466` 
expands to 
`https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-+3466`
which does not display the expected result.

Am I missing something?

**Comment by Ambrevar** [comment]
Nope, and thanks for reporting, you just found a bug!
Should be fixed in 05180ac9c4f7c6e8c55a2799904f25c9d5504bbd.
