### ISSUE TITLE
Make `--session` CLI argument more useful

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#486]
The `--session` command line argument is unnaturral: it's a boolean, but using `--session` seems to do nothing.  It only does something with `--session nil`.  

So why not using `--no-session` instead?

But maybe we could do something even more general: use `--session FILE`.
If the file does not exist, create it.
If it exists, load it and save the session into it.
If it's the empty string `""`, disable session.

Thoughts?
@vindarel?

**Comment by vindarel** [comment]
I'd enjoy `--session NAME` instead of FILE. `--no-session` works for me.

**Comment by Ambrevar** [comment]
`--session NAME` means we need to infer the name somehow.

I propose the following rules:

- If NAME matches a file, load this file.
- If not and NAME has no slash, match the basename (optional extension)
  in ~/.local/share/next.

In all cases, print the full path of the loaded session on startup to
disambiguate the chosen profile.

Thoughts?

**Comment by vindarel** [comment]
\+1

shall we have a `local/share/next/sessions/` subdirectory?

**Comment by Ambrevar** [comment]
Seems like the simplest way to go!

**Comment by Ambrevar** [comment]
While we are refactoring command line arguments, what about renaming the short args to something more consistent, for instance have the "no-*" version be in uppercase?

- `--session`, `-s`
- `--no-session`, `-S`
- `--init`, `-i`
- `--no-init`, `-I`

Thoughts? @vindarel @jmercouris

**Comment by jmercouris** [comment]
I'm okay with either, I personally only use the long form of command line arguments anyways, as the short form is almost impossible to remember outside of something like `ls -l`

**Comment by Ambrevar** [comment]
Fixed in 507f054ab5129ddffe523d49c0fd0479ea733980.
This also fixes a crash because of a non-existing folder when XDG_DATA_HOME was set to something else.

I haven't changed --no-init shortform `-Q` for now.

**Comment by Ambrevar** [comment]
I just noticed another inconsistency:
The negation of "--init-file" is "--no-init".
I suggest to rename "--init-file" to "--init".

**Comment by Ambrevar** [comment]
Done in 374c50abd41a7f97faab3555bbad07c00a6575ca.
