### ISSUE TITLE
The custom command example of the documentation doesn't work: "NEXT:MINIBUFFER is undefined".

### ISSUE THREAD

**Issue by noloop** [atlas-engineer/next#487]
**Describe the bug**

I try use one custom command as in the documentation and I get "NEXT:MINIBUFFER is undefined".

**Precise recipe to reproduce the issue**

In my **init.lisp**:

```lisp
(in-package :next) 

;;(setf +platform-port-command+ ...

(define-command bookmark-url ()
  "Allow the user to bookmark a URL via minibuffer input."
  (with-result (url (read-from-minibuffer (minibuffer *interface*)))
    (%bookmark-url url)))
```

In next I try `M-x bookmark-url` and I get:

```lisp
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: The function
                                                              NEXT:MINIBUFFER
                                                              is undefined..
```
**Information**

- OS: voidlinux
- Kernel name+version: x86_64 GNU/Linux 5.3.8_2
- Window manager bspwm 0.9.9:
- Next version: Version 1.3.4-eeea083
- How you installed Next: build from source
- WebKitGTK+ 4.0:

**Comment by Ambrevar** [comment]
The correct call is `(make-instance 'minibuffer ...)`, not `(minibuffer *interface*)`.

Which part of the documentation did you follow?

**Comment by noloop** [comment]
> Which part of the documentation did you follow?

https://next.atlas.engineer/documentation#creating-your-own-interactive-commands

**Comment by vindarel** [comment]
Thanks for the report.

The bookmark command is now

```
;; bookmark.lisp
(define-command bookmark-url ()
  "Allow the user to bookmark a URL via minibuffer input."
  (with-result (url (read-from-minibuffer
                     (make-instance 'minibuffer
                                    :input-prompt "Bookmark URL:")))
    (bookmark-add url)))
```

To get the url of the current buffer:

    (url (current-buffer))

(it is the accessor of the url slot of the buffer class. Previously, with `with-result … buffer-get-url`, it was an asynchronous call.)

We'll update the doc.

**Comment by noloop** [comment]
I try:

```lisp
(define-command dl (&optional video-url)
  "Download video with youtube-dl in the currently open buffer or optional video-url."
  (with-result (u (or video-url (url (current-buffer))))
		(next/video:download
   (list "youtube-dl" u
	 "-o" (format nil "~a/%(title)s.%(ext)s" "/home/noloop/common-lisp/")
	 "--embed-subs"))))
```

But it doens't work, and it doens't return any error.

**Comment by vindarel** [comment]
First, with good indentation:

```
(define-command dl (&optional video-url)
  "Download video with youtube-dl in the currently open buffer or optional video-url."
  (with-result (u (or video-url (url (current-buffer))))
    (next/video:download
     (list "youtube-dl" u
           "-o" (format nil "~a/%(title)s.%(ext)s" "/home/noloop/common-lisp/")
           "--embed-subs"))))
```

Then, you don't need `with-result` anymore:

```
(define-command dl (&optional video-url)
  "Download video with youtube-dl in the currently open buffer or optional video-url."
  (next/video:download
     (list "youtube-dl" (or video-url (url (current-buffer)))
           "-o" (format nil "~a/%(title)s.%(ext)s" "/home/noloop/common-lisp/")
           "--embed-subs")))
```

but this fails, which is expected.

```
The value
  "youtube-dl"
is not of type
  CHARACTER
when setting an element of (ARRAY CHARACTER)
```

look at `download`:

    (defun download (url &optional target-dir)

it takes an url as parameter, not a list.

So, what do you actually want to do? Add the `--embed-subs` argument? Try to use the parameter `*download-args*`.

Or, directly use

```
        (launch-and-notify (list with everything)
                                :success-msg (format nil "Video downloaded to ~a." target-dir)
                                :error-msg (format nil "Failed to download video.~&")))
```

**Comment by noloop** [comment]
I only follow the documentation:

https://next.atlas.engineer/documentation#downloading-videos

**Comment by vindarel** [comment]
damn, and yet the `next/video:download` function didn't change its signature since its introduction…

thanks. You'd better follow the manual on github: https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org

**Comment by noloop** [comment]
Thanks, I'll see in this link now. And also I forked the Next, I'll see directly in the code now.

**Comment by vindarel** [comment]
But keep an eye on the doc :D 

I'm looking forward to see what you'll come up with.
