### ISSUE TITLE
The keymap-scheme doesn't exist.

### ISSUE THREAD

**Issue by noloop** [atlas-engineer/next#489]
In the [documentation](https://next.atlas.engineer/documentation#keybinding) I see the use of the `keymap-scheme`, so I try:

```lisp
(define-key :keymap (getf (keymap-scheme
			   (find-mode (current-buffer) 'web-mode))
			  :emacs)
  "C-RIGHT" #'scroll-to-bottom)
(define-key :keymap (getf (keymap-scheme
			   (find-mode (current-buffer) 'web-mode))
			  :emacs)
  "C-LEFT" #'scroll-to-top)
```

and it doesn't work, the `keymap-scheme` doesn't exist.

**Comment by noloop** [comment]
So, I was wrong, the correct as I can see in the code is: `keymap-schemes`

I try:

```
(define-key :keymap (getf (keymap-schemes
			   (find-mode (current-buffer) 'web-mode))
			  :emacs)
  "C-c C-c" #'scroll-to-bottom)
```

and I get:

```
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 31809, child pid 31810
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 65.43 ms
Next version 1.3.4-05180ac
Loading configuration from #P"/home/noloop/.config/next/init.lisp"...
While evaluating the form starting at line 24, column 0
  of #P"~/noloop-refuge/next.d/init.lisp":
While evaluating the form starting at line 3, column 0
  of #P"/home/noloop/.config/next/init.lisp":
Error: we could not load the init file
Method error: "The name engineer.atlas.next.platform was not provided by any .service files".

Parent is shutting down, bye...

```

**Comment by noloop** [comment]
I believe that the bug is in the try use **(current-buffer)** when starts the Next, because I think that doesn't exist yet.

But how do I get the web-mode? I try:

`(set-key :next/web-mode:web-mode "M-;" #'scroll-to-bottom)`

I think that could use some hook and capture the web-mode of the current-buffer, so after call the `set-key`. But it smells bad.

Is there some reason for the `web-mode` doesn't be exported?

And what is?

```
Error: we could not load the init file
Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
```

**Comment by Ambrevar** [comment]
You must use `define-key`, not `set-key`.

Looking at
https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#keybinding,
you need to do something along those lines:

```
(defvar *my-keymap* (make-keymap)
  "Keymap for `my-mode'.")

(define-mode my-mode ()
  "Dummy mode for the custom key bindings in `*my-keymap*'."
  ((keymap-schemes :initform (list :emacs-map *my-keymap*
                                   :vi-normal *my-keymap*))))

(defun my-buffer-defaults (buffer)
  (dolist (mode '(proxy-mode
                  ;; ... More modes...
                  ;; Put your mode last so that it has highest priority.
                  my-mode))))

(defun my-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'my-buffer-defaults))

(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults)
```

> And what is?
>
> ```
> Error: we could not load the init file
> Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
> ```

It seems you have D-Bus issues, or that the next-gtk-webkit platform
port crashed for some reason.
Have a look at ~/.local/share/next/next-gtk-webkit.log, maybe this will
give you more information.

**Comment by noloop** [comment]
I see this, but I don't want create a new mode, I want re-write one key of the web-mode.

**Comment by Ambrevar** [comment]
Note that creating mode is a clean way to customize existing modes.

If you really don't want to create a mode, you can rebind keys in web-mode-hook.  The hook takes the mode as argument.

**Comment by noloop** [comment]
I get that the web-mode-hook doesn't exist.

**Comment by tviti** [comment]
There's also the `override-map`, although I'm not sure what the proper
protocol is for that (I've only ever used it for a keybinding that spoofs a
different key-event to the core, and hence I REALLY wanted to take
precedence over everything else).

**Comment by tviti** [comment]
> Error: we could not load the init file
> The hook NEXT::WEB-MODE-HOOK could not be found.

Also, it looks like `web-mode` isn't in the `next` namespace, which might mean that the hooks aren't in there either (on a phone so I can't try this atm). You might have to reference the `web-mode` package, i.e. something like `next/web-mode:web-mode-hook`.

**Comment by Ambrevar** [comment]
You are right about the namespace, but what I wrote was wrong: mode
hooks are called `enable-hook` and `disable-hook`.  But then you must
already have the instance at hand in order to configure the hooks, so
you'd rather directly configure the map.

Currently the best way to configure a mode's binding is to define a
custom mode on that override the bindings.  Note that a mode can inherit
from another and this way can override mode-specific slots.

Example:

```
(define-mode my-web-mode (web-mode)
  "Dummy web mode for the custom key bindings."
  ((keymap-schemes :initform (list :emacs-map ...
                                   :vi-normal ...))))
```

**Comment by noloop** [comment]
I try:

```
(defvar *noloop-keymap* (make-keymap)
  "Keymap for noloop-mode.")

(define-key :keymap *noloop-keymap* "C-p" #'scroll-to-bottom)

(define-mode noloop-mode (web-mode)
  "Dummy mode for the custom key bindings in *noloop-keymap*."
  ((keymap-schemes :initform (list :emacs-map *noloop-keymap*
                                   :vi-normal *noloop-keymap*))))

```

And Doesn't work. So I try:

```
(defvar *noloop-keymap* (make-keymap)
  "Keymap for noloop-mode.")

(define-key :keymap *noloop-keymap* "C-p" #'scroll-to-bottom)

(define-mode noloop-mode ()
  "Dummy mode for the custom key bindings in *noloop-keymap*."
  ((keymap-schemes :initform (list :emacs-map *noloop-keymap*
                                   :vi-normal *noloop-keymap*))))

(defun noloop-buffer-defaults (buffer)
  (dolist (mode '(web-mode
                  noloop-mode))))

(defun noloop-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'noloop-buffer-defaults))

(hooks:add-to-hook '*after-init-hook* #'noloop-interface-defaults)
```

Also doesn't work.

I think that it should be simple as emacs:

`(add-hook 'web-mode #'noloop-mode)`

With this all web-mode is used also the noloop-mode is called.

**Comment by Ambrevar** [comment]
You forgot to do something with the mode in noloop-buffer-defaults:

(defun noloop-buffer-defaults (buffer)
  (dolist (mode '(web-mode
                  noloop-mode))
    (pushnew mode (default-modes buffer))))

Agreed the configuration is a bit cumbersome at the moment.
See https://github.com/atlas-engineer/next/pull/484 which should make
things much simpler.

**Comment by noloop** [comment]
I changed:

```
(defvar *noloop-keymap* (make-keymap)
  "Keymap for noloop-mode.")

(define-key :keymap *noloop-keymap* "C-p" #'scroll-to-bottom)

(define-mode noloop-mode ()
  "Dummy mode for the custom key bindings in *noloop-keymap*."
  ((keymap-schemes :initform (list :emacs-map *noloop-keymap*
                                   :vi-normal *noloop-keymap*))))

(defun noloop-buffer-defaults (buffer)
  (dolist (mode '(web-mode
                  noloop-mode))
    (pushnew mode (default-modes buffer))))

(defun noloop-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'noloop-buffer-defaults))

(hooks:add-to-hook '*after-init-hook* #'noloop-interface-defaults)

```

And still doesn't work.

**Comment by Ambrevar** [comment]
Sorry for the delay.

I can't reproduce, the snippet you posted works perfectly for me.

Maybe this is #480? Can you try with another key binding known to work?

**Comment by Ambrevar** [comment]
Can you try on master again?  We've ironed out most key binding issues.
Besides, configuration got tremendously simplified.  We will update the documentation soon for the upcoming 2.0 release.

**Comment by Ambrevar** [comment]
Documentation updated!  Hopefully this should no longer be an issue.  Feel free to reopen if you've got more questions.
