### ISSUE TITLE
Function to kill all buffers

### ISSUE THREAD

**Issue by noloop** [atlas-engineer/next#490]
There is some function for kill all buffers?

Also would be interesting delete all history urls at once in one buffer.

**Comment by Ambrevar** [comment]
You can kill all buffers with

    C-x k M-a Return

Or, with the VI scheme:

    d M-a Return

> Also would be interesting delete all history urls at once in one buffer.

You mean the buffer history?  Indeed, we could add this functionality.

More generally, we could remove select tree nodes.  How do we remove a
node that's not a leaf though?

**Comment by jmercouris** [comment]
You can't remove a node that is not a leaf, the integrity of the history would be compromised. Now, you technically COULD remove a node that is not a leaf and then join it up to its closes parent or something, but then the history is no longer the true history.

**Comment by Ambrevar** [comment]
Our history-tree structure is a tree with varying arity.
When deleting a node, we can join the children to the list of nodes that
the parent of the deleted node has.  We can place the children in place
of the deleted node, to keep some integrity. The would still make some
sort of sense I suppose.

**Comment by noloop** [comment]
> C-x k M-a Return

What function is called? I need do this in init.lisp.

**Comment by Ambrevar** [comment]
`rpc-buffer-delete`.  It takes a buffer as argument.
To delete a list of buffers, you can do:

    (mapc #'rpc-buffer-delete buffers)

To delete all buffers:

    (mapc #'rpc-buffer-delete (alexandria:hash-table-values (buffers *interface*)))

**Comment by vindarel** [comment]
(mapc #'rpc-buffer-delete (alexandria:hash-table-values (buffers *interface*)))

I'd accept this as a function, I'd accept a PR.
