### ISSUE TITLE
How do I choose qtwebengine over webkitgtk?

### ISSUE THREAD

**Issue by elais** [atlas-engineer/next#492]
Hi. Didn't know where the best place to ask this was so I did so here. How do I switch which port I use?

**Comment by Ambrevar** [comment]
Hi,

you can customize the platform port by setting the `+platform-port-command+` variable.

For instance, in your `~/.config/next/init.lisp` you'd write

```lisp
(in-package :next-user)

(setf +platform-port-command+
      "~/common-lisp/next/ports/gtk-webkit/next-pyqt-webengine")
```

If the executable is in your PATH, it's enough to only provide the base name.

**Comment by elais** [comment]
Thanks Ambrevar!

When you say the executable do you mean the qtwebengine executable? I'm using guix and I'm wondering if I can just add the definition for qtwebengine that's in the nonguix repo. If not will I have to write a package definition to add pyqt-webengine as well?

**Comment by jmercouris** [comment]
He in fact does mean the qtwebengine executable. You only need to point Next to the executable via your init file as specified above. It could be anywhere on your system. It does not need to be installed via Guix or anything.

**Comment by elais** [comment]
Awesome, thanks to both of you for your helpful answers.

**Comment by jmercouris** [comment]
No problem :-) best of luck!

**Comment by Ambrevar** [comment]
Note that Guix only packages webkitgtk (and as such the gtk-webkit
platform port) for now.

**Comment by glglwty** [comment]
A note on using qtwebengine on nix:
```
nix-shell -p python3 python3Packages.dbus-python python3Packages.pyqtwebengine  --run "QT_PLUGIN_PATH=/nix/store/pfsm8mmw5vi2b7xfavlkawl9yqal71ak-qtwayland-5.12.6-bin/lib/qt-5.12.6/plugins next"
```
