### ISSUE TITLE
Issues related to using Next with high zoom.

### ISSUE THREAD

**Issue by Drainful** [atlas-engineer/next#494]
Having used Next on a hi dpi screen (I am really enjoying it), I have found a 2 problems that arise when operating at high zoom levels (tested on versions 1.3.4 and master):

1. SCROLL-TO-TOP and SCROLL-TO-BOTTOM only take you a portion of the way across the page when at high zoom.
2. When at high zoom and scrolled down on a page, link hints above a certain height are squished into one point. The greater the distance you have scrolled down the page, the lower the threshold. The included screenshots show this page at 2.0 zoom on a high dpi screen at increasing scroll amounts.

- https://ibb.co/1KP0nHZ -- top of page
- https://ibb.co/JdwR927 -- slightly scrolled, some hints are missing
- https://ibb.co/jT09fnx -- scrolled farther, more hints are missing
- https://ibb.co/sKBN0HS -- below this point there are no link hints

I was able to hack the scrolling functions to scale their distance based on zoom (https://gist.github.com/Drainful/dce0e5dcbb62e334e1e14a360b36f1fd), but I don't really understand the parenscript involved in displaying link hints, so I'm not sure how to fix that problem.

**Comment by jmercouris** [comment]
Thank you for your report! I'm glad you are enjoying Next! There are quite a few issues with the parenscript regarding link-hints. It was mostly copy/pasta'd from Lispkit (https://github.com/AeroNotix/lispkit). We are looking to rewrite that after doing some big architectural changes.

With regards to the link hints not appearing, it is also probably related to the zoom. So, basically we only try to calculate and draw link hints for the visible portion of the screen. If the visible portion of the screen is miscalculated because the screen is actually zoomed, then we won't draw hints for them.

My guess is that you would have to edit the following function in link-hint.lisp to be aware of zoom as you've already done for scrolling:
```
  (defun is-in-viewport (el)
    "Finds out if an element is in the viewport"
    (let ((rect (ps:chain el (get-bounding-client-rect))))
      (and
       (>= (ps:@ rect top) 0)
       (>= (ps:@ rect left) 0)
       (<= (ps:@ rect bottom) (or (ps:@ window inner-height)
                                  (ps:@ document document-element client-height)))
       (<= (ps:@ rect right) (or (ps:@ window inner-width)
                                 (ps:@ document document-element client-width))))))
```

I'm sorry, but that's all I can really say about that for now :-D

**Comment by Drainful** [comment]
Thanks for the help! It seems that the problem could be solved in lines 5 and 6 of the snippet you posted; when both zoomed and scrolled the zero positions of the links' bounding-client-rects are somewhere in the middle of the page for some reason. The zooming is handled by webkit through a style option, so I'm not sure how to calculate exactly by how much the zero point is shifted. As a personal solution I will just delete lines 5 and 6 which shouldn't cause a problem in most circumstances.

**Comment by jmercouris** [comment]
No problem!

You could also just always return true for `is-in-viewport`. It would create link-hints for every element and possibly be slightly slower.

**Comment by Drainful** [comment]
Yep that's essentially what I did, except that I left in the checks for the bottom of the page so that at least some link hints outside of the view would be prevented from rendering. Should I leave this issue open until the underlying issue is solved?

**Comment by jmercouris** [comment]
Yes, that would be ideal. We aren't likely to forget about it, but it will help people who won't necessarily look at closed issues.

**Comment by Ambrevar** [comment]
We can fix this properly now that we have FFI.

**Comment by Ambrevar** [comment]
Also see #152.

**Comment by Ambrevar** [comment]
Can you try again on master?  I seems that all your issues are fixed now! :)

- Load https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitEditorState.html.
- Zoom in a few times.
- scroll-to-top and scroll-to-bottom work as expected.
- Link hints seem to work as well at any position in the page.

**Comment by Drainful** [comment]
I'm having trouble running Next on master. `guix package -f guix.scm` fails in the `move-bundle` phase, and when running Next from source with `guix environment -l guix.scm` I get the error "Unsupported operation for this renderer." which seems to be invoked unconditionally at
 https://github.com/atlas-engineer/next/blob/master/source/browser.lisp#L780
Should I open an issue?

**Comment by Ambrevar** [comment]
Sorry for the delay.
guix.scm was broken for a couple of days, I've just fixed it.

- `guix pull`
- `guix ... build-scripts/guix.scm`

The result seems to have issues with the bindings.  Maybe some Common
Lisp libraries need to be updated in Guix.  I'll investigate.

**Comment by Ambrevar** [comment]
Found it!

The issue was in the outdated cl-str package.
I've updated it in Guix.

So re-`guix pull`, `git pull` the Next repository, then try again,
everything should work.

**Comment by Ambrevar** [comment]
@Drainful About the glib-networking, you can do as it suggests and install glib-networking to your user profile (you'll also need dconf).  However, Guix should wrap the Next executable and this should automatically be taken care of.  See the content of the "bin" folder in the Next Guix package, it should have a "next" wrapper
and a ".next-gtk-real" binary.

**Comment by Ambrevar** [comment]
Closing this (need to clean up the issues).  Feel free to reopen if you notice that some issues persist.

Feel free to ask if you need help building Next.
