### ISSUE TITLE
No display, white screen 

### ISSUE THREAD

**Issue by rowhit** [atlas-engineer/next#496]
**Describe the bug**
- I have installed the next browser using nix package manager as described here:
  - https://next.atlas.engineer/download
- However, when I launch the next. I see a white screen. I am not sure if I am missing any packages.

**Precise recipe to reproduce the issue**
- Install next using using latest unstable channel:
nix-env -iA nixpkgs.next

**Information**
- OS name+version: 
  - Ubuntu 19.04
- Kernel name+version: 
  - 5.0.0-36-generic
- Graphics card and driver: 
  - Radeon RX 550 640SP / RX 560/560X and 
  - driver=amdgpu
- Desktop environment / Window manager name+version:
  - Stumpwm
- Next version (from =M-x next-version= or =next --version=): 
  - 1.3.4
- How you installed Next (Guix pack, package manager, build from source): 
  - nix package manager
- SBCL version (if built from source): 
  - SBCL 1.5.3.nixos, Installed using nix package manager
- WebKitGTK+ / PyQt-Webengine version: 
  - Not sure, I am assuming that nix should have taken care of this.

**Comment by rowhit** [comment]
Installing the apt packages resolves the issue. Not sure why, because nix in general should be standalone package. 

```bash
sudo apt install sbcl libwebkit2gtk-4.0-dev default-dbus-session-bus glib-networking sqlite gsettings-desktop-schemas libfixposix-dev libgstreamer1.0-0 gir1.2-gst-plugins-base-1.0 xclip notify-osd
```

More details are available here:
https://github.com/atlas-engineer/next/tree/master/documents

**Comment by vindarel** [comment]
Glad it finally works.

> I have installed the next browser using _nix_ package manager as described here: 

so you meant Guix.

**Comment by Ambrevar** [comment]
I think Rohit meant Nix indeed.  I looked at the recipe, and it seems
that gsettings-desktop-schemas is missing.

I'll open an issue upstream.

**Comment by Ambrevar** [comment]
See https://github.com/NixOS/nixpkgs/issues/74258
