### ISSUE TITLE
Translation of changed keybinding in on-screen instructions

### ISSUE THREAD

**Issue by jellelicht** [atlas-engineer/next#498]
It would be amazing to have instructions such as the following:
https://github.com/atlas-engineer/next/blob/bfe7ce73e1f1f9d6b25cd4619c32f6befd2be62f/source/download-mode.lisp#L48

... be adapted when one is in e.g. `vi-normal-mode`. It this specific instance, it should be `(:code ": download-open-file")`.

**Comment by jmercouris** [comment]
Ah yes, indeed! In general introspection of the active mode and keybinding definition could use some nice information presented in the mini buffer. I would really enjoy something akin to which-key https://github.com/justbur/emacs-which-key.

**Comment by Ambrevar** [comment]
This can be fixed easily, since we already query the bindings in M-x.
The code is in the `object-string` method of `command`.
All we need is to extract it.

How shall we name the function?

A low-level Emacs function is `substitute-command-keys`.
I don't like the name much.  Does anyone know a higher-level function
with a better name in Emacs?

**Comment by jmercouris** [comment]
What does the function do? I don't quite understand.

**Comment by Ambrevar** [comment]
It returns the list of bindings associated to a given command.

**Comment by jmercouris** [comment]
How about the method `key-chord-bindings` which accepts a `command` object?

**Comment by Ambrevar** [comment]
Hmm... since it's not strictly a key-chord (it can be a mouse button),
then we could even shorten it to `bindings`.

That said, I'd like to know which name Emacs uses.  It's nice to reuse
names when they are good, it helps reducing the friction.

**Comment by jmercouris** [comment]
Is a key on a mouse not a key?

**Comment by Ambrevar** [comment]
It's often referred to as a "button", but I agree the distinction might
not be worth it :p

**Comment by jmercouris** [comment]
I would like to update this issue to note that Pierre has now implemented dynamic bindings in the help, there are still spots in the codebase though where text is hardcoded

**Comment by Ambrevar** [comment]
I think the main fix that's needed now is to update the bindings in M-x.
I know how to fix it (without killing the performance), will do as soon
as possible.

**Comment by Ambrevar** [comment]
I have the final fix for the minibuffer bindings in the `wip-command-display` branch but it needs a bit more polishing.

**Comment by Ambrevar** [comment]
Fixed with 81aee6d638781cb45accff99579a2291cbb92ddd.
