### ISSUE TITLE
https://next.atlas.engineer returns 502

### ISSUE THREAD

**Issue by cjp** [atlas-engineer/next#499]
https://next.atlas.engineer is returning 502, seemingly for all routes, including https://next.atlas.engineer/quickstart.

![Screen Shot 2019-11-28 at 4 40 37 PM](https://user-images.githubusercontent.com/161960/69832733-e1bed700-11fd-11ea-97f5-f7d270331508.png)

**Comment by jmercouris** [comment]
Fixed, thank you! Having problems with Clack :-D
