### ISSUE TITLE
Connection refused if init.lisp exists

### ISSUE THREAD

**Issue by azzamsa** [atlas-engineer/next#502]
**Describe the bug**

I get the following error:

`Could not connect to proxy server 127.0.0.1: Connection refused`

if I have `init.lisp` which contains:

``` cl
(in-package :next-user)

(defvar *my-keymap* (make-keymap)
  "My keymap.")

(define-mode my-mode ()
  "Dummy mode for the custom key bindings in `*my-keymap*'."
  ((keymap-schemes :initform (list :emacs *my-keymap*
                                   :vi-normal *my-keymap*))))

(defun my-buffer-defaults (buffer)
  (dolist (mode '(proxy-mode my-mode)) ;; <= Any mode that you want by default!
    (pushnew mode (default-modes buffer))))

(defun my-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'buffer-make-hook)
                     #'my-buffer-defaults))

;;(setf *start-page-url* "about:blank")

(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults)
(define-key :keymap *my-keymap* "S-m" #'switch-buffer)
```

But when I remove `init.lisp` the problem disappears.

**Precise recipe to reproduce the issue**

1) download next: https://next.atlas.engineer/static/release/next-linux-gtk-webkit.tar.lz
2) extract.
3) add `init.lisp` with the same contents as above.

**Information**

- OS name+version:  OS: Debian GNU/Linux 10 (buster) x86_6
- Kernel name+version: 4.19.0-5-amd64
- Graphics card and driver: Intel UHD Graphics 620
- Desktop environment / Window manager name+version: i3 version 4.17.1-2-g840208c2 (2019-08-30, branch "gaps") © 2009 Michael Stapelberg and contributors
- Next version (from =M-x next-version= or =next --version=): Next 1.3.4
- How you installed Next (Guix pack, package manager, build from source): mentioned above
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version:

**Comment by azzamsa** [comment]
Update:

The problem solved with changing:

``` diff
- (in-package :next-user)
(in-package :next)
```

Hope this report can reveal unintended behavior.

**Comment by Ambrevar** [comment]
I cannot reproduce.

Do you have a proxy running on the default address
which is socks5://127.0.0.1:9050?
If not, then it's normal it cannot connect! :)

You can customize the default proxy with something like

```lisp
(setf next/proxy-mode:*default-proxy*
  (make-instance next::*proxy-class*
                 :server-address "socks5://127.0.0.1:9050"
                 :whitelist '("localhost" "localhost:8080")
                 :proxied-downloads-p t))
```

**Comment by csfreebird** [comment]
I am new to Next. The above code(list below again) should be put into init.lsp file?

```lisp
(setf next/proxy-mode:*default-proxy*
  (make-instance next::*proxy-class*
                 :server-address "socks5://127.0.0.1:9050"
                 :whitelist '("localhost" "localhost:8080")
                 :proxied-downloads-p t))
```

**Comment by Ambrevar** [comment]
Note that it's `init.lisp`, not `init.lsp`.

The code snippet is only necessary if you want to forward the network
connections to a proxy, e.g. Tor.

**Comment by csfreebird** [comment]
> Note that it's `init.lisp`, not `init.lsp`. The code snippet is only necessary if you want to forward the network connections to a proxy, e.g. Tor.

Thanks. After correcting the file extension it works.

**Comment by Ambrevar** [comment]
Feel free to reopen if there are more troubles.
