### ISSUE TITLE
name suggestion

### ISSUE THREAD

**Issue by discipolo** [atlas-engineer/next#509]
how about "gnubrowser"?

**Comment by Ambrevar** [comment]
Why "gnubrowser"? :p
Next is not affiliated to the GNU project, so there is no reason it
should bear "GNU" in its name :)

**Comment by jmercouris** [comment]
The only other name I am personally considering is Nyx because it is the Greek goddess of the night https://en.wikipedia.org/wiki/Nyx.

It would fit in to our theme of ancient Greek mythology...

Anyways, thank you for sharing your thoughts! Feedback is always greatly appreciated!
