### ISSUE TITLE
Factor set-url-to-buffer back into set-url*

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#511]
See https://github.com/atlas-engineer/next/commit/53ad4fad1e1d716782d37b7e9e045b0eb7c83258.
I think we have too many set-url* functions.  I suggest we factor in set-url-to-buffer.

@vindarel ?

**Comment by vindarel** [comment]
I sent a PR, waiting for the release before merging.

**Comment by Ambrevar** [comment]
Fixed with #555.
