### ISSUE TITLE
Correct usage of buffer-make-hook

### ISSUE THREAD

**Issue by tviti** [atlas-engineer/next#513]
I was updating my `init.lisp` to work with the new hook mechanism introduced in
v1.4.0, and encountered an error when trying to use `remote-interface`'s
`buffer-make-hook`.

Minimal example + error message:
```
(defun test (buffer))
(next-hooks:add-hook (buffer-make-hook *interface*)
	(next-hooks:make-handler-void #'test))

;; There is no applicable method for the generic function
;;   #<STANDARD-GENERIC-FUNCTION NEXT-HOOKS:ADD-HOOK (11)>
;; when called with arguments
;;   (#<HOOK-BUFFER {1004E970D3}>
;;    #<NEXT-HOOKS:HANDLER-VOID {100878BB33}>).
;;    [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
;; See also:
;;   Common Lisp Hyperspec, 7.6.6 [:section]
```

Pretty sure that I'm just using `buffer-make-hook` incorrectly, and am wondering
what the correct way is. Am I supposed to be defining a class that inherits
`remote-interface` if I want to add a handler hei

**Comment by Ambrevar** [comment]
Since 1.4, hooks are now typed (which is great, since it will catch bad handlers
at compile time).

You need to use the typed handler:

``` common-lisp
(make-handler-buffer #'test)
```

Note that Next-specific make-handler-* functions are in the Next namespace, not
in `next-hooks`.

Does it make sense?

**Comment by tviti** [comment]
Makes sense! Thanks for your help, got it working now.
