### ISSUE TITLE
Adblock example in manual does not work

### ISSUE THREAD

**Issue by chrisboeg** [atlas-engineer/next#514]
**Describe the bug**

The adblock example [in the manual](https://next.atlas.engineer/documentation#resource-blocking-ad-blocking) does not work. I get an error when starting Next after adding the code.

To make it work, I have to add a (documentation) string as the first argument to the `define-mode` block so it looks something like this:

```
(define-mode my-blocker-mode (next/blocker-mode:blocker-mode)
  "my adblocker mode"
  ((hostlists :initform (list *my-blocked-hosts* next/blocker-mode:*default-host-list*))))
```

**Precise recipe to reproduce the issue**

- Install next from AUR
- Copy [adblock example code](https://next.atlas.engineer/documentation#resource-blocking-ad-blocking) from manual and add it to `~/.config/next/init.lisp`.
- Start next
- next won't start, gives error:

```
Next version 1.4.0
Loading configuration from #P"/home/cb/.config/next/init.lisp"...
 <WARN> [11:32:40] next utility.lisp (setf get-default) -
  The (setf (get-default ...)) and (add-to-default-list ...) forms are deprecated.
While evaluating the form starting at line 11, column 0
  of #P"/home/cb/.config/next/init.lisp":
Error: we could not load the init file
Error while parsing arguments to DEFMACRO NEXT:DEFINE-MODE:
  too few elements in
    (NEXT::MY-BLOCKER-MODE (NEXT/BLOCKER-MODE:BLOCKER-MODE)
     ((NEXT::HOSTLISTS :INITFORM
       (LIST NEXT/BLOCKER-MODE:*DEFAULT-HOST-LIST*))))
  to satisfy lambda list
    (NEXT::NAME NEXT::DIRECT-SUPERCLASSES NEXT::DOCSTRING NEXT::DIRECT-SLOTS):
  exactly 4 expected, but got 3
```
- Modify the adblock code by adding a (documentation) string as the first argument to the `define-mode` block in the example code
- now next will start

**Information**
- OS name+version: Arch Linux (up-to-date)
- Next version (from =M-x next-version= or =next --version=): 1.4.0
- How you installed Next (Guix pack, package manager, build from source): AUR

**Comment by jmercouris** [comment]
Thank you for your report! The documentation string should be indeed optional, it seems we've got a small bug with our macro, we'll get that fixed!
