### ISSUE TITLE
load-hook on buffer is only called when loading url via minibuffer

### ISSUE THREAD

**Issue by chrisboeg** [atlas-engineer/next#517]
**Describe the bug**

As far as I can see, the `load-hook`s on a buffer is only called when you try to load an URL via minibuffer. If you click on a link on a website, the `load-hook`s doesn't get called.

**Precise recipe to reproduce the issue**

Add this code to your init.lisp file:

```
(defun my-load-hook (url)
  (let* ((uri (quri:uri url)))
    (log:info "want to load url: ~a" url)
    url))

(defclass my-buffer (buffer)
  ((load-hook :initform (next-hooks:make-hook-string->string
                          :handlers (list #'my-load-hook)
                          :combination #'next-hooks:combine-composed-hook))))

(setf *buffer-class* 'my-buffer)
```

Now open next via a shell so you can monitor log output via stdout and try to load urls via e.g. C-l shortcut as well as by clicking links on websites. By monitoring the stdout from next, you should be able to see that the `(log:info ...)` only writes to stdout when visiting urls via the C-l binding, not by clicking on links on webpages.

**Information**
- Next version (from =M-x next-version= or =next --version=): 1.4.0
- WebKitGTK+ / PyQt-Webengine version: WebKitGTK+

**Comment by jmercouris** [comment]
Thank you for the report! We will look into it!

**Comment by chrisboeg** [comment]
@jmercouris I can see if I can figure it out and send a PR. I just want to have it confirmed that the load-hook is indeed supposed to be called in all cases where an url is called.

**Comment by jmercouris** [comment]
It is not supposed to be called, looking at the documentation string:

```
Hook run in `set-url' after `parse-url' was
processed.  The handlers take the URL going to be loaded as argument and must
return a (possibly new) URL.
```

I can't remember what all the hooks are, there may already be a hook for your use case. If not, there should be one.

**Comment by jmercouris** [comment]
I should note that did-commit-navigation and did-finish-navigation are invoked upon the loading of URLs, however they are not designed to be friendly to users. @Ambrevar may know more about a more appropriate hook.

**Comment by chrisboeg** [comment]
Ah, okay. I must be confused. I saw the hook in the "old-reddit-hook" example from the manual where "load-hook" is used to redirect reddit.com to old.reddit.com, and where old-reddit is actually only redirected to in the case of navigating to reddit via for example the minibuffer, not when clicking a reddit-link on a website. So if `load-hook` is actually not supposed to be used in such a case, then the manual should probably also not use it for such case.

**Comment by jmercouris** [comment]
The manual is a bit out of date... it used to be indeed possible. It is probably still possible, just with a different hook, OR the hook is insufficiently implemented. I am leaning towards insufficiently implemented because the commands set-url-* have hooks before and after, so having a special hook just for set-url seems unnecessary.

**Comment by chrisboeg** [comment]
Alright, I'll check them out. Is there perhaps anything on this issue you can imagine I could do to sort it out, or is it a complex issue needing a good overview of code base to be able to make the changes?

**Comment by jmercouris** [comment]
Difficult question to answer. I don't think one needs a complete overview of the code base to solve it, no. To sort it out, I would take a look at where the hook is defined and see if anyone depends on it being there. If nobody does then, perhaps making it as we described earlier may make sense (OR adding another hook).

**Comment by chrisboeg** [comment]
Alright, so the attack plan is:

- Check if there is a hook that gets called every time an url is to be loaded and that can deny the load (like load-hook)
- If there is no such hook:
  - Check if other parts of the code depend on load-hook functioning as it does current where it only gets called when you load an url via the minibuffer, not when clicking an url in a website.
    - If there is no hard dependency on it's current functionality that will break by making it getting called every time an url is to be loaded, make it happen so it always is called when an url is to be loaded
    - If parts of the code relies on load-hook functioning as it does now, then implement another hook that get's called before 

Is that how you envision it?

**Comment by jmercouris** [comment]
Absolutely correct! I should point out one other possibility though:

> If parts of the code relies on load-hook functioning as it does now, then implement another hook that get's called before

Could be:

> IF parts of the code relies on load-hook functioning as it does now, AND it would be too difficult to change, THEN implement another hook that get's called before

**Comment by chrisboeg** [comment]
Alright, I'll see what I can figure out.

**Comment by Ambrevar** [comment]
Maybe we can remove load-hook now that we have request-resource-hook.  That would remove the confusion.

**Comment by jmercouris** [comment]
After thinking about it a little bit longer, I actually just think it should be called `set-url-hook` as indicated by the TODO, I'm still OK with removing it though. Thoughts?

**Comment by Ambrevar** [comment]
I'll first test to be sure that everything can be move to request-resource-hook.

**Comment by jmercouris** [comment]
I would still like to really keep the hook in after thought. It could very well be useful to know if the action was initated by the set-url function

**Comment by jmercouris** [comment]
Renamed in: c17e3e1f

**Comment by Ambrevar** [comment]
Fair enough, be we need to update the examples that use load-hook with request-resource-hook.

**Comment by jmercouris** [comment]
OK!

**Comment by Ambrevar** [comment]
Re-opening to remember to do it.

**Comment by Ambrevar** [comment]
In 4a8b0e890a38fdebe1cd5a6f7a6f3032955e6487, I made it possible to compose hooks and to edit the requested URL from request-resource-hook.
This effectively makes it possible to hi-jack the requested URL when clicking on links for instance.  @chrisboeg This should answer your request ;)
