### ISSUE TITLE
Minibuffer obscures link hinting

### ISSUE THREAD

**Issue by impaktor** [atlas-engineer/next#520]
**Describe the bug**
When C-g to do link hinting, the minibuffer opens and hides the links. Scrolling to bottom of page, (getting the links higer on your screen) doesn't help if already at botom of page.

**Precise recipe to reproduce the issue**
- Go to *help* buffer of next
- Scroll to bottom
- Feel a burning desire to open the bottom link "customizing next"
- C-g to select it. 
- Observe: Now minibuffer opens and obscures the bottom links, so you can't see them, thus not knowing how to select them. If user beforehand knows the url, then you see it in the minibuffer, but usually (for me) this is not the case

**Information**
  "Version 1.4.0-5c8ffa4", AUR package.

**Possible mitigation**
- Either have the minibuffer push the buffer up by equal amount that minibuffer obscures
- Or allow option to not open minibuffer. In conkeror, minibuffer is inactive when link-hinting, instead it narrows down the hinted links as you type, and you can also move between them with C-n/C-p or arrow keys. Screenshot below after having typed "x":
![2020-01-17-140959_1600x900_scrot](https://user-images.githubusercontent.com/619390/72615065-14e73200-3934-11ea-9193-ef12d979aa15.png)

**Comment by Ambrevar** [comment]
Have you tested master recently?  Link hints can now be matched against URL, title, over the entire page, which largely mitigates this issue.

See also #354.

**Comment by impaktor** [comment]
Just compiled master. Yeah, I guess this addresses this issue, so could be closed. I have many other inputs/suggestions, but probably best in other issues.

**Comment by impaktor** [comment]
Although, for instance, test going to the issues page of next, and link-hint. It indexes a lot of stuff that doesn't seem to exist, and leavs out other that do (like github menu-buttons). I guess you address that in above mentioned issue.

**Comment by Ambrevar** [comment]
Yes.  Let's keep working on this in #354.
