### ISSUE TITLE
Next doesn't find functions `history-backwards`,`history-forwards`

### ISSUE THREAD

**Issue by impaktor** [atlas-engineer/next#523]
**Describe the bug**
If trying to bind a key to `history-backwards` or `history-forwards`, next claims the function isn't defined. (I've successfully re-binded(?)/re-bound many other keys to functions).

**Precise recipe to reproduce the issue**
Try to bind a key to above functions

**Information**
"Version 1.4.0-5c8ffa4", AUR package

**Comment by Ambrevar** [comment]
How did you do it?

Note that `history-forwards` belongs to the `next/web-mode` package, so
if you are not in it you must refer to it with  `#'next/web-mode:history-forwards`.

**Comment by impaktor** [comment]
OK, using the web-mode package specifier, next doesn't crash, but the keys doesn't seem to work.

```lisp
;;; Conkeror like key bindings
(define-key :keymap *conkeror*
  "B" 'next/web-mode:history-backwards  ; C-b (doesn't work)
  "F" 'next/web-mode:history-forwards   ; C-f
  "M-n" #'switch-buffer-next            ; C-x n / C-x right
  "M-p" #'switch-buffer-previous        ; C-x p / C-x left
  "c" #'copy-hint-url                   ; C-x C-w
  "f" #'follow-hint                     ; C-g
  "d" #'follow-hint-new-buffer
  "D" #'follow-hint-new-buffer-focus  ; M-l
  "g" #'set-url-current-buffer        ; C-l load url in current buffer
  "q" #'delete-current-buffer         ; C-x C-k
  "r" #'reload-buffer
  "C-x C-f" #'set-url-new-buffer
  "BACKSPACE" #'scroll-page-up
  "SPACE" #'scroll-page-down
  "C-v" #'scroll-page-down
  "M-v" #'scroll-page-up)


```

**Comment by impaktor** [comment]
Doh! I forgot two `#` in the fix above (as indicated by the syntax highligting). It works now. Sorry for taking your time.

**Comment by Ambrevar** [comment]
You forgot the leading `#`, which is the marker for functions in Common Lisp.
