### ISSUE TITLE
How to copy text from html page in buffer?

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/next#549]
I know there is a right click menu "copy".
I try to use M-w to copy text but it does not work.

**Comment by jmercouris** [comment]
Hi, what happens when you type M-x copy, does it work then?

**Comment by csfreebird** [comment]
It works, I did not know this way before.
But C-c is not emacs way, why use it?

**Comment by jmercouris** [comment]
C-c is the paradigm on almost every other interface in the world. You can of course rebind it to C-w and C-y if you wish.

**Comment by csfreebird** [comment]
I am new to Next, how to?

**Comment by jmercouris** [comment]
Please see the section here in the manual: https://next.atlas.engineer/documentation#keybinding
