### ISSUE TITLE
Ignore case or use smart case in search

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#554]
Currently search is case-sensitive which is counter-intuitive because the user must know the case in advance before searching.
For instance, if I look for "foo" anywhere, including at the beginning of a sentence, then I have to perform 2 searches: `Foo` and `foo`.

Smart case would be nice: if the input contains at least one upper case, be case sensitive, otherwise don't.

**Comment by jmercouris** [comment]
I agree with this change, it would be quite nice. The search code is quite difficult to modify to do this though, I did originally have case insensitive search in place and it would downcase the whole string to do the comparison as Javascript seems to lack a case insensitive way to find a substring. The consequence is that any matched strings were all in lowercase... I am sure there is a way around this, just making a note for when we decide to look at the implementation again.

**Comment by jmercouris** [comment]
I've added a case insensitive search. The implementation is fully functional, but it does have a side effect of making the entire text node one is matching against lowercase... In order to avoid this we would need to work with indices rather than split in our parenscript code. I've made a note of it in the commit log. In any case, this gives you a fully functional option for case insensitive search. Step by step :-) we refine and we improve the search!

c15c479
beac90c
8108540

**Comment by Ambrevar** [comment]
I'd suggest make it the default.

Regarding the cosmetic issue, I haven't looked at the code but what
about storing a pair (real-string lower-case-string), matching against
the second and display the first?

**Comment by Ambrevar** [comment]
The rationale for making it the default: the newcomers will not know the
detail about case sensitivity, so they will be startled that "something"
does not hit "Something".

Better than a keyword: implement smart case, i.e. if input has at least
one upper case letter, be case sensitive, otherwise be case insensitive.

**Comment by jmercouris** [comment]
> I'd suggest make it the default. Regarding the cosmetic issue, I haven't looked at the code but what about storing a pair (real-string lower-case-string), matching against the second and display the first?

Unfortunately, this would not work. Split produces an array of the resultant values (and split is case sensitive), not the indices, I have a rework on another branch.

**Comment by jmercouris** [comment]
> The rationale for making it the default: the newcomers will not know the detail about case sensitivity, so they will be startled that "something" does not hit "Something". Better than a keyword: implement smart case, i.e. if input has at least one upper case letter, be case sensitive, otherwise be case insensitive.

OK, will do

**Comment by jmercouris** [comment]
Please see branch case-insensitive-search
for details about how it is now implemented. Still a little bit more work to do, it doesn't find nested child elements, but I know why, I've set a TODO, hopefully I can hammer that out tomorrow

**Comment by jmercouris** [comment]
Ignore case is now default, new version that doesn't have strange side effect is now on master! We can implement smart case search a later a time, for now, a default of case insensitive should be OK. Smart case search doesn't require any parenscript, just some lisp to detect if any capital letters used or not, and then turn on case sensitivity

**Comment by Ambrevar** [comment]
I'll implement smart case, no problem.

One side effect seem to subsist: the yellow highlighted text is turned
to downcase: is it possible to preserve the text case?

**Comment by jmercouris** [comment]
It is possible to preserve the text case, but I wanted to actually have literally the query that the person was typing in. So if you search DOCument, that's how it'll appear highlighted as well

**Comment by Ambrevar** [comment]
I'm not sure I understand your rationale: we see what we've typed in the
minibuffer anyways, and we should highlight existing words, not modified
ones.

Besides, changing the case looks like we are creating typographical errors.
For instance, if I search "the", then the sentence "...blah. The browser..." will
be turned to "blah. the browser..." which looks like a typo.

**Comment by Ambrevar** [comment]
Something else: I suggest turning the keyword argument
`case-insensitive` to its positive form `case-sensitive`: we save some
characters and we avoid double-negations! :)

**Comment by jmercouris** [comment]
my rationale was that it would be easier to see THE highlighted when I typed in THE rather than something in a different case. it is just a single line to change the case to the original case, if you think that is better

sure it will look like a typo, but it will be easier to spot, in my opinion :-)

**Comment by Ambrevar** [comment]
But we already have the yellow frame to highlight the search.
If we don't preserve the case, then all matches will look like THE, thus
none of them will be easier to spot than another since they all look the same.

**Comment by jmercouris** [comment]
I changed case-insensitive to case-sensitive 

A good point about the case! I will see if I can fix that later today!

**Comment by jmercouris** [comment]
Et Voilà!

ccaab06

**Comment by Ambrevar** [comment]
Thanks!

I believe there was a mistake in the logic that I've fixed in
7e7d47db8dffaccedbe1252c7974f85e16a4b595.  Let me know it I'm wrong.

There is bug still: some highlighting is at the wrong place.

Recipe: on the help start page, search "the", press RETURN and see that
"y o" is highlighted in the following line:

> Customization is possible through the creation of a ~/.config/next/init.lisp file. From here you can override and redefine any of they of they of the functions by defining your init file as part of the :next package. For more information please see: customizing Next.

**Comment by jmercouris** [comment]
You are correct about that fix! thank you!

No idea about the "y o", spent a few minutes looking. That is a separate issue, and I think for now, for 2.0, the search is good enough. I would suggest let's file a separate bug report and work on it a latter time. Thoughts?

**Comment by Ambrevar** [comment]
Done, see https://github.com/atlas-engineer/next/issues/666.

**Comment by jmercouris** [comment]
thank you!
