### ISSUE TITLE
support emacs text edit way

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/next#557]
when type text in editor on web page, can support following keys:
1. C-@ Set the mark where point is, and activate it
2. M-w copy selected text
3. C-w Kill ("cut") text between point and mark.
4. C-f Move point N characters forward
....

It's basic and important features, hope will support it later.

**Comment by jmercouris** [comment]
Hello, yes, a good idea! To confirm, you are talking about `<input>` and `<textarea>` boxes as they appear on HTML forms?

**Comment by csfreebird** [comment]
yes, it's what I mean.

**Comment by Ambrevar** [comment]
The quick workaround is to implement "edit field in external editor".  Qutebrowser supports this.

Later we can implement full-fledged editing, maybe leveraging Lem.

**Comment by Ambrevar** [comment]
Closing this in favour of #112.
