### ISSUE TITLE
Release 1.5?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#559]
Now that we've got a handful of useful fixes and features in, shall we release 1.5 before dealing with the big FFI change?

I might have 1 or 2 more fixes waiting here, will see.

**Comment by jmercouris** [comment]
That sounds good to me! :-)

**Comment by csfreebird** [comment]
I would like to try ASAP

**Comment by travankor** [comment]
Does this fix the Fedora problem(#493)?

**Comment by Ambrevar** [comment]
Not yet :(

**Comment by Ambrevar** [comment]
@jmercouris Anything you'd like to land before 1.5?
My last wish is to add the export macro.

**Comment by jmercouris** [comment]
Please do not add the export macro as it will make my merge even more difficult :-D
I suggest we do it after the FFI things are landed back on master. I think that from my end, I am OK for 1.5! :-)

**Comment by jmercouris** [comment]
Unless of course you are willing to help with some of the merge operations ;-)

**Comment by Ambrevar** [comment]
Fair enough :)

**Comment by Ambrevar** [comment]
I've updated the ChangeLog.
1.5.0 is ready to be released for me.
Let me know if it's good for you.

**Comment by jmercouris** [comment]
It is good!

**Comment by jmercouris** [comment]
I don't believe anything is missing. Unless you want to get really technical and talk about the Minibuffer state-changed callback.

**Comment by Ambrevar** [comment]
Done.

**Comment by jmercouris** [comment]
Thank you!
