### ISSUE TITLE
Drop ring-buffer for cl-containers

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#560]
The LIFO ring-buffer is finally in cl-containers!

https://github.com/gwkkwg/cl-containers/commit/f4fb24a4be6737179afa7e6c4fc3ed4e70a38a07

Special thanks to @noogie13  for the hard work!
I wrote some tests, so that's good too.

I guess now it's safe to remove libraries/ring and use cl-containers instead.
Maybe we wait for the next Quicklisp release to make sure not to break everyone's installs.

**Comment by jmercouris** [comment]
Great news! I also think we should wait for the next Quicklisp release.

**Comment by Ambrevar** [comment]
The latest cl-containers is now in Quicklisp, so it's safe to proceed.

**Comment by Ambrevar** [comment]
I tested today, and cl-containers needed some last-minute adjustments to fit in Next.  I pushed them.  But since it's not on Quicklisp now, let's wait until the next release, end of April.

Also need to update the Guix package for cl-containers.

**Comment by Ambrevar** [comment]
Quicklisp has been updated on April 27th, we can proceed.
Will do as soon as possible.

**Comment by Ambrevar** [comment]
Fixed in 2b31b151f660c379a6e1a161194b25027fee893d.
