### ISSUE TITLE
Upstream cl-webkit

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#568]
If we are going to use it, it'd be nice to use a version that's available in Quicklisp + to avoid duplicate work.
Can we upstream the changes?

By the way, the https://github.com/atlas-engineer/cl-webkit repo does not allow for opening issues.

**Comment by jmercouris** [comment]
We can upstream the changes yes, I don't believe Joachim has any problems with that. He was very helpful when I last spoke to him.

**Comment by jmercouris** [comment]
I've also enabled issues.

**Comment by Ambrevar** [comment]
Thanks!

**Comment by Ambrevar** [comment]
See https://github.com/joachifm/cl-webkit/pull/37.
Once merged, we can delete atlas-engineer/cl-webkit.

**Comment by jmercouris** [comment]
I'd rather keep our fork so we can keep working on it freely, and then merge things onto cl-webkit source periodically

**Comment by Ambrevar** [comment]
We have full access to upstream now.
We can work on a branch there if we need to do anything dirty.

Having 2 repositories might create confusions.

**Comment by Ambrevar** [comment]
Quicklisp just updated cl-webkit (from Joachifm).  @jmercouris Do you still want to keep a mirror at atlas-engineer?  Then we need to make sure we are never out of sync! ;)

**Comment by jmercouris** [comment]
I would still like to keep a mirror, yes, I'll look into ways to keep it in sync, there must be some way :-)
