### ISSUE TITLE
C-x C-+ and friends not triggering zoom* commands

### ISSUE THREAD

**Issue by bzg** [atlas-engineer/next#569]
**Describe the bug**

With next 1.5.0 installed from guix on Ubuntu 18.04, hitting `C-x C-+` does not trigger the `zoom-in-page` command. The command is available and run correctly with `M-x`.

**Precise recipe to reproduce the issue**

Hit C-x C-+ and stare at the void.

**Information**
- OS name+version: Ubuntu 18.04
- Kernel name+version: IDK.
- Graphics card and driver: IDK.
- Desktop environment / Window manager name+version: i3
- Next version (from =M-x next-version= or =next --version=): 1.5.0
- How you installed Next (Guix pack, package manager, build from source): Guix
- SBCL version (if built from source): from distribution
- WebKitGTK+ / PyQt-Webengine version: I don't know.

**Comment by Ambrevar** [comment]
Weird, `zi` works in `vi-normal-mode`.  I'll look into it.

**Comment by jmercouris** [comment]
Have you tried similar keybinds like C-x C-=?

**Comment by bzg** [comment]
> Have you tried similar keybinds like C-x C-=?

Yes, with no luck. I confirm that `C-x b` works fine though, so it's not related to the `C-x` prefix directly.

`C-x 0` and `C-x -` don't work too, so this is not because of the shift key I use to hit `+` on a french keyboard.

I will test from another window manager and report.

**Comment by Ambrevar** [comment]
Fixed in b8a5e1dab3447290f58867303a8cedccc2c7bb64.

**Comment by bzg** [comment]
Great, thanks for the super-quick feedback and fix!

**Comment by Ambrevar** [comment]
You're welcome!

**Comment by bzg** [comment]
Quickly looking at the patch (I haven't tested it yet): isn't it the same problem with `-`? `C-x -` does not work it either.

**Comment by jmercouris** [comment]
We already handle `-` as HYPHEN

**Comment by Ambrevar** [comment]
It's "C-x C-HYPHEN".
"C-x HYPHEN" is missing: should we really add it?

**Comment by jmercouris** [comment]
I do not believe we should handle it as it is a single exception that will add complexity to the keybinding parsing code

**Comment by Ambrevar** [comment]
I think you misunderstood the question: the question is about simply
adding a the binding `C-x HYPHEN` as a synonym for `C-x C-HYPHEN`.

This would be consistent with `C-x C-=` and `C-x C-+`.

**Comment by jmercouris** [comment]
Ah, I see now, I was thinking about the feasibility of supporting `C-x -` as a syntactically valid key binding definition. In the above case, I don’t see why not as long as it does not cause any significant issues.

**Comment by jmercouris** [comment]
That is, `C-x HYPHEN` is OK with me

**Comment by bzg** [comment]
PS: I tried `C-x HYPHEN` because it was in the user manual.

**Comment by Ambrevar** [comment]
You are right, the binding was there, it's just that my fix was not
working properly.  Should be fixed now.

@jmercouris: This reminds me that we need to implement binding
translation à-la Emacs, e.g. so that "C-x s-+" gets automatically
translated to "C-x +" if unbound.

**Comment by jmercouris** [comment]
Yes, definitely :-)

**Comment by Ambrevar** [comment]
This is fixed since we've merged the keymap library.

**Comment by bzg** [comment]
Thanks - shall I install from the current `master` branch?  Or is this already available in a released version?

**Comment by Ambrevar** [comment]
It's only on master for now.  Next version is going to be 2.0, expect in the
coming weeks.  Stay tuned ;)

**Comment by Ambrevar** [comment]
By the way, now all special keys are lowercase (e.g. `escape`, `return`).  `-` is supported as in Emacs, so `C--` will do what you expect.

**Comment by bzg** [comment]
Great, thanks a lot for this!
