### ISSUE TITLE
no 1.5.0 deb package file

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/next#570]
since 1.5.0 has been released a few days ago, but still cannot dowload deb file for ubuntu installation.

**Comment by Ambrevar** [comment]
@vindarel Would you have time to generate it?

**Comment by vindarel** [comment]
I have to check, but I wouldn't be able to upload it, I have no more access to the servers.

**Comment by vindarel** [comment]
I built it. Where do I put it?

**Comment by Ambrevar** [comment]
Nice, thanks a lot!
@jmercouris?

**Comment by jmercouris** [comment]
Sorry I forgot to respond, you can upload the deb on the GitHub release and from there we can upload it.

**Comment by vindarel** [comment]
I don't have the rights to do that anymore.

**Comment by csfreebird** [comment]
how about uploading deb file here. At least I can try it.

**Comment by vindarel** [comment]
Here we are: https://framadrop.org/r/O2Jz5JuHmP#LP5IObTmMlSr9imVBL4xEaAQsKyQz24bloyKDC2OggA= (stays 30 days)

**Comment by csfreebird** [comment]
![image](https://user-images.githubusercontent.com/870486/75837847-0203c080-5e01-11ea-91c8-a4da33bc4424.png)

Cannot play video on youtube.com.

**Comment by csfreebird** [comment]
proxy in ~/init.lsp does not work now.

```
(setf next/proxy-mode:*default-proxy*
      (make-instance next::*proxy-class*
                     :server-address "socks5://127.0.0.1:8528"
                     :whitelist '("localhost" "localhost:8080")
                     :proxied-downloads-p t))

```

**Comment by csfreebird** [comment]
Thanks for your work on 1.5, I begin to enjoy this.

**Comment by Ambrevar** [comment]
You don't need flash to play Youtube videos.  I recommend you remove it.
Instead, install gstreamer and its plugins like gst-libav and gst-plugin-bad.

Thanks for reporting the proxy issue, I'll look into it.

**Comment by csfreebird** [comment]
> You don't need flash to play Youtube videos. I recommend you remove it.
> Instead, install gstreamer and its plugins like gst-libav and gst-plugin-bad.
> 
> Thanks for reporting the proxy issue, I'll look into it.

yes, I use flash to visit other video sites, youtube does not need flash.

**Comment by Ambrevar** [comment]
@jmercouris: Update on the .deb upload?

**Comment by Ambrevar** [comment]
I've uploaded the .deb to the home page.  Thanks @vindarel!
