### ISSUE TITLE
define-command does not redefine + creates doubles in M-x

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#575]
From the REPL, evaluating a  new definition of a `define-command` does not change the command of the running instance.

Besides, it's possible to create duplicate entries in M-x while it should not be.

**Comment by Ambrevar** [comment]
I wasn't able to reproduce today.  @jmercouris: Can you?
Maybe the issue is when we eval the command from next-user.  Needs more testing.

**Comment by jmercouris** [comment]
I'll try to do this as soon as I can, still hammering away on Qt :-)

**Comment by Ambrevar** [comment]
The bug may only appear when we restart the browser from the REPL.  Which we cannot do right now with the current state of FFI.

Let's leave this open and investigate once we can restart the browser from the REPL.

**Comment by Ambrevar** [comment]
@jmercouris The issue might actually be in the bindings: We don't bind against commands but against functions, so when we redefine a command, the bindings against the old function is keps.

I can think of 2 options:

- Use symbols instead of functions.  We need to be careful about the package though.
- Use command instead of functions.  This makes it easy to invoke the function with the right package.

We need to be careful about evaluation order during compilation.

**Comment by jmercouris** [comment]
I tried the following 3 times in the REPL:

```
(define-command hello-world () (echo "Hello World"))
```

I did not get triplicate M-x. I have experienced the behavior where the bindings are invoking an old version of the function. I don't see how that is possible, unless it is capturing a closer around them, because every time I evaluate my new command I get the following:

```
WARNING: redefining NEXT-USER:HELLO-WORLD in DEFUN
```

More investigation...

As per symbols instead of functions. Yes, we should always use symbols ' instead of #' just to give ourselves that expected behavior

**Comment by Ambrevar** [comment]
I think the duplication of commands is either solved, or an issue that
occurs on restart from the same REPL.  Nothing we can reproduce now, and
nothing to worry about for 2.0 (since it's not reproducible from a
binary).

About the rebinding issue: this is Common Lisp.
Try the following:

--8<---------------cut here---------------start------------->8---
CL-USER>  (defun foo ())
FOO
CL-USER>  (defvar *bar* #'foo)
*BAR*
CL-USER> *bar*
#<FUNCTION FOO>
CL-USER>  (funcall *bar*)
NIL
CL-USER>  (defun foo () (print 'BOOM))
WARNING: redefining COMMON-LISP-USER::FOO in DEFUN
FOO
CL-USER>  (funcall *bar*)
NIL
CL-USER> *bar*
#<FUNCTION FOO {52DD66FB}>
CL-USER> #'foo
#<FUNCTION FOO>
--8<---------------cut here---------------end--------------->8---

Functions are first-class _values_, not symbols.

I believe the fix is as we said, use symbols instead of functions.
We could type the bindings as follows:

```
(and symbol
     (satisfies #'fboundp))
```

to ensure that we bind against function symbols.

**Comment by jmercouris** [comment]
OK, so after binding the symbol and checking that the symbol points to a function in define-key, we should be good to close this?

**Comment by Ambrevar** [comment]
Yes, so it's a 1-2 liner in input.lisp, + a big replace "#'" -> "#'" :)

**Comment by Ambrevar** [comment]
I'll send a pull request for this as soon as possible.

**Comment by Ambrevar** [comment]
Should be fixed now.
Let's remember this when Next can be restarted from the REPL.
