### ISSUE TITLE
Blank page when visiting URL 

### ISSUE THREAD

**Issue by Asalle** [atlas-engineer/next#576]
**Describe the bug**
When strarting next with `export $(dbus-launch) && ./usr/local/bin/next` I can see a blank screen on startup:
![Screenshot from 2020-03-02 15-23-21](https://user-images.githubusercontent.com/4975074/75684869-e92ccb00-5c99-11ea-924b-09718afd748c.png)
I assumed it's fine. Then I tried to access a URL, like `google.com` with `C-l` and still I saw nothing rendered in the window:
![Screenshot from 2020-03-02 15-20-25](https://user-images.githubusercontent.com/4975074/75684905-fcd83180-5c99-11ea-9655-ea7f30fff13c.png)
Then I tried to find out which version of `next` I use with `M-x next-version`. Autocomplete worked fine, but still - there was nothing to be seen:
![Screenshot from 2020-03-02 15-26-13](https://user-images.githubusercontent.com/4975074/75684997-2beea300-5c9a-11ea-8c0c-b523a7b3c0a3.png)

**Precise recipe to reproduce the issue**
1. Start next with  `export $(dbus-launch) && ./usr/local/bin/next`
2. `C-l` google.com 
3. See nothing.

**Information**
- OS name+version: Fedora 30
- Kernel name+version: 5.1.17-300.fc30.x86_64
- Graphics card and driver: GeForce GTX 1060/PCIe/SSE2, NVIDIA-SMI Driver Version: 430.34, CUDA Version: 10.1 
- Desktop environment / Window manager name+version: GNOME Version 3.32.2
- Next version (from =M-x next-version= or =next --version=): Next 1.5.0
- How you installed Next (Guix pack, package manager, build from source): tarball 
- SBCL version (if built from source): did not build from source
- WebKitGTK+ / PyQt-Webengine version: I assume the one that comes with the tarball, please let me know how can I find this out if it's not true.

**Comment by Ambrevar** [comment]
This sounds like #422.

Can you export WEBKIT_DISABLE_COMPOSITING_MODE=1 and report the output
you get in a shell?

**Comment by jmercouris** [comment]
Very fascinating that the bottom web-view renders, but not the top one. I wonder why that could be. The bottom one doesn't require any acceleration?

**Comment by Ambrevar** [comment]
It does not indeed, but I'm not sure why _all_ other buffer are blank:
should only be the web pages that demand hardware acceleration.

**Comment by Asalle** [comment]
> Can you export WEBKIT_DISABLE_COMPOSITING_MODE=1 and report the output
you get in a shell?

next did not start and I saw a warning in console: 

```
➜  export WEBKIT_DISABLE_COMPOSITING_MODE=1 && export $(dbus-launch) && ./usr/local/bin/next
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_US.UTF-8
Next version 1.5.0
Loading configuration from #P"/home/asalle/.config/next/init.lisp"...
 <INFO> [16:39:44] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-y9Rx7tXCaP">)
 <INFO> [16:39:44] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.1
 <INFO> [16:39:44] next port.lisp (run-program port) -
  Current directory: /mnt/opt/next/
 <INFO> [16:39:44] next port.lisp (run-program port) -
  Platform port path: /gnu/store/7kjkz38mryryyf8865m2gv08yz59pg66-next-gtk-webkit-1.5.0/bin/next-gtk-webkit
 <INFO> [16:39:44] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [16:39:44] next port.lisp (run-program port) -
  Platform port log file: /home/asalle/.local/share/next/next-gtk-webkit.log
<ERROR> [16:39:45] next start.lisp (start fun5) -
  Could not connect to platform port: /gnu/store/7kjkz38mryryyf8865m2gv08yz59pg66-next-gtk-webkit-1.5.0/bin/next-gtk-webkit
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
```

**Comment by Ambrevar** [comment]
Can you make sure all "next" and "next-gtk-webkit" processes are killed?
Then try again.

Is the "user namespaces" feature enabled in your kernel?
If not, you can try to extract the Guix pack to `/`, it should fix the
issue.

Else you can build Next from master, the new architecture does not have
any of the D-Bus / multiprocess issues.

**Comment by Asalle** [comment]
> Can you make sure all "next" and "next-gtk-webkit" processes are killed?
Then try again.

Same result.

> Is the "user namespaces" feature enabled in your kernel?

I looked in `/boot/config-<my kernel version>` and found `CONFIG_USER_NS=y`, so I assume it is enabled. 
Weird, but when I moved the whole `next` folder (including `usr` and `gnu` extracted from the tarball) it worked and I saw some getting started page and I could access various addresses.

![Screenshot from 2020-03-06 11-33-13](https://user-images.githubusercontent.com/4975074/76076010-4a0c1a00-5f9e-11ea-800c-5735c27c1768.png)

**Comment by Asalle** [comment]
If you don't mind, I'll close this issue

**Comment by Ambrevar** [comment]
Where did you move it?

**Comment by jmercouris** [comment]
I am OK with closing this issue, as it is now a deprecated issue (since you just built from source).

**Comment by Asalle** [comment]
> Where did you move it?

I moved the folder `next`, that contains folders `usr` and `gnu` (the ones that I got from unpacking the tarball) to `/`. So that I could start next like so: `/next/usr/local/bin/next`

**Comment by Ambrevar** [comment]
Seems like namespacing is working for you, so something else was wrong.
