### ISSUE TITLE
Remove prop line from .asd

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#579]
`next.asd` starts with

```
;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Base: 10 -*-
```

which prompts Emacs when I open it.  I don't believe this mode line is needed at all actually.  Can we remove it?

**Comment by jmercouris** [comment]
I don’t believe asd files are automatically correctly handled by Emacs without it, it could have been fixed a long time ago already and I just don’t know it. In Emacs -q do you get proper Lisp support?

**Comment by Ambrevar** [comment]
Yes :)

**Comment by jmercouris** [comment]
Then let’s remove it!

**Comment by Ambrevar** [comment]
Fixed in dc7762e3ad8f14b96738ff42665e241cc41eb0cc.
