### ISSUE TITLE
Remove trivial-features dep from .asd

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#580]
Can we remove

```
  :defsystem-depends-on ("trivial-features")
```

from next.asd?

**Comment by jmercouris** [comment]
I would like to if it is possible :-)

**Comment by Ambrevar** [comment]
It is, unless we want to specialize the .asd depending on the platform.
The specialization is gone on the `ffi` branch.

**Comment by jmercouris** [comment]
The specialization is no longer necessary since both the Qt and GTK port will work on macOS and GNU/Linux

**Comment by Ambrevar** [comment]
Fixed in 7a81a6d3a6aa737befd5f2734fc67a466cf15273.
