### ISSUE TITLE
Use local nicknames for Alexandria (and serapeum later)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#584]
Use `alex:` and `sera:` local nicknames instead of the lengthy `alexandria:` and
`serapeum:`.

Or simply `a:` and `s:`?

**Comment by jmercouris** [comment]
Alex and sera are preferred so that query-replace can actually find them. There will be many false matches with a: and s:, it also adds a bit of cognitive load when they are single characters.

**Comment by Ambrevar** [comment]
Fixed in 4f082076ff38ad79dd0e67ee3f0074798da53a55
and 6f6f2e47d84d3d86d5f9cd6371b0523cc9869ac1.
