### ISSUE TITLE
Restore certificate-whitelist-mode

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#585]
It's gone on master because we need some update to cl-webkit.

But anyways, the mode was implemented in a rather convoluted way because of how 1.5 was architectured.  We can now fully leverage CFFI to implement this properly.

**Comment by Ambrevar** [comment]
Also see #110, #296, #372.

**Comment by Ambrevar** [comment]
Restored!

Shall we make it part of the default modes?  I'd say yes.
@jmercouris?

**Comment by jmercouris** [comment]
I would hesitate to say yes only because I think default things should be supported by all renderers, other than that I have no objection :-)

**Comment by Ambrevar** [comment]
QtWebengine also supports it I think.

**Comment by Ambrevar** [comment]
I confirm that Qutebrowser can do the same thing we QtWebengine.

**Comment by jmercouris** [comment]
Great! Let’s do it then!

**Comment by Ambrevar** [comment]
Done in ceeb60a72657af8c2612c55d480400e80a21c95f.
