### ISSUE TITLE
Rename `interprocess-communication` to `renderer`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#587]
We now have an `interprocess-communication-gtk.lisp` file, and more -gi, -qt, -giqt to come.

The filename is deceptive however: this is not about IPC since we have only one process here, it's about interfacing with the web renderer and the GUI toolkit.
Ironically, Next 1.5 had 2 processes, so there it would have made sense to use the term "interprocess-communication" but we didn't :p 

This is why I suggest we rename the file to `renderer-gtk.lisp`.
Thoughts? @jmercouris

**Comment by jmercouris** [comment]
It really is still an FFI/remote process. That is the whole point behind the naming. Actually the cl-cffi-gtk forks a new thread (I am pretty sure), so it is a type of IPC. That said, the succinctness of renderer-gtk.lisp appeals to me. I will need to think about this one. I am OK with either, but I do think interproces-communication-gtk.lisp is clearer.

**Comment by Ambrevar** [comment]
GTK starts a thread that's inside the process.  This is why
"interprocess" is confusing, because it's all just happening within one
thread (which is the great benefit of this new architecture :p).

**Comment by jmercouris** [comment]
done!

**Comment by Ambrevar** [comment]
Shouldn't we also update the "ipc-" prefix to "renderer-"?

**Comment by jmercouris** [comment]
It is still communicating with a different process, just not a system level process, plus ipc is a short prefix

**Comment by Ambrevar** [comment]
What is a process?

Among computer users, a "process" is commonly understood as system-level
process.

IPC is unambiguously referring to "inter system-level process
communication".

This is not the right term here.

**Comment by jmercouris** [comment]
how about "ff" prefix, short for foreign function?

**Comment by Ambrevar** [comment]
Why not!
Let's sleep on it and decide in a little while.

**Comment by Ambrevar** [comment]
So what about `ffi`?  The benefit over `ff` is that it's a well-known acronym.

**Comment by jmercouris** [comment]
What do you mean? firefox?

**Comment by jmercouris** [comment]
I'm ok with FFI as well

**Comment by Ambrevar** [comment]
Fixed in f7f44bcefb139dd191952b7b1ec283139cd9351f.
