### ISSUE TITLE
TODO in Codebase

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/next#594]
I think we should just keep all TODOs at the top of file as you have very nicely done in keymap.lisp, otherwise they are quite distracting to me whilst coding. Thoughts @Ambrevar?

**Comment by Ambrevar** [comment]
I think keeping them at the right spot is beneficial: it gives immediate
context, it's less confusing, it's resilient to file changes
(e.g. moving a function to another file).

Anyways, most of them will disappear Real Soon©.

**Comment by jmercouris** [comment]
I like the copyright :-P

**Comment by jmercouris** [comment]
How about then keeping them just within the top of the function body? right below the DEFUN?

**Comment by Ambrevar** [comment]
Hmmm, why not, but what advantage does it give us?

**Comment by jmercouris** [comment]
I believe it will improve my sleep quality ;-)

**Comment by Ambrevar** [comment]
Of course this is important, but this does not rationally explain why we
should move TODO items to the top-level :p

**Comment by jmercouris** [comment]
There is no rational reason, I just like it that way :-D
