### ISSUE TITLE
Suggestion for the readme: Update for 2.0

### ISSUE THREAD

**Issue by defunkydrummer** [atlas-engineer/next#597]
The part:

`In this case, you’ll have to make sure the Quicklisp distribution is up-to-date or else future versions of Next might fail to build. In a REPL:`

Is also necessary when you want to run Next from source. Thus, it should be specified as a necessary step on the "Run from source" section.

**Comment by Ambrevar** [comment]
Thanks for the notice.

I've added a pointer in 6021e6d76c8f5fdfecb24fbd1f8c66d4c1b00f94 plus
some other tweaks.

All that said, the developer README surely needs some editing :p

**Comment by Ambrevar** [comment]
Should be more complete since 483b0a8b1fc35f439c0f6b0a845d8bc02fa340d5.
MANUAL is deprecated and soon to be removed.
