### ISSUE TITLE
Can't load Next because of missing symbol WEBKIT-NAVIGATION-POLICY-DECISION-GET-NAVIGATION-ACTION on source/interprocess-communication-gtk.lisp

### ISSUE THREAD

**Issue by defunkydrummer** [atlas-engineer/next#598]
When loading the :next system through quicklisp:

All systems load fine until hitting file `source/interprocess-communication-gtk.lisp`

Error:

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "WEBKIT-NAVIGATION-POLICY-DECISION-GET-NAVIGATION-ACTION" not found in the CL-WEBKIT2 package.
;   
;       Line: 279, Column: 93, File-Position: 12193
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/flavio/portacle/projects/next/source/interprocess-communication-gtk.lisp" {1002E19053}>
```
**Precise recipe to reproduce the issue**
(My QL dist had been updated, before proceeding) 

- Start SBCL instance 
- Quickload trivial-features
- Quickload prove
- Quickload next

**Information**
- OS name+version:
- Kernel name+version:
Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Lisp implementation/version (if built from source):
 SBCL is version 2.0.0

**Comment by Ambrevar** [comment]
You need the latest cl-webkit from https://github.com/joachifm/cl-webkit.

Master is quite experimental at this point, sorry about that :p

**Comment by Ambrevar** [comment]
The latest cl-webkit is now in Quicklisp (April 27th).  Closing.
