### ISSUE TITLE
Can't build on Arch using yay (autoreconf error)

### ISSUE THREAD

**Issue by kevindirect** [atlas-engineer/next#604]
I'm trying to install next with my package manager and it isn't working. I'm on arch and attempting to use yay to install it, I've ran into the same error with the git and non-git versions. I haven't been able to find anyone with the same problem. Here's the build error:

> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal -I config/m4 --output=aclocal.m4t
> Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
> autoreconf: failed to run aclocal: No such file or directory

It seems to me that my system either doesn't have or can't find "aclocal". It's not anywhere in the PATH. I'm not sure what it is so I don't know what packages to install or what else to try. I'd prefer not to build from source.

**Comment by kevindirect** [comment]
[Figured it out](https://groups.google.com/forum/#!topic/pure-lang/1FzaWyrGiZ0), I didn't have GNU automake. For some reason it isn't one of the build depdendencies in the next browser PKGBUILD.

**Comment by Ambrevar** [comment]
Next does not use autotools :p

There is a package in the AUR but it likely works only for 1.5.
If you want to build master, a new recipe is needed.  Thankfully master
should now be much easier to build.

**Comment by kevindirect** [comment]
Yeah the AUR package I'm using is version 1.40-2, last updated on 2020-01-08 20:17.
Ideally I like to run the latest version of a package, but I don't do manual package mangement unless I have to.
Thanks for the info.

**Comment by Ambrevar** [comment]
Please flag the AUR package as out of date so that the maintainers
update it:
https://aur.archlinux.org/packages/next-browser/

**Comment by GoliathLabs** [comment]
@kevindirect the build-devel metapackage is expected to be installed on your system as you build aur packages. Therefore there is no need for adding it to the makedeps.
Cheers,
Felix (maintainer of the AUR package of next)

**Comment by kevindirect** [comment]
Hey thanks for updating the package
[You mean this package in the aur](https://aur.archlinux.org/packages/meta-group-base-devel/)? I had no idea. It looks like I have everything in that metapackage except automake. I guess I never ran into a problem with this till now because I don't install many AUR packages. I appreciate the information

**Comment by GoliathLabs** [comment]
@kevindirect sorry, meant base-devel nvm
