### ISSUE TITLE
The Browser just freezes as soon as I type anything into the address bar

### ISSUE THREAD

**Issue by vineethkartha** [atlas-engineer/next#605]
**Describe the bug**
After opening the browser, I press Ctrl-l and in the address bar as soon as I type any character, it freezes
**Information**
- OS name+version: elementary OS 5.1.2 Hera
- Kernel name+version: Linux 5.3.0-40-generic
- Graphics card and driver: NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1)
- Desktop environment / Window manager name+version: GTK 3.22.30
- Next version (from =M-x next-version= or =next --version=): 1.5.0
- How you installed Next (Guix pack, package manager, build from source): Build from the source
- Lisp implementation/version (if built from source):  SBCL 1.4.5

**Comment by jmercouris** [comment]
Any information in stdout?

**Comment by Ambrevar** [comment]
@jmercouris: I'd like to re-add the question about the renderer version
in the GitHub template.  It can be valuable info in issues such as this one.

**Comment by Ambrevar** [comment]
By the way, you are right we could also ask the reporters to include
stdout! :)

**Comment by jmercouris** [comment]
I thought I had already re-added it? Interesting!

**Comment by vineethkartha** [comment]
> Any information in stdout?

Next version 1.5.0
 <INFO> [01:25:09] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
 <INFO> [01:25:09] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.131
 <INFO> [01:25:09] next port.lisp (run-program port) -
  Current directory: /home/vineeth/Downloads/
 <INFO> [01:25:09] next port.lisp (run-program port) -
  Platform port path: next-gtk-webkit
 <INFO> [01:25:09] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [01:25:09] next port.lisp (run-program port) -
  Platform port log file: /home/vineeth/.local/share/next/next-gtk-webkit.log
 <WARN> [01:25:09] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
 <INFO> [01:25:09] next session.lisp (restore-sexp-session form-fun-4) -
  Restoring (https://mirrors.gigenet.com/OSDN//storage/g/m/ma/manjaro-arm/rpi2/minimal/18.12.1/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz
             https://duckduckgo.com/?q=arrange+all+the+cables+on+your+desk&ia=web
             https://www.thepapyrusitineraries.in/tour-item/parambikulam-tour/
             https://raspberrytips.com/install-manjaro-raspberry-pi/)
 <INFO> [01:25:09] next minibuffer.lisp (echo form-fun-6) -
  "Loading global history of 52 URLs."
 <INFO> [01:25:09] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://mirrors.gigenet.com/OSDN//storage/g/m/ma/manjaro-arm/rpi2/minimal/18.12.1/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz."
 <INFO> [01:25:09] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://duckduckgo.com/?q=arrange+all+the+cables+on+your+desk&ia=web."
 <INFO> [01:25:09] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://www.thepapyrusitineraries.in/tour-item/parambikulam-tour/."
 <INFO> [01:25:09] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://raspberrytips.com/install-manjaro-raspberry-pi/."
 <INFO> [01:25:10] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://duckduckgo.com/?q=arrange+all+the+cables+on+your+desk&ia=web."
 <INFO> [01:25:10] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://mirrors.gigenet.com/OSDN//storage/g/m/ma/manjaro-arm/rpi2/minimal/18.12.1/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz."
 <INFO> [01:25:10] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://www.thepapyrusitineraries.in/tour-item/parambikulam-tour/."
 <INFO> [01:25:10] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://raspberrytips.com/install-manjaro-raspberry-pi/."
 <INFO> [01:25:10] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://duckduckgo.com/?q=arrange+all+the+cables+on+your+desk&ia=web."
 <INFO> [01:25:12] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://duckduckgo.com/?q=arrange+all+the+cables+on+your+desk&ia=web."
 <INFO> [01:25:12] next remote.lisp (resource-query-default buffer) -
  Buffer #<BUFFER {1008386CE3}> downloads https://mirrors.gigenet.com/OSDN//storage/g/m/ma/manjaro-arm/rpi2/minimal/18.12.1/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz
 <INFO> [01:25:12] download-manager native.lisp (cache :uri) -
  DOWNLOAD-MANAGER::URI: "https://mirrors.gigenet.com/OSDN//storage/g/m/ma/manjaro-arm/rpi2/minimal/18.12.1/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz"
  DOWNLOAD-MANAGER::ARGS: (:DIRECTORY #P"/home/vineeth/Downloads/" :COOKIES ""
                           :PROXY NIL)
  
 <INFO> [01:25:14] download-manager native.lisp (fetch download) - Downloading
  https://mirrors.gigenet.com/OSDN//storage/g/m/ma/manjaro-arm/rpi2/minimal/18.12.1/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz
to
  '/home/vineeth/Downloads/Manjaro-ARM-minimal-rpi2-18.12.1.img.xz'.

WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::REQUEST-RESOURCE) signaled an error: The value
                                                                "297815424"
                                                              is not of type
                                                                NUMBER
                                                              when binding SB-KERNEL::X.
 <INFO> [01:25:14] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://www.thepapyrusitineraries.in/tour-item/parambikulam-tour/."
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                  {1006496763}>:
  The value
    "297815424"
  is not of type
    NUMBER
  when binding SB-KERNEL::X

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006496763}>
0: (SB-KERNEL:TWO-ARG-= "297815424" 0) [external]
1: (SB-VM::GENERIC-=)
2: (NEXT::DOWNLOAD-REFRESH)
3: (NEXT::DOWNLOAD-WATCH)
4: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
5: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
7: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
8: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
9: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF09CED4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006496763}>> NIL T NIL)
10: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006496763}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100649670B}> NIL)
11: ("foreign function: call_into_lisp")
12: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting

**Comment by Ambrevar** [comment]
Thank you for the trace.

I believe you are hitting 
4ab494d7a4295c73b57eb8b7e271d9fa52917c53.

So this should be fixed on master.
You can try running 

``` sh
next --session nil
```

And the browser should start properly.

Or simply remove `~/.local/share/next/session.lisp`.

**Comment by vineethkartha** [comment]
> Thank you for the trace.
> 
> I believe you are hitting
> [4ab494d](https://github.com/atlas-engineer/next/commit/4ab494d7a4295c73b57eb8b7e271d9fa52917c53).
> 
> So this should be fixed on master.
> You can try running
> 
> ```shell
> next --session nil
> ```
> 
> And the browser should start properly.
> 
> Or simply remove `~/.local/share/next/session.lisp`.

Yes this did fix my problem. Thank you
