### ISSUE TITLE
Xdg base directory specification support

### ISSUE THREAD

**Issue by bijang** [atlas-engineer/next#606]
Stupid question probably, but is this supported, for config dot file allocation etc? Only thought of it when I saw emacs 27 is adopting it.

**Comment by Ambrevar** [comment]
Yes, the `uiop` library has a bunch of `xdg-*` functions and Next has
xdg-config-home and xdg-data-home.

**Comment by jmercouris** [comment]
We are ahead of the game! :-)

**Comment by bijang** [comment]
of course ! 
apologies if i were a serious hacker i wouldve known that

**Comment by Ambrevar** [comment]
I've pushed a fixed on master which makes Next obbey XDG_DATA_HOME properly.
