### ISSUE TITLE
Implement a status bar

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#608]
We need a status bar.

Having an echo area + status + minibuffer in the single widget makes for unavoidable race conditions.  This is not a code problem, it's a structural problem: we simply can't display multiple things at the same time.

In particular, the lack of status bar is a real hindrance for every-day use of Next since it fails to display the current URLs / modes properly.  For instance, it rarely displays properly which of VI-NORMAL or VI-INSERT is active.

Now that we have GTK bindings, adding a customizable status bar is trivial.

**Comment by impaktor** [comment]
I miss not being able to see index of buffer, i.e. `3/42` for third buffer of 42 open.

**Comment by Ambrevar** [comment]
Noted! :)

**Comment by Ambrevar** [comment]
See #582.

**Comment by Ambrevar** [comment]
See #665 .  @impaktor It lets you customize the status view.  Do you think we should make `3/42` the default?  I would say no, but it can be a nice example to add to the manual :)

**Comment by Ambrevar** [comment]
Closed with ac6eb9c94a1612957af722c65d64958e64862b09.
