### ISSUE TITLE
Rename the *-inspect commands

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#614]
"command-inspect" does not quite roll off the tongue... :p 

I suggest we rename those commands to the Emacs counterparts: describe-command, describe-variable, etc.

**Comment by jmercouris** [comment]
I had prefixed with `command-` so you could easily see all operations against command by typing `command` into the minibuffer, but the same cold be said about `describe-*`, so that is fine with me

**Comment by Ambrevar** [comment]
Also now the minibuffer has fuzzy-completion, so word order does not matter.

**Comment by jmercouris** [comment]
Ja woll!

**Comment by Ambrevar** [comment]
Fixed in 08d6f6117fd9f4dbf2d4254f61500f238ad49e5f.
