### ISSUE TITLE
Don't exit on init.lisp errors and report graphically

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#619]
When there is an error in init.lisp, Next does not start and nothing happens _graphically_.
It can be jarring to the users who would not think to start it from the shell.

**Comment by jmercouris** [comment]
I agree, it should probably attempt to restart itself with no init file and report to the user that there is an error in their init file

**Comment by Ambrevar** [comment]
Exactly.

**Comment by jmercouris** [comment]
Done!

See: 
5a730f8
fb91d5c
69c5683
d484b0c

**Comment by Ambrevar** [comment]
Works well, thanks!

**Comment by jmercouris** [comment]
no problem!
