### ISSUE TITLE
How to know next binary is gtk or qt?

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/next#620]
any commandline can check if the next pargroam installed on my ubuntu is gtk or qt?

**Comment by Ambrevar** [comment]
If you've installed 1.5, it's GTK :)

We are working on 2.0 which (hopefully) should allow the user to
explicitly choose between QtWebEngine and WebKitGTK+.
Stay tuned!

**Comment by csfreebird** [comment]
thanks. I am using 1.5 now.
