### ISSUE TITLE
Make sure C-button1 opens the clicked URL in a new buffer.

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#625]
Seems to be broken on master.

**Comment by Ambrevar** [comment]
Fixed in be2911ec266d90a7bc6d9dac80e20c94846194e0.
Made customizable in b4c323426989ff1aaab139db9ae254366d3b76a4.

**Comment by jmercouris** [comment]
Double yay!

**Comment by jmercouris** [comment]
`(* 2 'yay)`
