### ISSUE TITLE
Undefined behaviour in DECLAIM FTYPE DEFINE-SCHEME*

### ISSUE THREAD

**Issue by phoe** [atlas-engineer/next#629]
https://github.com/atlas-engineer/next/blob/3b804e89bda597dce98b2421d70c43760989b503/libraries/keymap/scheme.lisp#L37

This line states that each `&rest` argument of that function must be a list, as per [CLHS System Class Function](http://www.lispworks.com/documentation/HyperSpec/Body/t_fn.htm):

> The type specifier provided with `&rest` is the type of each actual argument, not the type of the corresponding variable. 

You seem to be calling `DEFINE-SCHEME` with a plist though, meaning an alternating list of symbols and values. From the example in the docstring:
```lisp
  (define-scheme \"my-mode\"
    scheme:cua (list
                \"C-c\" 'copy
                \"C-v\" 'paste)
    scheme:emacs '(\"M-w\" copy
                   \"M-y\" paste))
```
In that macro, after typechecking, all of the arguments are passed as-is to `DEFINE-SCHEME*`. This means that `scheme:emacs` is not a list, which violates the FTYPE proclamation, which is invalid Common Lisp and has undefined behaviour. I have become aware that it leads to errors in loading next on CCL - hence this bugticket.

**Comment by Ambrevar** [comment]
Good catch and excellent investigation, thanks!
It should be fixed in ce1ec572e574f396cba700f896e099a3fb73b93f, can you
confirm it works for you?

**Comment by phoe** [comment]
The `ftype` declaration seems consistent with the usage now. Thanks for the fix!

Will wait a day or two for the Freenode user `mitigate` to confirm whether that fixes their issue with loading next on CCL; if I don't give any lifesigns after that time, please feel free to close the ticket.

**Comment by Ambrevar** [comment]
I've fixed a couple more issues with CCL 1.12-dev.5.
CCL is good at catching type errors! :)

**Comment by Ambrevar** [comment]
Sadly Next does not start with CCL for me :(
The issue could be with the lower-level parts like cl-webkit or
cl-cffi-gtk, in which case we will need to wait for the QtWebEngine FFIs
to test.

**Comment by phoe** [comment]
That should be a separate issue, I think - attempting to run Next on CCL. I will close this one for the time being, since it was resolved.

**Comment by jmercouris** [comment]
The problem is in `cl-cffi-gtk`, at least on macOS. I did get it to work in previous versions on Linux.
