### ISSUE TITLE
Remove SQLite

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/next#630]
We only use SQLite currently for migrating old databases into SEXP our based format. I suggest we remove it to make our system simpler, and compilation easier.

**Comment by Ambrevar** [comment]
Agreed.
Users can always asdf:load-system sqlite in their config file if they
want to use this format.

To import other bookmarks from Chrome, Firefox, etc. the usual format is
HTML anyways, so no need for SQLite here.

**Comment by Ambrevar** [comment]
Done in 904efececc4eb515034e7a3b7320ff7bd6628372.

**Comment by jmercouris** [comment]
Yay! Thank you
