### ISSUE TITLE
Docs: custom search engines unsupported operation for this renderer.

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#634]
**Describe the bug**

The example on how to customize search engines [here](https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#searching-via-search-engine) results in Next failing to start.

**Precise recipe to reproduce the issue**

1) Use example
2) Start next

**Information**

- WebKitGTK+ | QtWebEngine version: webkitgtk 2.28

**Output when started from a shell**

```
Next version 1.5.0-eb783f06
Loading configuration from #P"/home/hector/.config/next/init.lisp"...
Unhandled NEXT::UNSUPPORTED-OPERATION in thread #<SB-THREAD:THREAD "main thread" R
                                                   {10005F8083}>:
  Unsupported operation for this renderer.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005F8083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<NEXT::UNSUPPORTED-OPERATION {1006C56ED3}> #IT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<NEXT::UNSUPPORTED-OPERATION {1006C
2: (INVOKE-DEBUGGER #<NEXT::UNSUPPORTED-OPERATION {1006C56ED3}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<NEXT::UNSUPPORTED-OPERATION {1006C56ED3}>)
4: (SB-KERNEL::%SIGNAL #<NEXT::UNSUPPORTED-OPERATION {1006C56ED3}>)
5: (ERROR NEXT::UNSUPPORTED-OPERATION)
6: ((:METHOD NEXT:FFI-INITIALIZE (NEXT:BROWSER T T)) #<unused argument> #<unused aument>) [fast-method]
7: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
8: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IM005DA0BEB}>)
9: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
11: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

**Comment by jmercouris** [comment]
Thank you for the report!

You have to inherit from gtk-browser rather than just browser as in the example. It actually depends on which renderer you want to use. Do you think that you could maybe update the documentation with a note? That would be greatly appreciated!

**Comment by Ambrevar** [comment]
In the near future (before 2.0) we need to have a single knob to
specify the renderer to use.

The user would only have to write, say, `(setf *renderer* 'gtk)`
then everything else would be taken care of.

In particular, we should have a way to configure the various classes
(window, buffer, etc.) in a renderer-independent way.

**Comment by Ambrevar** [comment]
Regarding the renderer-independent class configuration, I suggest the following:

```
(defclass my-browser (browser)
 ((search-engines :initform
                  (append
                   my-search-engines
                   (get-default 'browser 'search-engines)))))

(defclass my-gtk-browser (my-browser gtk-browser) ())
(setf *browser-class* 'my-gtk-browser)
```

The trick is to use multiple inheritance: my-gtk-browser inherits from
both the generic-user-defined class and gtk-browser.

**Comment by jmercouris** [comment]
Then we could just have the user literally extend *browser* without any additional steps. There is a problem though, if the user would like to have multiple extensions of *browser* that they switch between. It loses the explicitness in this way...

**Comment by jmercouris** [comment]
Actually scratch what I said, I think the multiple inheritance solution is the best for now, though I would like a little more time to think about it.

**Comment by Ambrevar** [comment]
Expanding on this, we could remove the *buffer-class*, *browser-class*,
etc.

Then rename the `buffer` class to something like `buffer*`.

Finally provide the non-starred classes that are defined dynamically,
e.g. for GTK:

(defclass buffer (gtk-buffer buffer*) ())

**Comment by Ambrevar** [comment]
For configuration, the user would be able to override those empty
classes (here `buffer`) directly.

This raises a warning in SBCL but as far as I understand it's perfectly
legal Common Lisp, it's even one perk of the language to be able to
redefine classes at runtime.  Any drawback I could be missing?

**Comment by hsanjuan** [comment]
I switch to the QT renderer (I think), but it seems the settings that have `defclass my-buffer (gtk-buffer)...` still work...

**Comment by Ambrevar** [comment]
How did you switch to the Qt renderer?
Considering keys don't really work in the Qt renderer at the moment, I suppose that you didn't actually switch to it ;)

**Comment by hsanjuan** [comment]
well I set `NEXT_RENDERER` to `qt` and it seemed to build qt things and things seem to work?

**Comment by Ambrevar** [comment]
I've fixed the build of next-qt in
ae42dfbf797a6e2de48deef9e074dce8917e5631.
I am making a separate executable (for now) to allow testing the very
unfinished next-qt without overwriting the working `next` (GTK) binary
all the time.

The bindings don't seem to work at all the the moment.
Most the the QtWebengine support is there I believe, only a few methods
regarding keyboard input are missing.  If you are interested in hacking
on this, you are welcome!
Otherwise I'm hoping to find time to finish this before 2.0.

**Comment by hsanjuan** [comment]
Hmm you are right. `next-qt` does not start for me (missing some lib) but I'm going to wait a bit before I give it a go and try to debug... we can close this though.

**Comment by Ambrevar** [comment]
For reference, you need at least

- qtbase
- qtwebengine
- qtwebchannel
- qtdeclarative
