### ISSUE TITLE
Class and renderer configuration

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#639]
Continuation of #635.

We need to fix our configuration architecture for the classes and the renderer,
mostly for these reasons:

- Be as simple as possible.
  Indeed, since classes are involved in entry level configuration, every line
  we can remove from the config is a line less to confuse the user.

- General-purpose configuration should not need to know about the renderer.

I can think of a few strategies:

1. Rename our current `buffer` class to `buffer*` (or find a better name), then
   replace `*buffer-class*`, etc. with an empty, user-facing class `buffer` that
   inherits from the actual implementation class.  This way the user can do

   ```lisp
   ;; init.lisp

   ;; Override Next's `buffer`:
   (defclass buffer (<buffer-implementation-class>)
     (user slots))
   ```

   For the user config, no need to create a new class and in particular, no need for the extra line
   ```lisp
   (setf *buffer-class* 'my-buffer-class)
   ```
   which is prone to trip newcomers.

2. With the above strategy, notice that the inherited class is not
   parameterizable because `defclass` is a macro, not a function.  Concretely,
   we cannot write
   ```lisp
   (defclass buffer (*lower-level-buffer-class-variable*)
     ...)
   ```

   And we don't want to expose the renderer here, so the user should not have to write
   ```lisp
   (defclass buffer (gtk-buffer buffer*)
     ...)
   ```
   with `buffer*` being our current `buffer` class.

   To mitigate this, one option is to introduce yet another class in Next:

   ```lisp
   ;; In renderer-gtk.lisp
   (defclass buffer-real (gtk-buffer buffer*) ()) ; TODO: Find a better name.
   ```
   Then we would expose

   ```lisp
   (defclass buffer (buffer-real) ())
   ```

   Finally, the user would only have to override this last class while specifying the
   `buffer-real` superclass which hides the renderer details.

   To sum up, we would have 3 classes for buffers + 1 per renderer:
   `buffer*`, `buffer-real`, `buffer` and `gtk-buffer`, `qt-buffer`.  The hierarchy would be

   ```
   buffer* -> gtk-buffer -> buffer-real -> buffer
          \                 ^
           \_______________/ 
   ```
3. Instead of introducing a new class in the previous strategy, we could expose
   our own `defclass-next` macro that expands the superclass parameter.
   I'm not leaning towards this option since the difference between `defclass`
   and `defclass-next` could trip both newcomers and experienced Lispers.

4. The above class juggling might be too convoluted.

   Actually we don't need `gtk-buffer` to inherit from `buffer`: they are
   semantically two different things.
   Instead, we could add an `ffi-buffer` slot to `buffer*`, then use some lower-level
   variable `*ffi-buffer-class*` that's set to `gtk-buffer` in `renderer-gtk.lisp` to know which ffi-buffer implementation to instantiate..

   This would require a few modifications to the code:
   - All ffi-* calls must be done over `(ffi-buffer BUFFER)` instead of `BUFFER`.

   - The `ffi-buffer` class needs a `buffer` slot which refers to the parent buffer.

   Reusing the first strategy, we would have the following class hierarchy for buffers:
   `buffer*` -> `buffer`.
   The renderer-specific buffer classes are separate from this hierarchy.

Thoughts?

**Comment by jmercouris** [comment]
I like where you are going with regards to simplifying the user configuration. I am however not very excited about introducing so much indirection into the codebase :-D

I have some ideas I am thinking about, that I will propose in this thread, one involving using a macro for users in the next-user package. Allow the user to specify everything via (defconfiguration ...) form, and leave everything the way it is currently in the program. We would only need to make the macro pretty smart, and should the user want full control and power (assuming they are more advanced), they can go ahead and use the existing techniques to define multiple classes that inherit from browser etc.

**Comment by jmercouris** [comment]
The idea is this: most beginner users only care about setting the value of some variables, or of making a couple little functions. So we provide them a very simple way to set some defaults:

```
(defconfiguration window
  ((status-buffer-height 30)))
```

In this case, they are saying they want to set the status buffer height to 30. They shouldn't need to care about any other details.

This macro will expand to:

```
(defclass user-window (gtk-window)
  ((status-buffer-height :accessor status-buffer-height
                         :type integer
                         :documentation "The height of the status buffer in pixels.")))
(setf *window-class* 'user-window)
```

In this case, the value of `gtk-window` would be determined dynamically, and the other features of the slot would be also determined dynamically by introspecting on the `gtk-window` class. This will prevent the user from having to rewrite the accessor, documentation, etc. I have already seen a couple issues of forgetting to rewrite the accessor.

I think this will be the simplest to implement with no changes to the codebase, as well as the simplest for the user. Thoughts?

**Comment by Ambrevar** [comment]
You are right about the slots: it's too easy to forget or mistype the
accessor and break everything.

I like your suggestion, it's hitting 2-3 birds with one stone.

The only question I have at the moment: how do we determine which
renderer class to expand to?  Globaly variable like `*renderer-window-class*`?
We might need a know to easily switch renderer.
Say, a function `(set-renderer 'gtk)` which sets `*renderer-*-class*`.

**Comment by jmercouris** [comment]
We could have a (set-renderer 'gtk) as a top level form in renderer-gtk.lisp, and that would definitely cover it!

I was thinking we could check for the existence of the class renderer-gtk, then check for renderer-qt, and so on until we find one that exists, that is then our renderer.

Either one is OK for me :-)

**Comment by jmercouris** [comment]
I'll try to work on the defconfiguration today, I'll probably have a basic version that we can slowly iterate on :-)

**Comment by Ambrevar** [comment]
Great!

**Comment by jmercouris** [comment]
Et voila!

```
(define-configuration browser
  ((autofills (list (make-autofill :key "Name" :fill "John Doe")))))
```

**Comment by jmercouris** [comment]
On Master:

```

(serapeum:export-always 'define-configuration)
(defmacro define-configuration (super &body slots)
  (let* ((name (intern (str:concat "USER-" (symbol-name super))))
         (configured-class (intern (str:concat "*" (symbol-name super) "-CLASS*")))
         (super (intern (str:concat (symbol-name *renderer-class*) "-" (symbol-name super)))))
    `(progn
       (defclass ,name (,super)
         ,(loop for slot in (car slots)
                collect (list (car slot) :initform (cadr slot))))
       (setf ,configured-class ',name))))
```

note we do not have to recreate accessors, I was wrong about that, found out the information on `#lisp`

**Comment by Ambrevar** [comment]
Tested and approved!
Thanks!

**Comment by jmercouris** [comment]
Please note, currently missing is the set-renderer form in the top level of GTK and QT, it would be `(set-renderer 'gtk)` or `(set-renderer 'qt)`. I didn't put it yet because it is just defaulted to GTK and I figured that is good for now.
