### ISSUE TITLE
Feature request: proxy support

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/next#64]
nEXT doesn't seem to know about proxies at all (I can't find the word in the source code). When you are in a network that doesn't allow Web access without a proxy, that's a show-stopper.

**Comment by jmercouris** [comment]
Hi, thank you for your feature suggestion! This is definitely on the to-do list, I haven't put it in the actual org todo list in the readme yet :D

There is a lot complexity in this as it involves specific work for each of the ports on MacOS/Linux, but I am confident it is something we can do!

**Comment by khinsen** [comment]
As a first step, platform-neutral proxy support (enabled via explicit user configuration) would be a great start. Getting the settings from system-level configuration on each platform would of course be even nicer, but it's also a lot of extra work.

I wonder if nEXT could reuse existing Lisp HTTP libraries with proxy support, such as [Drakma](https://edicl.github.io/drakma/), or at least borrow code from them?

**Comment by Ambrevar** [comment]
Proxy support has been added to Next 1.2.1.  You can try it out with the `%toggle-proxy` command (experimental, it will probably be replaced with a mode in the future).

Note that proxy is only support with gtk-webkit for now.  We plan to switch the macOS version to using qtwebengine in a coming release.

Feel free to re-open if you have any question or issue with the implementation.

**Comment by khinsen** [comment]
Thanks! Judging from a first quick test this seems to work fine.

**Comment by lisponly** [comment]
Is there a way to use a proxy auto-config (PAC) file?

If not, it would be a useful feature to implement.
