### ISSUE TITLE
`execute-command` performance severely diminished

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/next#640]
Not sure what is going on, but some recent commits resulted in a hugely slowed down version of `execute-command` for me.

Just making a note of it here, so that we can investigate.

**Comment by jmercouris** [comment]
I have found the commit with the problem:

89ea44e * Match against minibuffer entry display, not object-string.

if I revert this commit, performance is way better. Not sure why that would be...

**Comment by Ambrevar** [comment]
Don't revert the commit though, it fixes every other minibuffer! :)

I've noticed the same thing.  I'll investigate just now.

**Comment by jmercouris** [comment]
I won't revert :-D
maybe fuzzy search can be passed a :key argument, with a default value of #'object-string or something

**Comment by Ambrevar** [comment]
Got it, fix inbound.

**Comment by Ambrevar** [comment]
Done.

**Comment by jmercouris** [comment]
I see the memoization, very clever :-D. I don't think it is fully right though, what was the purpose of object-string and object-display? I thought object-display was to show the user, and object-string was for the purposes of matching? So that we could match against things that are not visible to the user in an easy way

**Comment by Ambrevar** [comment]
No object-string is for tab-completion or candidate copy (with C-w).

We fuzzy-match against object-display (what's actually displayed in the
minibuffer) so that we match against both URL and titles for instance.

**Comment by jmercouris** [comment]
aah! right! Then I close this issue, thanks!
