### ISSUE TITLE
Set default package to next-user?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#641]
I've recently overhauled the command line arguments.
We can now send multiple --eval expressions to a remote process.
The default package is cl-user, which means that running something like

```
next --remote --eval '(current-buffer)'
```

will fail.
The following works

```
next --remote --eval '(in-package :next-user) (current-buffer)'
```
but is more cumbersome.

The init file also default to cl-user, which has tripped many users in the past.

Shall we default command line evaluation to `:next-user`?  The init file?

**Comment by jmercouris** [comment]
I really like it. I would say let's do it, but we should make an important and large note that the init.lisp file will be executed from the next-user package, UNLESS otherwise specified by an in-package declaration, so that users are not confused why they are not able to access certain symbols without using double colon operator

**Comment by jmercouris** [comment]
I'll look into this today

**Comment by jmercouris** [comment]
One very long day later and this is complete :-)

The one thing I have not done is the "eval" usage to force next-user. I'm not sure exactly what that behavior should be or how the control flow should look.

Now on start and entry-point, and load-init-file the package is set to the next-user package. The function load-lisp now accepts a key package parameter where you can supply a package designator or a package directly!

**Comment by Ambrevar** [comment]
Great, thanks!

For `eval`: I think the "do what I mean" approach would be to be in the
:next-user package by default, but if the user does `--eval '(in-package
:foo)'` then the subsequent evals should be in :foo.

**Comment by jmercouris** [comment]
I believe that is quite difficult. We'd have to determine whether the eval changes the packages and back and forth. For example, should the user set :foo, but then set it back to :salmon we'd have to know that. I am of the opinion that we should leave eval the way it is, the user having to be explicit

thoughts?

**Comment by Ambrevar** [comment]
I think you misunderstood.

If I call

`next --remote --eval '(in-package :foo)'`

then *package* is set to the FOO package globally.  So all subsequent
--eval calls will happen in the FOO package.

Until we call in-package again.

There is nothing we need to remember manually.  We just need to set
*package* to (find-package :next-user) but I'm not sure how to do that.

**Comment by jmercouris** [comment]
to do that just let bind *package*, see load-lisp and how it accepts the key argument :package

**Comment by Ambrevar** [comment]
In the end, I tried to put

(in-package :next-user)

in entry-point (like I did a few days ago when I first tried).
And it works.  Don't know what I did wrong the first time.

Your PACKAGE parameter to load-lisp is still necessary since the current
package is not known when starting  from the REPL.

**Comment by jmercouris** [comment]
it is also convenient :-)
