### ISSUE TITLE
Font anti-aliasing is disabled?

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#642]
**Describe the bug**

Using Next, fonts are not smoothed. It would seem anti-aliasing is disabled.

I have it enabled in the system, explicitally set in .Xresources and fontconfig afaik (it should be the default there). I have tried both gtk and qt and see no differences... so after looking around for a bit I thought I may ask... any tips?

**Information**

- OS name+version: OpenSUSE Tumbleweed
- Desktop environment / Window manager name+version: i3
- Next version (from =M-x next-version= or =next --version=): Version 1.5.0-6868d9de
- How you installed Next (Guix pack, package manager, build from source): Source
- WebKitGTK+ | QtWebEngine version: Gtk 2.28

**Comment by Ambrevar** [comment]
How do you test this?

Can you reproduce with Epiphany?
I can't find smoothing-related options in 
https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitSettings.html.

**Comment by jmercouris** [comment]
Maybe we can use: https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitSettings.html#webkit-settings-font-size-to-pixels

to change the perceived sharpness of the text?

**Comment by hsanjuan** [comment]
I can reproduce it with Epiphany, but I wonder if it's really anti-aliasing or something more subtle like subpixel rendering or hinthing, or simply smoothing. It is really visible here on github... fonts in Next and Epiphany look rougher, particularly at normal font sizes. Zooming in the differences are less clear.

**Comment by Ambrevar** [comment]
To clarify, what are you comparing it with?  Firefox, Chrome?

Could you send a screenshot highlighting those differences?  I
personally don't notice any difference.

**Comment by Ambrevar** [comment]
John Mercouris <notifications@github.com> writes:

> Maybe we can use: https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitSettings.html#webkit-settings-font-size-to-pixels

I think this function only converts font dimension units.  Or am I mistaken?

**Comment by hsanjuan** [comment]
setting up xsettingsd and playing with different hinting modes in .Xresources has no effect.

I'm comparing against Firefox.

![image](https://user-images.githubusercontent.com/1027022/79043708-16f22180-7c01-11ea-8593-1da38e8f61bf.png)

**Comment by Ambrevar** [comment]
I confirm that I don't experience your issue.

If I understand it right, .Xresources won't have any effect on GTK3
applications (could be wrong here, please let me know).

What's your window manager?

Try installing dejavu fonts.
See your distribution documentation.
Otherwise, I found this which might help:

https://wiki.archlinux.org/index.php/GTK#Configuration_tools

In particular, check out this file:

$XDG_CONFIG_HOME/gtk-3.0/settings.ini

**Comment by hsanjuan** [comment]
I use `.i3` on OpenSUSE. Dejavu fonts installed. I have explicitally enabled antialiasing in gtk-3.0/settings.ini now without luck. I will keep looking, since this is not Next-browser and affects other applications we can close this, but thanks so much for looking into it.

**Comment by jmercouris** [comment]
about what I was saying earlier: we can use a large font size and then zoom out to make the text appear crisper

on another note, I have the same problem on macOS hidpi displays with the GTK renderer, maybe there is a setting or something we can compile into the app, it may be worth asking the WebKitGTK+ people

**Comment by hsanjuan** [comment]
Ok, openSUSE has a Yast2-fonts configuration thing and I selected the Roboto families as default (similar to Firefox) and made sure subpixel rendering, anti-aliasing and hinting were enabled and everything got fixed for me. Now I realized this was an obvious place to look :/ apparently default fontconfig settings were not really optimal.

**Comment by Ambrevar** [comment]
Thanks for the details! :)

**Comment by hsanjuan** [comment]
(this can be closed on my side, if you want to re-use the issue it for problems in hidpi displays feel free though).

**Comment by Ambrevar** [comment]
If anyone else complains about this, we will document it.
