### ISSUE TITLE
Keyup events not filtered while in minibuffer

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#643]
**Describe the bug**

Typing something in the minibuffer still lets Keyup events through to the current webpage.

You can see this here https://dmauro.github.io/Keypress/

**Information**

- Next from built from source at master
- WebKitGTK+ | QtWebEngine version: gtk 2.28.

**Comment by Ambrevar** [comment]
Indeed, good catch!  Actually even the modifiers are forwarded to the page when the
modifier is up.

I guess the fix is simple: don't forward when the minibuffer is up.

**Comment by Ambrevar** [comment]
Should be fixed in e82d5db996c2e905bb029e2e21381dc9a762e00a.
Let me know if it works for you.

**Comment by hsanjuan** [comment]
Thanks, works!
