### ISSUE TITLE
Can't input text in EXWM

### ISSUE THREAD

**Issue by mindlike** [atlas-engineer/next#645]
**Describe the bug**

Normal text is not getting through to the text input areas offered by Next. They just remain blank white. Input in webpages is fine, as are the keybindings like C-l.

When I switch from EXWM to XMonad, the issue goes away. 

I've tried toggling EXWM's char-mode and line-mode, with no luck.

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: Ubuntu 18.04.2 LTS \n \l
- Kernel name+version: #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020
- Graphics card and driver: 00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
- Desktop environment / Window manager name+version: EXWM 0.23
- Next version (from =M-x next-version= or =next --version=): 1.5.0
- How you installed Next (Guix pack, package manager, build from source): nix
- Lisp implementation/version (if built from source):
- WebKitGTK+ | QtWebEngine version:

Source: webkit2gtk
Version: 2.28.0-0ubuntu0.18.04.3

**Output when started from a shell**

WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_US.UTF-8
Next version 1.5.0
 <INFO> [02:17:39] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "/run/user/1000/bus">)
 <INFO> [02:17:39] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.4713
 <INFO> [02:17:39] next port.lisp (run-program port) -
  Current directory: /home/dan/.emacs.d/
 <INFO> [02:17:39] next port.lisp (run-program port) -
  Platform port path: /nix/store/grm4kjmjnglpvm8rybsp4jhk8cphb2g4-next-gtk-webkit-1.5.0/bin/next-gtk-webkit
 <INFO> [02:17:39] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [02:17:39] next port.lisp (run-program port) -
  Platform port log file: /home/dan/.local/share/next/next-gtk-webkit.log
 <WARN> [02:17:39] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
 <INFO> [02:17:39] next session.lisp (restore-sexp-session form-fun-4) -
  Restoring (https://github.com/atlas-engineer/next/issues
             https://news.ycombinator.com/
             https://github.com/atlas-engineer/next/issues
             https://news.ycombinator.com/)
 <INFO> [02:17:40] next minibuffer.lisp (echo form-fun-6) -
  "Loading global history of 2 URLs."
 <INFO> [02:17:40] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/atlas-engineer/next/issues."

**Comment by Ambrevar** [comment]
I'm also using EXWM 0.23, I cannot reproduce.

Are you using VI bindings?
Anything binding-related in your ~/.config/next/init.lisp file?

You might want to try master, many binding issues have been fixed.

**Comment by mindlike** [comment]
Thanks for the quick reply!

I'm not using VI bindings, and don't have a next config file.

All the bindings I've tried work fine. It's the normal text input that's broken.

I'll try master.

**Comment by mindlike** [comment]
The issue was having EXWM configured to use XIM. Removing the following from my startup script solves the issue.

```
# Uncomment the following block to use the exwm-xim module.
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim
```

**Comment by Ambrevar** [comment]
Do you experience the same issue with Epiphany or any other WebKitGTK program?

**Comment by mindlike** [comment]
Unsure, can't test that right now.

I just remove those lines, and now have `GTK_IM_MODULE=ibus`.

**Comment by Ambrevar** [comment]
OK, I think this is related to #324.
