### ISSUE TITLE
Build fail: :IRONCLAD not found

### ISSUE THREAD

**Issue by mindlike** [atlas-engineer/next#647]
**Describe the bug**

Got this while trying to build a fresh clone of master:

```
  Component :IRONCLAD not found, required by #<SYSTEM "next">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000518083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component :IRONCLAD not found, required by #<SYSTEM "next"> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* Component :IRONCLAD not found, required by #<SYSTEM "next">)
2: (INVOKE-DEBUGGER Component :IRONCLAD not found, required by #<SYSTEM "next">)
3: (ERROR ASDF/FIND-COMPONENT:MISSING-DEPENDENCY :REQUIRED-BY #<ASDF/SYSTEM:SYSTEM "next"> :REQUIRES :IRONCLAD)
4: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "next"> :IRONCLAD NIL)
5: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "next"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1004099FEB}>)
6: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
7: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
8: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {100408C073}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "next"> NIL)
9: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/COMPONENT:MODULE "next" "source"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {100409972B}>)
10: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
11: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
12: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {100408C073}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/COMPONENT:MODULE "next" "source"> NIL)
13: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "patches/patch-serialization"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10040993AB}>)
14: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
15: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
16: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {100408C073}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "patches/patch-serialization"> NIL)
```

**Precise recipe to reproduce the issue**

- fresh clone
- `make next`

**Information**

    OS name+version: Ubuntu 18.04.2 LTS \n \l
    Kernel name+version: #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020
    Graphics card and driver: 00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
    Desktop environment / Window manager name+version: EXWM 0.23
    Next version (from =M-x next-version= or =next --version=): 1.5.0
    How you installed Next (Guix pack, package manager, build from source): source
    Lisp implementation/version (if built from source): sbcl v2.0.2.nixos
    WebKitGTK+ | QtWebEngine version:

Source: webkit2gtk
Version: 2.28.0-0ubuntu0.18.04.3

**Comment by jmercouris** [comment]
Hello, thank you for the report!

Can you please try executing in a new Lisp REPL:

`(ql:quickload :ironclad)`

what happens then?

You might also try:

`(ql:update-all-dists)`


In your makefile, is the following set?:
```
NEXT_INTERNAL_QUICKLISP = true
```

If so, can you please try setting that to false, and making your own Quicklisp install?

Thanks in advance!

**Comment by mindlike** [comment]
Had to do several tweaks to get it going with my system QL, including removing the `--no-userinit` flag from `LISP_FLAGS` in the Makefile and manually installing deps from `next.asd`. At that point I realized my `LD_LIBRARY_PATH` wasn't set. Setting it to the `libs` dir to my user nix profile (which I had already installed next into) seems to have fixed the original problem.

**Comment by Ambrevar** [comment]
For Nix and Guix, you indeed need to tell your compiler (here SBCL) to
use your profile "lib" directory.

Your ~/.sbclrc needs somthing like:

```lisp
(export 'set-cffi-library-dirs)
(defun set-cffi-library-dirs (dirs)
  "Call this to set `cffi:*foreign-library-directories*' to DIRS."
  (when (ignore-errors (asdf:load-system "cffi"))
    (setf (symbol-value (find-symbol (string '*foreign-library-directories*)
                                     (find-package 'cffi)))

          (union (symbol-value (find-symbol (string '*foreign-library-directories*)
                                            (find-package 'cffi)))
                 ;; CFFI needs a trailing "/".
                 (delete nil (mapcar #'uiop:ensure-directory-pathname dirs))
                 :test #'uiop:pathname-equal))))

(set-cffi-library-dirs "~/.guix-profile/lib")
```

Then `make help` gives you an example command at the end of the right
invokation:

```sh
make next NEXT_INTERNAL_QUICKLISP=false LISP_FLAGS=
```

**Comment by mindlike** [comment]
Thanks!

I'm very excited for next, and spend a few days every few months trying it
again. Still a bit alpha for my use case, but I'll be back. Thanks for
continuing to push it!

**Comment by Ambrevar** [comment]
Thanks for the continuous interest then!
Please open issues and let us know which features are missing for you.
2.0 release is coming very soon!
