### ISSUE TITLE
Select a textbox with keyboard

### ISSUE THREAD

**Issue by lucasemmoreira** [atlas-engineer/next#649]
Hi! Apologies if this question has been answered previously.

I am new to this very nice browser, but I could not find a good way to reach the textboxes.
Is it possible to reach a textbox in a page using only keyboard? For example, I would like to go to the issue page in this repository and then, type for something without having to use the mouse to select where to start typing.
I tried using C-g but, I could only use it to access links.

I am using next 1.5.0 on Ubuntu 18.04

**Comment by jmercouris** [comment]
Hello, firstly thank you so much for the kind words! The answer to your question is yes, but not in 1.5.0, only on the master branch, so this feature will be landing with our next release!

**Comment by lucasemmoreira** [comment]
Great! Thanks! I will be closing this then.
