### ISSUE TITLE
GLib-GIO Errors

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/next#650]
I've noticed, latest commits result in:

```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1000638083}>:
  Problem running initialization hook GLIB::RUN-INITIALIZERS:
  Unhandled memory fault at #x203620FF22.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Skip this initialization hook.
  1: [ABORT   ] Exit from the current thread.

(SB-INT:CALL-HOOKS "initialization" (GLIB::RUN-INITIALIZERS LOG4CL-IMPL::INIT-HOOK) :ON-ERROR :ERROR)
0] 1
~/Work/Atlas/Next $ next
dbus[4859]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!

(sbcl:4859): GLib-GIO-CRITICAL **: 13:33:38.849: g_tls_client_connection_get_validation_flags: assertion 'G_IS_TLS_CLIENT_CONNECTION (conn)' failed
```

only sometimes though, possibly, probably, we'll need to put some `#-darwin` flags in the codebase, should everything be working as expected on Linux

**Comment by jmercouris** [comment]
Additionally:

```
(process:4864): GLib-GObject-WARNING **: 13:36:11.371: invalid unclassed pointer in cast to 'SoupCookieJar'

(process:4864): libsoup-CRITICAL **: 13:36:11.371: soup_cookie_jar_get_cookies: assertion 'SOUP_IS_COOKIE_JAR (jar)' failed
dbus[4874]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!

(process:4864): libsoup-CRITICAL **: 13:36:11.468: soup_cookie_jar_add_cookie: assertion 'SOUP_IS_COOKIE_JAR (jar)' failed

(process:4864): libsoup-CRITICAL **: 13:36:11.468: soup_cookie_jar_add_cookie: assertion 'SOUP_IS_COOKIE_JAR (jar)' failed

(process:4864): libsoup-CRITICAL **: 13:36:11.468: soup_cookie_jar_add_cookie: assertion 'SOUP_IS_COOKIE_JAR (jar)' failed

(process:4864): libsoup-CRITICAL **: 13:36:11.468: soup_cookie_jar_add_cookie: assertion 'SOUP_IS_COOKIE_JAR (jar)' failed

```

**Comment by jmercouris** [comment]
I can confirm that all errors appear after commit:

`7cce2df * @ Restore certificate-whitelist-mode.`

**Comment by Ambrevar** [comment]
Which version of glib do you run?  I run 2.60.  You might need 2.28 at least.

**Comment by Ambrevar** [comment]
I'm also seeing this line when I build the binary:


--8<---------------cut here---------------start------------->8---
; wrote /home/ambrevar/.cache/common-lisp/sbcl-2.0.2-linux-x64/home/ambrevar/common-lisp/next/source/renderer-gtk-tmpGW0QV22K.fasl
; compilation finished in 0:00:00.191

(sbcl:17776): GLib-GIO-CRITICAL **: 15:47:14.882: g_tls_client_connection_get_validation_flags: assertion 'G_IS_TLS_CLIENT_CONNECTION (conn)' failed
--8<---------------cut here---------------end--------------->8---

Everything works alright though.

I suspect I'm doing something wrong in renderer-gtk:

--8<---------------cut here---------------start------------->8---
(in-package :gio)
(define-g-flags "GTlsCertificateFlags" g-tls-certificate-flags
  (:export t
   :type-initializer "g_tls_client_connection_get_validation_flags")
  (:g-tls-certificate-unknown-ca 1)
  (:g-tls-certificate-bad-identity 2)
  (:g-tls-certificate-not-activated 4)
  (:g-tls-certificate-expired 8)
  (:g-tls-certificate-revoked 16)
  (:g-tls-certificate-insecure 32)
  (:g-tls-certificate-generic-error 64)
  (:g-tls-certificate-validate-all 128))
--8<---------------cut here---------------end--------------->8---

The type initializer may not be right.  Could be my sheer ignorance of CFFI.

**Comment by jmercouris** [comment]
Right, so the problems are not Darwin specific. I don't knkow about the type initializers, I'm sorry I can't offer any insight there.

To be clear: I see the same issues when making the binary, so we have the same problem/set of problems here. I'll try to investigate a little bit and see if I come up with anything.

**Comment by jmercouris** [comment]
I run:
glib2 @2.58.3_0+x11 (active)
glib-networking @2.60.3_0 (active)

**Comment by Ambrevar** [comment]
OK, the version is probably not the problem.  We simply need to read the
CFFI doc ;)

**Comment by Ambrevar** [comment]
Should be fixed in 4301212af2334d554147393bee0987dd3f3968eb.
@jmercouris Can you confirm?

**Comment by jmercouris** [comment]
I can confirm it fixes it! Yay!

Also, making the name -gtk and -qt in the asd breaks the system. Load a fresh lisp, and `(ql:quickload :next-gtk)`, it will fail unless there is something special about your ASDF. I've reverted the commit on my local machine, but have not pushed to master unless there is something I am missing here

**Comment by Ambrevar** [comment]
You are right, we need a slash.  I'll revert and try to fix the Guix
build system.

**Comment by Ambrevar** [comment]
Fixed.
