### ISSUE TITLE
Turn certificate-whitelist class into type

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#652]
Current our certificate-whitelist class has only one slot, `whitelist`.
Seems like a useless level of indirection.
I propose to define a `whitelist` type to be a list of strings and set the buffer's slot `certificate-whitelist` to be of that type.

**Comment by jmercouris** [comment]
OK!

**Comment by Ambrevar** [comment]
Done in e61e6df87d3760a3922a62b5a0800ca41ffcaa72.
