### ISSUE TITLE
Switching keymap scheme

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#656]
How do we switch keymap scheme in general?

For VI, we have a dedicated mode.  The mode is needed because we need some extra setups beyond setting the keymap scheme.

What about switching from CUA to Emacs and vice versa?

Suggestion 1:  Add a "switch-keymap-scheme" command which displays CUA, Emacs and VI.  In the case of VI, the `vi-normal-mode` command should be called instead of just setting the keymap scheme.

Suggestion 2: Add a cua-mode and emacs-mode.

I'd say that suggestion 1 scales better.

**Comment by jmercouris** [comment]
I like suggestion 1, it can also accept a key argument, so that it can be invoked non-interactively

**Comment by Ambrevar** [comment]
Actually I realized something today: the perk of using modes is that
they are displayed in the status line.

Without that, how would we know if we are using scheme:emacs?

Thus I'm leaning towards adding a trivial emacs-mode.  No need for a
cua-mode since it's the default.

**Comment by Ambrevar** [comment]
Thoughts on this?  Should I go ahead and add emacs-mode?

**Comment by jmercouris** [comment]
OK, I see no problem with that!

**Comment by Ambrevar** [comment]
Added with fdc12e85a07689f8a2a99d40a7238d2b4b777df0.
