### ISSUE TITLE
Slynk support

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#658]
It'd be nice to add an build option to replace Swank by slynk.

**Comment by Ambrevar** [comment]
Or simply documentation on how to add it in the init file, since Slynk users are probably advance Common Lisp users.

**Comment by jmercouris** [comment]
Could be nice indeed! I think the documentation should suffice, a build option might be confusing for package maintainers

**Comment by Ambrevar** [comment]
See discussion in #712.
