### ISSUE TITLE
Feature request: `set-url-current-buffer` (C-l) should set current url as first option

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#660]
I find myself wanting to edit the current url and it would be nice if the current url is the first option for C-l (given provided the list does not seem to have any relevant order).

By coincidence, I saw there is https://github.com/atlas-engineer/next/issues/416 but I think this would still be nice (as it does not need to setup a new keybinding for the new command).

**Comment by Ambrevar** [comment]
I think it's a good suggestion and an easy fix.

Note that we also have the minibuffer history (M-h) which shows the current URI first.

**Comment by Ambrevar** [comment]
Fixed in 8f1ad8d41a8124617cabddeb8ade1f3a793150d7.

**Comment by hsanjuan** [comment]
thanks so much!
