### ISSUE TITLE
Feature request: multiple windows

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#662]
It would be great if next can open in several windows.

(alternatively multiple buffers the same window in a emacs-style fashion).

**Comment by jmercouris** [comment]
C-x 5 2, should already work :-)

**Comment by hsanjuan** [comment]
ah Works For Me!

**Comment by hsanjuan** [comment]
Although shouldn't running `next` again behave like that and open a new window?

**Comment by jmercouris** [comment]
It is an option to open multiple instances of next that you can set, but they won’t share buffers, they’ll be separate applications

When you invoke Next via the command line and specify a URL it will make a new buffer with that URL rather than a new window

Does that make sense?

**Comment by Ambrevar** [comment]
Better: you can still run in single-instance mode and decide to open
external links in new windows.  For that, set the browser slot
`open-external-link-in-new-window-p` to t.

**Comment by hsanjuan** [comment]
But, if running `next` can tell the existing Next instance to open a new buffer with a new url, it could also tell the existing instance to open a new window in which buffers are shared like with `C-x 5 2` (unless passing in a new url)?

**Comment by jmercouris** [comment]
That’s correct :-) that’s what Pierre is saying, if you follow his advice that’s what will happen

**Comment by jmercouris** [comment]
If you just want a new window, you could just pass URL of about:blank and it will do that for you

**Comment by hsanjuan** [comment]
I understand now! Thanks!

**Comment by jmercouris** [comment]
no problem!

**Comment by edgar-vincent** [comment]
I hate to be the annoying guy, but what if I don't want external links to open in a new window, but I do want to open a new window from the shell/keyboard shortcut manually (something life `firefox --new-window`)?

**Comment by Ambrevar** [comment]
Would

  nyxt --remote --eval '(make-window)'

work?

**Comment by Ambrevar** [comment]
Note that the `remote-execution-p' browser slot must be non-nil.

Understand the security risk! ;)

**Comment by edgar-vincent** [comment]
I forgot to mention that I'd already tried that, but I get `Nyxt already started.` when I do.

**Comment by Ambrevar** [comment]
OK, thanks for reporting, I'll have a look later.

**Comment by Ambrevar** [comment]
It works for me.
If Nyxt reports "Nyxt already started", it probably means that you
didn't pass the `--remote` option.

Can you provide a precise recipe of the command you run?
Can you share you init.lisp file?

**Comment by edgar-vincent** [comment]
I've not idea why, but it works now. Somehow my local build of Nyxt seemed to have been interfering with the packaged version.

Thanks a lot!

**Comment by Ambrevar** [comment]
Glad to hear!
