### ISSUE TITLE
Freeze on right-click + paste in a form field

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#667]
**Describe the bug**

Next freezes on paste sometimes. I'm unsure about which clipboard it would paste from though.

**Precise recipe to reproduce the issue**

1) Copy something by manually selecting on emacs and clicking the copy icon
1) Right click on a form field (i.e. when editing labels in a repository, click on edit label and try to paste something in the color form field).
2 ) Everything freezes

I have also experienced this once where I used `xclip` to put something on the clipboard and then tried pasting with C-y or M-y on a issue description. Might be related to pasting from a specific type of clipboard (there are at least two on linux I think). Hopefully you can reproduce...

**Information**
- OS name+version: openSUSE tumbleweed
- Kernel name+version: 5.6.2
- Graphics card and driver: Intel
- Desktop environment / Window manager name+version: i3
- Next version (from =M-x next-version= or =next --version=): master
- How you installed Next (Guix pack, package manager, build from source): source
- Lisp implementation/version (if built from source): sbcl
- WebKitGTK+ | QtWebEngine version: webkit 2.28

**Output when started from a shell**

No relevant output, just freezes.

**Comment by hsanjuan** [comment]
Actually, Ctrl-C on the shell throws this, not sure if relevant though, but there seems to be some deadlock involved:

```
^CUnhandled SB-SYS:INTERACTIVE-INTERRUPT in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                    {1000618083}>:
  Interactive interrupt at #x7F40EB868F57.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000618083}>
0: ("bogus stack frame")
1: ((FLET SB-UNIX::BODY :IN SB-THREAD::FUTEX-WAIT))
2: (SB-THREAD::%%WAIT-FOR-MUTEX #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100731ACD3}>> #<SB-THREAD:THREAD "main thread" RUNNING {1000618083}> NIL NIL NIL NIL)
3: (SB-THREAD::%WAIT-FOR-MUTEX #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100731ACD3}>> #<SB-THREAD:THREAD "main thread" RUNNING {1000618083}> NIL NIL NIL NIL NIL NIL)
4: ((FLET "WITHOUT-INTERRUPTS-BODY-2" :IN SB-THREAD:JOIN-THREAD))
5: (SB-THREAD:JOIN-THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100731ACD3}> :DEFAULT NIL :TIMEOUT NIL)
6: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
7: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1005DA6C8B}>)
8: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
10: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

**Comment by Ambrevar** [comment]
This is https://github.com/atlas-engineer/next/issues/593 and yes, it's
been annoying me for a while.

Note that the issue does not happen when built with Guix.  I suppose due
due difference in the cl-cffi-gtk library.

We need to think of a working, this is a blocking issue.

**Comment by hsanjuan** [comment]
Should have searched existing issues better. Feel free to close as duplicate.

**Comment by Ambrevar** [comment]
Maybe we could customize the right-click menu to use our own paste
function to avoid this.

**Comment by jmercouris** [comment]
Are you sure it’s a problem with the version of the cl-cffi-gtk library? Are you able to bisect a commit at when the problem occurs?

**Comment by Ambrevar** [comment]
No, could be with cl-cffi too.
I can't think of other libraries that would matter here.

**Comment by hsanjuan** [comment]
> Maybe we could customize the right-click menu to use our own paste function to avoid this.

If that is possible...

I was under the impression that I triggered this using keys too and not only the mouse but I see that the paste shortcuts are not forwarded so probably not the case.

**Comment by Ambrevar** [comment]
My too actually.  But I don't know how that would be possible.
Need to find a recipe.

**Comment by Ambrevar** [comment]
Closing this in favour of #688 and #593.
