### ISSUE TITLE
Add slot introspection command

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#669]
For which classes? Probably
- `*buffer-class*`.
- `*window-class*`.
- `*browser-class*`.
- `*minibuffer-class*`.

Anything else?

Don't forget to print the slot accessors, type, initform.

**Comment by jmercouris** [comment]
probably dynamically determine the classes by do-symbols find those with earmuffs, and check if they are a class

**Comment by Ambrevar** [comment]
What about listing _all_ classes?

**Comment by jmercouris** [comment]
OK! That is easier :-)

**Comment by jmercouris** [comment]
and better!

**Comment by Ambrevar** [comment]
While we are at it, we can introduce the describe-function command.
And fix the display of describe-command.

**Comment by Ambrevar** [comment]
I'm on it!

**Comment by Ambrevar** [comment]
I've added `describe-class` and `describe-function`.
Need to add a `describe-all` so that the user can find slots without having to go through all the classes.

**Comment by jmercouris** [comment]
Yay! Very well done!

**Comment by Ambrevar** [comment]
Finished in 7f77d7f28ece68872ccd78665ca9a1f48c56f676.
`describe-all` is missing, but I think it's best to wait until we have multi-source support in the minibuffer.

The HTML/CSS is terrible, but I'm not the best one to fix it I'm afraid!  Any artist out there? :)

**Comment by jmercouris** [comment]
What would you like to draw?

**Comment by Ambrevar** [comment]
What?

**Comment by Ambrevar** [comment]
A rainbow butterfly of course!

**Comment by jmercouris** [comment]
and what color would you like for the body of the butterfly?

**Comment by Ambrevar** [comment]
For a rainbow butterfly, any color would do as long as it's white.

**Comment by jmercouris** [comment]
Seriously though, I don't understand what help you need :-D Making the describe functions look a little bit nicer or?

**Comment by Ambrevar** [comment]
The help buffer look ugly and the HTML structure is not consistent
between the various describe-* commands.

Nothing urgent though! :)
