### ISSUE TITLE
Unbound variable: *GLOBAL-MAP*, Class named APPLICATION-MODE not found

### ISSUE THREAD

**Issue by LaloHao** [atlas-engineer/next#67]
I'm just playing around, am i missing something?

My ~/.next.d/init.lisp
```lisp
(in-package :next)
(define-key *global-map* (kbd "Escape") 'evil-mode)

(defvar *evil-mode-map* (make-hash-table :test 'equalp))

(defun evil-mode ()
  (make-instance 'application-mode
                 :name "evil-mode"
                 :keymap *evil-mode-map*))
```

*document-mode-map* doesnt work either

**Comment by jmercouris** [comment]
Hi, I am sorry for the problems you are having! I hope we can figure it out together!

Firstly, I would just like to confirm, is your configuration being loaded at all? The config system has been updated to XDG specifications and should reside at ~/.config/next/init.lisp- or whatever xdg home for your account is

**Comment by LaloHao** [comment]
Thank you, i think the problem was with the binary, i had downloaded from the site, if i run from source i get no errors.

Now, i know this is another issue but can i ask why is my mode not working?
```lisp
(in-package :next)

(defvar *evil-mode-map* (make-hash-table :test 'equalp))

(define-key *evil-mode-map* (kbd "k") 'scroll-up)
(define-key *evil-mode-map* (kbd "j") 'scroll-down)

(defclass evil-mode (mode) ())

(defun evil-mode ()
  (make-instance 'evil-mode
                 :name "Evil-mode"
                 :keymap *evil-mode-map*))

(define-key *global-map* (kbd "Escape") 'evil-mode)
(define-key *global-map* (kbd "S-e") 'evil-mode)
```

Neither does Escape or S-e activates the mode

**Comment by lehmacdj** [comment]
You need to call `'add-or-switch-to-mode` to enable the new mode. Just creating an instance isn't enough to switch to the new mode. I had some difficulty with switching modes when I was working on [my evil-mode script](https://gist.github.com/lehmacdj/b3c897ab46af34574b2947f8dc4e937d) as well, but eventually decided to just overwrite the function `'document-mode` so that it would start out enabled.

**Comment by jmercouris** [comment]
Yeah, this is an issue, I wanted to make something akin to auto-mode-alist for nEXT (https://www.emacswiki.org/emacs/AutoModeAlist), but that is further down the line, first have to complete the tasks in release 0.08 which will make nEXT much easier to extend
