### ISSUE TITLE
MacPorts Portfile still at version 1.3.0

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/next#674]
With that shiny 2.0 label decorating recent issues, it seems a bit anachronistic to keep the macOS release at 1.3.

**Comment by Ambrevar** [comment]
Which macOS release are you referring to?

**Comment by jmercouris** [comment]
We have a 1.3.0 binary we last made, and I also think the port file on SOURCE is out of date. Both will be updated when we are ready for 2.0 :-)

**Comment by jmercouris** [comment]
In progress, I've submitted libfixposix to MacPorts, as soon as that is approved, I can submit Next as well :-)

https://github.com/macports/macports-ports/pull/6933

**Comment by jmercouris** [comment]
Both are now updated, just need to update the commit hash they refer to as soon as 2.0 is released, that and hopefully MacPorts port will work and be accepted

**Comment by khinsen** [comment]
I tried to update everything and rebuild Next, but the build fails. Log attached. 

[main.log](https://github.com/atlas-engineer/next/files/4552010/main.log)

**Comment by jmercouris** [comment]
Please try executing `portindex` in your ports directory and recreating it, also make sure you don't have a Next.app bundle in your `/Applications`, as that will cause the install to fail. Please let me know how it goes :-)

**Comment by khinsen** [comment]
Right, I had an `/Applications/Next.app` already. And now I have a shiny new one to play with, thanks!

**Comment by jmercouris** [comment]
Yay!

**Comment by jmercouris** [comment]
No problem!
