### ISSUE TITLE
Display bindings dynamically in the start page.

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#677]
By the way, C-x C-c is not correct by default now that we use CUA, it should be `C-q`.

**Comment by jmercouris** [comment]
We could certainly construct it dynamically instead of hitting our page for body:-)

**Comment by Ambrevar** [comment]
Will do!

**Comment by Ambrevar** [comment]
Done f2aa06d196675eb67cebb5164f9681089d01c01e.

**Comment by jmercouris** [comment]
Yay! Can you please explain why help needs to be loaded after web-mode? Are you compiling the contents?

**Comment by Ambrevar** [comment]
Because of binding references to web-mode functions.

**Comment by jmercouris** [comment]
Would it be possible to use the symbols and look up the bindings at runtime to avoid the file reordering?

**Comment by Ambrevar** [comment]
Same issue with symbols: web-mode is a different package, so if we
declare symbols before we load web-mode, then when web-mode gets
compiled it will raise a condition because it's _using_ `next` which
exports the same symbols.  (Remember the `modifiers` issue on Darwin?)

**Comment by jmercouris** [comment]
Ah, yes, I remember!
