### ISSUE TITLE
By default, ask whether to restore session or not

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#678]
Like Firefox! :)

A few users have asked me this question already, I suspect it might be a popular request.

It's trivial to implement: add another "restore session" function that prompts the user with the minibuffer.

Better: prompt which buffer to restore.

**Comment by jmercouris** [comment]
To clarify, on start-up  you would like it to ask: "would you like to restore your previous session" y/n?

**Comment by jmercouris** [comment]
completed with 4d13fa51

doesn't ask about individual buffers, but that can come later

**Comment by Ambrevar** [comment]
Excellent, thanks!
