### ISSUE TITLE
Undo / restore dead buffers error: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#679]
Possibly a bug in the order in which we run the GTK code when making buffers.

**Comment by jmercouris** [comment]
I can confirm this bug

**Comment by jmercouris** [comment]
I know the problem, we don't restore dead buffers properly. Complicated by the fact that ffi-buffer-make does not only return a buffer object, but just a gtk-browser object.

Probably should return two values...

**Comment by jmercouris** [comment]
one of a gtk-buffer, and one of the actual buffer

**Comment by jmercouris** [comment]
then we would be exposing internal details, the EASIEST solution for now would just be setting the URL again, but that is not a true reopening of the buffer

**Comment by jmercouris** [comment]
Really we would need an ffi-restore-buffer command... because the behavior will probably be renderer specific

**Comment by jmercouris** [comment]
On second thought, that will break many many things... for example the renderer specific history will be out of sync what is true for the view, perhaps for now it is good enough to just reopen the URL in a new buffer with the same modes etc

I'll push a fix for that, and we can think about the greater restoration in the future

**Comment by jmercouris** [comment]
I've fixed the issue, for now, but with a big caveat.

``` 
  ;; TODO: dead-buffer implementation is not ideal. We only reopen a
  ;; buffer with the same URL, we do not actually maintain history,
  ;; etc. We make a new buffer object and just set the URL to be the
  ;; same. Ideally we would have an ffi-buffer-restore function which
  ;; restores the view for a buffer object.
```

I'll open up a new issue to address this after 2.0

**Comment by jmercouris** [comment]
Created issue:

https://github.com/atlas-engineer/next/issues/701
