### ISSUE TITLE
Loading bar

### ISSUE THREAD

**Issue by MasonProtter** [atlas-engineer/next#68]
There should be some sort of visual indicator when a page is loading

**Comment by jmercouris** [comment]
Hi! Thank you for your interest in the project. It would definitely be nice to have a visual indicator the page is loading, but I am hesitant to extend the UI unless absolutely necessary, maybe it can be an inclusion as part of a "modeline" if such a thing will come to arise

**Comment by jmercouris** [comment]
This has now been officially implemented and is available in the latest release! :)

**Comment by jmercouris** [comment]
please let me know if you experience any further issues and feel free to re-open the topic, thank you!
