### ISSUE TITLE
Report what to do on certificate error

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#689]
At the moment Next only displays the TLS error on certificate error.
We need to tell the user to run `add-domain-to-certificate-whitelist`.

Should be trivial!

**Comment by jmercouris** [comment]
I believe this should be fixed with:

d35f504f
c93347d9
f66a29ce

can you please verify?

**Comment by jmercouris** [comment]
I can confirm the fix

**Comment by Ambrevar** [comment]
Sadly it should not spawn a new buffer, we should chagne the current
buffer or else the users will run the command in the wrong buffer :(

I'm trying to do it but it seems that the domain is automatically
reloaded after the load-failed-with-tls-errors signal is sent.

Working on it.

**Comment by jmercouris** [comment]
Yes, that's why I decided to just make a new buffer. It doesn't matter if they run the command in the new buffer, they will try that reload in the new buffer

**Comment by jmercouris** [comment]
Anyways, I see that you fixed it :-)

**Comment by Ambrevar** [comment]
No, it won't work: the certificate whitelist is per-buffer.  This could
be very confusing, which is why it's important that we remained in the
same buffer.

**Comment by jmercouris** [comment]
it opens up a new buffer, they see the issue, they add the certificate whitelist, they C-l to that URL again. Of course they could just go to the OTHER buffer and it wouldn't work... :-D, yes

**Comment by Ambrevar** [comment]
Doing `C-l` and retype the URL is not the familiar behaviour. I suppose most users would expect a reload or "history-backwards" to work.

  It's also confusing to leave behind a buffer with the certificate error.
"Forcing" users to a new buffer also deprives them from the former buffer history.

**Comment by Ambrevar** [comment]
I think I got it:

https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-load-failed

If load-failed is not handled, we will get the template error page.

**Comment by jmercouris** [comment]
that is true, but how do we handle it?

**Comment by Ambrevar** [comment]
Let's keep discussing this in #710.
