### ISSUE TITLE
Next sets the master device output volume - Linux

### ISSUE THREAD

**Issue by aykaramba** [atlas-engineer/next#691]
NOTE: I don't know the Linux sound system terminology, I hope plain english is descriptive enough.

DESCRPTION: Next video and sound playback sets the master sound volume of the system.

OS: Debian 10

NEXT: 1.5

AUDIO SERVER: Pulseaudio

MIXER: Pavucontrol

SOURCE OF INSTALL: Official deb package

NOTES: On other browsers, if I set the device output volume to 25%, all sound sources get mixed up / down to 25%.  On Next, all sound sources change the device output volume (master volume?) to whatever the user sets in the player or whatever the default for the player might be.

100% on good audio systems can be quite painful. 

EXPECTED BEHAVIOUR: The expected behaviour is to allow the source to set its volume to whatever it wants and leave the default device output volume alone as that should be controlled by the user.  It would also prevent surprises as no one expects this behaviour.

EXPECTED SOLUTION: It would be sufficient to learn that there is a config setting to change this, however, I suspect that the audio output is hard coded somewhere so I am filing a bug.  If this is a configuration issue, please post and close this issue.

Thanks.

**Comment by Ambrevar** [comment]
Thanks for your report!

I haven't heard of this before.  Actually Next does not deal with audio
at all.  Maybe WebKitGTK has some default behaviour that behaves the way
you are seeing it?

Can you reproduce this issue with Epiphany (GNOME Web)?

Could you test master and see if you can reproduce this issue?

**Comment by aykaramba** [comment]
Oh wow. You are correct, Epiphany does the same thing.  

Okay I will look into this further, clearly this is an issue with GTK.  Thanks for the hint.
