### ISSUE TITLE
Downloading file makes browser do not respond

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/next#693]
I tried to download file using mouse click and keyboard.
The browser no respond, and have to kill the browser and start it again.
Ubuntu 18.04 and next 1.5

**Comment by Ambrevar** [comment]
Indeed, this is not supported :(
I'm planning to add support for this for 2.0.  Stay tuned!

See also #688.

**Comment by Ambrevar** [comment]
Closing in favour of #688.
