### ISSUE TITLE
Dead-buffer implementation improvements

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/next#701]
dead-buffer implementation is not ideal. We only reopen a buffer with the same URL, we do not actually maintain history, etc. We make a new buffer object and just set the URL to be the same. Ideally we would have an ffi-buffer-restore function which restores the view for a buffer object so that we maintain all of the other information stored in the original buffer object.

**Comment by Ambrevar** [comment]
Fixed in 85f9ca3a44d0c0bc3436bc012a28180270e919f5, without even adding a new FFI function :)

**Comment by jmercouris** [comment]
I was hoping we could retain the initialize-instance as I really liked how that was set-up. How do you feel about passing a key argument to initialize-instance to decide whether to make the external view or the other set-up? That way we could still use initialize-instance instead of breaking apart into another function

**Comment by Ambrevar** [comment]
I haven't created a new function, I've moved the code from one place to
another.
I think the FFI code belongs to ffi-buffer-make.  Well, it has
"ffi" in it's name :)

Why would you want initialize-instance to have the code?  The problem
with this approach is that we can't re-initialize dead buffers.

**Comment by jmercouris** [comment]
If it accepts a key to have the alternate behavior, then we can reinitialize dead buffers... I'll think about it some more :-)

There is one other potential issue, will the "renderer history" not be incorrect? It may for example try to go back, but there is no actual back in the view

**Comment by Ambrevar** [comment]
The renderer history is only use as a means for optimization.
Indeed, when resurrecting dead buffers the renderer history will be
empty, but it won't break the history, it only requires refetching the
resources. I guess that's OK.

The proper way to fix it is the infinite buffer strategy:
https://github.com/atlas-engineer/next/issues/366

**Comment by jmercouris** [comment]
Yes, and that will be very cool for memory pressure as well!

**Comment by igoralmeida** [comment]
I get this all the time when testing stuff for my nx-notmuch thingy, which is basically a bunch of very minimal internal buffers. Is there anything I could do to avoid this?

**Comment by Ambrevar** [comment]
Sorry, what do you get all the time?  Can you detail the problem?

**Comment by igoralmeida** [comment]
Open nyxt, run a search, open a thread, move around, delete the thread buffer:

![Peek 2021-06-22 20-12](https://user-images.githubusercontent.com/40757/123011349-8ed7e200-d396-11eb-8aec-207b6ee1c753.gif)

After the error message, notice the prompt does not go away. I'm also pressing `[` just to show that the only buffers are now `*Help*` and the search.

**Comment by igoralmeida** [comment]
I just realized I can reproduce this without even loading my nx-notmuch extension, which suggests there might be something wrong with my build or my environment (exec xmonad directly from .xinitrc).

Simply opening the Manual and then deleting its buffer is enough to get WebKitJavascriptError 699.

**Comment by Ambrevar** [comment]
Indeed, should be fixed with 2.1.
