### ISSUE TITLE
macOS build uses X windows

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/next#705]
**Describe the bug**

A fresh install via MacPorts (commit a4d64480cd9d8ef077717887405d004d43baa6f3) yields a `Next.app` that opens windows in XQuartz. Not sure this is a bug, but since it's unusual for a Qt application, I considered it worth signalling.

**Comment by jmercouris** [comment]
That’s expected behavior, the macports variant is using GTK. The Qt bindings are still alpha.

**Comment by khinsen** [comment]
OK, closing!
