### ISSUE TITLE
Unexport implementation detail slots

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#707]
Classes have many slots with accessors like `downloads`, `startup-timestamp`, etc.
We should remove the accessors / readers / writers so that those slots don't get exposed to the user (e.g. in describe-slot).

**Comment by jmercouris** [comment]
Well then... it looks we should manually export the slot accessors in the package ;-)

**Comment by Ambrevar** [comment]
It's too bad `defclass` does not have an :export slot option.
Maybe time for a macro?

Otherwise let's see which of the exported and unexported slots are the
most numerous.

**Comment by jmercouris** [comment]
Could be time for a macro... wouldn't be too hard...

**Comment by Ambrevar** [comment]
Fix with 2a62ff33bcbfb5019bc0ec2c285dbe5c253163ba.
