### ISSUE TITLE
Add a --quit command line option?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#714]
At the moment, using --eval or --load automatically quits the browser after evaluation.

It could be useful to add a `--quit` command line option so that we can choose whether we want to quit or start the browser.
This would allow us to run a short code snippet after the init file has loaded and before starting the browser.

Thoughts?

**Comment by jmercouris** [comment]
This is a good idea! Can we release 2.0 without it? in my opinion yes. I think we are maybe letting in some feature creep :-D

**Comment by Ambrevar** [comment]
The trick is that adding a --quit flag would reverse the current behaviour of `--eval` and `--load`: instead of quitting by default, they would start the browser by default.

**Comment by jmercouris** [comment]
yes, I don’t think that’s a big problem, it could be “no-quit” or something if we want to keep the behavior the same

**Comment by Ambrevar** [comment]
Well, it's trivial to add! :)

**Comment by Ambrevar** [comment]
Done in  1a05260d50886d1c0d0e65183ad3a9d54d19326d.
