### ISSUE TITLE
Add C-space to the override-map?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#715]
Now that CUA is the default and that C-space runs `execute-command', should we add it to the override-map?
Should we leave M-x in the override-map?

**Comment by jmercouris** [comment]
if we added it, it would prevent someone in emacs mode from setting the mark though right? if so, I think M-x in the override map should be left- I think that individuals with CUA bindings are probably less likely to modify the keybindings to where the override map will be useful for them

**Comment by Ambrevar** [comment]
We could argue the other way around: M-x is not bindable for CUA users :p

**Comment by Ambrevar** [comment]
Fair enough, CUA users are less likely to need M-x.
Besides, the override map is configurable.

That said, CUA users are the users who are potentially not going to
change any settings: thus if they are told to use C-space to bring up
commands, this is also the "escape it all" binding that can get them out
of, say, application-mode.

This is why my vote is to keep C-space only in the override map and to
remove M-x.
Emacs users who want to use C-space can configure their override map to
use M-x instead.

**Comment by jmercouris** [comment]
Good points! Then let C-space be the default override map value :-)

**Comment by Ambrevar** [comment]
Done in dabd700e883701c8bdbf3fa2835a21fba73ae655.
