### ISSUE TITLE
Copy password: Tried to examine first-element from an empty queue.

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#719]
**Describe the bug**

`<ERROR> [18:49:07] In #<FUNCTION NEXT/WEB-MODE:PASTE>: Tried to examine first-element from an empty queue.` after copy password and M-y for pasting.

No error before that. It happens with several usernames on the same buffer.

(master).

**Comment by Ambrevar** [comment]
Good catch!
Should be fixed in 817223e050f5cce265780c98446cfcb9850dcef4.

(Note: cl-containers has a weird API that errors out when trying to
access empty queues.)

**Comment by hsanjuan** [comment]
It is a bit better, but in general copy-password is unreliable and quite a few times it does not seem to copy anything :S

**Comment by Ambrevar** [comment]
Did you have this issue before commit
2b31b151f660c379a6e1a161194b25027fee893d ?
