### ISSUE TITLE
C-w (copy current url) + M-y (paste) fails

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#721]
**Describe the bug**

Paste does not seem to work.

`<WARN> [10:19:49] JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: myurl: TypeError: undefined is not an object (evaluating 'activeElement1.value.substring')`

**Precise recipe to reproduce the issue**

1) C-w on a buffer (seems to work)
2) M-y on a different buffer (in a Github issue textarea for example)

emacs-mode, on 817223e0 from yesterday.

**Comment by jmercouris** [comment]
`M-y` paste has been similarly failing for me for quite some time. Not sure what it is :-) I'll try to look into it if I have a moment

**Comment by Ambrevar** [comment]
I can't reproduce.  Can you reproduce systematically?
Without init file?  (`--no-init`)

**Comment by Ambrevar** [comment]
Can you give a URL for which this fails?  I tried on this page.

**Comment by Ambrevar** [comment]
I can reproduce only when there is no active element.

**Comment by Ambrevar** [comment]
I've fixed the error message when trying to paste outside of an element
with a value:

5a383f6a488dd64cd3a1e822256b4a394e1cb706

**Comment by hsanjuan** [comment]
paste doesn't work for me at all now ? Particularly `copy-password` copies something but M-y doesn't paste. However if I paste in a different window the password is there.

**Comment by Ambrevar** [comment]
Oops!  My bad, should be fixed in 1afc63ceb5184b753a6556529ddb2470d52f2a6b.

**Comment by hsanjuan** [comment]
ok this seems to work now. Thanks!

**Comment by jmercouris** [comment]
I can also confirm that the fix works
