### ISSUE TITLE
next fails to load when adding define-configuration for minimal config for vi mode

### ISSUE THREAD

**Issue by honestSalami** [atlas-engineer/next#725]
**Describe the bug**
Adding the "minimal vi mode configuration" as described in the [manual](https://github.com/atlas-engineer/next/blob/master/documents/MANUAL.org#vi-style-bindings) to init.lisp crashes next.

**Precise recipe to reproduce the issue**
have this as you init.lisp file

(in-package :next)
(define-configuration buffer
		      ((default-modes (append '(vi-normal-mode)
					      %slot-default))))

**Information**
- Graphics card and driver: n/a
- Desktop environment / Window manager name+version: X window manager, dwm
- How you installed Next (Guix pack, package manager, build from source): built from AUR [next repo](https://aur.archlinux.org/packages/next-browser/)
- Information from command copy-system-information: command not installed

**Output when started from a shell**

Next version 1.5.0
Loading configuration from #P"/home/bruno/.config/next/init.lisp"...

; file: /home/bruno/.config/next/init.lisp
; in: DEFINE-CONFIGURATION BUFFER
;     ((NEXT:DEFAULT-MODES (APPEND '(NEXT::VI-NORMAL-MODE) NEXT::%SLOT-DEFAULT)))
; 
; caught ERROR:
;   illegal function call

; file: /home/bruno/.config/next/init.lisp
; in: DEFINE-CONFIGURATION BUFFER
;     (NEXT::DEFINE-CONFIGURATION NEXT:BUFFER
;      ((NEXT:DEFAULT-MODES (APPEND '(NEXT::VI-NORMAL-MODE) NEXT::%SLOT-DEFAULT))))
; 
; caught WARNING:
;   undefined variable: NEXT:BUFFER
; 
; caught STYLE-WARNING:
;   undefined function: NEXT::DEFINE-CONFIGURATION
; 
; compilation unit finished
;   Undefined function:
;     DEFINE-CONFIGURATION
;   Undefined variable:
;     BUFFER
;   caught 1 ERROR condition
;   caught 1 WARNING condition
;   caught 1 STYLE-WARNING condition
While evaluating the form starting at line 4, column 0
  of #P"/home/bruno/.config/next/init.lisp":
[31mError: we could not load the init file[0m
The variable NEXT:BUFFER is unbound.

**Comment by Ambrevar** [comment]
This manual is for the upcoming 2.0 (master).

If you want to consult the manual for 1.5, see

https://github.com/atlas-engineer/next/blob/1.5.0/documents/MANUAL.org

If you've got the time, I warmly recommend you give master a shot, it
includes many improvements.

Cheers!

**Comment by honestSalami** [comment]
oh, I see, I was using the wrong version XD
Thanks! I'll check out the latest version when I have some free time.
