### ISSUE TITLE
Document how to customize search-engines

### ISSUE THREAD

**Issue by tviti** [atlas-engineer/next#735]
**Describe the bug**

From where I stand, this kinda just looks like the documentation is lagging behind the source?

`MANUAL.org` claims that:

```
You can set the list of search engines in your init file:

(define-configuration browser
  ((search-engines (append (list '("yt"
                                   "https://www.youtube.com/results?search_query=~a"
                                   "https://www.youtube.com/"))
                           %slot-default))))
```

However, when attempting to use the above snippet by navigating to `yt lol`, the following error is thrown:

```
<ERROR> [16:02:18] In #<CLOSURE (LAMBDA (URL) :IN SET-URL) {10090895AB}>: There is no applicable method for the generic function
                                                                            #<STANDARD-GENERIC-FUNCTION NEXT:SHORTCUT (2)>
                                                                          when called with arguments
                                                                            (("yt"
                                                                              "https://www.youtube.com/results?search_query=~a"
                                                                              "https://www.youtube.com/")).

```

Passing a list of search-engine's as follows, works just fine though:

```common-lisp
(define-configuration browser
  ((search-engines (append (list (make-instance 'search-engine
						:shortcut "yt"
						:search-url "https://www.youtube.com/results?search_query=~a"
						:fallback-url "https://www.youtube.com/"))
                           %slot-default))))
```

**Precise recipe to reproduce the issue**

**Information**
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- How you installed Next (Guix pack, package manager, build from source):
- Information from command copy-system-information:

**Output when started from a shell**

**Comment by tviti** [comment]
Here's how I'm currently dealing with this in my `init.lisp`:

```common-lisp
(defvar *my-search-engines* nil)
(setf *my-search-engines*
      (list
       '("google" "https://www.google.com/search?q=~a" "https://www.google.com/")
       '("quickdocs" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/")
       '("wiki" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/")
       '("define" "https://en.wiktionary.org/w/index.php?search=~a" "https://en.wiktionary.org/")
       '("python3" "https://docs.python.org/3/search.html?q=~a" "https://docs.python.org/3")
       '("doi" "https://dx.doi.org/~a" "https://dx.doi.org/")))

(define-configuration browser
  ((search-engines (append (mapcar (lambda (x)
				     (make-instance 'search-engine
						:shortcut (first x)
						:search-url (second x)
						:fallback-url (third x)))
				   *my-search-engines*)
                           %slot-default))))
```

Is this the intended usage for the `search-engines` slot? (willing to file a PR on `MANUAL.org` if so)

**Comment by Ambrevar** [comment]
You are correct, forgot to update the doc.
No need to send a PR, I'll move the section in the manual to the
docstring, this way we won't have those "doc bugs" anymore.

Do you find the (make-instance 'search-engine ...) syntax too verbose?
Maybe it's time for a dedicated constructor, e.g.

(make-search-engine "quickdocs" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/")

(Optional third arg.)

Thanks for the catch!

**Comment by tviti** [comment]
> Do you find the (make-instance 'search-engine ...) syntax too verbose?
> Maybe it's time for a dedicated constructor, e.g.
>
> (make-search-engine "quickdocs" "http://quickdocs.org/search?q=~a" "http://quickdocs.org/")
>
> (Optional third arg.)

Yeah, I think it does start to feel like boilerplate, although as far as boilerplate goes it's not so bad.

Would be nifty to dispatch on a list argument too, so that the whole thing could be collapsed to:

```common-lisp
(define-configuration browser
  ((search-engines (append (mapcar #'make-search-engine *my-search-engines*)
                           %slot-default))))
```

**Comment by Ambrevar** [comment]
Without changing my constructor, you could do

(define-configuration browser
   ((search-engines (append (mapcar (alex:curry #'apply #'make-search-engine) *my-search-engines*)
                            %slot-default))))

**Comment by Ambrevar** [comment]
Done in 575e9a363bde338877976411325c97a0e398cb0d.

**Comment by Ambrevar** [comment]
Feel free to reopen if there is anything else.
