### ISSUE TITLE
Override map for minibuffer? (C-space should allow selection)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#742]
Currently C-space is in the override map and shadows C-space in the minibuffer.

This is not really "do what I mean".

I can think of 2 options:

- Have an override map for the minibuffer.  It would have one binding, `escape` to quit.
- Rebinding `C-space` to `execute-command-or-mark`, a command that calls `execute-command` when minibuffer is down, or `minibuffer-toggle-mark` otherwise.

**Comment by jmercouris** [comment]
I'm currently just using shift space for this function, and I think it should remain that way. Consider that we probably want the user to be able to use C-space in the minibuffer to toggle the mark and highlight text (in the future). Thoughts?

**Comment by jmercouris** [comment]
In any case, the conflict you have described remains. For that I would suggest a seprate override map for the minibuffer.

**Comment by Ambrevar** [comment]
Indeed, we need 2 features, text selection and candidate marking.

Instead of using shift-space, I suggest using M-space and bind
shift-space to "minibuffer-toggle-mark-backwards" to move up.

**Comment by Ambrevar** [comment]
Out of consistency with shift-space on a web page which scrolls up.

**Comment by jmercouris** [comment]
That does make more sense, indeed!

**Comment by Ambrevar** [comment]
Done in b5939ad029c89c1489d470f18648b114bf4d375d.
