### ISSUE TITLE
Overloaded C-g?

### ISSUE THREAD

**Issue by acidtoyman** [atlas-engineer/next#743]
Emacs normally binds C-g to quitting; normally you can C-g multiple times in a row to be sure you've quit even multiple commands in a row.  This is also the default behaviour in other software with Emacs-like bindings, such as Conkeror (where, I imagine, quite of few potential Next users are coming from).

In Next, though, you have to be careful how many times you've hit C-g, as it's also bound to "Follow link in current buffer".  This results in unexpected (and irritating) behaviour, especially if you're in the habit of jumping back and forth between Emacs and a browser.

Yeah, you can remap keybindings (though I haven't had luck with this one), but I think this is a bothersome enough surprise that it'd be a good idea to have the default behaviour of C-g match that of Emacs and remap the default keybinding for "Follow link in current buffer" to something else.

**Comment by Ambrevar** [comment]
I agree, I already had complaints about this before.

I suggest the following:

       "M-g M-g" 'follow-hint ; Maps Emacs `goto-line`.
       "M-g g" 'follow-hint-new-buffer-focus
       "C-u M-g M-g" 'follow-hint-new-buffer
       "C-u M-g g" 'follow-hint-new-buffer

**Comment by jmercouris** [comment]
OK, that's fine with me!

**Comment by Ambrevar** [comment]
Done in 7a4ac4b3866ca4a39761dbce20e2a110deaf6eb6.
