### ISSUE TITLE
Can't open the download/docs pages

### ISSUE THREAD

**Issue by riccardopinosio** [atlas-engineer/next#744]
Hello,

From the looks of it this is a fantastic project, looking forward to try it.
However I have an issue with downloading it, I get a 502 bad gateway from
[https://next.atlas.engineer/download](https://next.atlas.engineer/download).

**Comment by jmercouris** [comment]
Its available again, sorry for that! Until we release the pre-release for 2.0, it is reccommended to build from source as it is much better than 1.5!

**Comment by riccardopinosio** [comment]
@jmercouris ok I'll do that!

**Comment by azzamsa** [comment]
@jmercouris it's happening again. https://next.atlas.engineer/documentation (502)

**Comment by jmercouris** [comment]
I'll be working on the website soon... until then, thanks for your patience :-D
