### ISSUE TITLE
Move zoom, scroll, hinting, etc. to web-mode

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#746]
In web-mode we bind commands like scrolling, element hinting, etc.
But most of these bindings seem to be basic enough that they should go to base-mode. 

At the moment, both from the developer and the user point of view, it's had to tell which bindings belongs to web-mode and which one belongs to base-mode.

The only specificity of web-mode is that it has a history of pages.

Thus I suggest to move all non-history-related bindings to base-mode and rename web-mode history-mode.

Thoughts?

**Comment by jmercouris** [comment]
Yes, I forgot to reply, sorry!

The separation for me is clear, web-mode is for operations against the buffers and web documents, whereas base-mode is for bindings against the browser itself. For example:

base mode: make a new buffer
web mode: navigate backwards in buffer

base mode: kill the browser
web mode: scroll down

etc, etc

What do you think, logical?

**Comment by Ambrevar** [comment]
OK, but we need to fix the bindings because we are
inconsistent! :p

Examples to move to base-mode:
- bookmark-page
- bookmark-current-page
- bookmark-current-page
- open-inspector
- set-url-from-bookmark

Examples to move to web-mode
- autofill

Finally, some categorizations are not so obvious, for instance

- copy-url
- copy-title

I'd say they belong to base-mode.

**Comment by Ambrevar** [comment]
The element hinting commands should be part of web-mode.  Otherwise in a non-web-mode enabled buffer, the hint commands will still be there.

Same goes with zooming, scrolling. etc.

**Comment by Ambrevar** [comment]
@jmercouris Shall I proceed?

**Comment by jmercouris** [comment]
Yes, please :-)

**Comment by Ambrevar** [comment]
Done in ea1ceacd5f60237501455825f6a771518315509d.
