### ISSUE TITLE
Debian stable and libwebkit2gtk-4.0-dev - Next Developer Readme

### ISSUE THREAD

**Issue by Mestelan** [atlas-engineer/next#747]
Sorry, I do not particularly understand this warning in the documentation, section [Next Developer Readme](https://github.com/atlas-engineer/next/tree/master/documents):

> Install the WebKitGTK+ package of your distribution that provides libwebkit2gtk-4.0.so (the shared library for WebKitGTK+).
> 
>     For most Debian-based systems (including Ubuntu) this package is libwebkit2gtk-4.0-dev. **Debian Stable is not supported. Debian users are advised to use more up-to-date packages from Debian Testing at least.**

The version in Debian stable (Buster) is the same as in Sid or Buster backports (2.28.2-2), except for very minor digits. Is the difference yet significant? 
https://packages.debian.org/buster/libwebkit2gtk-4.0-dev

Does this warning still apply? I have been able to build and install all right, following the instructions. Does the warning imply that incorrect behaviors might show up?

**Comment by jmercouris** [comment]
Hi! Thank you for your interest in the project! Unfortunately none of us are Debian users, however we do suggest to run as recent a version of WebKit as possible to get the most security patches as possible. If you think the warning should be rephrased or changed, please let us know!

**Comment by Ambrevar** [comment]
Jean-Baptiste is right, the warning predates Debian Buster: WebKitGTK
used to be very outdated in the previous Debian release.

I'll update the documentation.

**Comment by Ambrevar** [comment]
Fixed in b44e62d6c9b72651c0446f65719157a8c4a2cd06.
