### ISSUE TITLE
copy-password not working

### ISSUE THREAD

**Issue by sirmacik** [atlas-engineer/next#748]
When I use M-x copy-password and select one from the minibuffer, then
paste it into some field I usually get some previously copied text or
nothing in case the clipboard buffer was clear, but no password.

Unfortunately while trying that out and failing I get no output in
verbose mode.

I'm running next from git with revision: 
```
f4f10887 help: Fix describe-bindings.
```

My system-information:

```
Next Version: 0.0.0 
Lisp Implementation: SBCL 
Lisp Version: 2.0.4 
Operating System: Linux 5.4.41-gnu 
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
           OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
           CLOSER-MOP SB-BSD-SOCKETS-ADDRINFO CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
           CL-JSON-SINGLE-FLOAT-IS-SUBSUMED BORDEAUX-THREADS
           LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
```

**Comment by Ambrevar** [comment]
I can't reproduce.  How did you build Next?
Do you have xsel or xclip installed?

**Comment by sirmacik** [comment]
I did it by `guix package -f build-scripts/guix.scm` and xclip is present. No xsel though.

**Comment by Ambrevar** [comment]
Are you using password-store or keepassxc?

**Comment by sirmacik** [comment]
I'm using password-store, but keepassxc is also installed. While using copy-password it correctly shows contents of my `~/.password-store` in the minibuffer and let's me choose from them. Unfortunately it does not copy the password.

**Comment by Ambrevar** [comment]
I've added debug info in commit 54424ccc7a6dce2adc1218d15ac653c71a700c39.

Start Next with the --verbose option and you should see a line like

    <DEBUG> [12:03:46] Password interface PASSWORD-STORE-INTERFACE uses executable "/home/ambrevar/.guix-extra-profiles/main/main/bin/pass".

when copying a password.

Please report this line.

**Comment by Ambrevar** [comment]
Since the aforementioned commit, you should now see this message after a
successful password copy:

> Password saved to clipboard for 15 seconds.

**Comment by sirmacik** [comment]
Here's what I've got:
```
<DEBUG> [17:19:58] next password.lisp (copy-password form-fun-6) -
  Calling command COPY-PASSWORD.
<DEBUG> [17:19:58] next password.lisp (password-debug-info) -
  Password interface PASSWORD-STORE-INTERFACE uses executable NIL.
<DEBUG> [17:19:58] next browser.lisp (initialize-modes buffer) -
  NEXT::MODE-CLASS: MINIBUFFER-MODE BUFFER: #<MINIBUFFER {1008564C43}>
  (NEXT::MODE-COMMAND NEXT::MODE-CLASS): #<NEXT::COMMAND {1003800D53}>
<DEBUG> [17:19:58] next minibuffer.lisp (minibuffer-mode form-fun-15) -
  Calling command MINIBUFFER-MODE.
<DEBUG> [17:19:58] next minibuffer.lisp (minibuffer-mode form-fun-15) -
  MINIBUFFER-MODE enabled.
<DEBUG> [17:19:58] next minibuffer.lisp (cancel-input form-fun-6) -
  Calling command CANCEL-INPUT.
<DEBUG> [17:20:00] next renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
  NEXT::KEY-STRING: "return" NEXT::KEYCODE: 36 CHARACTER: #\Return
  NEXT::KEYVAL-NAME: "Return"
<DEBUG> [17:20:00] next input.lisp (dispatch-input-event) -
  Key sequence return (#36) (translated from return (#36))
<DEBUG> [17:20:00] next minibuffer.lisp (return-input form-fun-6) -
  Calling command RETURN-INPUT.
<ERROR> [17:20:00] next utility.lisp (funcall-safely fun3) -
  In #<FUNCTION (LAMBDA (NEXT::PASSWORD-NAME)
                  :IN
                  COPY-PASSWORD) {5265F5EB}>: The value
                                                NIL
                                              is not of type
                                                (OR (VECTOR CHARACTER)
                                                    (VECTOR NIL) BASE-STRING
                                                    PATHNAME SYNONYM-STREAM
                                                    FILE-STREAM)

                                              when binding PATHNAME
<DEBUG> [17:20:00] next minibuffer.lisp (cancel-input form-fun-6) -
  Calling command CANCEL-INPUT.
```

**Comment by Ambrevar** [comment]
This helps!  The `pass` executable cannot be found.

Can you report the output of the following:

```sh
$ which pass
```

```lisp
(multiple-value-bind (path)
      (ignore-errors
       (uiop:run-program (format nil "command -v ~A" "pass")
                         :output '(:string :stripped t)))
    path)
```

(You can run the last one in an SBCL REPL.)

**Comment by sirmacik** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> This helps! The `pass` executable cannot be found.
>
> Can you report the output of the following:

No problem, here they come:

> ```sh
> $ which pass
> ```

```sh
% which pass
/run/current-system/profile/bin/pass
```

> ```lisp
> (multiple-value-bind (path)
> (ignore-errors
> (uiop:run-program (format nil "command -v ~A" "pass")
> :output '(:string :stripped t)))
> path)
> ```

```lisp
* (multiple-value-bind (path)
(ignore-errors
(uiop:run-program (format nil "command -v ~A" "pass")
:output '(:string :stripped t)))
path)
"/run/current-system/profile/bin/pass"
```

> (You can run the last one in an SBCL REPL.)

-- 
Marcin „sirmacik” Karpezo
PGP: 0xCE97A6633F332AEF
https://sirmacik.net

**Comment by Ambrevar** [comment]
Unrelated, but you should not install pass (or any user-facing program)
in your Guix system.

How do you start Next?

Can you start with `--no-init` and try again?

Do you know how to use a Common Lisp REPL?  If so, you could investigate
the value of (password-interface *browser*) while running the browser,
see why and when the path is set to NIL.

In other words, why you get this line:

	 Password interface PASSWORD-STORE-INTERFACE uses executable NIL.

**Comment by sirmacik** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Unrelated, but you should not install pass (or any user-facing program)
> in your Guix system.

Why is that? So far I find manifests not as handy and prefer to keeep it
in system config. It'd be great if user could have some way to configure
his profile in similar manner. 

> How do you start Next?

by running next from stumpWM command prompt. It has my complete
$PATH. For previous test and with verbose flag I run it from my terminal
emulator. 

> Can you start with `--no-init` and try again?

Here comes the output:

    <DEBUG> [18:48:32] next input.lisp (dispatch-input-event) -
      Key sequence return (#36) (translated from return (#36))
    <DEBUG> [18:48:32] next minibuffer.lisp (return-input form-fun-6) -
      Calling command RETURN-INPUT.
    <DEBUG> [18:48:32] next password.lisp (copy-password form-fun-6) -
      Calling command COPY-PASSWORD.
    <DEBUG> [18:48:32] next password.lisp (password-debug-info) -
      Password interface PASSWORD-STORE-INTERFACE uses executable NIL.
    <DEBUG> [18:48:32] next browser.lisp (initialize-modes buffer) -
      NEXT::MODE-CLASS: MINIBUFFER-MODE BUFFER: #<MINIBUFFER {1009C04C43}>
      (NEXT::MODE-COMMAND NEXT::MODE-CLASS): #<NEXT::COMMAND {1003800D53}>
    <DEBUG> [18:48:32] next minibuffer.lisp (minibuffer-mode form-fun-15) -
      Calling command MINIBUFFER-MODE.
    <DEBUG> [18:48:32] next minibuffer.lisp (minibuffer-mode form-fun-15) -
      MINIBUFFER-MODE enabled.
    <DEBUG> [18:48:32] next minibuffer.lisp (cancel-input form-fun-6) -
      Calling command CANCEL-INPUT.
    <DEBUG> [18:48:34] next renderer-gtk.lisp (on-signal-key-press-event gtk-window) -
      NEXT::KEY-STRING: "return" NEXT::KEYCODE: 36 CHARACTER: #\Return
      NEXT::KEYVAL-NAME: "Return"
    <DEBUG> [18:48:34] next input.lisp (dispatch-input-event) -
      Key sequence return (#36) (translated from return (#36))
    <DEBUG> [18:48:34] next minibuffer.lisp (return-input form-fun-6) -
      Calling command RETURN-INPUT.
    <ERROR> [18:48:34] next utility.lisp (funcall-safely fun3) -
      In #<FUNCTION (LAMBDA (NEXT::PASSWORD-NAME)
                      :IN
                      COPY-PASSWORD) {5265F5EB}>: The value
                                                    NIL
                                                  is not of type
                                                    (OR (VECTOR CHARACTER)
                                                        (VECTOR NIL) BASE-STRING
                                                        PATHNAME SYNONYM-STREAM
                                                        FILE-STREAM)

                                                  when binding PATHNAME
    <DEBUG> [18:48:34] next minibuffer.lisp (cancel-input form-fun-6) -
      Calling command CANCEL-INPUT.

> Do you know how to use a Common Lisp REPL? If so, you could investigate
> the value of (password-interface *browser*) while running the browser,
> see why and when the path is set to NIL.
>
> In other words, why you get this line:
>
> Password interface PASSWORD-STORE-INTERFACE uses executable NIL.

NEXT-USER>  (password-interface *browser*)
#<PASSWORD::PASSWORD-STORE-INTERFACE {100C56F4E3}>

If you'll give me some more guidance I can investigate it further.

-- 
Marcin „sirmacik” Karpezo
PGP: 0xCE97A6633F332AEF
https://sirmacik.net

**Comment by Ambrevar** [comment]
I think I've found out what this is about.  Check out commit
84b452bd817f87811a2a5d85414f57a0d60543c7, it should fix the issue.

**Comment by sirmacik** [comment]
It works great, thank you! Cant wait for 2.0 release party. (;

-- 
sirmacik
PGP: 0xE0DC81D523891771
