### ISSUE TITLE
cl-webkit submodule isn't cloned during build

### ISSUE THREAD

**Issue by tviti** [atlas-engineer/next#758]
**Describe the bug**

`make cl-webkit` doesn't actually clone cl-webkit into `quicklisp/local-projects/cl-webkit`

The `next` and `all` targets still produce a binary, but the resulting binary crashes when trying to bring up the context menu.

If i manually `git clone ...` cl-webkit into `quicklisp/local-projects`, and then re-build, the resulting binary works fine (i.e. doesn't crash on right-click).

I think this is because a subproject commit was never made when cl-webkit was added as a submodule (likely because `quicklisp/` is gitignored), rather it was only added to `.gitmodules`. Not sure if this was intended though.

As a test, I tried temporarily whitelisting `quicklisp/`, then squashing a subproject commit into master, then `make clean; make next`, which seems to have worked.

**Comment by Ambrevar** [comment]
Good catch, thanks!

Should be fixed in 1580c27c86c5ee1464458b26695f303acda01402.

I'm still a bit ignorant about submodules and I wonder what purpose this
subproject commit serves if we don't want to track a specific commit.
In our case, we want to follow cl-webkit master.

Annoyingly, every time cl-webkit is updated, the commit file will be
updated by the

  git submodule update --init --remote

command.  Is there a way to avoid this?

**Comment by jmercouris** [comment]
I do not know of a way to avoid this

**Comment by jmercouris** [comment]
A bit of a bikeshed here, but can we please put it in a 'local-projects/' dir rather than 'quicklisp/local-projects/', it could be loaded by anything including just ASDF.

**Comment by Ambrevar** [comment]
The point of putting it in quicklisp/local-projects is that only users
who use the internal quicklisp will benefit from the submodule.

I think it's better to let the other users decide how they want to load
cl-webkit since they already manage their Common Lisp libraries.

Thoughts?

**Comment by Ambrevar** [comment]
Clarification: the "quicklisp/" subdirectory is where the internal
Quicklisp distribution is stored, it's a folder that's bound to exist by default.

**Comment by tviti** [comment]
> if we don't want to track a specific commit.

I think the problem is that this is how the submodule mechanism is supposed
to behave: that is, the intention is to version dependencies alongside the
project source (like version pinning). There might be other ways of using
submodules, but I'm not familiar.

**Comment by jmercouris** [comment]
Taylor is correct, that is exactly how it is intended to be used. Every time you update remote you have to make a commit in your own repository tracking the new version. (I remember using it for devops)

**Comment by jmercouris** [comment]
I think the old solution was better

**Comment by jmercouris** [comment]
Also, what you (Pierre) said about the quicklisp directory makes sense, I didn't know that as I do not use the internal quicklisp :-)

**Comment by tviti** [comment]
To keep the subproject commits out of master, you could create a
"submodules" branch that you just constantly pollute with update commits
(e.g. "submodules: updated cl-webkit"). Then, during the build process,
checkout the latest version of cl-webkit from the submodule branch (I've
never done this with submodules so IDK if you can actually do a
single-dir-checkout on one like this).

This is similar to how git-annex versions binary resources, but TBH sounds
like a lot of uneccessary pain if you don't really care about version
consistency w/ the submodule. You'd still basically be cloning the
submodule, with the new issue of remembering to keep the branch up-to-date.

**Comment by Ambrevar** [comment]
I think a separate branch will complicate things.
The "commit commit" is unfortunate but until we figure out how to get rid of it I think this is the best solution.

@tviti Is everything fine for you now?

**Comment by tviti** [comment]
I agree, that it's more trouble than it's worth.

Haven't had any issues building since the subproject commit was added!

**Comment by Ambrevar** [comment]
Thanks for the feedback!
