### ISSUE TITLE
provide a deb package

### ISSUE THREAD

**Issue by trenkert** [atlas-engineer/next#76]
It's an interesting project, but the compilation steps are too many for somebody who wants to just chekc it out. It would be much easier to achieve a wider adoption if you could provide a deb package for debian/ubuntu.

**Comment by jmercouris** [comment]
Hi, thank you for the kind words! I am in fact working on a debian package or some way of distributing Linux binaries, I’ll update this issue when I have something good!

**Comment by ohot2015** [comment]
up +++

**Comment by BrokeRU** [comment]
@jmercouris Hi! We are all waiting for deb package! It would be nice to try this browser without horrible compilation steps on Debian/Ubuntu/Mint/Elementary :) Good luck!

**Comment by jmercouris** [comment]
@BrokeRU I am working on it still! A new release/UI models means a new packaging build system, this will come out in version 0.09, I'll keep this thread updated :)

**Comment by jmercouris** [comment]
hi @azzamsa this will now be possible! @Ambrevar is working on a Guix package which will allow exactly just that! So look forward to that :)

We just have to now make it available for download, which involves some work on the Next website!

**Comment by Ambrevar** [comment]
@vindarel: Have you checked out the latest changes on master?  We've revamped the whole system.  Now the GTK port should be much more stable and the build procudure as simple as `make all`.
We also have a functional Guix package and Arch Linux package.

Would you be interested in producing a new .deb package?

**Comment by vindarel** [comment]
not yet but willing too. I didn't provide a deb but a linux binary (built with Gitlab CI on [my fork](https://gitlab.com/vindarel/next-browser/pipelines)). Hope I can give a hand again for this.

**Comment by jmercouris** [comment]
@vindarel unfortunately, the linux binary you've created will not work anymore as quite a lot has changed!

**Comment by vindarel** [comment]
What do you mean ? The binary is a binary and should carry on working :)

Anyway, I managed to build Next under Gitlab CI (under Docker) and produce the two binaries:

- https://gitlab.com/vindarel/next-browser/-/jobs/129848967 (download artifacts)
- the CI with notes: https://gitlab.com/vindarel/next-browser/blob/linux-binary/.gitlab-ci.yml

which is a good step :) (it was easy thanks to the Makefile installing all the dependencies)

However, I am unsure how to run them and there seems to be an error:

- with `export PATH…`:

```
Polling plartform port...
Polling plartform port...
Polling plartform port...
…
Polling plartform port...
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006485B3}>:
  no response from server

^^ I'd add a tip on what to check

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006485B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "no response from server" {100428F9C3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "no response from server" {100428F9C3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "no response from server" {100428F9C3}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SIMPLE-ERROR "no response from server" {100428F9C3}>)
4: (SB-KERNEL::%SIGNAL #<SIMPLE-ERROR "no response from server" {100428F9C3}>)
5: (ERROR "no response from server")
6: (S-XML-RPC:XML-RPC-CALL "<methodCall><methodName>window.make</methodName></methodCall>" :URL "/RPC2" :AGENT NIL :HOST "localhost" :PORT 8082 :AUTHORIZATION NIL :PROXY-HOST NIL :PROXY-PORT NIL)
7: ((:METHOD NEXT::WINDOW-MAKE (NEXT::REMOTE-INTERFACE)) #<NEXT::REMOTE-INTERFACE {1003DE0793}>) [fast-method]
8: (NEXT::MAKE-WINDOW)
```

with `next-gtk-webkit` in `/usr/local/bin`, it's shorter:

```
$ ./next                                                   *[master] 
Polling plartform port...
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006485B3}>:
  no response from server

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006485B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "no response from server" {100424CC23}> #<unused argument> :QUIT T)
```

by running the server in a terminal and `./next` in another:

```
$ ./ports/gtk-webkit/next-gtk-webkit                       *[master] 
./ports/gtk-webkit/next-gtk-webkit: symbol lookup error: ./ports/gtk-webkit/next-gtk-webkit: undefined symbol: soup_xmlrpc_parse_request
```
and
```
$ ./next                                                  *[master] 
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006485B3}>:
  no response from server
```

Can you make them work ? We're pretty close !

**Comment by Ambrevar** [comment]
Hi @vindarel, thanks for the good work!

Can you report those details:
- OS + version
- WebKit version
- Libsoup version (should be a dependency of WebKit)

If `next-gtk-webkit` has built, it should work, which is what is puzzling me here.

**Comment by vindarel** [comment]
my machine:

- Debian 8
- I found installed:  libwebkit2gtk-3.0-25 and libwebkit2gtk-4.0-dev and libwebkit2gtk-4.0-37
- libsoup2.4-1 and libsoup2.4-dev

The CI creates a binary on Debian Buster, with libwebkit2gtk-4.0-37, ibwebkit2gtk-4.0-dev, libsoup 2.4.1 and the -dev.

**Comment by Ambrevar** [comment]
You need libsoup 2.53+ (first released in 2015).  Debian 8 is a bit too old for Next I'm afraid :(

**Comment by azzamsa** [comment]
> Debian 8 is a bit too old for Next I'm afraid :(

Sure, I think so. Debian 8 is oldstable now.

**Comment by Ambrevar** [comment]
@vindarel : Do you think we could get a .deb for Debian testing?

**Comment by Ambrevar** [comment]
(Now that 1.2.1 is out?)

**Comment by vindarel** [comment]
Putting this on my todolist:

- create a (new) binary with Gitlab CI first
- see how to create a .deb (I never created a .deb), maybe from the binary.

**Comment by novoid** [comment]
No Guix on Debian:

```
vk@sherri ~ % cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
vk@sherri ~ % apt-cache search guix
vk@sherri ~ %
```

**Comment by Ambrevar** [comment]
Yup, that's a problem, although you can easily install it from the binary at http://guix.gnu.org/download/ : it's easy to install and uninstall, and it won't interfere with you file system hierarchy.

**Comment by alexanderbarbosa** [comment]
@novoid 
There is a script that takes no more than a few seconds to set Guix up! Worth a few megabytes on your drive! :+1: 
Eg: If your Distro dont provide some packages, as Fedora, you wont need to install a third-party repo that most of its commiters are not well verified!

**Comment by indigoviolet** [comment]
Having spent a couple hours on this I can report that I have been unable to get Guix to work with Next, which is unfortunate for someone fairly experienced with Linux systems and motivated to try Next.  First I ran into some `guix pull` issues and then Guix couldn't find `next`, and I've just run out of patience to fix this. Maybe I'll try building from source some another day, but I would love to see a deb package. I support this (to a minor extent) on Patreon, and would like to actually try it some day!

**Comment by Ambrevar** [comment]
Thanks for your support and you patience, it's very much appreciated! :)

A deb package has been on our TODO list for a while, and now it's top priority.  Stay tuned, it hopefully won't take long!
@vindarel What do you think?

Regarding Guix: many people have reported a smooth experience with it, it's possible that there was a hickup during the installation.  If `guix pull` didn't work properly, there is no chance you can install Next with it.

Feel free to report the output of the failing command, I can help you with it, no problem.
Also feel free to reach out to the mailing list (see http://guix.gnu.org/contact/), it's very helpful and Guix is a fantastic project that's definitely worth using even outside the scope of Next!

**Comment by vindarel** [comment]
I can only confirm it's in the top priority :]

**Comment by azzamsa** [comment]
Instead of deb package, why don't we just use binary format? as [comment](https://github.com/atlas-engineer/next/issues/76#issuecomment-438049603) above?

Yes, we have guix package (I use that in my other laptop). I think no one would install guix just in order to use `next`.

Why didn't just release binary as like firefox and others did.

**Comment by Ambrevar** [comment]
The binaries mentioned in the comment are not universal: they don't run on Guix or Nix at least, and they have other shortcomings (kernel, dbus, unexpected FHS differences...).  Maybe the worst part of all: they are not reproducible and as such represent an unacceptable security risk in my opinion, especially for a web browser :p

You don't have to install Guix: you can use the Guix pack, which is a better solution than a binary in my opinion (it works on many more distros plus it's reproducible).
Installing Guix is probably not a bad thing anyways: it gives you reproducible packages with profiles and rollbacks and all.  It's awesome!

Binary/Guix aside, I believe a .deb / ppa would help Debian-based distro users out there to have a one-click reliable installation of Next.

**Comment by vindarel** [comment]
@azzamsa: using binaries is possible, they just don't replace a proper debian package. We have binaries for the lisp side here: https://gitlab.com/atlas-engineer/next/pipelines (for linux x64 so far). One for a platform needs a bit more attention. Grabbing a new binary can be handy to get and test new features.

Note also that we are testing pyinstaller executables, see #275.

**Comment by azzamsa** [comment]
> You don't have to install Guix: you can use the Guix pack, which is a better solution than a binary in my opinion (it works on many more distros plus it's reproducible).

do we have the [guix pack](https://guix.gnu.org/manual/en/html_node/Invoking-guix-pack.html) ?

---

While I type the question I above, I tried Vindarel build. but resulted in the following errors:

``` bash
$ ./next
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006C05B3}>:
  Error opening shared object "libfixposix.so":
  libfixposix.so: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006C05B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000ED5493}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000ED5493}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000ED5493}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libfixposix.so" "libfixposix.so: cannot open shared object file: No such file or directory")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT)
9: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
11: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

Then I give up, and just want to browse https://next.atlas.engineer/ as always, just to know any recent info (because I always want to try it without a pain). Heading to https://next.atlas.engineer/download, I am surprised by "Download for GNU/Linux", I never find this before? before I need to compile it manually, is this new? (my bad I just know it). 

It run well on my fresh installed laptop without needing to install guix etc, great work, thank you. Now it easier for us to use `next`. This is what I mean in my [previous comment](https://github.com/atlas-engineer/next/issues/76#issuecomment-438049603)

Once again, thank you :)

**Comment by Ambrevar** [comment]
The Guix pack is on the download page, as you found out.
It has been available since 1.0 if I'm not wrong, so it's been a couple
of months ;)

You can find follow us on the Articles page
(https://next.atlas.engineer/articles) or our newsfeed
(https://next.atlas.engineer/feed).

> While I type the question I above, I tried Vindarel build. but resulted in the following errors:
>
> ``` bash
> $ ./next
> Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
>                                     {10006C05B3}>:
>   Error opening shared object "libfixposix.so":
>   libfixposix.so: cannot open shared object file: No such file or directory.

You need to install libfixposix on your system.

**Comment by azzamsa** [comment]
@Ambrevar wow :)

![image](https://user-images.githubusercontent.com/17734314/64551743-fd81b200-d35f-11e9-930c-eb9eb8c3e3ea.png)

Yes, it is the guix pack.

---

> The Guix pack is on the download page, as you found out.
It has been available since 1.0 if I'm not wrong, so it's been a couple
of months ;)

Yeah, been a while not visiting here :)

**Comment by vindarel** [comment]
Great news, I was able to build, install and use a Debian package :) 

You can grab it here: https://next.atlas.engineer/static/release/next_1.3.1_amd64.deb (ahem it's 1.3.2 though, will fix ASAP :) )

Feedback appreciated, even (mainly!) if it works. I didn't test in a fresh Debian or Ubuntu.

There are a couple minor issues & improvements left (https://github.com/atlas-engineer/next/blob/vindarel%2Fdebian-package/debian/README.org).

**Comment by novoid** [comment]
> Feedback appreciated

I do run **Debian GNU/Linux 9** (stretch; oldstable) where installation fails:

```
root@sherri ~log # dpkg -i ~vk/tmp/2del/next_1.3.1_amd64.deb 
Selecting previously unselected package next.
(Reading database ... 411367 files and directories currently installed.)
Preparing to unpack .../tmp/2del/next_1.3.1_amd64.deb ...
Unpacking next (1.3.1) ...
dpkg: dependency problems prevent configuration of next:
 next depends on sbcl (>= 1.4.2); however:
  Package sbcl is not installed.
 next depends on libwebkit2gtk-4.0-37 (>= 2.21.1); however:
  Version of libwebkit2gtk-4.0-37:amd64 on system is 2.18.6-1~deb9u1.0.
 next depends on libwebkit2gtk-4.0-dev (>= 2.24); however:
  Package libwebkit2gtk-4.0-dev is not installed.
 next depends on sqlite; however:
  Package sqlite is not installed.
 next depends on libfixposix-dev; however:
  Package libfixposix-dev is not installed.
 next depends on gir1.2-gst-plugins-base-1.0; however:
  Package gir1.2-gst-plugins-base-1.0 is not installed.

dpkg: error processing package next (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 next
1 root@sherri ~log # apt-get -f install                                                                                                                                                                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  next
0 upgraded, 0 newly installed, 1 to remove and 6 not upgraded.
1 not fully installed or removed.
After this operation, 25.9 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 411391 files and directories currently installed.)
Removing next (1.3.1) ...
root@sherri ~log #
```

Since there is Debian 10 out there already, I don't think that Debian 9 install fails are that important. I posted this more or less for documentation purpose.

**Comment by Ambrevar** [comment]
Fantastic news!  Please go ahead and update the doc wherever we need to
mention need.
We could ping a couple of issues on GitHub too :)

**Comment by Ambrevar** [comment]
Thanks for reporting.

Indeed, this is expected, you need Debian Testing at least as per the
README.

I don't know if Debian 10 is good enough.

**Comment by 4t0m** [comment]
This is great!  I had no problem installing on Ubuntu 19.04.  

Strangely the command NEXT-VERSION has no result.  I haven't run into any other problems.

**Comment by Ambrevar** [comment]
Thanks for reporting!

> Strangely the command NEXT-VERSION has no result.  I haven't run into any other problems.

This is a known issue, but the version should still be in your
clipboard, you can paste it somewhere.

**Comment by lxbarbosa** [comment]
@vindarel 
Everything working in Debian 10 SID

*more:*
```shell
The following additional packages will be installed:       
  gir1.2-gst-plugins-base-1.0 libsqlite0 sqlite            
Suggested packages:                                        
  sqlite-doc                                               
```

**Comment by Ambrevar** [comment]
Thanks for the feedback!

**Comment by indigoviolet** [comment]
Thanks! I was able to install it on Ubuntu 19.04 as well! Suggestion: Consider making a PPA (https://askubuntu.com/questions/71510/how-do-i-create-a-ppa/493577#493577) so that future users aren't confused by the `dpkg -i` failure and then `apt-get --fix-broken` process.

**Comment by lxbarbosa** [comment]
@indigoviolet 
Well, that's usual of `dpkg`,  if you use `apt` instead that would not be a issue:

``` shell
sudo apt install ./next.deb 
```

**Comment by vindarel** [comment]
thanks for the link of the ppa.

You can also use the (built-in?) `gdebi` graphical installer, it installs the dependencies. I'll add a note to the installation instructions.

**Comment by novoid** [comment]
No issue installing the deb via `sudo apt install ./next*.deb` on Xubuntu 18.04.3 LTS (Bionic Beaver).

However, after the first start and invoking `M-l` or `C-l` I got: `Could not prepare an sqlite statement. Code ERROR: no such column: visits. Database: /home/vk/.local/share/next/history.db SQL: select url from typed where url like ? order by visits desc`

The db file exists.

I added the column 'visits' (as text) to the DB and then next was able to open URLs.

**Comment by jmercouris** [comment]
Yeah, the migration database code isn't exactly the best :D

The default data store will no longer be SQLite and is now S-EXP, so things will get better, and we'll add some pretty cool functionality as well. You can see some of it already on master with the enhanced fuzzy searching of bookmarks.

**Comment by vindarel** [comment]
Thank you. Had you tried to use an old version of Next before ? It seems so given this DB issue.

**Comment by novoid** [comment]
> Thank you. Had you tried to use an old version of Next before ? It seems so given this DB issue.

Yes, on 2018-12-07 I tested the tarball version and failed:

```
vk@floyd ~2d/unp % bin/next                                                                                                  
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LC_ALL=en_US.utf8
  LANG=en_US.utf8
  LC_MESSAGES=en_US.utf8
  LC_MONETARY=de_AT.UTF-8
  LC_NUMERIC=de_AT.UTF-8
  LC_TIME=de_AT.UTF-8
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10005885B3}>:
  Couldn't execute "/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit": No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005885B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10037921E3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10037921E3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10037921E3}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10037921E3}>)
4: (SB-KERNEL::%SIGNAL #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10037921E3}>)
5: (ERROR "Couldn't execute ~S: ~A" "/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit" "No such f
ile or directory")
6: (RUN-PROGRAM "/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit" ("--port" "8082" "--core-socke
t" "http://localhost:8081/RPC2") :ENV NIL :ENVIRONMENT NIL :WAIT NIL :SEARCH T :PTY NIL :INPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :OU
TPUT #P"/tmp/next-gtk-webkit.log" :IF-OUTPUT-EXISTS :APPEND :ERROR :OUTPUT :IF-ERROR-EXISTS :APPEND :STATUS-HOOK NIL :EXTERNAL-FORMAT
:UTF-8 :DIRECTORY NIL)
7: (UIOP/LAUNCH-PROGRAM:LAUNCH-PROGRAM ("/gnu/store/8llinghxcslyxmvszjlvlxbv411vra0x-next-gtk-webkit-1.1.0/bin/next-gtk-webkit" "--por
t" "8082" "--core-socket" "http://localhost:8081/RPC2") :OUTPUT #P"/tmp/next-gtk-webkit.log" :ERROR-OUTPUT :OUTPUT)
8: ((:METHOD NEXT::RUN-PROGRAM (NEXT::PORT)) #<NEXT::PORT {1001CB0BF3}>) [fast-method]
9: (NEXT:START :WITH-PLATFORM-PORT-P T)
10: (NEXT-EXEC:MAIN)
11: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
12: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10035CE82B}>)
13: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
13: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-27" :IN SAVE-LISP-AND-DIE))
15: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
vk@floyd ~2d/unp %
```

It must have had success creating the DB file. I did not purge everything afterwards.

**Comment by Ambrevar** [comment]
Delete ~/.local/share/next/history.db and you'll be good to go!

**Comment by azzamsa** [comment]
anyone successfully install it, on Debian 10 (buster)?

**Comment by vindarel** [comment]
hey, I suggest you read a bit up the thread, and/or try by yourself and tell us the result ;)

**Comment by azzamsa** [comment]
:), I have read it. Okay.

**Comment by deepaknegilachu** [comment]
Thanks for deb package.
