### ISSUE TITLE
Duplicate/Redunant documentation

### ISSUE THREAD

**Issue by azzamsa** [atlas-engineer/next#760]
We have `keybinding customization` in manual.org and the same thing in `tutorial.lisp` which is hardcoded. If the interface for keymap changes (again). We need to update the docs in more than one place.  

This sometimes lead us to lost single source of truth and not-DRY.

Any idea?

**Comment by Ambrevar** [comment]
The tutorial is the new reference documentation.
The MANUAL.org is going to be removed soon.

**Comment by Ambrevar** [comment]
(It's still there because I am not done yet with moving everything to the tutorial and the docstrings.)

**Comment by azzamsa** [comment]
> The MANUAL.org is going to be removed soon.

good news!
