### ISSUE TITLE
Can't play videos

### ISSUE THREAD

**Issue by azzamsa** [atlas-engineer/next#761]
**Describe the bug**

**Precise recipe to reproduce the issue**
- go to https://next.atlas.engineer/
- play the video

**Information**
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- How you installed Next (Guix pack, package manager, build from source):
- Information from command copy-system-information:

```
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-5-amd64
Shell: bash 5.0.3
WM: i3
GPU: Intel UHD Graphics 620
```
```
Next Version: 0.0.0 (*latest revision*)
Lisp Implementation: SBCL 
Lisp Version: 2.0.4 
Operating System: Linux 4.19.0-5-amd64 
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
           OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
           CLOSER-MOP SB-BSD-SOCKETS-ADDRINFO CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
           CL-JSON-SINGLE-FLOAT-IS-SUBSUMED BORDEAUX-THREADS
           LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
```

**Output when started from a shell**

none

----

in FF:

![image](https://user-images.githubusercontent.com/17734314/82963851-15808b00-9fee-11ea-9606-e89f43d25adf.png)

in next:

![image](https://user-images.githubusercontent.com/17734314/82963889-3052ff80-9fee-11ea-83df-62a41244711d.png)

**Comment by Ambrevar** [comment]
You need to install gst-libav and other gstreamer plugins.

**Comment by azzamsa** [comment]
do we have this in our docs? or can we include those step in build process?

**Comment by Ambrevar** [comment]
It's in the developer's README but you are right that it should go in
the documentation.  We could add a section about it in the tutorial,
then remove it from the dev's README.

We can't include the plugins in the build process as the GStreamer
plugins should remain opt-in.

**Comment by Ambrevar** [comment]
@jmercouris OK with move the gst-* instructions to a "Troubleshooting -> Play videos" section?

**Comment by jmercouris** [comment]
I am of the belief that all compiled versions/packages should include the plugins, and otherwise it should be that you have to build from source to build without. In this case, the documentation is appropriate where it is. If you disagree with that, then I am OK to add a troubleshooting section to the end of the tutorial.

**Comment by Ambrevar** [comment]
The problem is that most distributions won't do it, and it does not work
right now in Guix I think (could be a bug in Guix or in the recipe).

**Comment by azzamsa** [comment]
@Ambrevar do you have any other package recommendation?

I did `guix install gst-libav` but it still didn't work.

I am on GNU/Linux with guix package manager.

**Comment by Ambrevar** [comment]
gst-plugins-bad
gst-plugins-base
gst-plugins-good
gst-plugins-ugly
gst-libav

**Comment by azzamsa** [comment]
I did `$ guix install gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gst-libav`

I can't try it on previos page (atlas engineer) because of 502, tried in youtube this is what I get

![2020-05-28_15-26](https://user-images.githubusercontent.com/17734314/83117934-e5251380-a0f7-11ea-8a35-3e89294e477f.png)

**Comment by Ambrevar** [comment]
If you are on Guix System, you might have to clean up the stale cache:

    rm -r ~/.cache/gstreamer-1.0

Then restart the browser.

**Comment by azzamsa** [comment]
worked like a charm, thank you.

![image](https://user-images.githubusercontent.com/17734314/83127255-24596180-a104-11ea-92cb-50b24326c90d.png)

**Comment by azzamsa** [comment]
we should add all this steps to the docs.

**Comment by Ambrevar** [comment]
Will do!

**Comment by honestSalami** [comment]
Where in the docs are the steps for this? I can't find it

**Comment by jmercouris** [comment]
Not sure, maybe it is only in the developer documentation, did you check there? Or in the manual?

**Comment by honestSalami** [comment]
I did a word search for "video" and "youtube" in both. Let me do a deeper search and get back to you

**Comment by jmercouris** [comment]
OK! if it hasn't really been added, PR is welcome.

**Comment by honestSalami** [comment]
yeah, I could not find it in any of the readmes or the tutorial
I'll perform the actions and add it to the readme?

**Comment by jmercouris** [comment]
That would be nice of you to add it to the developer readme (documents/readme). It is already in the manual though. You will find it in the manual:

```
    (:p "When using the WebKitGTK backends, GStreamer and its plugins are
leveraged.  Depending on the video, you will need to install some of the
following packages:")
    (:ul
     (:li "gst-libav")
     (:li "gst-plugins-bad")
     (:li "gst-plugins-base")
     (:li "gst-plugins-good")
     (:li "gst-plugins-ugly"))
```
