### ISSUE TITLE
Changing the theme?

### ISSUE THREAD

**Issue by shubham1172** [atlas-engineer/next#770]
The next browser opens in "dark mode" with gray background and white text. How do I change it? I am running it on a Manjaro system with i3.

**Comment by Ambrevar** [comment]
Next does not do any theming, I suspect this is your GTK config.
See
https://wiki.archlinux.org/index.php/GTK.

**Comment by Ambrevar** [comment]
Did you find a solution?

**Comment by shubham1172** [comment]
Yeah, I wasn't able to figure out how to do that in i3, so I logged in with KDE and unchecked the "prefer dark mode" GTK setting.

**Comment by Ambrevar** [comment]
Thanks for sharing!
