### ISSUE TITLE
Documentation: Vim binding

### ISSUE THREAD

**Issue by shubham1172** [atlas-engineer/next#773]
I have configured next to use vim bindings, but the documentation only has emacs bindings. 
It would be really nice to have side by side bindings for vim as well.

**Comment by Ambrevar** [comment]
Which documentation are you referring to?

This is in the tutorial (`f1 t`):

```
Next supports multiple bindings schemes such as CUA (the default), Emacs or VI. Changing scheme is as simple as running the corresponding mode, e.g. emacs-mode. To make the change persistent across sessions, add the following to you configuration (for VI bindings):


(define-configuration buffer
  ((default-modes (append '(vi-normal-mode) %slot-default))))
```

**Comment by shubham1172** [comment]
I am talking about the official [docs](https://next.atlas.engineer/documentation).

For example, in the section below, we can see only emacs binding. 
![image](https://user-images.githubusercontent.com/22132944/83527484-7be13e00-a505-11ea-9f7c-13427c9b93ba.png)

**Comment by Ambrevar** [comment]
There is a documentation mismatch at the moment which I hope to fix as
soon as possible.

In the future, the documentation will only be embedded in the browser.
You can safely ignore the link above.

Sorry for the mess :p

**Comment by Ambrevar** [comment]
See #767.
