### ISSUE TITLE
Rename visual-editor to external-editor-program

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#776]
"visual" is misleading here: it refers to a historical implementation detail, but the newcomer might get it wrong (i.e. "an editor that edits visuals"?).

After all, the file is called `external-editor` and out of consistency I'd call the slot `external-editor-program`.  This is also consistent with how we specify external programs in the rest of the Lisp world (including Emacs and Next).

**Comment by jmercouris** [comment]
You make a good point!

Done: 1d84f5ca

**Comment by Ambrevar** [comment]
Thanks!
