### ISSUE TITLE
Arch Linux package

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#78]
I could create a package for Arch Linux if you like, that could help a bit spreading the word! :)

Some recommendations / guidelines?

**Comment by jmercouris** [comment]
I don't have much experience with arch, so I unfortunately do not even know where to begin :D

If you have experience with C, and with GTK, or are willing to learn, that would help a lot on the Linux end. I am currently in the process of transforming the way Next interacts with interfaces, so it would be a wasted effort to make a package for arch when the build process will change dramatically within the next release. I can explain more if you are interested, or feel free to join the irc channel and we can talk about it there too :)

**Comment by Ambrevar** [comment]
Yes, yes and yes:
- I know C.
- I know a bit of GTK.
- I'm interested! :)

There is no need for you to know Arch (Arch Linux strives at keeping packages as vanilla as possible), in the end the build procedure should be universal.

Let's wait until the next release then.

I don't use IRC, but please go ahead here or e-mail.  By the way, is there a mailing list for next-browser?

**Comment by jmercouris** [comment]
Alright, what a journey, I managed to finally get GNU Mailman working!

http://mail.next-browser.com/listinfo/development

We can talk about it on the mailing list now :)

Thanks,

-John

**Comment by Ambrevar** [comment]
I've tried registering but I never received any confirmation.

**Comment by jmercouris** [comment]
That's strange, I also don't see your name in the mailing list, please send me an email: John at Mercouris dot email, and I'll manually add you to the mailing list!

thanks,

-John

**Comment by jmercouris** [comment]
Actually, I know what the problem is, please check your spam folder, it should be in there, gmail moves new server mailman to spam right away...

**Comment by Ambrevar** [comment]
You were right, it went to the spam folder...
I've subscribed to many Mailman-based mailing lists and it is the first
time (I think) it got spammed.

There might be more than that, or maybe just Gmail...

**Comment by jmercouris** [comment]
It is also a new domain with a new mx record, that may have something to do with it, not sure

**Comment by Ambrevar** [comment]
I've been working on this and I've managed to get a decent PKGBUILD, but for one issue: the executable crashes immediately on startup, only printing 5 `S-W-M` lines.
It works if I run it as root however.
The strace is quite hard to read, I haven't figured out why yet.

Does this ring a bell?  @jmercouris, @vindarel?

**Comment by Ambrevar** [comment]
Here is a first draft: https://gitlab.com/ambrevar/archlinux-pkgbuilds/blob/master/next-browser-git/PKGBUILD.

Also note that Next works fine on Arch when not compiled to a binary.

**Comment by vindarel** [comment]
hello, the mailing list isn't reachable: http://mail.next-browser.com/listinfo

**Comment by jmercouris** [comment]
Hi Vindarel,we’re working on setting up a new installation, sorry about that!

**Comment by Ambrevar** [comment]
Done: https://aur.archlinux.org/packages/next-browser-git/.
