### ISSUE TITLE
Include documentation HTML in nEXT ?

### ISSUE THREAD

**Issue by chuchana** [atlas-engineer/next#85]
Currently, nEXT starts with an Error 404. In earlier versions, I thought at first that it didn't work because I started it without internet access.

Wouldn't it make sense to include the docs in the browser itself?

**Comment by jmercouris** [comment]
Hi, thank you for your report!

You are right, it would be very convenient and nice for things to be able to load correctly all of the time, if not at least to provide some fallback when the internet connection is not present

there are still a couple of issues that I see though:

1. Bundling documentation into the browser means that that information will be out of date possibly, we could use the start screen for example to inform users of a new version available
2. It will involve a new build step if we are going to include documentation inside the application bundle, not a huge deal, but it is some work

if you can think of a way to mitigate these concerns, I am all ears :)

**Comment by Ambrevar** [comment]
Actually, I disagree with point 1: building the documentation into the browser means it matches the browser version and is not out-of-sync.

Regarding 2, the build step:
- What about generating all the documentations programmatically e.g. from the docstrings, etc. à-la Emacs?
- Else we would need to snarf the Org files.  Either at build time by first using pandoc to bake the HTMLs into the executable, or by rolling out our cl-org parser :)

**Comment by vindarel** [comment]
FYI I included a quickstart with `M-x help` a few days ago.

**Comment by vindarel** [comment]
and Next starts on it. Thanks.
