### ISSUE TITLE
mac OS keychain integration 

### ISSUE THREAD

**Issue by sandersantema** [atlas-engineer/next#87]
Would it be possible to integrate the macOS system keychain in Next? Unfortunately I'm not really well versed in programming lisp and programming in general but after some googling I've found this little [thread](https://lists.gnu.org/archive/html/emacs-devel/2012-08/msg00634.html). Which discusses the integration of the macOS system keychain into emacs which would hopefully be applicable to Next. 

Thanks in advance 😄

**Comment by jmercouris** [comment]
Hi, I'm very sorry for the delay in replying! This is an excellent feature idea that I would love to get started with (I am on OSX user myself). Currently we are working on a really large scale change to the codebase, but as soon as that is implemented, we'll keep this high up on our list. Thank you for your feedback and interest!

**Comment by MasonProtter** [comment]
Just thought I'd chime in: Keychain integration is the only feature I'm waiting for before this becomes my main browser!

**Comment by sandersantema** [comment]
Any updates on this?

**Comment by jmercouris** [comment]
Nothing to report yet, sorry! We are actively working on some more architectural changes, this is on our radar though- as soon as we finish the tasks from our first campaign.

**Comment by jmercouris** [comment]
This is now completed on master!

**Comment by jmercouris** [comment]
well, there are some improvements to be made of course, but it is functional :-)
